-- GENERATED by code/julia/scripts/certificates/v0_from_recorded.jl — do not edit.
-- Regenerate and `git diff --exit-code` to prove the Lean corpus is a
-- pure function of the JSON certificates.

import Formal.Certificates.Prelude

set_option maxRecDepth 8000
set_option maxHeartbeats 1000000

namespace Quitting.V0


/-- Condition `quitdev_1` of `seed202_r78_gen011_face_4`, with the sense the trace reads it in. The
certificate refutes the system in which all of them hold at once. -/
def seed202_r78_gen011_face_4_f01 (x1 x2 x3 x4 : ℝ) : Prop :=
  -5642885 / 1048576 + 313 / 51 * x4 - 45 / 17 * x3 + 7819 / 1632 * x3 * x4 + 5 / 3 * x2 - 1145 / 663 * x2 * x4 + 1001 / 102 * x2 * x3 - 1253221 / 109616 * x2 * x3 * x4 + 5 * x1 - 313 / 51 * x1 * x4 + 45 / 17 * x1 * x3 - 7819 / 1632 * x1 * x3 * x4 - 5 / 3 * x1 * x2 + 1145 / 663 * x1 * x2 * x4 - 1001 / 102 * x1 * x2 * x3 + 1253221 / 109616 * x1 * x2 * x3 * x4 ≤ 0

/-- Condition `contdev_1` of `seed202_r78_gen011_face_4`, with the sense the trace reads it in. The
certificate refutes the system in which all of them hold at once. -/
def seed202_r78_gen011_face_4_f02 (x1 x2 x3 x4 : ℝ) : Prop :=
  -400005 / 1048576 - 74681 / 65536 * x1 + 7643 / 3342336 * x1 * x4 + 9789257 / 1114112 * x1 * x3 - 36533723 / 3342336 * x1 * x3 * x4 + 879403 / 196608 * x1 * x2 - 191726623 / 43450368 * x1 * x2 * x4 - 53321179 / 3342336 * x1 * x2 * x3 + 7889768427 / 448987136 * x1 * x2 * x3 * x4 ≤ 0

/-- Condition `quitdev_2` of `seed202_r78_gen011_face_4`, with the sense the trace reads it in. The
certificate refutes the system in which all of them hold at once. -/
def seed202_r78_gen011_face_4_f03 (x1 x2 x3 x4 : ℝ) : Prop :=
  -6691461 / 1048576 - 17 / 29 * x4 + 120 / 19 * x3 - 4720 / 4959 * x3 * x4 + 6 * x2 + 17 / 29 * x2 * x4 - 120 / 19 * x2 * x3 + 4720 / 4959 * x2 * x3 * x4 + 159 / 22 * x1 + 1880 / 4147 * x1 * x4 - 30631 / 2717 * x1 * x3 + 2609207 / 1527372 * x1 * x3 * x4 - 159 / 22 * x1 * x2 - 1880 / 4147 * x1 * x2 * x4 + 30631 / 2717 * x1 * x2 * x3 - 2609207 / 1527372 * x1 * x2 * x3 * x4 ≤ 0

/-- Condition `contdev_2` of `seed202_r78_gen011_face_4`, with the sense the trace reads it in. The
certificate refutes the system in which all of them hold at once. -/
def seed202_r78_gen011_face_4_f04 (x1 x2 x3 x4 : ℝ) : Prop :=
  -400005 / 1048576 - 2654795 / 3145728 * x2 + 677823103 / 91226112 * x2 * x4 + 31566737 / 59768832 * x2 * x3 - 30638427719 / 5199888384 * x2 * x3 * x4 - 13264583 / 34603008 * x1 * x2 - 95195407601 / 13045334016 * x1 * x2 * x4 + 37862058497 / 8546942976 * x1 * x2 * x3 + 2056265435995 / 400391405568 * x1 * x2 * x3 * x4 ≤ 0

/-- Condition `quitdev_3` of `seed202_r78_gen011_face_4`, with the sense the trace reads it in. The
certificate refutes the system in which all of them hold at once. -/
def seed202_r78_gen011_face_4_f05 (x1 x2 x3 x4 : ℝ) : Prop :=
  -5642885 / 1048576 - 19 / 12 * x4 + 5 * x3 + 19 / 12 * x3 * x4 + 193 / 19 * x2 - 8743 / 1824 * x2 * x4 - 193 / 19 * x2 * x3 + 8743 / 1824 * x2 * x3 * x4 - 15 / 31 * x1 + 21131 / 2604 * x1 * x4 + 15 / 31 * x1 * x3 - 21131 / 2604 * x1 * x3 * x4 - 397 / 589 * x1 * x2 - 15017463 / 3826144 * x1 * x2 * x4 + 397 / 589 * x1 * x2 * x3 + 15017463 / 3826144 * x1 * x2 * x3 * x4 ≤ 0

/-- Condition `contdev_3` of `seed202_r78_gen011_face_4`, with the sense the trace reads it in. The
certificate refutes the system in which all of them hold at once. -/
def seed202_r78_gen011_face_4_f06 (x1 x2 x3 x4 : ℝ) : Prop :=
  -400005 / 1048576 - 628215 / 262144 * x3 + 7061989 / 786432 * x3 * x4 - 13754027 / 4980736 * x2 * x3 - 38896639 / 14942208 * x2 * x3 * x4 + 64039145 / 8126464 * x1 * x3 - 2647087901 / 170655744 * x1 * x3 * x4 - 1037961547 / 154402816 * x1 * x2 * x3 + 354855698041 / 31343771648 * x1 * x2 * x3 * x4 ≤ 0

/-- Condition `quitdev_4` of `seed202_r78_gen011_face_4`, with the sense the trace reads it in. The
certificate refutes the system in which all of them hold at once. -/
def seed202_r78_gen011_face_4_f07 (x1 x2 x3 x4 : ℝ) : Prop :=
  -5642885 / 1048576 + 5 * x4 + 185 / 19 * x3 - 185 / 19 * x3 * x4 + 44 / 9 * x2 - 44 / 9 * x2 * x4 - 450787 / 42408 * x2 * x3 + 450787 / 42408 * x2 * x3 * x4 + 11 / 12 * x1 - 11 / 12 * x1 * x4 - 38299 / 5244 * x1 * x3 + 38299 / 5244 * x1 * x3 * x4 - 1423 / 1800 * x1 * x2 + 1423 / 1800 * x1 * x2 * x4 + 1085860103 / 134115300 * x1 * x2 * x3 - 1085860103 / 134115300 * x1 * x2 * x3 * x4 ≤ 0

/-- Condition `contdev_4` of `seed202_r78_gen011_face_4`, with the sense the trace reads it in. The
certificate refutes the system in which all of them hold at once. -/
def seed202_r78_gen011_face_4_f08 (x1 x2 x3 x4 : ℝ) : Prop :=
  -400005 / 1048576 - 472569 / 262144 * x4 - 14614149 / 4980736 * x3 * x4 + 4515265 / 2359296 * x2 * x4 + 5318173427 / 1389625344 * x2 * x3 * x4 + 4628971 / 786432 * x1 * x4 + 172071385 / 343670784 * x1 * x3 * x4 - 354611161 / 58982400 * x1 * x2 * x4 - 11371342904783 / 8789380300800 * x1 * x2 * x3 * x4 ≤ 0

/-- on the face {x4 = 1} of the stage-1 profile cube no point leaves all 2N stage-1 deviation gains at most eps = 400005/1048576; the unknown continuation values are replaced by the certified min-max lower bounds (continue-deviations) and by max(0, max_S r^S_k) (quit-deviations), both of which only lower the gains. Termination with probability one at stage 1 forces some x_i = 1, so the four faces are the whole case enumeration.

Proved by the recorded subdivision of the box: every leaf carries one
condition that the Bernstein corner-basis expansion makes strictly
positive there. Machine-written. -/
theorem seed202_r78_gen011_face_4
    (x1 x2 x3 x4 : ℝ)
    (hlo1 : (0 : ℝ) ≤ x1)
    (hhi1 : x1 ≤ (1 : ℝ))
    (hlo2 : (0 : ℝ) ≤ x2)
    (hhi2 : x2 ≤ (1 : ℝ))
    (hlo3 : (0 : ℝ) ≤ x3)
    (hhi3 : x3 ≤ (1 : ℝ))
    (hlo4 : (1 : ℝ) ≤ x4)
    (hhi4 : x4 ≤ (1 : ℝ))
    : ¬ (
      seed202_r78_gen011_face_4_f01 x1 x2 x3 x4 ∧
      seed202_r78_gen011_face_4_f02 x1 x2 x3 x4 ∧
      seed202_r78_gen011_face_4_f03 x1 x2 x3 x4 ∧
      seed202_r78_gen011_face_4_f04 x1 x2 x3 x4 ∧
      seed202_r78_gen011_face_4_f05 x1 x2 x3 x4 ∧
      seed202_r78_gen011_face_4_f06 x1 x2 x3 x4 ∧
      seed202_r78_gen011_face_4_f07 x1 x2 x3 x4 ∧
      seed202_r78_gen011_face_4_f08 x1 x2 x3 x4) := by
  rintro ⟨c1, _, _, c4, c5, _, _, c8⟩
  obtain rfl : x4 = (1 : ℝ) := le_antisymm hhi4 hlo4
  simp only [seed202_r78_gen011_face_4_f01, seed202_r78_gen011_face_4_f04, seed202_r78_gen011_face_4_f05, seed202_r78_gen011_face_4_f08] at c1 c4 c5 c8
  rcases le_total x1 (1 / 2 : ℝ) with hs1 | hs1
  · -- `quitdev_1` ≥ 2139967 / 13631488 > 0 on x1 ∈ [0, 1 / 2], x2 ∈ [0, 1], x3 ∈ [0, 1]
    have d1lo : (0:ℝ) ≤ x1 - 0 := sub_nonneg.mpr hlo1
    have d1hi : (0:ℝ) ≤ 1 / 2 - x1 := sub_nonneg.mpr hs1
    have d2lo : (0:ℝ) ≤ x2 - 0 := sub_nonneg.mpr hlo2
    have d2hi : (0:ℝ) ≤ 1 - x2 := sub_nonneg.mpr hhi2
    have d3lo : (0:ℝ) ≤ x3 - 0 := sub_nonneg.mpr hlo3
    have d3hi : (0:ℝ) ≤ 1 - x3 := sub_nonneg.mpr hhi3
    linarith only [c1, mul_nonneg (mul_nonneg (d1hi) d2hi) d3hi, mul_nonneg (mul_nonneg (d1lo) d2hi) d3hi, mul_nonneg (mul_nonneg (d1hi) d2lo) d3hi, mul_nonneg (mul_nonneg (d1lo) d2lo) d3hi, mul_nonneg (mul_nonneg (d1hi) d2hi) d3lo, mul_nonneg (mul_nonneg (d1lo) d2hi) d3lo, mul_nonneg (mul_nonneg (d1hi) d2lo) d3lo, mul_nonneg (mul_nonneg (d1lo) d2lo) d3lo]
  · rcases le_total x2 (1 / 2 : ℝ) with hs2 | hs2
    · rcases le_total x3 (1 / 2 : ℝ) with hs3 | hs3
      · rcases le_total x1 (3 / 4 : ℝ) with hs4 | hs4
        · rcases le_total x2 (1 / 4 : ℝ) with hs5 | hs5
          · rcases le_total x3 (1 / 4 : ℝ) with hs6 | hs6
            · -- `contdev_4` ≥ 22348239389 / 1644796313600 > 0 on x1 ∈ [1 / 2, 3 / 4], x2 ∈ [0, 1 / 4], x3 ∈ [0, 1 / 4]
              have d1lo : (0:ℝ) ≤ x1 - 1 / 2 := sub_nonneg.mpr hs1
              have d1hi : (0:ℝ) ≤ 3 / 4 - x1 := sub_nonneg.mpr hs4
              have d2lo : (0:ℝ) ≤ x2 - 0 := sub_nonneg.mpr hlo2
              have d2hi : (0:ℝ) ≤ 1 / 4 - x2 := sub_nonneg.mpr hs5
              have d3lo : (0:ℝ) ≤ x3 - 0 := sub_nonneg.mpr hlo3
              have d3hi : (0:ℝ) ≤ 1 / 4 - x3 := sub_nonneg.mpr hs6
              linarith only [c8, mul_nonneg (mul_nonneg (d1hi) d2hi) d3hi, mul_nonneg (mul_nonneg (d1lo) d2hi) d3hi, mul_nonneg (mul_nonneg (d1hi) d2lo) d3hi, mul_nonneg (mul_nonneg (d1lo) d2lo) d3hi, mul_nonneg (mul_nonneg (d1hi) d2hi) d3lo, mul_nonneg (mul_nonneg (d1lo) d2hi) d3lo, mul_nonneg (mul_nonneg (d1hi) d2lo) d3lo, mul_nonneg (mul_nonneg (d1lo) d2lo) d3lo]
            · -- `quitdev_1` ≥ 55815857 / 7183794176 > 0 on x1 ∈ [1 / 2, 3 / 4], x2 ∈ [0, 1 / 4], x3 ∈ [1 / 4, 1 / 2]
              have d1lo : (0:ℝ) ≤ x1 - 1 / 2 := sub_nonneg.mpr hs1
              have d1hi : (0:ℝ) ≤ 3 / 4 - x1 := sub_nonneg.mpr hs4
              have d2lo : (0:ℝ) ≤ x2 - 0 := sub_nonneg.mpr hlo2
              have d2hi : (0:ℝ) ≤ 1 / 4 - x2 := sub_nonneg.mpr hs5
              have d3lo : (0:ℝ) ≤ x3 - 1 / 4 := sub_nonneg.mpr hs6
              have d3hi : (0:ℝ) ≤ 1 / 2 - x3 := sub_nonneg.mpr hs3
              linarith only [c1, mul_nonneg (mul_nonneg (d1hi) d2hi) d3hi, mul_nonneg (mul_nonneg (d1lo) d2hi) d3hi, mul_nonneg (mul_nonneg (d1hi) d2lo) d3hi, mul_nonneg (mul_nonneg (d1lo) d2lo) d3hi, mul_nonneg (mul_nonneg (d1hi) d2hi) d3lo, mul_nonneg (mul_nonneg (d1lo) d2hi) d3lo, mul_nonneg (mul_nonneg (d1hi) d2lo) d3lo, mul_nonneg (mul_nonneg (d1lo) d2lo) d3lo]
          · rcases le_total x3 (1 / 4 : ℝ) with hs6 | hs6
            · rcases le_total x1 (5 / 8 : ℝ) with hs7 | hs7
              · -- `quitdev_1` ≥ 7805743 / 231735296 > 0 on x1 ∈ [1 / 2, 5 / 8], x2 ∈ [1 / 4, 1 / 2], x3 ∈ [0, 1 / 4]
                have d1lo : (0:ℝ) ≤ x1 - 1 / 2 := sub_nonneg.mpr hs1
                have d1hi : (0:ℝ) ≤ 5 / 8 - x1 := sub_nonneg.mpr hs7
                have d2lo : (0:ℝ) ≤ x2 - 1 / 4 := sub_nonneg.mpr hs5
                have d2hi : (0:ℝ) ≤ 1 / 2 - x2 := sub_nonneg.mpr hs2
                have d3lo : (0:ℝ) ≤ x3 - 0 := sub_nonneg.mpr hlo3
                have d3hi : (0:ℝ) ≤ 1 / 4 - x3 := sub_nonneg.mpr hs6
                linarith only [c1, mul_nonneg (mul_nonneg (d1hi) d2hi) d3hi, mul_nonneg (mul_nonneg (d1lo) d2hi) d3hi, mul_nonneg (mul_nonneg (d1hi) d2lo) d3hi, mul_nonneg (mul_nonneg (d1lo) d2lo) d3hi, mul_nonneg (mul_nonneg (d1hi) d2hi) d3lo, mul_nonneg (mul_nonneg (d1lo) d2hi) d3lo, mul_nonneg (mul_nonneg (d1hi) d2lo) d3lo, mul_nonneg (mul_nonneg (d1lo) d2lo) d3lo]
              · -- `contdev_4` ≥ 11052062157593 / 37501355950080 > 0 on x1 ∈ [5 / 8, 3 / 4], x2 ∈ [1 / 4, 1 / 2], x3 ∈ [0, 1 / 4]
                have d1lo : (0:ℝ) ≤ x1 - 5 / 8 := sub_nonneg.mpr hs7
                have d1hi : (0:ℝ) ≤ 3 / 4 - x1 := sub_nonneg.mpr hs4
                have d2lo : (0:ℝ) ≤ x2 - 1 / 4 := sub_nonneg.mpr hs5
                have d2hi : (0:ℝ) ≤ 1 / 2 - x2 := sub_nonneg.mpr hs2
                have d3lo : (0:ℝ) ≤ x3 - 0 := sub_nonneg.mpr hlo3
                have d3hi : (0:ℝ) ≤ 1 / 4 - x3 := sub_nonneg.mpr hs6
                linarith only [c8, mul_nonneg (mul_nonneg (d1hi) d2hi) d3hi, mul_nonneg (mul_nonneg (d1lo) d2hi) d3hi, mul_nonneg (mul_nonneg (d1hi) d2lo) d3hi, mul_nonneg (mul_nonneg (d1lo) d2lo) d3hi, mul_nonneg (mul_nonneg (d1hi) d2hi) d3lo, mul_nonneg (mul_nonneg (d1lo) d2hi) d3lo, mul_nonneg (mul_nonneg (d1hi) d2lo) d3lo, mul_nonneg (mul_nonneg (d1lo) d2lo) d3lo]
            · rcases le_total x1 (5 / 8 : ℝ) with hs7 | hs7
              · -- `quitdev_1` ≥ 1140699825 / 7183794176 > 0 on x1 ∈ [1 / 2, 5 / 8], x2 ∈ [1 / 4, 1 / 2], x3 ∈ [1 / 4, 1 / 2]
                have d1lo : (0:ℝ) ≤ x1 - 1 / 2 := sub_nonneg.mpr hs1
                have d1hi : (0:ℝ) ≤ 5 / 8 - x1 := sub_nonneg.mpr hs7
                have d2lo : (0:ℝ) ≤ x2 - 1 / 4 := sub_nonneg.mpr hs5
                have d2hi : (0:ℝ) ≤ 1 / 2 - x2 := sub_nonneg.mpr hs2
                have d3lo : (0:ℝ) ≤ x3 - 1 / 4 := sub_nonneg.mpr hs6
                have d3hi : (0:ℝ) ≤ 1 / 2 - x3 := sub_nonneg.mpr hs3
                linarith only [c1, mul_nonneg (mul_nonneg (d1hi) d2hi) d3hi, mul_nonneg (mul_nonneg (d1lo) d2hi) d3hi, mul_nonneg (mul_nonneg (d1hi) d2lo) d3hi, mul_nonneg (mul_nonneg (d1lo) d2lo) d3hi, mul_nonneg (mul_nonneg (d1hi) d2hi) d3lo, mul_nonneg (mul_nonneg (d1lo) d2hi) d3lo, mul_nonneg (mul_nonneg (d1hi) d2lo) d3lo, mul_nonneg (mul_nonneg (d1lo) d2lo) d3lo]
              · -- `contdev_4` ≥ 313449192491 / 18750677975040 > 0 on x1 ∈ [5 / 8, 3 / 4], x2 ∈ [1 / 4, 1 / 2], x3 ∈ [1 / 4, 1 / 2]
                have d1lo : (0:ℝ) ≤ x1 - 5 / 8 := sub_nonneg.mpr hs7
                have d1hi : (0:ℝ) ≤ 3 / 4 - x1 := sub_nonneg.mpr hs4
                have d2lo : (0:ℝ) ≤ x2 - 1 / 4 := sub_nonneg.mpr hs5
                have d2hi : (0:ℝ) ≤ 1 / 2 - x2 := sub_nonneg.mpr hs2
                have d3lo : (0:ℝ) ≤ x3 - 1 / 4 := sub_nonneg.mpr hs6
                have d3hi : (0:ℝ) ≤ 1 / 2 - x3 := sub_nonneg.mpr hs3
                linarith only [c8, mul_nonneg (mul_nonneg (d1hi) d2hi) d3hi, mul_nonneg (mul_nonneg (d1lo) d2hi) d3hi, mul_nonneg (mul_nonneg (d1hi) d2lo) d3hi, mul_nonneg (mul_nonneg (d1lo) d2lo) d3hi, mul_nonneg (mul_nonneg (d1hi) d2hi) d3lo, mul_nonneg (mul_nonneg (d1lo) d2hi) d3lo, mul_nonneg (mul_nonneg (d1hi) d2lo) d3lo, mul_nonneg (mul_nonneg (d1lo) d2lo) d3lo]
        · -- `contdev_4` ≥ 51692137509979 / 140630084812800 > 0 on x1 ∈ [3 / 4, 1], x2 ∈ [0, 1 / 2], x3 ∈ [0, 1 / 2]
          have d1lo : (0:ℝ) ≤ x1 - 3 / 4 := sub_nonneg.mpr hs4
          have d1hi : (0:ℝ) ≤ 1 - x1 := sub_nonneg.mpr hhi1
          have d2lo : (0:ℝ) ≤ x2 - 0 := sub_nonneg.mpr hlo2
          have d2hi : (0:ℝ) ≤ 1 / 2 - x2 := sub_nonneg.mpr hs2
          have d3lo : (0:ℝ) ≤ x3 - 0 := sub_nonneg.mpr hlo3
          have d3hi : (0:ℝ) ≤ 1 / 2 - x3 := sub_nonneg.mpr hs3
          linarith only [c8, mul_nonneg (mul_nonneg (d1hi) d2hi) d3hi, mul_nonneg (mul_nonneg (d1lo) d2hi) d3hi, mul_nonneg (mul_nonneg (d1hi) d2lo) d3hi, mul_nonneg (mul_nonneg (d1lo) d2lo) d3hi, mul_nonneg (mul_nonneg (d1hi) d2hi) d3lo, mul_nonneg (mul_nonneg (d1lo) d2hi) d3lo, mul_nonneg (mul_nonneg (d1hi) d2lo) d3lo, mul_nonneg (mul_nonneg (d1lo) d2lo) d3lo]
      · rcases le_total x1 (3 / 4 : ℝ) with hs4 | hs4
        · -- `quitdev_1` ≥ 1338408979 / 21551382528 > 0 on x1 ∈ [1 / 2, 3 / 4], x2 ∈ [0, 1 / 2], x3 ∈ [1 / 2, 1]
          have d1lo : (0:ℝ) ≤ x1 - 1 / 2 := sub_nonneg.mpr hs1
          have d1hi : (0:ℝ) ≤ 3 / 4 - x1 := sub_nonneg.mpr hs4
          have d2lo : (0:ℝ) ≤ x2 - 0 := sub_nonneg.mpr hlo2
          have d2hi : (0:ℝ) ≤ 1 / 2 - x2 := sub_nonneg.mpr hs2
          have d3lo : (0:ℝ) ≤ x3 - 1 / 2 := sub_nonneg.mpr hs3
          have d3hi : (0:ℝ) ≤ 1 - x3 := sub_nonneg.mpr hhi3
          linarith only [c1, mul_nonneg (mul_nonneg (d1hi) d2hi) d3hi, mul_nonneg (mul_nonneg (d1lo) d2hi) d3hi, mul_nonneg (mul_nonneg (d1hi) d2lo) d3hi, mul_nonneg (mul_nonneg (d1lo) d2lo) d3hi, mul_nonneg (mul_nonneg (d1hi) d2hi) d3lo, mul_nonneg (mul_nonneg (d1lo) d2hi) d3lo, mul_nonneg (mul_nonneg (d1hi) d2lo) d3lo, mul_nonneg (mul_nonneg (d1lo) d2lo) d3lo]
        · rcases le_total x2 (1 / 4 : ℝ) with hs5 | hs5
          · rcases le_total x3 (3 / 4 : ℝ) with hs6 | hs6
            · -- `contdev_4` ≥ 111490523665309 / 562520339251200 > 0 on x1 ∈ [3 / 4, 1], x2 ∈ [0, 1 / 4], x3 ∈ [1 / 2, 3 / 4]
              have d1lo : (0:ℝ) ≤ x1 - 3 / 4 := sub_nonneg.mpr hs4
              have d1hi : (0:ℝ) ≤ 1 - x1 := sub_nonneg.mpr hhi1
              have d2lo : (0:ℝ) ≤ x2 - 0 := sub_nonneg.mpr hlo2
              have d2hi : (0:ℝ) ≤ 1 / 4 - x2 := sub_nonneg.mpr hs5
              have d3lo : (0:ℝ) ≤ x3 - 1 / 2 := sub_nonneg.mpr hs3
              have d3hi : (0:ℝ) ≤ 3 / 4 - x3 := sub_nonneg.mpr hs6
              linarith only [c8, mul_nonneg (mul_nonneg (d1hi) d2hi) d3hi, mul_nonneg (mul_nonneg (d1lo) d2hi) d3hi, mul_nonneg (mul_nonneg (d1hi) d2lo) d3hi, mul_nonneg (mul_nonneg (d1lo) d2lo) d3hi, mul_nonneg (mul_nonneg (d1hi) d2hi) d3lo, mul_nonneg (mul_nonneg (d1lo) d2hi) d3lo, mul_nonneg (mul_nonneg (d1hi) d2lo) d3lo, mul_nonneg (mul_nonneg (d1lo) d2lo) d3lo]
            · rcases le_total x1 (7 / 8 : ℝ) with hs7 | hs7
              · rcases le_total x2 (1 / 8 : ℝ) with hs8 | hs8
                · rcases le_total x3 (7 / 8 : ℝ) with hs9 | hs9
                  · rcases le_total x1 (13 / 16 : ℝ) with hs10 | hs10
                    · -- `quitdev_1` ≥ 742698545 / 7183794176 > 0 on x1 ∈ [3 / 4, 13 / 16], x2 ∈ [0, 1 / 8], x3 ∈ [3 / 4, 7 / 8]
                      have d1lo : (0:ℝ) ≤ x1 - 3 / 4 := sub_nonneg.mpr hs4
                      have d1hi : (0:ℝ) ≤ 13 / 16 - x1 := sub_nonneg.mpr hs10
                      have d2lo : (0:ℝ) ≤ x2 - 0 := sub_nonneg.mpr hlo2
                      have d2hi : (0:ℝ) ≤ 1 / 8 - x2 := sub_nonneg.mpr hs8
                      have d3lo : (0:ℝ) ≤ x3 - 3 / 4 := sub_nonneg.mpr hs6
                      have d3hi : (0:ℝ) ≤ 7 / 8 - x3 := sub_nonneg.mpr hs9
                      linarith only [c1, mul_nonneg (mul_nonneg (d1hi) d2hi) d3hi, mul_nonneg (mul_nonneg (d1lo) d2hi) d3hi, mul_nonneg (mul_nonneg (d1hi) d2lo) d3hi, mul_nonneg (mul_nonneg (d1lo) d2lo) d3hi, mul_nonneg (mul_nonneg (d1hi) d2hi) d3lo, mul_nonneg (mul_nonneg (d1lo) d2hi) d3lo, mul_nonneg (mul_nonneg (d1hi) d2lo) d3lo, mul_nonneg (mul_nonneg (d1lo) d2lo) d3lo]
                    · -- `contdev_4` ≥ 957169783083433 / 3000108476006400 > 0 on x1 ∈ [13 / 16, 7 / 8], x2 ∈ [0, 1 / 8], x3 ∈ [3 / 4, 7 / 8]
                      have d1lo : (0:ℝ) ≤ x1 - 13 / 16 := sub_nonneg.mpr hs10
                      have d1hi : (0:ℝ) ≤ 7 / 8 - x1 := sub_nonneg.mpr hs7
                      have d2lo : (0:ℝ) ≤ x2 - 0 := sub_nonneg.mpr hlo2
                      have d2hi : (0:ℝ) ≤ 1 / 8 - x2 := sub_nonneg.mpr hs8
                      have d3lo : (0:ℝ) ≤ x3 - 3 / 4 := sub_nonneg.mpr hs6
                      have d3hi : (0:ℝ) ≤ 7 / 8 - x3 := sub_nonneg.mpr hs9
                      linarith only [c8, mul_nonneg (mul_nonneg (d1hi) d2hi) d3hi, mul_nonneg (mul_nonneg (d1lo) d2hi) d3hi, mul_nonneg (mul_nonneg (d1hi) d2lo) d3hi, mul_nonneg (mul_nonneg (d1lo) d2lo) d3hi, mul_nonneg (mul_nonneg (d1hi) d2hi) d3lo, mul_nonneg (mul_nonneg (d1lo) d2hi) d3lo, mul_nonneg (mul_nonneg (d1hi) d2lo) d3lo, mul_nonneg (mul_nonneg (d1lo) d2lo) d3lo]
                  · rcases le_total x1 (13 / 16 : ℝ) with hs10 | hs10
                    · -- `quitdev_1` ≥ 1069607281 / 7183794176 > 0 on x1 ∈ [3 / 4, 13 / 16], x2 ∈ [0, 1 / 8], x3 ∈ [7 / 8, 1]
                      have d1lo : (0:ℝ) ≤ x1 - 3 / 4 := sub_nonneg.mpr hs4
                      have d1hi : (0:ℝ) ≤ 13 / 16 - x1 := sub_nonneg.mpr hs10
                      have d2lo : (0:ℝ) ≤ x2 - 0 := sub_nonneg.mpr hlo2
                      have d2hi : (0:ℝ) ≤ 1 / 8 - x2 := sub_nonneg.mpr hs8
                      have d3lo : (0:ℝ) ≤ x3 - 7 / 8 := sub_nonneg.mpr hs9
                      have d3hi : (0:ℝ) ≤ 1 - x3 := sub_nonneg.mpr hhi3
                      linarith only [c1, mul_nonneg (mul_nonneg (d1hi) d2hi) d3hi, mul_nonneg (mul_nonneg (d1lo) d2hi) d3hi, mul_nonneg (mul_nonneg (d1hi) d2lo) d3hi, mul_nonneg (mul_nonneg (d1lo) d2lo) d3hi, mul_nonneg (mul_nonneg (d1hi) d2hi) d3lo, mul_nonneg (mul_nonneg (d1lo) d2hi) d3lo, mul_nonneg (mul_nonneg (d1hi) d2lo) d3lo, mul_nonneg (mul_nonneg (d1lo) d2lo) d3lo]
                    · -- `contdev_4` ≥ 108993728813 / 2343834746880 > 0 on x1 ∈ [13 / 16, 7 / 8], x2 ∈ [0, 1 / 8], x3 ∈ [7 / 8, 1]
                      have d1lo : (0:ℝ) ≤ x1 - 13 / 16 := sub_nonneg.mpr hs10
                      have d1hi : (0:ℝ) ≤ 7 / 8 - x1 := sub_nonneg.mpr hs7
                      have d2lo : (0:ℝ) ≤ x2 - 0 := sub_nonneg.mpr hlo2
                      have d2hi : (0:ℝ) ≤ 1 / 8 - x2 := sub_nonneg.mpr hs8
                      have d3lo : (0:ℝ) ≤ x3 - 7 / 8 := sub_nonneg.mpr hs9
                      have d3hi : (0:ℝ) ≤ 1 - x3 := sub_nonneg.mpr hhi3
                      linarith only [c8, mul_nonneg (mul_nonneg (d1hi) d2hi) d3hi, mul_nonneg (mul_nonneg (d1lo) d2hi) d3hi, mul_nonneg (mul_nonneg (d1hi) d2lo) d3hi, mul_nonneg (mul_nonneg (d1lo) d2lo) d3hi, mul_nonneg (mul_nonneg (d1hi) d2hi) d3lo, mul_nonneg (mul_nonneg (d1lo) d2hi) d3lo, mul_nonneg (mul_nonneg (d1hi) d2lo) d3lo, mul_nonneg (mul_nonneg (d1lo) d2lo) d3lo]
                · rcases le_total x3 (7 / 8 : ℝ) with hs9 | hs9
                  · rcases le_total x1 (13 / 16 : ℝ) with hs10 | hs10
                    · -- `quitdev_1` ≥ 528083889 / 7183794176 > 0 on x1 ∈ [3 / 4, 13 / 16], x2 ∈ [1 / 8, 1 / 4], x3 ∈ [3 / 4, 7 / 8]
                      have d1lo : (0:ℝ) ≤ x1 - 3 / 4 := sub_nonneg.mpr hs4
                      have d1hi : (0:ℝ) ≤ 13 / 16 - x1 := sub_nonneg.mpr hs10
                      have d2lo : (0:ℝ) ≤ x2 - 1 / 8 := sub_nonneg.mpr hs8
                      have d2hi : (0:ℝ) ≤ 1 / 4 - x2 := sub_nonneg.mpr hs5
                      have d3lo : (0:ℝ) ≤ x3 - 3 / 4 := sub_nonneg.mpr hs6
                      have d3hi : (0:ℝ) ≤ 7 / 8 - x3 := sub_nonneg.mpr hs9
                      linarith only [c1, mul_nonneg (mul_nonneg (d1hi) d2hi) d3hi, mul_nonneg (mul_nonneg (d1lo) d2hi) d3hi, mul_nonneg (mul_nonneg (d1hi) d2lo) d3hi, mul_nonneg (mul_nonneg (d1lo) d2lo) d3hi, mul_nonneg (mul_nonneg (d1hi) d2hi) d3lo, mul_nonneg (mul_nonneg (d1lo) d2hi) d3lo, mul_nonneg (mul_nonneg (d1hi) d2lo) d3lo, mul_nonneg (mul_nonneg (d1lo) d2lo) d3lo]
                    · -- `contdev_4` ≥ 125641871090511 / 500018079334400 > 0 on x1 ∈ [13 / 16, 7 / 8], x2 ∈ [1 / 8, 1 / 4], x3 ∈ [3 / 4, 7 / 8]
                      have d1lo : (0:ℝ) ≤ x1 - 13 / 16 := sub_nonneg.mpr hs10
                      have d1hi : (0:ℝ) ≤ 7 / 8 - x1 := sub_nonneg.mpr hs7
                      have d2lo : (0:ℝ) ≤ x2 - 1 / 8 := sub_nonneg.mpr hs8
                      have d2hi : (0:ℝ) ≤ 1 / 4 - x2 := sub_nonneg.mpr hs5
                      have d3lo : (0:ℝ) ≤ x3 - 3 / 4 := sub_nonneg.mpr hs6
                      have d3hi : (0:ℝ) ≤ 7 / 8 - x3 := sub_nonneg.mpr hs9
                      linarith only [c8, mul_nonneg (mul_nonneg (d1hi) d2hi) d3hi, mul_nonneg (mul_nonneg (d1lo) d2hi) d3hi, mul_nonneg (mul_nonneg (d1hi) d2lo) d3hi, mul_nonneg (mul_nonneg (d1lo) d2lo) d3hi, mul_nonneg (mul_nonneg (d1hi) d2hi) d3lo, mul_nonneg (mul_nonneg (d1lo) d2hi) d3lo, mul_nonneg (mul_nonneg (d1hi) d2lo) d3lo, mul_nonneg (mul_nonneg (d1lo) d2lo) d3lo]
                  · rcases le_total x1 (13 / 16 : ℝ) with hs10 | hs10
                    · -- `quitdev_1` ≥ 820916529 / 7183794176 > 0 on x1 ∈ [3 / 4, 13 / 16], x2 ∈ [1 / 8, 1 / 4], x3 ∈ [7 / 8, 1]
                      have d1lo : (0:ℝ) ≤ x1 - 3 / 4 := sub_nonneg.mpr hs4
                      have d1hi : (0:ℝ) ≤ 13 / 16 - x1 := sub_nonneg.mpr hs10
                      have d2lo : (0:ℝ) ≤ x2 - 1 / 8 := sub_nonneg.mpr hs8
                      have d2hi : (0:ℝ) ≤ 1 / 4 - x2 := sub_nonneg.mpr hs5
                      have d3lo : (0:ℝ) ≤ x3 - 7 / 8 := sub_nonneg.mpr hs9
                      have d3hi : (0:ℝ) ≤ 1 - x3 := sub_nonneg.mpr hhi3
                      linarith only [c1, mul_nonneg (mul_nonneg (d1hi) d2hi) d3hi, mul_nonneg (mul_nonneg (d1lo) d2hi) d3hi, mul_nonneg (mul_nonneg (d1hi) d2lo) d3hi, mul_nonneg (mul_nonneg (d1lo) d2lo) d3hi, mul_nonneg (mul_nonneg (d1hi) d2hi) d3lo, mul_nonneg (mul_nonneg (d1lo) d2hi) d3lo, mul_nonneg (mul_nonneg (d1hi) d2lo) d3lo, mul_nonneg (mul_nonneg (d1lo) d2lo) d3lo]
                    · -- `contdev_4` ≥ 51810401581 / 2343834746880 > 0 on x1 ∈ [13 / 16, 7 / 8], x2 ∈ [1 / 8, 1 / 4], x3 ∈ [7 / 8, 1]
                      have d1lo : (0:ℝ) ≤ x1 - 13 / 16 := sub_nonneg.mpr hs10
                      have d1hi : (0:ℝ) ≤ 7 / 8 - x1 := sub_nonneg.mpr hs7
                      have d2lo : (0:ℝ) ≤ x2 - 1 / 8 := sub_nonneg.mpr hs8
                      have d2hi : (0:ℝ) ≤ 1 / 4 - x2 := sub_nonneg.mpr hs5
                      have d3lo : (0:ℝ) ≤ x3 - 7 / 8 := sub_nonneg.mpr hs9
                      have d3hi : (0:ℝ) ≤ 1 - x3 := sub_nonneg.mpr hhi3
                      linarith only [c8, mul_nonneg (mul_nonneg (d1hi) d2hi) d3hi, mul_nonneg (mul_nonneg (d1lo) d2hi) d3hi, mul_nonneg (mul_nonneg (d1hi) d2lo) d3hi, mul_nonneg (mul_nonneg (d1lo) d2lo) d3hi, mul_nonneg (mul_nonneg (d1hi) d2hi) d3lo, mul_nonneg (mul_nonneg (d1lo) d2hi) d3lo, mul_nonneg (mul_nonneg (d1hi) d2lo) d3lo, mul_nonneg (mul_nonneg (d1lo) d2lo) d3lo]
              · -- `contdev_4` ≥ 719839900973 / 2343834746880 > 0 on x1 ∈ [7 / 8, 1], x2 ∈ [0, 1 / 4], x3 ∈ [3 / 4, 1]
                have d1lo : (0:ℝ) ≤ x1 - 7 / 8 := sub_nonneg.mpr hs7
                have d1hi : (0:ℝ) ≤ 1 - x1 := sub_nonneg.mpr hhi1
                have d2lo : (0:ℝ) ≤ x2 - 0 := sub_nonneg.mpr hlo2
                have d2hi : (0:ℝ) ≤ 1 / 4 - x2 := sub_nonneg.mpr hs5
                have d3lo : (0:ℝ) ≤ x3 - 3 / 4 := sub_nonneg.mpr hs6
                have d3hi : (0:ℝ) ≤ 1 - x3 := sub_nonneg.mpr hhi3
                linarith only [c8, mul_nonneg (mul_nonneg (d1hi) d2hi) d3hi, mul_nonneg (mul_nonneg (d1lo) d2hi) d3hi, mul_nonneg (mul_nonneg (d1hi) d2lo) d3hi, mul_nonneg (mul_nonneg (d1lo) d2lo) d3hi, mul_nonneg (mul_nonneg (d1hi) d2hi) d3lo, mul_nonneg (mul_nonneg (d1lo) d2hi) d3lo, mul_nonneg (mul_nonneg (d1hi) d2lo) d3lo, mul_nonneg (mul_nonneg (d1lo) d2lo) d3lo]
          · rcases le_total x3 (3 / 4 : ℝ) with hs6 | hs6
            · -- `contdev_4` ≥ 23910600944359 / 281260169625600 > 0 on x1 ∈ [3 / 4, 1], x2 ∈ [1 / 4, 1 / 2], x3 ∈ [1 / 2, 3 / 4]
              have d1lo : (0:ℝ) ≤ x1 - 3 / 4 := sub_nonneg.mpr hs4
              have d1hi : (0:ℝ) ≤ 1 - x1 := sub_nonneg.mpr hhi1
              have d2lo : (0:ℝ) ≤ x2 - 1 / 4 := sub_nonneg.mpr hs5
              have d2hi : (0:ℝ) ≤ 1 / 2 - x2 := sub_nonneg.mpr hs2
              have d3lo : (0:ℝ) ≤ x3 - 1 / 2 := sub_nonneg.mpr hs3
              have d3hi : (0:ℝ) ≤ 3 / 4 - x3 := sub_nonneg.mpr hs6
              linarith only [c8, mul_nonneg (mul_nonneg (d1hi) d2hi) d3hi, mul_nonneg (mul_nonneg (d1lo) d2hi) d3hi, mul_nonneg (mul_nonneg (d1hi) d2lo) d3hi, mul_nonneg (mul_nonneg (d1lo) d2lo) d3hi, mul_nonneg (mul_nonneg (d1hi) d2hi) d3lo, mul_nonneg (mul_nonneg (d1lo) d2hi) d3lo, mul_nonneg (mul_nonneg (d1hi) d2lo) d3lo, mul_nonneg (mul_nonneg (d1lo) d2lo) d3lo]
            · -- `contdev_2` ≥ 139300339 / 1049624576 > 0 on x1 ∈ [3 / 4, 1], x2 ∈ [1 / 4, 1 / 2], x3 ∈ [3 / 4, 1]
              have d1lo : (0:ℝ) ≤ x1 - 3 / 4 := sub_nonneg.mpr hs4
              have d1hi : (0:ℝ) ≤ 1 - x1 := sub_nonneg.mpr hhi1
              have d2lo : (0:ℝ) ≤ x2 - 1 / 4 := sub_nonneg.mpr hs5
              have d2hi : (0:ℝ) ≤ 1 / 2 - x2 := sub_nonneg.mpr hs2
              have d3lo : (0:ℝ) ≤ x3 - 3 / 4 := sub_nonneg.mpr hs6
              have d3hi : (0:ℝ) ≤ 1 - x3 := sub_nonneg.mpr hhi3
              linarith only [c4, mul_nonneg (mul_nonneg (d1hi) d2hi) d3hi, mul_nonneg (mul_nonneg (d1lo) d2hi) d3hi, mul_nonneg (mul_nonneg (d1hi) d2lo) d3hi, mul_nonneg (mul_nonneg (d1lo) d2lo) d3hi, mul_nonneg (mul_nonneg (d1hi) d2hi) d3lo, mul_nonneg (mul_nonneg (d1lo) d2hi) d3lo, mul_nonneg (mul_nonneg (d1hi) d2lo) d3lo, mul_nonneg (mul_nonneg (d1lo) d2lo) d3lo]
    · rcases le_total x3 (1 / 2 : ℝ) with hs3 | hs3
      · rcases le_total x1 (3 / 4 : ℝ) with hs4 | hs4
        · -- `contdev_2` ≥ 136537985 / 4348444672 > 0 on x1 ∈ [1 / 2, 3 / 4], x2 ∈ [1 / 2, 1], x3 ∈ [0, 1 / 2]
          have d1lo : (0:ℝ) ≤ x1 - 1 / 2 := sub_nonneg.mpr hs1
          have d1hi : (0:ℝ) ≤ 3 / 4 - x1 := sub_nonneg.mpr hs4
          have d2lo : (0:ℝ) ≤ x2 - 1 / 2 := sub_nonneg.mpr hs2
          have d2hi : (0:ℝ) ≤ 1 - x2 := sub_nonneg.mpr hhi2
          have d3lo : (0:ℝ) ≤ x3 - 0 := sub_nonneg.mpr hlo3
          have d3hi : (0:ℝ) ≤ 1 / 2 - x3 := sub_nonneg.mpr hs3
          linarith only [c4, mul_nonneg (mul_nonneg (d1hi) d2hi) d3hi, mul_nonneg (mul_nonneg (d1lo) d2hi) d3hi, mul_nonneg (mul_nonneg (d1hi) d2lo) d3hi, mul_nonneg (mul_nonneg (d1lo) d2lo) d3hi, mul_nonneg (mul_nonneg (d1hi) d2hi) d3lo, mul_nonneg (mul_nonneg (d1lo) d2hi) d3lo, mul_nonneg (mul_nonneg (d1hi) d2lo) d3lo, mul_nonneg (mul_nonneg (d1lo) d2lo) d3lo]
        · rcases le_total x2 (3 / 4 : ℝ) with hs5 | hs5
          · -- `contdev_4` ≥ 7110578212429 / 93753389875200 > 0 on x1 ∈ [3 / 4, 1], x2 ∈ [1 / 2, 3 / 4], x3 ∈ [0, 1 / 2]
            have d1lo : (0:ℝ) ≤ x1 - 3 / 4 := sub_nonneg.mpr hs4
            have d1hi : (0:ℝ) ≤ 1 - x1 := sub_nonneg.mpr hhi1
            have d2lo : (0:ℝ) ≤ x2 - 1 / 2 := sub_nonneg.mpr hs2
            have d2hi : (0:ℝ) ≤ 3 / 4 - x2 := sub_nonneg.mpr hs5
            have d3lo : (0:ℝ) ≤ x3 - 0 := sub_nonneg.mpr hlo3
            have d3hi : (0:ℝ) ≤ 1 / 2 - x3 := sub_nonneg.mpr hs3
            linarith only [c8, mul_nonneg (mul_nonneg (d1hi) d2hi) d3hi, mul_nonneg (mul_nonneg (d1lo) d2hi) d3hi, mul_nonneg (mul_nonneg (d1hi) d2lo) d3hi, mul_nonneg (mul_nonneg (d1lo) d2lo) d3hi, mul_nonneg (mul_nonneg (d1hi) d2hi) d3lo, mul_nonneg (mul_nonneg (d1lo) d2hi) d3lo, mul_nonneg (mul_nonneg (d1hi) d2lo) d3lo, mul_nonneg (mul_nonneg (d1lo) d2lo) d3lo]
          · rcases le_total x3 (1 / 4 : ℝ) with hs6 | hs6
            · -- `quitdev_3` ≥ 10817161 / 212860928 > 0 on x1 ∈ [3 / 4, 1], x2 ∈ [3 / 4, 1], x3 ∈ [0, 1 / 4]
              have d1lo : (0:ℝ) ≤ x1 - 3 / 4 := sub_nonneg.mpr hs4
              have d1hi : (0:ℝ) ≤ 1 - x1 := sub_nonneg.mpr hhi1
              have d2lo : (0:ℝ) ≤ x2 - 3 / 4 := sub_nonneg.mpr hs5
              have d2hi : (0:ℝ) ≤ 1 - x2 := sub_nonneg.mpr hhi2
              have d3lo : (0:ℝ) ≤ x3 - 0 := sub_nonneg.mpr hlo3
              have d3hi : (0:ℝ) ≤ 1 / 4 - x3 := sub_nonneg.mpr hs6
              linarith only [c5, mul_nonneg (mul_nonneg (d1hi) d2hi) d3hi, mul_nonneg (mul_nonneg (d1lo) d2hi) d3hi, mul_nonneg (mul_nonneg (d1hi) d2lo) d3hi, mul_nonneg (mul_nonneg (d1lo) d2lo) d3hi, mul_nonneg (mul_nonneg (d1hi) d2hi) d3lo, mul_nonneg (mul_nonneg (d1lo) d2hi) d3lo, mul_nonneg (mul_nonneg (d1hi) d2lo) d3lo, mul_nonneg (mul_nonneg (d1lo) d2lo) d3lo]
            · rcases le_total x1 (7 / 8 : ℝ) with hs7 | hs7
              · -- `contdev_2` ≥ 1061588611 / 13045334016 > 0 on x1 ∈ [3 / 4, 7 / 8], x2 ∈ [3 / 4, 1], x3 ∈ [1 / 4, 1 / 2]
                have d1lo : (0:ℝ) ≤ x1 - 3 / 4 := sub_nonneg.mpr hs4
                have d1hi : (0:ℝ) ≤ 7 / 8 - x1 := sub_nonneg.mpr hs7
                have d2lo : (0:ℝ) ≤ x2 - 3 / 4 := sub_nonneg.mpr hs5
                have d2hi : (0:ℝ) ≤ 1 - x2 := sub_nonneg.mpr hhi2
                have d3lo : (0:ℝ) ≤ x3 - 1 / 4 := sub_nonneg.mpr hs6
                have d3hi : (0:ℝ) ≤ 1 / 2 - x3 := sub_nonneg.mpr hs3
                linarith only [c4, mul_nonneg (mul_nonneg (d1hi) d2hi) d3hi, mul_nonneg (mul_nonneg (d1lo) d2hi) d3hi, mul_nonneg (mul_nonneg (d1hi) d2lo) d3hi, mul_nonneg (mul_nonneg (d1lo) d2lo) d3hi, mul_nonneg (mul_nonneg (d1hi) d2hi) d3lo, mul_nonneg (mul_nonneg (d1lo) d2hi) d3lo, mul_nonneg (mul_nonneg (d1hi) d2lo) d3lo, mul_nonneg (mul_nonneg (d1lo) d2lo) d3lo]
              · -- `quitdev_3` ≥ 5111023 / 30408704 > 0 on x1 ∈ [7 / 8, 1], x2 ∈ [3 / 4, 1], x3 ∈ [1 / 4, 1 / 2]
                have d1lo : (0:ℝ) ≤ x1 - 7 / 8 := sub_nonneg.mpr hs7
                have d1hi : (0:ℝ) ≤ 1 - x1 := sub_nonneg.mpr hhi1
                have d2lo : (0:ℝ) ≤ x2 - 3 / 4 := sub_nonneg.mpr hs5
                have d2hi : (0:ℝ) ≤ 1 - x2 := sub_nonneg.mpr hhi2
                have d3lo : (0:ℝ) ≤ x3 - 1 / 4 := sub_nonneg.mpr hs6
                have d3hi : (0:ℝ) ≤ 1 / 2 - x3 := sub_nonneg.mpr hs3
                linarith only [c5, mul_nonneg (mul_nonneg (d1hi) d2hi) d3hi, mul_nonneg (mul_nonneg (d1lo) d2hi) d3hi, mul_nonneg (mul_nonneg (d1hi) d2lo) d3hi, mul_nonneg (mul_nonneg (d1lo) d2lo) d3hi, mul_nonneg (mul_nonneg (d1hi) d2hi) d3lo, mul_nonneg (mul_nonneg (d1lo) d2hi) d3lo, mul_nonneg (mul_nonneg (d1hi) d2lo) d3lo, mul_nonneg (mul_nonneg (d1lo) d2lo) d3lo]
      · -- `contdev_2` ≥ 127749619 / 1049624576 > 0 on x1 ∈ [1 / 2, 1], x2 ∈ [1 / 2, 1], x3 ∈ [1 / 2, 1]
        have d1lo : (0:ℝ) ≤ x1 - 1 / 2 := sub_nonneg.mpr hs1
        have d1hi : (0:ℝ) ≤ 1 - x1 := sub_nonneg.mpr hhi1
        have d2lo : (0:ℝ) ≤ x2 - 1 / 2 := sub_nonneg.mpr hs2
        have d2hi : (0:ℝ) ≤ 1 - x2 := sub_nonneg.mpr hhi2
        have d3lo : (0:ℝ) ≤ x3 - 1 / 2 := sub_nonneg.mpr hs3
        have d3hi : (0:ℝ) ≤ 1 - x3 := sub_nonneg.mpr hhi3
        linarith only [c4, mul_nonneg (mul_nonneg (d1hi) d2hi) d3hi, mul_nonneg (mul_nonneg (d1lo) d2hi) d3hi, mul_nonneg (mul_nonneg (d1hi) d2lo) d3hi, mul_nonneg (mul_nonneg (d1lo) d2lo) d3hi, mul_nonneg (mul_nonneg (d1hi) d2hi) d3lo, mul_nonneg (mul_nonneg (d1lo) d2hi) d3lo, mul_nonneg (mul_nonneg (d1hi) d2lo) d3lo, mul_nonneg (mul_nonneg (d1lo) d2lo) d3lo]


/-- Certificate identifier proved in this module. The `#guard`
below turns a silently dropped certificate into a compile error. -/
def Seed202R78Gen011Face4Ids : List String :=
  ["v1/v0/seed202_r78_gen011/face_4"]

#guard Seed202R78Gen011Face4Ids.length = 1

end Quitting.V0
