-- GENERATED by code/julia/scripts/certificates/v0_from_recorded.jl — do not edit.
-- Regenerate and `git diff --exit-code` to prove the Lean corpus is a
-- pure function of the JSON certificates.

import Formal.Certificates.Prelude

set_option maxRecDepth 8000
set_option maxHeartbeats 1000000

namespace Quitting.V0


/-- Condition `quit_at_most_L` of `seed202_r78_gen011_minmax_lower_3`, with the sense the trace reads it in. The
certificate refutes the system in which all of them hold at once. -/
def seed202_r78_gen011_minmax_lower_3_f01 (x1 x2 _x3 x4 : ℝ) : Prop :=
  628215 / 262144 - 19 / 12 * x4 + 3 / 19 * x2 - 359 / 228 * x2 * x4 - 46 / 31 * x1 + 2903 / 2604 * x1 * x4 + 1370 / 589 * x1 * x2 + 1348175 / 1434804 * x1 * x2 * x4 ≤ 0

/-- Condition `wait_at_most_L` of `seed202_r78_gen011_minmax_lower_3`, with the sense the trace reads it in. The
certificate refutes the system in which all of them hold at once. -/
def seed202_r78_gen011_minmax_lower_3_f02 (x1 x2 _x3 x4 : ℝ) : Prop :=
  1938935 / 262144 * x4 - 682505 / 262144 * x2 - 1095159 / 262144 * x2 * x4 + 1676791 / 262144 * x1 - 3773943 / 262144 * x1 * x4 - 1152503 / 262144 * x1 * x2 + 9642469 / 786432 * x1 * x2 * x4 ≤ 0

end Quitting.V0
