-- GENERATED by code/julia/scripts/certificates/v0_from_recorded.jl — do not edit.
-- Regenerate and `git diff --exit-code` to prove the Lean corpus is a
-- pure function of the JSON certificates.

import Formal.Certificates.Prelude
import Formal.Certificates.V0.Seed202R78Gen011MinmaxLower3.Defs
import Formal.Certificates.V0.Seed202R78Gen011MinmaxLower3.Part01

set_option maxRecDepth 8000
set_option maxHeartbeats 1000000

namespace Quitting.V0


/-- with L = -366071/262144, no stationary punishment z of player 3 satisfies both a(z) <= L and b(z) <= L*q(z), so the smallest level w_3 admitting one exceeds L; and v^3 >= w_3 unconditionally (docs/V0_MINIMAX.md 2.1). Coordinate x3 is pinned to 0: the punishment is played by the other players.

Proved by the recorded subdivision of the box: every leaf carries one
condition that the Bernstein corner-basis expansion makes strictly
positive there. Machine-written. -/
theorem seed202_r78_gen011_minmax_lower_3
    (x1 x2 x3 x4 : ℝ)
    (hlo1 : (0 : ℝ) ≤ x1)
    (hhi1 : x1 ≤ (1 : ℝ))
    (hlo2 : (0 : ℝ) ≤ x2)
    (hhi2 : x2 ≤ (1 : ℝ))
    (hlo3 : (0 : ℝ) ≤ x3)
    (hhi3 : x3 ≤ (0 : ℝ))
    (hlo4 : (0 : ℝ) ≤ x4)
    (hhi4 : x4 ≤ (1 : ℝ))
    : ¬ (
      seed202_r78_gen011_minmax_lower_3_f01 x1 x2 x3 x4 ∧
      seed202_r78_gen011_minmax_lower_3_f02 x1 x2 x3 x4) := by
  rintro ⟨c1, c2⟩
  obtain rfl : x3 = (0 : ℝ) := le_antisymm hhi3 hlo3
  rcases le_total x1 (1 / 2 : ℝ) with hs1 | hs1
  · rcases le_total x2 (1 / 2 : ℝ) with hs2 | hs2
    · exact seed202_r78_gen011_minmax_lower_3_sub001 x1 x2 x4 hlo1 hs1 hlo2 hs2 hlo4 hhi4 c1
    · rcases le_total x4 (1 / 2 : ℝ) with hs3 | hs3
      · exact seed202_r78_gen011_minmax_lower_3_sub002 x1 x2 x4 hlo1 hs1 hs2 hhi2 hlo4 hs3 c1
      · rcases le_total x1 (1 / 4 : ℝ) with hs4 | hs4
        · rcases le_total x2 (3 / 4 : ℝ) with hs5 | hs5
          · exact seed202_r78_gen011_minmax_lower_3_sub003 x1 x2 x4 hlo1 hs4 hs2 hs5 hs3 hhi4 c2
          · rcases le_total x4 (3 / 4 : ℝ) with hs6 | hs6
            · exact seed202_r78_gen011_minmax_lower_3_sub004 x1 x2 x4 hlo1 hs4 hs5 hhi2 hs3 hs6 c1
            · rcases le_total x1 (1 / 8 : ℝ) with hs7 | hs7
              · rcases le_total x2 (7 / 8 : ℝ) with hs8 | hs8
                · exact seed202_r78_gen011_minmax_lower_3_sub005 x1 x2 x4 hlo1 hs7 hs5 hs8 hs6 hhi4 c2
                · rcases le_total x4 (7 / 8 : ℝ) with hs9 | hs9
                  · rcases le_total x1 (1 / 16 : ℝ) with hs10 | hs10
                    · rcases le_total x2 (15 / 16 : ℝ) with hs11 | hs11
                      · exact seed202_r78_gen011_minmax_lower_3_sub006 x1 x2 x4 hlo1 hs10 hs8 hs11 hs6 hs9 c2
                      · rcases le_total x4 (13 / 16 : ℝ) with hs12 | hs12
                        · rcases le_total x1 (1 / 32 : ℝ) with hs13 | hs13
                          · rcases le_total x2 (31 / 32 : ℝ) with hs14 | hs14
                            · exact seed202_r78_gen011_minmax_lower_3_sub007 x1 x2 x4 hlo1 hs13 hs11 hs14 hs6 hs12 c1
                            · rcases le_total x4 (25 / 32 : ℝ) with hs15 | hs15
                              · exact seed202_r78_gen011_minmax_lower_3_sub008 x1 x2 x4 hlo1 hs13 hs14 hhi2 hs6 hs15 c1
                              · rcases le_total x1 (1 / 64 : ℝ) with hs16 | hs16
                                · rcases le_total x2 (63 / 64 : ℝ) with hs17 | hs17
                                  · exact seed202_r78_gen011_minmax_lower_3_sub009 x1 x2 x4 hlo1 hs16 hs14 hs17 hs15 hs12 c1
                                  · rcases le_total x4 (51 / 64 : ℝ) with hs18 | hs18
                                    · exact seed202_r78_gen011_minmax_lower_3_sub010 x1 x2 x4 hlo1 hs16 hs17 hhi2 hs15 hs18 c1
                                    · rcases le_total x1 (1 / 128 : ℝ) with hs19 | hs19
                                      · rcases le_total x2 (127 / 128 : ℝ) with hs20 | hs20
                                        · exact seed202_r78_gen011_minmax_lower_3_sub011 x1 x2 x4 hlo1 hs19 hs17 hs20 hs18 hs12 c2
                                        · rcases le_total x4 (103 / 128 : ℝ) with hs21 | hs21
                                          · exact seed202_r78_gen011_minmax_lower_3_sub012 x1 x2 x4 hlo1 hs19 hs20 hhi2 hs18 hs21 c1
                                          · rcases le_total x1 (1 / 256 : ℝ) with hs22 | hs22
                                            · rcases le_total x2 (255 / 256 : ℝ) with hs23 | hs23
                                              · exact seed202_r78_gen011_minmax_lower_3_sub013 x1 x2 x4 hlo1 hs22 hs20 hs23 hs21 hs12 c2
                                              · rcases le_total x4 (207 / 256 : ℝ) with hs24 | hs24
                                                · exact seed202_r78_gen011_minmax_lower_3_sub014 x1 x2 x4 hlo1 hs22 hs23 hhi2 hs21 hs24 c1
                                                · rcases le_total x1 (1 / 512 : ℝ) with hs25 | hs25
                                                  · exact seed202_r78_gen011_minmax_lower_3_sub015 x1 x2 x4 hlo1 hs25 hs23 hhi2 hs24 hs12 c1 c2
                                                  · exact seed202_r78_gen011_minmax_lower_3_sub016 x1 x2 x4 hs25 hs22 hs23 hhi2 hs24 hs12 c1 c2
                                            · exact seed202_r78_gen011_minmax_lower_3_sub017 x1 x2 x4 hs22 hs19 hs20 hhi2 hs21 hs12 c1 c2
                                      · exact seed202_r78_gen011_minmax_lower_3_sub018 x1 x2 x4 hs19 hs16 hs17 hhi2 hs18 hs12 c1
                                · exact seed202_r78_gen011_minmax_lower_3_sub019 x1 x2 x4 hs16 hs13 hs14 hhi2 hs15 hs12 c1
                          · exact seed202_r78_gen011_minmax_lower_3_sub020 x1 x2 x4 hs13 hs10 hs11 hhi2 hs6 hs12 c1
                        · exact seed202_r78_gen011_minmax_lower_3_sub021 x1 x2 x4 hlo1 hs10 hs11 hhi2 hs12 hs9 c2
                    · exact seed202_r78_gen011_minmax_lower_3_sub022 x1 x2 x4 hs10 hs7 hs8 hhi2 hs6 hs9 c1 c2
                  · exact seed202_r78_gen011_minmax_lower_3_sub023 x1 x2 x4 hlo1 hs7 hs8 hhi2 hs9 hhi4 c2
              · exact seed202_r78_gen011_minmax_lower_3_sub024 x1 x2 x4 hs7 hs4 hs5 hhi2 hs6 hhi4 c1 c2
        · exact seed202_r78_gen011_minmax_lower_3_sub025 x1 x2 x4 hs4 hs1 hs2 hhi2 hs3 hhi4 c1
  · exact seed202_r78_gen011_minmax_lower_3_sub026 x1 x2 x4 hs1 hhi1 hlo2 hhi2 hlo4 hhi4 c1


/-- Certificate identifier proved in this module. The `#guard`
below turns a silently dropped certificate into a compile error. -/
def Seed202R78Gen011MinmaxLower3Ids : List String :=
  ["v1/v0/seed202_r78_gen011/minmax_lower_3"]

#guard Seed202R78Gen011MinmaxLower3Ids.length = 1

end Quitting.V0
