-- GENERATED by code/julia/scripts/certificates/dir_from_certified.jl — do not edit.
-- Regenerate and `git diff --exit-code` to prove the Lean corpus is a
-- pure function of the JSON certificates.

import Formal.Certificates.Prelude

set_option maxRecDepth 8000
set_option maxHeartbeats 1000000

namespace Quitting.Directional


/-- Condition `simplex` of `seed202_r78_gen011_dir_margin`, with the sense the trace reads it in. The
certificate refutes the system in which all of them hold at once. -/
def seed202_r78_gen011_dir_margin_f01 (d1 d2 d3 : ℝ) : Prop :=
  -1 + d3 + d2 + d1 ≤ 0

/-- Condition `gain_1` of `seed202_r78_gen011_dir_margin`, with the sense the trace reads it in. The
certificate refutes the system in which all of them hold at once. -/
def seed202_r78_gen011_dir_margin_f02 (d1 d2 d3 : ℝ) : Prop :=
  25643 / 49152 - 17 / 3 * d3 - d2 - 2 / 3 * d1 ≤ 0

/-- Condition `gain_2` of `seed202_r78_gen011_dir_margin`, with the sense the trace reads it in. The
certificate refutes the system in which all of them hold at once. -/
def seed202_r78_gen011_dir_margin_f03 (d1 d2 d3 : ℝ) : Prop :=
  -100679 / 16384 + 7 * d3 + 6 * d2 + 7 * d1 ≤ 0

/-- Condition `gain_3` of `seed202_r78_gen011_dir_margin`, with the sense the trace reads it in. The
certificate refutes the system in which all of them hold at once. -/
def seed202_r78_gen011_dir_margin_f04 (d1 d2 d3 : ℝ) : Prop :=
  -84295 / 16384 + 5 * d3 + 10 * d2 + d1 ≤ 0

/-- Condition `gain_4` of `seed202_r78_gen011_dir_margin`, with the sense the trace reads it in. The
certificate refutes the system in which all of them hold at once. -/
def seed202_r78_gen011_dir_margin_f05 (d1 d2 d3 : ℝ) : Prop :=
  -2375 / 16384 + 5 * d3 - d2 - 5 * d1 ≤ 0

/-- Condition `prod_1` of `seed202_r78_gen011_dir_margin`, with the sense the trace reads it in. The
certificate refutes the system in which all of them hold at once. -/
def seed202_r78_gen011_dir_margin_f06 (d1 d2 d3 : ℝ) : Prop :=
  -2375 / 16384 - 2 / 3 * d1 + 17 / 3 * d1 * d3 + d1 * d2 + 2 / 3 * d1 ^ 2 ≤ 0

/-- Condition `prod_2` of `seed202_r78_gen011_dir_margin`, with the sense the trace reads it in. The
certificate refutes the system in which all of them hold at once. -/
def seed202_r78_gen011_dir_margin_f07 (d1 d2 d3 : ℝ) : Prop :=
  -2375 / 16384 + 6 * d2 - 7 * d2 * d3 - 6 * d2 ^ 2 - 7 * d1 * d2 ≤ 0

/-- Condition `prod_3` of `seed202_r78_gen011_dir_margin`, with the sense the trace reads it in. The
certificate refutes the system in which all of them hold at once. -/
def seed202_r78_gen011_dir_margin_f08 (d1 d2 d3 : ℝ) : Prop :=
  -2375 / 16384 + 5 * d3 - 5 * d3 ^ 2 - 10 * d2 * d3 - d1 * d3 ≤ 0

/-- Condition `prod_4` of `seed202_r78_gen011_dir_margin`, with the sense the trace reads it in. The
certificate refutes the system in which all of them hold at once. -/
def seed202_r78_gen011_dir_margin_f09 (d1 d2 d3 : ℝ) : Prop :=
  -2375 / 16384 - 5 * d3 + 5 * d3 ^ 2 + d2 + 4 * d2 * d3 - d2 ^ 2 + 5 * d1 - 6 * d1 * d2 - 5 * d1 ^ 2 ≤ 0

end Quitting.Directional
