-- GENERATED by code/julia/scripts/certificates/dir_from_certified.jl — do not edit.
-- Regenerate and `git diff --exit-code` to prove the Lean corpus is a
-- pure function of the JSON certificates.

import Formal.Certificates.Prelude
import Formal.Certificates.Directional.Seed202R78Gen011Margin.Defs
import Formal.Certificates.Directional.Seed202R78Gen011Margin.Part01
import Formal.Certificates.Directional.Seed202R78Gen011Margin.Part02
import Formal.Certificates.Directional.Seed202R78Gen011Margin.Part03
import Formal.Certificates.Directional.Seed202R78Gen011Margin.Part04
import Formal.Certificates.Directional.Seed202R78Gen011Margin.Part05
import Formal.Certificates.Directional.Seed202R78Gen011Margin.Part06
import Formal.Certificates.Directional.Seed202R78Gen011Margin.Part07
import Formal.Certificates.Directional.Seed202R78Gen011Margin.Part08
import Formal.Certificates.Directional.Seed202R78Gen011Margin.Part09
import Formal.Certificates.Directional.Seed202R78Gen011Margin.Part10
import Formal.Certificates.Directional.Seed202R78Gen011Margin.Part11
import Formal.Certificates.Directional.Seed202R78Gen011Margin.Part12
import Formal.Certificates.Directional.Seed202R78Gen011Margin.Part13
import Formal.Certificates.Directional.Seed202R78Gen011Margin.Part14
import Formal.Certificates.Directional.Seed202R78Gen011Margin.Part15
import Formal.Certificates.Directional.Seed202R78Gen011Margin.Part16
import Formal.Certificates.Directional.Seed202R78Gen011Margin.Part17
import Formal.Certificates.Directional.Seed202R78Gen011Margin.Part18
import Formal.Certificates.Directional.Seed202R78Gen011Margin.Part19
import Formal.Certificates.Directional.Seed202R78Gen011Margin.Part20
import Formal.Certificates.Directional.Seed202R78Gen011Margin.Part21
import Formal.Certificates.Directional.Seed202R78Gen011Margin.Part22
import Formal.Certificates.Directional.Seed202R78Gen011Margin.Part23
import Formal.Certificates.Directional.Seed202R78Gen011Margin.Part24
import Formal.Certificates.Directional.Seed202R78Gen011Margin.Part25
import Formal.Certificates.Directional.Seed202R78Gen011Margin.Part26
import Formal.Certificates.Directional.Seed202R78Gen011Margin.Part27
import Formal.Certificates.Directional.Seed202R78Gen011Margin.Part28
import Formal.Certificates.Directional.Seed202R78Gen011Margin.Part29
import Formal.Certificates.Directional.Seed202R78Gen011Margin.Part30
import Formal.Certificates.Directional.Seed202R78Gen011Margin.Part31
import Formal.Certificates.Directional.Seed202R78Gen011Margin.Part32
import Formal.Certificates.Directional.Seed202R78Gen011Margin.Part33
import Formal.Certificates.Directional.Seed202R78Gen011Margin.Part34
import Formal.Certificates.Directional.Seed202R78Gen011Margin.Part35
import Formal.Certificates.Directional.Seed202R78Gen011Margin.Part36
import Formal.Certificates.Directional.Seed202R78Gen011Margin.Part37
import Formal.Certificates.Directional.Seed202R78Gen011Margin.Part38
import Formal.Certificates.Directional.Seed202R78Gen011Margin.Part39
import Formal.Certificates.Directional.Seed202R78Gen011Margin.Part40
import Formal.Certificates.Directional.Seed202R78Gen011Margin.Part41
import Formal.Certificates.Directional.Seed202R78Gen011Margin.Part42
import Formal.Certificates.Directional.Seed202R78Gen011Margin.Part43
import Formal.Certificates.Directional.Seed202R78Gen011Margin.Part44

set_option maxRecDepth 8000
set_option maxHeartbeats 1000000

namespace Quitting.Directional


/-- no direction d in the unit simplex leaves every term of nu(d) at most 2375/16384; equivalently min_{d in Delta} nu(d) > 2375/16384, where nu(d) = max_i max(g_i(d), d_i*(-g_i(d))) is the lower bound on the stationary deviation margin along the vanishing family x = t*d (docs/G1_LIMIT_LEMMA.md 3). The last coordinate is eliminated, d_4 = 1 - sum_j d_j, and the condition `simplex` is what excludes the part of the cube where that is negative. The bound is the quantitative form of `LCP(R,0) has only the trivial solution`, and it is the input the limit lemma consumes.

Proved by the recorded subdivision of the box: every leaf carries one
condition that the Bernstein corner-basis expansion makes strictly
positive there. Machine-written. -/
theorem seed202_r78_gen011_dir_margin
    (d1 d2 d3 : ℝ)
    (hlo1 : (0 : ℝ) ≤ d1)
    (hhi1 : d1 ≤ (1 : ℝ))
    (hlo2 : (0 : ℝ) ≤ d2)
    (hhi2 : d2 ≤ (1 : ℝ))
    (hlo3 : (0 : ℝ) ≤ d3)
    (hhi3 : d3 ≤ (1 : ℝ))
    : ¬ (
      seed202_r78_gen011_dir_margin_f01 d1 d2 d3 ∧
      seed202_r78_gen011_dir_margin_f02 d1 d2 d3 ∧
      seed202_r78_gen011_dir_margin_f03 d1 d2 d3 ∧
      seed202_r78_gen011_dir_margin_f04 d1 d2 d3 ∧
      seed202_r78_gen011_dir_margin_f05 d1 d2 d3 ∧
      seed202_r78_gen011_dir_margin_f06 d1 d2 d3 ∧
      seed202_r78_gen011_dir_margin_f07 d1 d2 d3 ∧
      seed202_r78_gen011_dir_margin_f08 d1 d2 d3 ∧
      seed202_r78_gen011_dir_margin_f09 d1 d2 d3) := by
  rintro ⟨_, c2, c3, c4, c5, c6, c7, c8, c9⟩
  rcases le_total d1 (1 / 2 : ℝ) with hs1 | hs1
  · rcases le_total d2 (1 / 2 : ℝ) with hs2 | hs2
    · rcases le_total d3 (1 / 2 : ℝ) with hs3 | hs3
      · rcases le_total d1 (1 / 4 : ℝ) with hs4 | hs4
        · rcases le_total d2 (1 / 4 : ℝ) with hs5 | hs5
          · exact seed202_r78_gen011_dir_margin_sub001 d1 d2 d3 hlo1 hs4 hlo2 hs5 hlo3 hs3 c2 c5 c6 c7 c8 c9
          · exact seed202_r78_gen011_dir_margin_sub002 d1 d2 d3 hlo1 hs4 hs5 hs2 hlo3 hs3 c4 c5 c6 c7
        · rcases le_total d2 (1 / 4 : ℝ) with hs5 | hs5
          · exact seed202_r78_gen011_dir_margin_sub003 d1 d2 d3 hs4 hs1 hlo2 hs5 hlo3 hs3 c6 c7 c8 c9
          · rcases le_total d3 (1 / 4 : ℝ) with hs6 | hs6
            · rcases le_total d1 (3 / 8 : ℝ) with hs7 | hs7
              · exact seed202_r78_gen011_dir_margin_sub004 d1 d2 d3 hs4 hs7 hs5 hs2 hlo3 hs6 c4 c6 c7 c9
              · rcases le_total d2 (3 / 8 : ℝ) with hs8 | hs8
                · exact seed202_r78_gen011_dir_margin_sub005 d1 d2 d3 hs7 hs1 hs5 hs8 hlo3 hs6 c6 c9
                · rcases le_total d3 (1 / 8 : ℝ) with hs9 | hs9
                  · rcases le_total d1 (7 / 16 : ℝ) with hs10 | hs10
                    · rcases le_total d2 (7 / 16 : ℝ) with hs11 | hs11
                      · exact seed202_r78_gen011_dir_margin_sub006 d1 d2 d3 hs7 hs10 hs8 hs11 hlo3 hs9 c6 c9
                      · exact seed202_r78_gen011_dir_margin_sub007 d1 d2 d3 hs7 hs10 hs11 hs2 hlo3 hs9 c4 c6 c9
                    · rcases le_total d2 (7 / 16 : ℝ) with hs11 | hs11
                      · rcases le_total d3 (1 / 16 : ℝ) with hs12 | hs12
                        · rcases le_total d1 (15 / 32 : ℝ) with hs13 | hs13
                          · rcases le_total d2 (13 / 32 : ℝ) with hs14 | hs14
                            · exact seed202_r78_gen011_dir_margin_sub008 d1 d2 d3 hs10 hs13 hs8 hs14 hlo3 hs12 c9
                            · rcases le_total d3 (1 / 32 : ℝ) with hs15 | hs15
                              · exact seed202_r78_gen011_dir_margin_sub009 d1 d2 d3 hs10 hs13 hs14 hs11 hlo3 hs15 c9
                              · rcases le_total d1 (29 / 64 : ℝ) with hs16 | hs16
                                · exact seed202_r78_gen011_dir_margin_sub010 d1 d2 d3 hs10 hs16 hs14 hs11 hs15 hs12 c6 c9
                                · rcases le_total d2 (27 / 64 : ℝ) with hs17 | hs17
                                  · exact seed202_r78_gen011_dir_margin_sub011 d1 d2 d3 hs16 hs13 hs14 hs17 hs15 hs12 c6 c9
                                  · rcases le_total d3 (3 / 64 : ℝ) with hs18 | hs18
                                    · rcases le_total d1 (59 / 128 : ℝ) with hs19 | hs19
                                      · exact seed202_r78_gen011_dir_margin_sub012 d1 d2 d3 hs16 hs19 hs17 hs11 hs15 hs18 c6 c9
                                      · rcases le_total d2 (55 / 128 : ℝ) with hs20 | hs20
                                        · exact seed202_r78_gen011_dir_margin_sub013 d1 d2 d3 hs19 hs13 hs17 hs20 hs15 hs18 c6 c9
                                        · rcases le_total d3 (5 / 128 : ℝ) with hs21 | hs21
                                          · exact seed202_r78_gen011_dir_margin_sub014 d1 d2 d3 hs19 hs13 hs20 hs11 hs15 hs21 c3 c9
                                          · rcases le_total d1 (119 / 256 : ℝ) with hs22 | hs22
                                            · exact seed202_r78_gen011_dir_margin_sub015 d1 d2 d3 hs19 hs22 hs20 hs11 hs21 hs18 c3 c6 c9
                                            · exact seed202_r78_gen011_dir_margin_sub016 d1 d2 d3 hs22 hs13 hs20 hs11 hs21 hs18 c3 c6 c9
                                    · exact seed202_r78_gen011_dir_margin_sub017 d1 d2 d3 hs16 hs13 hs17 hs11 hs18 hs12 c6
                          · rcases le_total d2 (13 / 32 : ℝ) with hs14 | hs14
                            · exact seed202_r78_gen011_dir_margin_sub018 d1 d2 d3 hs13 hs1 hs8 hs14 hlo3 hs12 c3 c6 c9
                            · rcases le_total d3 (1 / 32 : ℝ) with hs15 | hs15
                              · rcases le_total d1 (31 / 64 : ℝ) with hs16 | hs16
                                · exact seed202_r78_gen011_dir_margin_sub019 d1 d2 d3 hs13 hs16 hs14 hs11 hlo3 hs15 c3 c9
                                · rcases le_total d2 (27 / 64 : ℝ) with hs17 | hs17
                                  · exact seed202_r78_gen011_dir_margin_sub020 d1 d2 d3 hs16 hs1 hs14 hs17 hlo3 hs15 c3 c9
                                  · rcases le_total d3 (1 / 64 : ℝ) with hs18 | hs18
                                    · exact seed202_r78_gen011_dir_margin_sub021 d1 d2 d3 hs16 hs1 hs17 hs11 hlo3 hs18 c3 c9
                                    · rcases le_total d1 (63 / 128 : ℝ) with hs19 | hs19
                                      · exact seed202_r78_gen011_dir_margin_sub022 d1 d2 d3 hs16 hs19 hs17 hs11 hs18 hs15 c3 c9
                                      · exact seed202_r78_gen011_dir_margin_sub023 d1 d2 d3 hs19 hs1 hs17 hs11 hs18 hs15 c3 c9
                              · rcases le_total d1 (31 / 64 : ℝ) with hs16 | hs16
                                · rcases le_total d2 (27 / 64 : ℝ) with hs17 | hs17
                                  · exact seed202_r78_gen011_dir_margin_sub024 d1 d2 d3 hs13 hs16 hs14 hs17 hs15 hs12 c3 c6 c9
                                  · rcases le_total d3 (3 / 64 : ℝ) with hs18 | hs18
                                    · rcases le_total d1 (61 / 128 : ℝ) with hs19 | hs19
                                      · rcases le_total d2 (55 / 128 : ℝ) with hs20 | hs20
                                        · exact seed202_r78_gen011_dir_margin_sub025 d1 d2 d3 hs13 hs19 hs17 hs20 hs15 hs18 c3 c6 c9
                                        · rcases le_total d3 (5 / 128 : ℝ) with hs21 | hs21
                                          · exact seed202_r78_gen011_dir_margin_sub026 d1 d2 d3 hs13 hs19 hs20 hs11 hs15 hs21 c3 c9
                                          · exact seed202_r78_gen011_dir_margin_sub027 d1 d2 d3 hs13 hs19 hs20 hs11 hs21 hs18 c3 c9
                                      · exact seed202_r78_gen011_dir_margin_sub028 d1 d2 d3 hs19 hs16 hs17 hs11 hs15 hs18 c3 c9
                                    · exact seed202_r78_gen011_dir_margin_sub029 d1 d2 d3 hs13 hs16 hs17 hs11 hs18 hs12 c6
                                · exact seed202_r78_gen011_dir_margin_sub030 d1 d2 d3 hs16 hs1 hs14 hs11 hs15 hs12 c3 c6 c9
                        · exact seed202_r78_gen011_dir_margin_sub031 d1 d2 d3 hs10 hs1 hs8 hs11 hs12 hs9 c6
                      · rcases le_total d3 (1 / 16 : ℝ) with hs12 | hs12
                        · rcases le_total d1 (15 / 32 : ℝ) with hs13 | hs13
                          · rcases le_total d2 (15 / 32 : ℝ) with hs14 | hs14
                            · rcases le_total d3 (1 / 32 : ℝ) with hs15 | hs15
                              · rcases le_total d1 (29 / 64 : ℝ) with hs16 | hs16
                                · exact seed202_r78_gen011_dir_margin_sub032 d1 d2 d3 hs10 hs16 hs11 hs14 hlo3 hs15 c4 c9
                                · rcases le_total d2 (29 / 64 : ℝ) with hs17 | hs17
                                  · rcases le_total d3 (1 / 64 : ℝ) with hs18 | hs18
                                    · exact seed202_r78_gen011_dir_margin_sub033 d1 d2 d3 hs16 hs13 hs11 hs17 hlo3 hs18 c9
                                    · rcases le_total d1 (59 / 128 : ℝ) with hs19 | hs19
                                      · exact seed202_r78_gen011_dir_margin_sub034 d1 d2 d3 hs16 hs19 hs11 hs17 hs18 hs15 c3 c9
                                      · rcases le_total d2 (57 / 128 : ℝ) with hs20 | hs20
                                        · exact seed202_r78_gen011_dir_margin_sub035 d1 d2 d3 hs19 hs13 hs11 hs20 hs18 hs15 c3 c9
                                        · rcases le_total d3 (3 / 128 : ℝ) with hs21 | hs21
                                          · exact seed202_r78_gen011_dir_margin_sub036 d1 d2 d3 hs19 hs13 hs20 hs17 hs18 hs21 c9
                                          · rcases le_total d1 (119 / 256 : ℝ) with hs22 | hs22
                                            · rcases le_total d2 (115 / 256 : ℝ) with hs23 | hs23
                                              · exact seed202_r78_gen011_dir_margin_sub037 d1 d2 d3 hs19 hs22 hs20 hs23 hs21 hs15 c3 c9
                                              · exact seed202_r78_gen011_dir_margin_sub038 d1 d2 d3 hs19 hs22 hs23 hs17 hs21 hs15 c3 c9
                                            · rcases le_total d2 (115 / 256 : ℝ) with hs23 | hs23
                                              · exact seed202_r78_gen011_dir_margin_sub039 d1 d2 d3 hs22 hs13 hs20 hs23 hs21 hs15 c3 c9
                                              · exact seed202_r78_gen011_dir_margin_sub040 d1 d2 d3 hs22 hs13 hs23 hs17 hs21 hs15 c3 c9
                                  · rcases le_total d3 (1 / 64 : ℝ) with hs18 | hs18
                                    · exact seed202_r78_gen011_dir_margin_sub041 d1 d2 d3 hs16 hs13 hs17 hs14 hlo3 hs18 c4 c9
                                    · rcases le_total d1 (59 / 128 : ℝ) with hs19 | hs19
                                      · rcases le_total d2 (59 / 128 : ℝ) with hs20 | hs20
                                        · rcases le_total d3 (3 / 128 : ℝ) with hs21 | hs21
                                          · exact seed202_r78_gen011_dir_margin_sub042 d1 d2 d3 hs16 hs19 hs17 hs20 hs18 hs21 c4 c9
                                          · rcases le_total d1 (117 / 256 : ℝ) with hs22 | hs22
                                            · exact seed202_r78_gen011_dir_margin_sub043 d1 d2 d3 hs16 hs22 hs17 hs20 hs21 hs15 c4 c9
                                            · exact seed202_r78_gen011_dir_margin_sub044 d1 d2 d3 hs22 hs19 hs17 hs20 hs21 hs15 c3 c4 c9
                                        · exact seed202_r78_gen011_dir_margin_sub045 d1 d2 d3 hs16 hs19 hs20 hs14 hs18 hs15 c4 c9
                                      · rcases le_total d2 (59 / 128 : ℝ) with hs20 | hs20
                                        · rcases le_total d3 (3 / 128 : ℝ) with hs21 | hs21
                                          · rcases le_total d1 (119 / 256 : ℝ) with hs22 | hs22
                                            · exact seed202_r78_gen011_dir_margin_sub046 d1 d2 d3 hs19 hs22 hs17 hs20 hs18 hs21 c3 c4 c9
                                            · rcases le_total d2 (117 / 256 : ℝ) with hs23 | hs23
                                              · exact seed202_r78_gen011_dir_margin_sub047 d1 d2 d3 hs22 hs13 hs17 hs23 hs18 hs21 c3 c9
                                              · exact seed202_r78_gen011_dir_margin_sub048 d1 d2 d3 hs22 hs13 hs23 hs20 hs18 hs21 c3 c4 c9
                                          · rcases le_total d1 (119 / 256 : ℝ) with hs22 | hs22
                                            · rcases le_total d2 (117 / 256 : ℝ) with hs23 | hs23
                                              · rcases le_total d3 (7 / 256 : ℝ) with hs24 | hs24
                                                · exact seed202_r78_gen011_dir_margin_sub049 d1 d2 d3 hs19 hs22 hs17 hs23 hs21 hs24 c3 c4 c9
                                                · exact seed202_r78_gen011_dir_margin_sub050 d1 d2 d3 hs19 hs22 hs17 hs23 hs24 hs15 c3 c9
                                              · exact seed202_r78_gen011_dir_margin_sub051 d1 d2 d3 hs19 hs22 hs23 hs20 hs21 hs15 c4
                                            · exact seed202_r78_gen011_dir_margin_sub052 d1 d2 d3 hs22 hs13 hs17 hs20 hs21 hs15 c3 c9
                                        · exact seed202_r78_gen011_dir_margin_sub053 d1 d2 d3 hs19 hs13 hs20 hs14 hs18 hs15 c4
                              · rcases le_total d1 (29 / 64 : ℝ) with hs16 | hs16
                                · rcases le_total d2 (29 / 64 : ℝ) with hs17 | hs17
                                  · rcases le_total d3 (3 / 64 : ℝ) with hs18 | hs18
                                    · rcases le_total d1 (57 / 128 : ℝ) with hs19 | hs19
                                      · exact seed202_r78_gen011_dir_margin_sub054 d1 d2 d3 hs10 hs19 hs11 hs17 hs15 hs18 c4 c6 c9
                                      · rcases le_total d2 (57 / 128 : ℝ) with hs20 | hs20
                                        · exact seed202_r78_gen011_dir_margin_sub055 d1 d2 d3 hs19 hs16 hs11 hs20 hs15 hs18 c6 c9
                                        · rcases le_total d3 (5 / 128 : ℝ) with hs21 | hs21
                                          · exact seed202_r78_gen011_dir_margin_sub056 d1 d2 d3 hs19 hs16 hs20 hs17 hs15 hs21 c4 c9
                                          · rcases le_total d1 (115 / 256 : ℝ) with hs22 | hs22
                                            · exact seed202_r78_gen011_dir_margin_sub057 d1 d2 d3 hs19 hs22 hs20 hs17 hs21 hs18 c4 c6 c9
                                            · rcases le_total d2 (115 / 256 : ℝ) with hs23 | hs23
                                              · rcases le_total d3 (11 / 256 : ℝ) with hs24 | hs24
                                                · rcases le_total d1 (231 / 512 : ℝ) with hs25 | hs25
                                                  · rcases le_total d2 (229 / 512 : ℝ) with hs26 | hs26
                                                    · exact seed202_r78_gen011_dir_margin_sub058 d1 d2 d3 hs22 hs25 hs20 hs26 hs21 hs24 c9
                                                    · rcases le_total d3 (21 / 512 : ℝ) with hs27 | hs27
                                                      · exact seed202_r78_gen011_dir_margin_sub059 d1 d2 d3 hs22 hs25 hs26 hs23 hs21 hs27 c9
                                                      · rcases le_total d1 (461 / 1024 : ℝ) with hs28 | hs28
                                                        · exact seed202_r78_gen011_dir_margin_sub060 d1 d2 d3 hs22 hs28 hs26 hs23 hs27 hs24 c4 c6 c9
                                                        · exact seed202_r78_gen011_dir_margin_sub061 d1 d2 d3 hs28 hs25 hs26 hs23 hs27 hs24 c4 c6 c9
                                                  · rcases le_total d2 (229 / 512 : ℝ) with hs26 | hs26
                                                    · rcases le_total d3 (21 / 512 : ℝ) with hs27 | hs27
                                                      · exact seed202_r78_gen011_dir_margin_sub062 d1 d2 d3 hs25 hs16 hs20 hs26 hs21 hs27 c9
                                                      · rcases le_total d1 (463 / 1024 : ℝ) with hs28 | hs28
                                                        · exact seed202_r78_gen011_dir_margin_sub063 d1 d2 d3 hs25 hs28 hs20 hs26 hs27 hs24 c6 c9
                                                        · rcases le_total d2 (457 / 1024 : ℝ) with hs29 | hs29
                                                          · exact seed202_r78_gen011_dir_margin_sub064 d1 d2 d3 hs28 hs16 hs20 hs29 hs27 hs24 c6 c9
                                                          · rcases le_total d3 (43 / 1024 : ℝ) with hs30 | hs30
                                                            · exact seed202_r78_gen011_dir_margin_sub065 d1 d2 d3 hs28 hs16 hs29 hs26 hs27 hs30 c3 c9
                                                            · exact seed202_r78_gen011_dir_margin_sub066 d1 d2 d3 hs28 hs16 hs29 hs26 hs30 hs24 c3 c6 c9
                                                    · rcases le_total d3 (21 / 512 : ℝ) with hs27 | hs27
                                                      · rcases le_total d1 (463 / 1024 : ℝ) with hs28 | hs28
                                                        · exact seed202_r78_gen011_dir_margin_sub067 d1 d2 d3 hs25 hs28 hs26 hs23 hs21 hs27 c4 c9
                                                        · rcases le_total d2 (459 / 1024 : ℝ) with hs29 | hs29
                                                          · exact seed202_r78_gen011_dir_margin_sub068 d1 d2 d3 hs28 hs16 hs26 hs29 hs21 hs27 c3 c9
                                                          · rcases le_total d3 (41 / 1024 : ℝ) with hs30 | hs30
                                                            · exact seed202_r78_gen011_dir_margin_sub069 d1 d2 d3 hs28 hs16 hs29 hs23 hs21 hs30 c3 c9
                                                            · rcases le_total d1 (927 / 2048 : ℝ) with hs31 | hs31
                                                              · rcases le_total d2 (919 / 2048 : ℝ) with hs32 | hs32
                                                                · exact seed202_r78_gen011_dir_margin_sub070 d1 d2 d3 hs28 hs31 hs29 hs32 hs30 hs27 c3 c9
                                                                · rcases le_total d3 (83 / 2048 : ℝ) with hs33 | hs33
                                                                  · exact seed202_r78_gen011_dir_margin_sub071 d1 d2 d3 hs28 hs31 hs32 hs23 hs30 hs33 c3 c4 c9
                                                                  · rcases le_total d1 (1853 / 4096 : ℝ) with hs34 | hs34
                                                                    · exact seed202_r78_gen011_dir_margin_sub072 d1 d2 d3 hs28 hs34 hs32 hs23 hs33 hs27 c3 c4 c9
                                                                    · exact seed202_r78_gen011_dir_margin_sub073 d1 d2 d3 hs34 hs31 hs32 hs23 hs33 hs27 c3 c9
                                                              · rcases le_total d2 (919 / 2048 : ℝ) with hs32 | hs32
                                                                · rcases le_total d3 (83 / 2048 : ℝ) with hs33 | hs33
                                                                  · exact seed202_r78_gen011_dir_margin_sub074 d1 d2 d3 hs31 hs16 hs29 hs32 hs30 hs33 c3 c9
                                                                  · exact seed202_r78_gen011_dir_margin_sub075 d1 d2 d3 hs31 hs16 hs29 hs32 hs33 hs27 c3 c9
                                                                · exact seed202_r78_gen011_dir_margin_sub076 d1 d2 d3 hs31 hs16 hs32 hs23 hs30 hs27 c3 c9
                                                      · rcases le_total d1 (463 / 1024 : ℝ) with hs28 | hs28
                                                        · rcases le_total d2 (459 / 1024 : ℝ) with hs29 | hs29
                                                          · rcases le_total d3 (43 / 1024 : ℝ) with hs30 | hs30
                                                            · rcases le_total d1 (925 / 2048 : ℝ) with hs31 | hs31
                                                              · exact seed202_r78_gen011_dir_margin_sub077 d1 d2 d3 hs25 hs31 hs26 hs29 hs27 hs30 c9
                                                              · rcases le_total d2 (917 / 2048 : ℝ) with hs32 | hs32
                                                                · exact seed202_r78_gen011_dir_margin_sub078 d1 d2 d3 hs31 hs28 hs26 hs32 hs27 hs30 c9
                                                                · rcases le_total d3 (85 / 2048 : ℝ) with hs33 | hs33
                                                                  · exact seed202_r78_gen011_dir_margin_sub079 d1 d2 d3 hs31 hs28 hs32 hs29 hs27 hs33 c9
                                                                  · rcases le_total d1 (1851 / 4096 : ℝ) with hs34 | hs34
                                                                    · rcases le_total d2 (1835 / 4096 : ℝ) with hs35 | hs35
                                                                      · exact seed202_r78_gen011_dir_margin_sub080 d1 d2 d3 hs31 hs34 hs32 hs35 hs33 hs30 c9
                                                                      · rcases le_total d3 (171 / 4096 : ℝ) with hs36 | hs36
                                                                        · exact seed202_r78_gen011_dir_margin_sub081 d1 d2 d3 hs31 hs34 hs35 hs29 hs33 hs36 c9
                                                                        · rcases le_total d1 (3701 / 8192 : ℝ) with hs37 | hs37
                                                                          · exact seed202_r78_gen011_dir_margin_sub082 d1 d2 d3 hs31 hs37 hs35 hs29 hs36 hs30 c3 c9
                                                                          · exact seed202_r78_gen011_dir_margin_sub083 d1 d2 d3 hs37 hs34 hs35 hs29 hs36 hs30 c3 c9
                                                                    · rcases le_total d2 (1835 / 4096 : ℝ) with hs35 | hs35
                                                                      · exact seed202_r78_gen011_dir_margin_sub084 d1 d2 d3 hs34 hs28 hs32 hs35 hs33 hs30 c3 c9
                                                                      · rcases le_total d3 (171 / 4096 : ℝ) with hs36 | hs36
                                                                        · exact seed202_r78_gen011_dir_margin_sub085 d1 d2 d3 hs34 hs28 hs35 hs29 hs33 hs36 c3 c9
                                                                        · exact seed202_r78_gen011_dir_margin_sub086 d1 d2 d3 hs34 hs28 hs35 hs29 hs36 hs30 c3 c9
                                                            · rcases le_total d1 (925 / 2048 : ℝ) with hs31 | hs31
                                                              · rcases le_total d2 (917 / 2048 : ℝ) with hs32 | hs32
                                                                · exact seed202_r78_gen011_dir_margin_sub087 d1 d2 d3 hs25 hs31 hs26 hs32 hs30 hs24 c6 c9
                                                                · rcases le_total d3 (87 / 2048 : ℝ) with hs33 | hs33
                                                                  · rcases le_total d1 (1849 / 4096 : ℝ) with hs34 | hs34
                                                                    · exact seed202_r78_gen011_dir_margin_sub088 d1 d2 d3 hs25 hs34 hs32 hs29 hs30 hs33 c6 c9
                                                                    · rcases le_total d2 (1835 / 4096 : ℝ) with hs35 | hs35
                                                                      · exact seed202_r78_gen011_dir_margin_sub089 d1 d2 d3 hs34 hs31 hs32 hs35 hs30 hs33 c6 c9
                                                                      · rcases le_total d3 (173 / 4096 : ℝ) with hs36 | hs36
                                                                        · rcases le_total d1 (3699 / 8192 : ℝ) with hs37 | hs37
                                                                          · exact seed202_r78_gen011_dir_margin_sub090 d1 d2 d3 hs34 hs37 hs35 hs29 hs30 hs36 c6 c9
                                                                          · rcases le_total d2 (3671 / 8192 : ℝ) with hs38 | hs38
                                                                            · exact seed202_r78_gen011_dir_margin_sub091 d1 d2 d3 hs37 hs31 hs35 hs38 hs30 hs36 c6 c9
                                                                            · rcases le_total d3 (345 / 8192 : ℝ) with hs39 | hs39
                                                                              · rcases le_total d1 (7399 / 16384 : ℝ) with hs40 | hs40
                                                                                · exact seed202_r78_gen011_dir_margin_sub092 d1 d2 d3 hs37 hs40 hs38 hs29 hs30 hs39 c6 c9
                                                                                · exact seed202_r78_gen011_dir_margin_sub093 d1 d2 d3 hs40 hs31 hs38 hs29 hs30 hs39 c3 c6 c9
                                                                              · exact seed202_r78_gen011_dir_margin_sub094 d1 d2 d3 hs37 hs31 hs38 hs29 hs39 hs36 c6
                                                                        · exact seed202_r78_gen011_dir_margin_sub095 d1 d2 d3 hs34 hs31 hs35 hs29 hs36 hs33 c6
                                                                  · exact seed202_r78_gen011_dir_margin_sub096 d1 d2 d3 hs25 hs31 hs32 hs29 hs33 hs24 c6
                                                              · rcases le_total d2 (917 / 2048 : ℝ) with hs32 | hs32
                                                                · exact seed202_r78_gen011_dir_margin_sub097 d1 d2 d3 hs31 hs28 hs26 hs32 hs30 hs24 c3 c6 c9
                                                                · rcases le_total d3 (87 / 2048 : ℝ) with hs33 | hs33
                                                                  · rcases le_total d1 (1851 / 4096 : ℝ) with hs34 | hs34
                                                                    · rcases le_total d2 (1835 / 4096 : ℝ) with hs35 | hs35
                                                                      · exact seed202_r78_gen011_dir_margin_sub098 d1 d2 d3 hs31 hs34 hs32 hs35 hs30 hs33 c3 c6 c9
                                                                      · rcases le_total d3 (173 / 4096 : ℝ) with hs36 | hs36
                                                                        · rcases le_total d1 (3701 / 8192 : ℝ) with hs37 | hs37
                                                                          · rcases le_total d2 (3671 / 8192 : ℝ) with hs38 | hs38
                                                                            · exact seed202_r78_gen011_dir_margin_sub099 d1 d2 d3 hs31 hs37 hs35 hs38 hs30 hs36 c3 c6 c9
                                                                            · rcases le_total d3 (345 / 8192 : ℝ) with hs39 | hs39
                                                                              · rcases le_total d1 (7401 / 16384 : ℝ) with hs40 | hs40
                                                                                · exact seed202_r78_gen011_dir_margin_sub100 d1 d2 d3 hs31 hs40 hs38 hs29 hs30 hs39 c3 c6 c9
                                                                                · exact seed202_r78_gen011_dir_margin_sub101 d1 d2 d3 hs40 hs37 hs38 hs29 hs30 hs39 c3 c9
                                                                              · exact seed202_r78_gen011_dir_margin_sub102 d1 d2 d3 hs31 hs37 hs38 hs29 hs39 hs36 c3
                                                                          · exact seed202_r78_gen011_dir_margin_sub103 d1 d2 d3 hs37 hs34 hs35 hs29 hs30 hs36 c3 c9
                                                                        · exact seed202_r78_gen011_dir_margin_sub104 d1 d2 d3 hs31 hs34 hs35 hs29 hs36 hs33 c3
                                                                    · exact seed202_r78_gen011_dir_margin_sub105 d1 d2 d3 hs34 hs28 hs32 hs29 hs30 hs33 c3 c6 c9
                                                                  · exact seed202_r78_gen011_dir_margin_sub106 d1 d2 d3 hs31 hs28 hs32 hs29 hs33 hs24 c3
                                                          · rcases le_total d3 (43 / 1024 : ℝ) with hs30 | hs30
                                                            · rcases le_total d1 (925 / 2048 : ℝ) with hs31 | hs31
                                                              · rcases le_total d2 (919 / 2048 : ℝ) with hs32 | hs32
                                                                · rcases le_total d3 (85 / 2048 : ℝ) with hs33 | hs33
                                                                  · exact seed202_r78_gen011_dir_margin_sub107 d1 d2 d3 hs25 hs31 hs29 hs32 hs27 hs33 c9
                                                                  · rcases le_total d1 (1849 / 4096 : ℝ) with hs34 | hs34
                                                                    · exact seed202_r78_gen011_dir_margin_sub108 d1 d2 d3 hs25 hs34 hs29 hs32 hs33 hs30 c4 c9
                                                                    · rcases le_total d2 (1837 / 4096 : ℝ) with hs35 | hs35
                                                                      · rcases le_total d3 (171 / 4096 : ℝ) with hs36 | hs36
                                                                        · exact seed202_r78_gen011_dir_margin_sub109 d1 d2 d3 hs34 hs31 hs29 hs35 hs33 hs36 c9
                                                                        · rcases le_total d1 (3699 / 8192 : ℝ) with hs37 | hs37
                                                                          · exact seed202_r78_gen011_dir_margin_sub110 d1 d2 d3 hs34 hs37 hs29 hs35 hs36 hs30 c4 c9
                                                                          · rcases le_total d2 (3673 / 8192 : ℝ) with hs38 | hs38
                                                                            · rcases le_total d3 (343 / 8192 : ℝ) with hs39 | hs39
                                                                              · exact seed202_r78_gen011_dir_margin_sub111 d1 d2 d3 hs37 hs31 hs29 hs38 hs36 hs39 c9
                                                                              · rcases le_total d1 (7399 / 16384 : ℝ) with hs40 | hs40
                                                                                · exact seed202_r78_gen011_dir_margin_sub112 d1 d2 d3 hs37 hs40 hs29 hs38 hs39 hs30 c3 c4 c9
                                                                                · rcases le_total d2 (7345 / 16384 : ℝ) with hs41 | hs41
                                                                                  · exact seed202_r78_gen011_dir_margin_sub113 d1 d2 d3 hs40 hs31 hs29 hs41 hs39 hs30 c3 c9
                                                                                  · exact seed202_r78_gen011_dir_margin_sub114 d1 d2 d3 hs40 hs31 hs41 hs38 hs39 hs30 c3 c9
                                                                            · rcases le_total d3 (343 / 8192 : ℝ) with hs39 | hs39
                                                                              · exact seed202_r78_gen011_dir_margin_sub115 d1 d2 d3 hs37 hs31 hs38 hs35 hs36 hs39 c4 c9
                                                                              · exact seed202_r78_gen011_dir_margin_sub116 d1 d2 d3 hs37 hs31 hs38 hs35 hs39 hs30 c3 c4 c9
                                                                      · exact seed202_r78_gen011_dir_margin_sub117 d1 d2 d3 hs34 hs31 hs35 hs32 hs33 hs30 c4 c9
                                                                · exact seed202_r78_gen011_dir_margin_sub118 d1 d2 d3 hs25 hs31 hs32 hs23 hs27 hs30 c4 c9
                                                              · rcases le_total d2 (919 / 2048 : ℝ) with hs32 | hs32
                                                                · rcases le_total d3 (85 / 2048 : ℝ) with hs33 | hs33
                                                                  · rcases le_total d1 (1851 / 4096 : ℝ) with hs34 | hs34
                                                                    · exact seed202_r78_gen011_dir_margin_sub119 d1 d2 d3 hs31 hs34 hs29 hs32 hs27 hs33 c4 c9
                                                                    · rcases le_total d2 (1837 / 4096 : ℝ) with hs35 | hs35
                                                                      · exact seed202_r78_gen011_dir_margin_sub120 d1 d2 d3 hs34 hs28 hs29 hs35 hs27 hs33 c3 c9
                                                                      · rcases le_total d3 (169 / 4096 : ℝ) with hs36 | hs36
                                                                        · exact seed202_r78_gen011_dir_margin_sub121 d1 d2 d3 hs34 hs28 hs35 hs32 hs27 hs36 c3 c9
                                                                        · rcases le_total d1 (3703 / 8192 : ℝ) with hs37 | hs37
                                                                          · exact seed202_r78_gen011_dir_margin_sub122 d1 d2 d3 hs34 hs37 hs35 hs32 hs36 hs33 c3 c4 c9
                                                                          · exact seed202_r78_gen011_dir_margin_sub123 d1 d2 d3 hs37 hs28 hs35 hs32 hs36 hs33 c3 c9
                                                                  · rcases le_total d1 (1851 / 4096 : ℝ) with hs34 | hs34
                                                                    · rcases le_total d2 (1837 / 4096 : ℝ) with hs35 | hs35
                                                                      · rcases le_total d3 (171 / 4096 : ℝ) with hs36 | hs36
                                                                        · rcases le_total d1 (3701 / 8192 : ℝ) with hs37 | hs37
                                                                          · exact seed202_r78_gen011_dir_margin_sub124 d1 d2 d3 hs31 hs37 hs29 hs35 hs33 hs36 c3 c9
                                                                          · exact seed202_r78_gen011_dir_margin_sub125 d1 d2 d3 hs37 hs34 hs29 hs35 hs33 hs36 c3 c9
                                                                        · rcases le_total d1 (3701 / 8192 : ℝ) with hs37 | hs37
                                                                          · rcases le_total d2 (3673 / 8192 : ℝ) with hs38 | hs38
                                                                            · rcases le_total d3 (343 / 8192 : ℝ) with hs39 | hs39
                                                                              · exact seed202_r78_gen011_dir_margin_sub126 d1 d2 d3 hs31 hs37 hs29 hs38 hs36 hs39 c3 c9
                                                                              · rcases le_total d1 (7401 / 16384 : ℝ) with hs40 | hs40
                                                                                · rcases le_total d2 (7345 / 16384 : ℝ) with hs41 | hs41
                                                                                  · exact seed202_r78_gen011_dir_margin_sub127 d1 d2 d3 hs31 hs40 hs29 hs41 hs39 hs30 c3 c9
                                                                                  · exact seed202_r78_gen011_dir_margin_sub128 d1 d2 d3 hs31 hs40 hs41 hs38 hs39 hs30 c3 c9
                                                                                · exact seed202_r78_gen011_dir_margin_sub129 d1 d2 d3 hs40 hs37 hs29 hs38 hs39 hs30 c3 c9
                                                                            · rcases le_total d3 (343 / 8192 : ℝ) with hs39 | hs39
                                                                              · rcases le_total d1 (7401 / 16384 : ℝ) with hs40 | hs40
                                                                                · exact seed202_r78_gen011_dir_margin_sub130 d1 d2 d3 hs31 hs40 hs38 hs35 hs36 hs39 c3 c4 c9
                                                                                · exact seed202_r78_gen011_dir_margin_sub131 d1 d2 d3 hs40 hs37 hs38 hs35 hs36 hs39 c3 c9
                                                                              · exact seed202_r78_gen011_dir_margin_sub132 d1 d2 d3 hs31 hs37 hs38 hs35 hs39 hs30 c3 c9
                                                                          · exact seed202_r78_gen011_dir_margin_sub133 d1 d2 d3 hs37 hs34 hs29 hs35 hs36 hs30 c3 c9
                                                                      · exact seed202_r78_gen011_dir_margin_sub134 d1 d2 d3 hs31 hs34 hs35 hs32 hs33 hs30 c3 c4 c9
                                                                    · rcases le_total d2 (1837 / 4096 : ℝ) with hs35 | hs35
                                                                      · rcases le_total d3 (171 / 4096 : ℝ) with hs36 | hs36
                                                                        · rcases le_total d1 (3703 / 8192 : ℝ) with hs37 | hs37
                                                                          · exact seed202_r78_gen011_dir_margin_sub135 d1 d2 d3 hs34 hs37 hs29 hs35 hs33 hs36 c3 c9
                                                                          · exact seed202_r78_gen011_dir_margin_sub136 d1 d2 d3 hs37 hs28 hs29 hs35 hs33 hs36 c3 c9
                                                                        · exact seed202_r78_gen011_dir_margin_sub137 d1 d2 d3 hs34 hs28 hs29 hs35 hs36 hs30 c3
                                                                      · exact seed202_r78_gen011_dir_margin_sub138 d1 d2 d3 hs34 hs28 hs35 hs32 hs33 hs30 c3 c9
                                                                · exact seed202_r78_gen011_dir_margin_sub139 d1 d2 d3 hs31 hs28 hs32 hs23 hs27 hs30 c4 c9
                                                            · rcases le_total d1 (925 / 2048 : ℝ) with hs31 | hs31
                                                              · rcases le_total d2 (919 / 2048 : ℝ) with hs32 | hs32
                                                                · rcases le_total d3 (87 / 2048 : ℝ) with hs33 | hs33
                                                                  · rcases le_total d1 (1849 / 4096 : ℝ) with hs34 | hs34
                                                                    · exact seed202_r78_gen011_dir_margin_sub140 d1 d2 d3 hs25 hs34 hs29 hs32 hs30 hs33 c4 c6 c9
                                                                    · rcases le_total d2 (1837 / 4096 : ℝ) with hs35 | hs35
                                                                      · rcases le_total d3 (173 / 4096 : ℝ) with hs36 | hs36
                                                                        · rcases le_total d1 (3699 / 8192 : ℝ) with hs37 | hs37
                                                                          · rcases le_total d2 (3673 / 8192 : ℝ) with hs38 | hs38
                                                                            · rcases le_total d3 (345 / 8192 : ℝ) with hs39 | hs39
                                                                              · rcases le_total d1 (7397 / 16384 : ℝ) with hs40 | hs40
                                                                                · exact seed202_r78_gen011_dir_margin_sub141 d1 d2 d3 hs34 hs40 hs29 hs38 hs30 hs39 c4 c9
                                                                                · rcases le_total d2 (7345 / 16384 : ℝ) with hs41 | hs41
                                                                                  · exact seed202_r78_gen011_dir_margin_sub142 d1 d2 d3 hs40 hs37 hs29 hs41 hs30 hs39 c3 c6 c9
                                                                                  · rcases le_total d3 (689 / 16384 : ℝ) with hs42 | hs42
                                                                                    · exact seed202_r78_gen011_dir_margin_sub143 d1 d2 d3 hs40 hs37 hs41 hs38 hs30 hs42 c4 c9
                                                                                    · exact seed202_r78_gen011_dir_margin_sub144 d1 d2 d3 hs40 hs37 hs41 hs38 hs42 hs39 c3 c4 c6 c9
                                                                              · exact seed202_r78_gen011_dir_margin_sub145 d1 d2 d3 hs34 hs37 hs29 hs38 hs39 hs36 c6
                                                                            · exact seed202_r78_gen011_dir_margin_sub146 d1 d2 d3 hs34 hs37 hs38 hs35 hs30 hs36 c4
                                                                          · rcases le_total d2 (3673 / 8192 : ℝ) with hs38 | hs38
                                                                            · rcases le_total d3 (345 / 8192 : ℝ) with hs39 | hs39
                                                                              · rcases le_total d1 (7399 / 16384 : ℝ) with hs40 | hs40
                                                                                · rcases le_total d2 (7345 / 16384 : ℝ) with hs41 | hs41
                                                                                  · rcases le_total d3 (689 / 16384 : ℝ) with hs42 | hs42
                                                                                    · exact seed202_r78_gen011_dir_margin_sub147 d1 d2 d3 hs37 hs40 hs29 hs41 hs30 hs42 c3 c9
                                                                                    · exact seed202_r78_gen011_dir_margin_sub148 d1 d2 d3 hs37 hs40 hs29 hs41 hs42 hs39 c3 c6 c9
                                                                                  · rcases le_total d3 (689 / 16384 : ℝ) with hs42 | hs42
                                                                                    · rcases le_total d1 (14797 / 32768 : ℝ) with hs43 | hs43
                                                                                      · exact seed202_r78_gen011_dir_margin_sub149 d1 d2 d3 hs37 hs43 hs41 hs38 hs30 hs42 c3 c4 c9
                                                                                      · exact seed202_r78_gen011_dir_margin_sub150 d1 d2 d3 hs43 hs40 hs41 hs38 hs30 hs42 c3 c9
                                                                                    · exact seed202_r78_gen011_dir_margin_sub151 d1 d2 d3 hs37 hs40 hs41 hs38 hs42 hs39 c3 c9
                                                                                · exact seed202_r78_gen011_dir_margin_sub152 d1 d2 d3 hs40 hs31 hs29 hs38 hs30 hs39 c3 c9
                                                                              · exact seed202_r78_gen011_dir_margin_sub153 d1 d2 d3 hs37 hs31 hs29 hs38 hs39 hs36 c3
                                                                            · exact seed202_r78_gen011_dir_margin_sub154 d1 d2 d3 hs37 hs31 hs38 hs35 hs30 hs36 c4
                                                                        · exact seed202_r78_gen011_dir_margin_sub155 d1 d2 d3 hs34 hs31 hs29 hs35 hs36 hs33 c3
                                                                      · exact seed202_r78_gen011_dir_margin_sub156 d1 d2 d3 hs34 hs31 hs35 hs32 hs30 hs33 c4
                                                                  · exact seed202_r78_gen011_dir_margin_sub157 d1 d2 d3 hs25 hs31 hs29 hs32 hs33 hs24 c3
                                                                · exact seed202_r78_gen011_dir_margin_sub158 d1 d2 d3 hs25 hs31 hs32 hs23 hs30 hs24 c4
                                                              · exact seed202_r78_gen011_dir_margin_sub159 d1 d2 d3 hs31 hs28 hs29 hs23 hs30 hs24 c3
                                                        · rcases le_total d2 (459 / 1024 : ℝ) with hs29 | hs29
                                                          · rcases le_total d3 (43 / 1024 : ℝ) with hs30 | hs30
                                                            · rcases le_total d1 (927 / 2048 : ℝ) with hs31 | hs31
                                                              · rcases le_total d2 (917 / 2048 : ℝ) with hs32 | hs32
                                                                · exact seed202_r78_gen011_dir_margin_sub160 d1 d2 d3 hs28 hs31 hs26 hs32 hs27 hs30 c3 c9
                                                                · rcases le_total d3 (85 / 2048 : ℝ) with hs33 | hs33
                                                                  · exact seed202_r78_gen011_dir_margin_sub161 d1 d2 d3 hs28 hs31 hs32 hs29 hs27 hs33 c3 c9
                                                                  · rcases le_total d1 (1853 / 4096 : ℝ) with hs34 | hs34
                                                                    · rcases le_total d2 (1835 / 4096 : ℝ) with hs35 | hs35
                                                                      · exact seed202_r78_gen011_dir_margin_sub162 d1 d2 d3 hs28 hs34 hs32 hs35 hs33 hs30 c3 c9
                                                                      · exact seed202_r78_gen011_dir_margin_sub163 d1 d2 d3 hs28 hs34 hs35 hs29 hs33 hs30 c3 c9
                                                                    · exact seed202_r78_gen011_dir_margin_sub164 d1 d2 d3 hs34 hs31 hs32 hs29 hs33 hs30 c3 c9
                                                              · rcases le_total d2 (917 / 2048 : ℝ) with hs32 | hs32
                                                                · exact seed202_r78_gen011_dir_margin_sub165 d1 d2 d3 hs31 hs16 hs26 hs32 hs27 hs30 c3 c9
                                                                · exact seed202_r78_gen011_dir_margin_sub166 d1 d2 d3 hs31 hs16 hs32 hs29 hs27 hs30 c3 c9
                                                            · exact seed202_r78_gen011_dir_margin_sub167 d1 d2 d3 hs28 hs16 hs26 hs29 hs30 hs24 c3 c6 c9
                                                          · rcases le_total d3 (43 / 1024 : ℝ) with hs30 | hs30
                                                            · rcases le_total d1 (927 / 2048 : ℝ) with hs31 | hs31
                                                              · rcases le_total d2 (919 / 2048 : ℝ) with hs32 | hs32
                                                                · rcases le_total d3 (85 / 2048 : ℝ) with hs33 | hs33
                                                                  · rcases le_total d1 (1853 / 4096 : ℝ) with hs34 | hs34
                                                                    · rcases le_total d2 (1837 / 4096 : ℝ) with hs35 | hs35
                                                                      · exact seed202_r78_gen011_dir_margin_sub168 d1 d2 d3 hs28 hs34 hs29 hs35 hs27 hs33 c3 c9
                                                                      · exact seed202_r78_gen011_dir_margin_sub169 d1 d2 d3 hs28 hs34 hs35 hs32 hs27 hs33 c3 c9
                                                                    · exact seed202_r78_gen011_dir_margin_sub170 d1 d2 d3 hs34 hs31 hs29 hs32 hs27 hs33 c3 c9
                                                                  · exact seed202_r78_gen011_dir_margin_sub171 d1 d2 d3 hs28 hs31 hs29 hs32 hs33 hs30 c3
                                                                · exact seed202_r78_gen011_dir_margin_sub172 d1 d2 d3 hs28 hs31 hs32 hs23 hs27 hs30 c3 c4 c9
                                                              · exact seed202_r78_gen011_dir_margin_sub173 d1 d2 d3 hs31 hs16 hs29 hs23 hs27 hs30 c3
                                                            · exact seed202_r78_gen011_dir_margin_sub174 d1 d2 d3 hs28 hs16 hs29 hs23 hs30 hs24 c3
                                                · exact seed202_r78_gen011_dir_margin_sub175 d1 d2 d3 hs22 hs16 hs20 hs23 hs24 hs18 c6 c9
                                              · rcases le_total d3 (11 / 256 : ℝ) with hs24 | hs24
                                                · rcases le_total d1 (231 / 512 : ℝ) with hs25 | hs25
                                                  · exact seed202_r78_gen011_dir_margin_sub176 d1 d2 d3 hs22 hs25 hs23 hs17 hs21 hs24 c4 c9
                                                  · rcases le_total d2 (231 / 512 : ℝ) with hs26 | hs26
                                                    · rcases le_total d3 (21 / 512 : ℝ) with hs27 | hs27
                                                      · rcases le_total d1 (463 / 1024 : ℝ) with hs28 | hs28
                                                        · exact seed202_r78_gen011_dir_margin_sub177 d1 d2 d3 hs25 hs28 hs23 hs26 hs21 hs27 c4 c9
                                                        · exact seed202_r78_gen011_dir_margin_sub178 d1 d2 d3 hs28 hs16 hs23 hs26 hs21 hs27 c3 c4 c9
                                                      · exact seed202_r78_gen011_dir_margin_sub179 d1 d2 d3 hs25 hs16 hs23 hs26 hs27 hs24 c4
                                                    · exact seed202_r78_gen011_dir_margin_sub180 d1 d2 d3 hs25 hs16 hs26 hs17 hs21 hs24 c4
                                                · exact seed202_r78_gen011_dir_margin_sub181 d1 d2 d3 hs22 hs16 hs23 hs17 hs24 hs18 c4
                                    · exact seed202_r78_gen011_dir_margin_sub182 d1 d2 d3 hs10 hs16 hs11 hs17 hs18 hs12 c6 c9
                                  · exact seed202_r78_gen011_dir_margin_sub183 d1 d2 d3 hs10 hs16 hs17 hs14 hs15 hs12 c4 c9
                                · rcases le_total d2 (29 / 64 : ℝ) with hs17 | hs17
                                  · rcases le_total d3 (3 / 64 : ℝ) with hs18 | hs18
                                    · rcases le_total d1 (59 / 128 : ℝ) with hs19 | hs19
                                      · rcases le_total d2 (57 / 128 : ℝ) with hs20 | hs20
                                        · rcases le_total d3 (5 / 128 : ℝ) with hs21 | hs21
                                          · exact seed202_r78_gen011_dir_margin_sub184 d1 d2 d3 hs16 hs19 hs11 hs20 hs15 hs21 c3 c9
                                          · rcases le_total d1 (117 / 256 : ℝ) with hs22 | hs22
                                            · rcases le_total d2 (113 / 256 : ℝ) with hs23 | hs23
                                              · exact seed202_r78_gen011_dir_margin_sub185 d1 d2 d3 hs16 hs22 hs11 hs23 hs21 hs18 c6 c9
                                              · rcases le_total d3 (11 / 256 : ℝ) with hs24 | hs24
                                                · rcases le_total d1 (233 / 512 : ℝ) with hs25 | hs25
                                                  · exact seed202_r78_gen011_dir_margin_sub186 d1 d2 d3 hs16 hs25 hs23 hs20 hs21 hs24 c3 c6 c9
                                                  · rcases le_total d2 (227 / 512 : ℝ) with hs26 | hs26
                                                    · exact seed202_r78_gen011_dir_margin_sub187 d1 d2 d3 hs25 hs22 hs23 hs26 hs21 hs24 c6 c9
                                                    · exact seed202_r78_gen011_dir_margin_sub188 d1 d2 d3 hs25 hs22 hs26 hs20 hs21 hs24 c3 c6 c9
                                                · exact seed202_r78_gen011_dir_margin_sub189 d1 d2 d3 hs16 hs22 hs23 hs20 hs24 hs18 c6
                                            · rcases le_total d2 (113 / 256 : ℝ) with hs23 | hs23
                                              · exact seed202_r78_gen011_dir_margin_sub190 d1 d2 d3 hs22 hs19 hs11 hs23 hs21 hs18 c3 c6 c9
                                              · rcases le_total d3 (11 / 256 : ℝ) with hs24 | hs24
                                                · rcases le_total d1 (235 / 512 : ℝ) with hs25 | hs25
                                                  · exact seed202_r78_gen011_dir_margin_sub191 d1 d2 d3 hs22 hs25 hs23 hs20 hs21 hs24 c3 c6 c9
                                                  · exact seed202_r78_gen011_dir_margin_sub192 d1 d2 d3 hs25 hs19 hs23 hs20 hs21 hs24 c3 c9
                                                · exact seed202_r78_gen011_dir_margin_sub193 d1 d2 d3 hs22 hs19 hs23 hs20 hs24 hs18 c3
                                        · rcases le_total d3 (5 / 128 : ℝ) with hs21 | hs21
                                          · rcases le_total d1 (117 / 256 : ℝ) with hs22 | hs22
                                            · rcases le_total d2 (115 / 256 : ℝ) with hs23 | hs23
                                              · rcases le_total d3 (9 / 256 : ℝ) with hs24 | hs24
                                                · exact seed202_r78_gen011_dir_margin_sub194 d1 d2 d3 hs16 hs22 hs20 hs23 hs15 hs24 c9
                                                · rcases le_total d1 (233 / 512 : ℝ) with hs25 | hs25
                                                  · exact seed202_r78_gen011_dir_margin_sub195 d1 d2 d3 hs16 hs25 hs20 hs23 hs24 hs21 c3 c9
                                                  · rcases le_total d2 (229 / 512 : ℝ) with hs26 | hs26
                                                    · exact seed202_r78_gen011_dir_margin_sub196 d1 d2 d3 hs25 hs22 hs20 hs26 hs24 hs21 c3 c9
                                                    · rcases le_total d3 (19 / 512 : ℝ) with hs27 | hs27
                                                      · exact seed202_r78_gen011_dir_margin_sub197 d1 d2 d3 hs25 hs22 hs26 hs23 hs24 hs27 c3 c9
                                                      · rcases le_total d1 (467 / 1024 : ℝ) with hs28 | hs28
                                                        · exact seed202_r78_gen011_dir_margin_sub198 d1 d2 d3 hs25 hs28 hs26 hs23 hs27 hs21 c3 c9
                                                        · exact seed202_r78_gen011_dir_margin_sub199 d1 d2 d3 hs28 hs22 hs26 hs23 hs27 hs21 c3 c9
                                              · rcases le_total d3 (9 / 256 : ℝ) with hs24 | hs24
                                                · exact seed202_r78_gen011_dir_margin_sub200 d1 d2 d3 hs16 hs22 hs23 hs17 hs15 hs24 c3 c4 c9
                                                · rcases le_total d1 (233 / 512 : ℝ) with hs25 | hs25
                                                  · rcases le_total d2 (231 / 512 : ℝ) with hs26 | hs26
                                                    · rcases le_total d3 (19 / 512 : ℝ) with hs27 | hs27
                                                      · exact seed202_r78_gen011_dir_margin_sub201 d1 d2 d3 hs16 hs25 hs23 hs26 hs24 hs27 c3 c4 c9
                                                      · rcases le_total d1 (465 / 1024 : ℝ) with hs28 | hs28
                                                        · exact seed202_r78_gen011_dir_margin_sub202 d1 d2 d3 hs16 hs28 hs23 hs26 hs27 hs21 c3 c4 c9
                                                        · rcases le_total d2 (461 / 1024 : ℝ) with hs29 | hs29
                                                          · exact seed202_r78_gen011_dir_margin_sub203 d1 d2 d3 hs28 hs25 hs23 hs29 hs27 hs21 c3 c9
                                                          · exact seed202_r78_gen011_dir_margin_sub204 d1 d2 d3 hs28 hs25 hs29 hs26 hs27 hs21 c3 c4 c9
                                                    · exact seed202_r78_gen011_dir_margin_sub205 d1 d2 d3 hs16 hs25 hs26 hs17 hs24 hs21 c4 c9
                                                  · rcases le_total d2 (231 / 512 : ℝ) with hs26 | hs26
                                                    · rcases le_total d3 (19 / 512 : ℝ) with hs27 | hs27
                                                      · rcases le_total d1 (467 / 1024 : ℝ) with hs28 | hs28
                                                        · exact seed202_r78_gen011_dir_margin_sub206 d1 d2 d3 hs25 hs28 hs23 hs26 hs24 hs27 c3 c4 c9
                                                        · exact seed202_r78_gen011_dir_margin_sub207 d1 d2 d3 hs28 hs22 hs23 hs26 hs24 hs27 c3 c9
                                                      · exact seed202_r78_gen011_dir_margin_sub208 d1 d2 d3 hs25 hs22 hs23 hs26 hs27 hs21 c3 c9
                                                    · exact seed202_r78_gen011_dir_margin_sub209 d1 d2 d3 hs25 hs22 hs26 hs17 hs24 hs21 c3 c4 c9
                                            · rcases le_total d2 (115 / 256 : ℝ) with hs23 | hs23
                                              · rcases le_total d3 (9 / 256 : ℝ) with hs24 | hs24
                                                · exact seed202_r78_gen011_dir_margin_sub210 d1 d2 d3 hs22 hs19 hs20 hs23 hs15 hs24 c3 c9
                                                · rcases le_total d1 (235 / 512 : ℝ) with hs25 | hs25
                                                  · rcases le_total d2 (229 / 512 : ℝ) with hs26 | hs26
                                                    · exact seed202_r78_gen011_dir_margin_sub211 d1 d2 d3 hs22 hs25 hs20 hs26 hs24 hs21 c3 c9
                                                    · exact seed202_r78_gen011_dir_margin_sub212 d1 d2 d3 hs22 hs25 hs26 hs23 hs24 hs21 c3 c9
                                                  · exact seed202_r78_gen011_dir_margin_sub213 d1 d2 d3 hs25 hs19 hs20 hs23 hs24 hs21 c3 c9
                                              · rcases le_total d3 (9 / 256 : ℝ) with hs24 | hs24
                                                · rcases le_total d1 (235 / 512 : ℝ) with hs25 | hs25
                                                  · rcases le_total d2 (231 / 512 : ℝ) with hs26 | hs26
                                                    · exact seed202_r78_gen011_dir_margin_sub214 d1 d2 d3 hs22 hs25 hs23 hs26 hs15 hs24 c3 c9
                                                    · exact seed202_r78_gen011_dir_margin_sub215 d1 d2 d3 hs22 hs25 hs26 hs17 hs15 hs24 c3 c4 c9
                                                  · exact seed202_r78_gen011_dir_margin_sub216 d1 d2 d3 hs25 hs19 hs23 hs17 hs15 hs24 c3 c9
                                                · exact seed202_r78_gen011_dir_margin_sub217 d1 d2 d3 hs22 hs19 hs23 hs17 hs24 hs21 c3 c9
                                          · rcases le_total d1 (117 / 256 : ℝ) with hs22 | hs22
                                            · rcases le_total d2 (115 / 256 : ℝ) with hs23 | hs23
                                              · rcases le_total d3 (11 / 256 : ℝ) with hs24 | hs24
                                                · rcases le_total d1 (233 / 512 : ℝ) with hs25 | hs25
                                                  · rcases le_total d2 (229 / 512 : ℝ) with hs26 | hs26
                                                    · rcases le_total d3 (21 / 512 : ℝ) with hs27 | hs27
                                                      · exact seed202_r78_gen011_dir_margin_sub218 d1 d2 d3 hs16 hs25 hs20 hs26 hs21 hs27 c3 c9
                                                      · rcases le_total d1 (465 / 1024 : ℝ) with hs28 | hs28
                                                        · rcases le_total d2 (457 / 1024 : ℝ) with hs29 | hs29
                                                          · exact seed202_r78_gen011_dir_margin_sub219 d1 d2 d3 hs16 hs28 hs20 hs29 hs27 hs24 c3 c6 c9
                                                          · rcases le_total d3 (43 / 1024 : ℝ) with hs30 | hs30
                                                            · rcases le_total d1 (929 / 2048 : ℝ) with hs31 | hs31
                                                              · exact seed202_r78_gen011_dir_margin_sub220 d1 d2 d3 hs16 hs31 hs29 hs26 hs27 hs30 c3 c9
                                                              · exact seed202_r78_gen011_dir_margin_sub221 d1 d2 d3 hs31 hs28 hs29 hs26 hs27 hs30 c3 c9
                                                            · exact seed202_r78_gen011_dir_margin_sub222 d1 d2 d3 hs16 hs28 hs29 hs26 hs30 hs24 c3 c9
                                                        · exact seed202_r78_gen011_dir_margin_sub223 d1 d2 d3 hs28 hs25 hs20 hs26 hs27 hs24 c3 c6 c9
                                                    · rcases le_total d3 (21 / 512 : ℝ) with hs27 | hs27
                                                      · rcases le_total d1 (465 / 1024 : ℝ) with hs28 | hs28
                                                        · rcases le_total d2 (459 / 1024 : ℝ) with hs29 | hs29
                                                          · rcases le_total d3 (41 / 1024 : ℝ) with hs30 | hs30
                                                            · exact seed202_r78_gen011_dir_margin_sub224 d1 d2 d3 hs16 hs28 hs26 hs29 hs21 hs30 c9
                                                            · rcases le_total d1 (929 / 2048 : ℝ) with hs31 | hs31
                                                              · exact seed202_r78_gen011_dir_margin_sub225 d1 d2 d3 hs16 hs31 hs26 hs29 hs30 hs27 c3 c9
                                                              · exact seed202_r78_gen011_dir_margin_sub226 d1 d2 d3 hs31 hs28 hs26 hs29 hs30 hs27 c3 c9
                                                          · rcases le_total d3 (41 / 1024 : ℝ) with hs30 | hs30
                                                            · rcases le_total d1 (929 / 2048 : ℝ) with hs31 | hs31
                                                              · exact seed202_r78_gen011_dir_margin_sub227 d1 d2 d3 hs16 hs31 hs29 hs23 hs21 hs30 c3 c9
                                                              · exact seed202_r78_gen011_dir_margin_sub228 d1 d2 d3 hs31 hs28 hs29 hs23 hs21 hs30 c3 c9
                                                            · exact seed202_r78_gen011_dir_margin_sub229 d1 d2 d3 hs16 hs28 hs29 hs23 hs30 hs27 c3 c9
                                                        · rcases le_total d2 (459 / 1024 : ℝ) with hs29 | hs29
                                                          · exact seed202_r78_gen011_dir_margin_sub230 d1 d2 d3 hs28 hs25 hs26 hs29 hs21 hs27 c3 c9
                                                          · exact seed202_r78_gen011_dir_margin_sub231 d1 d2 d3 hs28 hs25 hs29 hs23 hs21 hs27 c3 c9
                                                      · exact seed202_r78_gen011_dir_margin_sub232 d1 d2 d3 hs16 hs25 hs26 hs23 hs27 hs24 c3 c9
                                                  · rcases le_total d2 (229 / 512 : ℝ) with hs26 | hs26
                                                    · rcases le_total d3 (21 / 512 : ℝ) with hs27 | hs27
                                                      · rcases le_total d1 (467 / 1024 : ℝ) with hs28 | hs28
                                                        · exact seed202_r78_gen011_dir_margin_sub233 d1 d2 d3 hs25 hs28 hs20 hs26 hs21 hs27 c3 c9
                                                        · exact seed202_r78_gen011_dir_margin_sub234 d1 d2 d3 hs28 hs22 hs20 hs26 hs21 hs27 c3 c9
                                                      · exact seed202_r78_gen011_dir_margin_sub235 d1 d2 d3 hs25 hs22 hs20 hs26 hs27 hs24 c3 c9
                                                    · exact seed202_r78_gen011_dir_margin_sub236 d1 d2 d3 hs25 hs22 hs26 hs23 hs21 hs24 c3 c9
                                                · exact seed202_r78_gen011_dir_margin_sub237 d1 d2 d3 hs16 hs22 hs20 hs23 hs24 hs18 c6
                                              · exact seed202_r78_gen011_dir_margin_sub238 d1 d2 d3 hs16 hs22 hs23 hs17 hs21 hs18 c3 c4 c9
                                            · exact seed202_r78_gen011_dir_margin_sub239 d1 d2 d3 hs22 hs19 hs20 hs17 hs21 hs18 c3 c9
                                      · rcases le_total d2 (57 / 128 : ℝ) with hs20 | hs20
                                        · rcases le_total d3 (5 / 128 : ℝ) with hs21 | hs21
                                          · rcases le_total d1 (119 / 256 : ℝ) with hs22 | hs22
                                            · exact seed202_r78_gen011_dir_margin_sub240 d1 d2 d3 hs19 hs22 hs11 hs20 hs15 hs21 c3 c9
                                            · exact seed202_r78_gen011_dir_margin_sub241 d1 d2 d3 hs22 hs13 hs11 hs20 hs15 hs21 c3 c9
                                          · exact seed202_r78_gen011_dir_margin_sub242 d1 d2 d3 hs19 hs13 hs11 hs20 hs21 hs18 c3 c9
                                        · rcases le_total d3 (5 / 128 : ℝ) with hs21 | hs21
                                          · rcases le_total d1 (119 / 256 : ℝ) with hs22 | hs22
                                            · rcases le_total d2 (115 / 256 : ℝ) with hs23 | hs23
                                              · rcases le_total d3 (9 / 256 : ℝ) with hs24 | hs24
                                                · exact seed202_r78_gen011_dir_margin_sub243 d1 d2 d3 hs19 hs22 hs20 hs23 hs15 hs24 c3 c9
                                                · exact seed202_r78_gen011_dir_margin_sub244 d1 d2 d3 hs19 hs22 hs20 hs23 hs24 hs21 c3 c9
                                              · exact seed202_r78_gen011_dir_margin_sub245 d1 d2 d3 hs19 hs22 hs23 hs17 hs15 hs21 c3 c9
                                            · exact seed202_r78_gen011_dir_margin_sub246 d1 d2 d3 hs22 hs13 hs20 hs17 hs15 hs21 c3 c9
                                          · exact seed202_r78_gen011_dir_margin_sub247 d1 d2 d3 hs19 hs13 hs20 hs17 hs21 hs18 c3
                                    · exact seed202_r78_gen011_dir_margin_sub248 d1 d2 d3 hs16 hs13 hs11 hs17 hs18 hs12 c6
                                  · exact seed202_r78_gen011_dir_margin_sub249 d1 d2 d3 hs16 hs13 hs17 hs14 hs15 hs12 c3 c4 c9
                            · exact seed202_r78_gen011_dir_margin_sub250 d1 d2 d3 hs10 hs13 hs14 hs2 hlo3 hs12 c4 c9
                          · rcases le_total d2 (15 / 32 : ℝ) with hs14 | hs14
                            · rcases le_total d3 (1 / 32 : ℝ) with hs15 | hs15
                              · rcases le_total d1 (31 / 64 : ℝ) with hs16 | hs16
                                · rcases le_total d2 (29 / 64 : ℝ) with hs17 | hs17
                                  · rcases le_total d3 (1 / 64 : ℝ) with hs18 | hs18
                                    · exact seed202_r78_gen011_dir_margin_sub251 d1 d2 d3 hs13 hs16 hs11 hs17 hlo3 hs18 c3 c9
                                    · rcases le_total d1 (61 / 128 : ℝ) with hs19 | hs19
                                      · rcases le_total d2 (57 / 128 : ℝ) with hs20 | hs20
                                        · exact seed202_r78_gen011_dir_margin_sub252 d1 d2 d3 hs13 hs19 hs11 hs20 hs18 hs15 c3 c9
                                        · rcases le_total d3 (3 / 128 : ℝ) with hs21 | hs21
                                          · exact seed202_r78_gen011_dir_margin_sub253 d1 d2 d3 hs13 hs19 hs20 hs17 hs18 hs21 c3 c9
                                          · exact seed202_r78_gen011_dir_margin_sub254 d1 d2 d3 hs13 hs19 hs20 hs17 hs21 hs15 c3 c9
                                      · rcases le_total d2 (57 / 128 : ℝ) with hs20 | hs20
                                        · exact seed202_r78_gen011_dir_margin_sub255 d1 d2 d3 hs19 hs16 hs11 hs20 hs18 hs15 c3 c9
                                        · exact seed202_r78_gen011_dir_margin_sub256 d1 d2 d3 hs19 hs16 hs20 hs17 hs18 hs15 c3 c9
                                  · rcases le_total d3 (1 / 64 : ℝ) with hs18 | hs18
                                    · rcases le_total d1 (61 / 128 : ℝ) with hs19 | hs19
                                      · rcases le_total d2 (59 / 128 : ℝ) with hs20 | hs20
                                        · exact seed202_r78_gen011_dir_margin_sub257 d1 d2 d3 hs13 hs19 hs17 hs20 hlo3 hs18 c3 c9
                                        · rcases le_total d3 (1 / 128 : ℝ) with hs21 | hs21
                                          · exact seed202_r78_gen011_dir_margin_sub258 d1 d2 d3 hs13 hs19 hs20 hs14 hlo3 hs21 c3 c4 c9
                                          · exact seed202_r78_gen011_dir_margin_sub259 d1 d2 d3 hs13 hs19 hs20 hs14 hs21 hs18 c3 c4 c9
                                      · rcases le_total d2 (59 / 128 : ℝ) with hs20 | hs20
                                        · exact seed202_r78_gen011_dir_margin_sub260 d1 d2 d3 hs19 hs16 hs17 hs20 hlo3 hs18 c3 c9
                                        · exact seed202_r78_gen011_dir_margin_sub261 d1 d2 d3 hs19 hs16 hs20 hs14 hlo3 hs18 c3 c4 c9
                                    · exact seed202_r78_gen011_dir_margin_sub262 d1 d2 d3 hs13 hs16 hs17 hs14 hs18 hs15 c3 c9
                                · rcases le_total d2 (29 / 64 : ℝ) with hs17 | hs17
                                  · rcases le_total d3 (1 / 64 : ℝ) with hs18 | hs18
                                    · rcases le_total d1 (63 / 128 : ℝ) with hs19 | hs19
                                      · exact seed202_r78_gen011_dir_margin_sub263 d1 d2 d3 hs16 hs19 hs11 hs17 hlo3 hs18 c3 c9
                                      · exact seed202_r78_gen011_dir_margin_sub264 d1 d2 d3 hs19 hs1 hs11 hs17 hlo3 hs18 c3 c9
                                    · exact seed202_r78_gen011_dir_margin_sub265 d1 d2 d3 hs16 hs1 hs11 hs17 hs18 hs15 c3 c9
                                  · exact seed202_r78_gen011_dir_margin_sub266 d1 d2 d3 hs16 hs1 hs17 hs14 hlo3 hs15 c3 c9
                              · exact seed202_r78_gen011_dir_margin_sub267 d1 d2 d3 hs13 hs1 hs11 hs14 hs15 hs12 c3 c9
                            · exact seed202_r78_gen011_dir_margin_sub268 d1 d2 d3 hs13 hs1 hs14 hs2 hlo3 hs12 c4
                        · exact seed202_r78_gen011_dir_margin_sub269 d1 d2 d3 hs10 hs1 hs11 hs2 hs12 hs9 c6
                  · exact seed202_r78_gen011_dir_margin_sub270 d1 d2 d3 hs7 hs1 hs8 hs2 hs9 hs6 c6
            · exact seed202_r78_gen011_dir_margin_sub271 d1 d2 d3 hs4 hs1 hs5 hs2 hs6 hs3 c6
      · exact seed202_r78_gen011_dir_margin_sub272 d1 d2 d3 hlo1 hs1 hlo2 hs2 hs3 hhi3 c5 c6
    · exact seed202_r78_gen011_dir_margin_sub273 d1 d2 d3 hlo1 hs1 hs2 hhi2 hlo3 hhi3 c3 c4 c7
  · rcases le_total d2 (1 / 2 : ℝ) with hs2 | hs2
    · rcases le_total d3 (1 / 2 : ℝ) with hs3 | hs3
      · rcases le_total d1 (3 / 4 : ℝ) with hs4 | hs4
        · rcases le_total d2 (1 / 4 : ℝ) with hs5 | hs5
          · rcases le_total d3 (1 / 4 : ℝ) with hs6 | hs6
            · rcases le_total d1 (5 / 8 : ℝ) with hs7 | hs7
              · exact seed202_r78_gen011_dir_margin_sub274 d1 d2 d3 hs1 hs7 hlo2 hs5 hlo3 hs6 c6 c9
              · rcases le_total d2 (1 / 8 : ℝ) with hs8 | hs8
                · exact seed202_r78_gen011_dir_margin_sub275 d1 d2 d3 hs7 hs4 hlo2 hs8 hlo3 hs6 c6 c8 c9
                · rcases le_total d3 (1 / 8 : ℝ) with hs9 | hs9
                  · rcases le_total d1 (11 / 16 : ℝ) with hs10 | hs10
                    · exact seed202_r78_gen011_dir_margin_sub276 d1 d2 d3 hs7 hs10 hs8 hs5 hlo3 hs9 c3 c6 c8 c9
                    · exact seed202_r78_gen011_dir_margin_sub277 d1 d2 d3 hs10 hs4 hs8 hs5 hlo3 hs9 c3 c6 c9
                  · exact seed202_r78_gen011_dir_margin_sub278 d1 d2 d3 hs7 hs4 hs8 hs5 hs9 hs6 c6
            · exact seed202_r78_gen011_dir_margin_sub279 d1 d2 d3 hs1 hs4 hlo2 hs5 hs6 hs3 c6
          · rcases le_total d3 (1 / 4 : ℝ) with hs6 | hs6
            · rcases le_total d1 (5 / 8 : ℝ) with hs7 | hs7
              · rcases le_total d2 (3 / 8 : ℝ) with hs8 | hs8
                · rcases le_total d3 (1 / 8 : ℝ) with hs9 | hs9
                  · rcases le_total d1 (9 / 16 : ℝ) with hs10 | hs10
                    · rcases le_total d2 (5 / 16 : ℝ) with hs11 | hs11
                      · exact seed202_r78_gen011_dir_margin_sub280 d1 d2 d3 hs1 hs10 hs5 hs11 hlo3 hs9 c6 c9
                      · rcases le_total d3 (1 / 16 : ℝ) with hs12 | hs12
                        · rcases le_total d1 (17 / 32 : ℝ) with hs13 | hs13
                          · exact seed202_r78_gen011_dir_margin_sub281 d1 d2 d3 hs1 hs13 hs11 hs8 hlo3 hs12 c3 c6 c9
                          · exact seed202_r78_gen011_dir_margin_sub282 d1 d2 d3 hs13 hs10 hs11 hs8 hlo3 hs12 c3 c6 c9
                        · exact seed202_r78_gen011_dir_margin_sub283 d1 d2 d3 hs1 hs10 hs11 hs8 hs12 hs9 c6
                    · rcases le_total d2 (5 / 16 : ℝ) with hs11 | hs11
                      · exact seed202_r78_gen011_dir_margin_sub284 d1 d2 d3 hs10 hs7 hs5 hs11 hlo3 hs9 c3 c6 c9
                      · rcases le_total d3 (1 / 16 : ℝ) with hs12 | hs12
                        · rcases le_total d1 (19 / 32 : ℝ) with hs13 | hs13
                          · exact seed202_r78_gen011_dir_margin_sub285 d1 d2 d3 hs10 hs13 hs11 hs8 hlo3 hs12 c3 c6 c9
                          · exact seed202_r78_gen011_dir_margin_sub286 d1 d2 d3 hs13 hs7 hs11 hs8 hlo3 hs12 c3 c9
                        · exact seed202_r78_gen011_dir_margin_sub287 d1 d2 d3 hs10 hs7 hs11 hs8 hs12 hs9 c3
                  · exact seed202_r78_gen011_dir_margin_sub288 d1 d2 d3 hs1 hs7 hs5 hs8 hs9 hs6 c6
                · rcases le_total d3 (1 / 8 : ℝ) with hs9 | hs9
                  · rcases le_total d1 (9 / 16 : ℝ) with hs10 | hs10
                    · rcases le_total d2 (7 / 16 : ℝ) with hs11 | hs11
                      · rcases le_total d3 (1 / 16 : ℝ) with hs12 | hs12
                        · rcases le_total d1 (17 / 32 : ℝ) with hs13 | hs13
                          · rcases le_total d2 (13 / 32 : ℝ) with hs14 | hs14
                            · rcases le_total d3 (1 / 32 : ℝ) with hs15 | hs15
                              · exact seed202_r78_gen011_dir_margin_sub289 d1 d2 d3 hs1 hs13 hs8 hs14 hlo3 hs15 c3 c9
                              · exact seed202_r78_gen011_dir_margin_sub290 d1 d2 d3 hs1 hs13 hs8 hs14 hs15 hs12 c3 c6 c9
                            · rcases le_total d3 (1 / 32 : ℝ) with hs15 | hs15
                              · rcases le_total d1 (33 / 64 : ℝ) with hs16 | hs16
                                · rcases le_total d2 (27 / 64 : ℝ) with hs17 | hs17
                                  · exact seed202_r78_gen011_dir_margin_sub291 d1 d2 d3 hs1 hs16 hs14 hs17 hlo3 hs15 c3 c9
                                  · exact seed202_r78_gen011_dir_margin_sub292 d1 d2 d3 hs1 hs16 hs17 hs11 hlo3 hs15 c3 c9
                                · exact seed202_r78_gen011_dir_margin_sub293 d1 d2 d3 hs16 hs13 hs14 hs11 hlo3 hs15 c3 c9
                              · exact seed202_r78_gen011_dir_margin_sub294 d1 d2 d3 hs1 hs13 hs14 hs11 hs15 hs12 c3
                          · exact seed202_r78_gen011_dir_margin_sub295 d1 d2 d3 hs13 hs10 hs8 hs11 hlo3 hs12 c3 c9
                        · exact seed202_r78_gen011_dir_margin_sub296 d1 d2 d3 hs1 hs10 hs8 hs11 hs12 hs9 c3
                      · exact seed202_r78_gen011_dir_margin_sub297 d1 d2 d3 hs1 hs10 hs11 hs2 hlo3 hs9 c3 c9
                    · exact seed202_r78_gen011_dir_margin_sub298 d1 d2 d3 hs10 hs7 hs8 hs2 hlo3 hs9 c3
                  · exact seed202_r78_gen011_dir_margin_sub299 d1 d2 d3 hs1 hs7 hs8 hs2 hs9 hs6 c3
              · exact seed202_r78_gen011_dir_margin_sub300 d1 d2 d3 hs7 hs4 hs5 hs2 hlo3 hs6 c3 c9
            · exact seed202_r78_gen011_dir_margin_sub301 d1 d2 d3 hs1 hs4 hs5 hs2 hs6 hs3 c3
        · rcases le_total d2 (1 / 4 : ℝ) with hs5 | hs5
          · rcases le_total d3 (1 / 4 : ℝ) with hs6 | hs6
            · rcases le_total d1 (7 / 8 : ℝ) with hs7 | hs7
              · exact seed202_r78_gen011_dir_margin_sub302 d1 d2 d3 hs4 hs7 hlo2 hs5 hlo3 hs6 c3 c6 c8 c9
              · exact seed202_r78_gen011_dir_margin_sub303 d1 d2 d3 hs7 hhi1 hlo2 hs5 hlo3 hs6 c3 c9
            · exact seed202_r78_gen011_dir_margin_sub304 d1 d2 d3 hs4 hhi1 hlo2 hs5 hs6 hs3 c3
          · exact seed202_r78_gen011_dir_margin_sub305 d1 d2 d3 hs4 hhi1 hs5 hs2 hlo3 hs3 c3
      · exact seed202_r78_gen011_dir_margin_sub306 d1 d2 d3 hs1 hhi1 hlo2 hs2 hs3 hhi3 c3
    · exact seed202_r78_gen011_dir_margin_sub307 d1 d2 d3 hs1 hhi1 hs2 hhi2 hlo3 hhi3 c3


/-- Certificate identifier proved in this module. The `#guard`
below turns a silently dropped certificate into a compile error. -/
def Seed202R78Gen011MarginIds : List String :=
  ["v1/directional/seed202_r78_gen011/margin"]

#guard Seed202R78Gen011MarginIds.length = 1

end Quitting.Directional
