-- GENERATED by code/julia/scripts/certificates/v0_from_recorded.jl — do not edit.
-- Regenerate and `git diff --exit-code` to prove the Lean corpus is a
-- pure function of the JSON certificates.

import Formal.Certificates.Prelude

set_option maxRecDepth 8000
set_option maxHeartbeats 1000000

namespace Quitting.V0

-- Conditions of certificate `seed202_r78_gen011_minmax_upper_4`, one per declaration.
-- Together they say: against this punishment, quitting now and
-- waiting both pay player 4 at most the stated level.

/-- Condition `U_minus_a` of `seed202_r78_gen011_minmax_upper_4`. -/
def seed202_r78_gen011_minmax_upper_4_c01 (x1 x2 x3 _x4 : ℝ) : Prop :=
  0 ≤ -3135240186271 / 1739193319424 + 5 / 19 * x3 - 8 / 9 * x2 + 14603 / 5301 * x2 * x3 - 11 / 12 * x1 + 545 / 228 * x1 * x3 + 175 / 72 * x1 * x2 - 1966289 / 466488 * x1 * x2 * x3

/-- Condition `qU_minus_b` of `seed202_r78_gen011_minmax_upper_4`. -/
def seed202_r78_gen011_minmax_upper_4_c02 (x1 x2 x3 _x4 : ℝ) : Prop :=
  0 ≤ 5560726410849 / 1739193319424 * x3 - 4874433505695 / 1739193319424 * x2 - 1864940607073 / 1739193319424 * x2 * x3 - 11831206783391 / 1739193319424 * x1 + 75588910923081 / 40001446346752 * x1 * x3 + 367087095681159 / 43479832985600 * x1 * x2 - 8764280230311011 / 3000108476006400 * x1 * x2 * x3

theorem seed202_r78_gen011_minmax_upper_4_c01_holds : seed202_r78_gen011_minmax_upper_4_c01 (1 / 16384) (27037 / 32768) (1) (0) := by
  unfold seed202_r78_gen011_minmax_upper_4_c01
  norm_num

theorem seed202_r78_gen011_minmax_upper_4_c02_holds : seed202_r78_gen011_minmax_upper_4_c02 (1 / 16384) (27037 / 32768) (1) (0) := by
  unfold seed202_r78_gen011_minmax_upper_4_c02
  norm_num

/-- the stationary punishment listed here holds player 4 to at most -1396046866847/1739193319424, so w_4 <= -1396046866847/1739193319424. Scope: this bounds the min-max value from above and is reported for the sandwich only; the refutation of branch (S.2) uses the lower bound alone.

Stated as an existential over one tuple: a punishment at this level
exists, so the min-max value is at most it. Machine-written. -/
theorem seed202_r78_gen011_minmax_upper_4 :
    ∃ x1 x2 x3 x4 : ℝ,
      seed202_r78_gen011_minmax_upper_4_c01 x1 x2 x3 x4 ∧
      seed202_r78_gen011_minmax_upper_4_c02 x1 x2 x3 x4 :=
  ⟨1 / 16384, 27037 / 32768, 1, 0,
   seed202_r78_gen011_minmax_upper_4_c01_holds, seed202_r78_gen011_minmax_upper_4_c02_holds⟩

/-- Certificate identifier proved in this module. The `#guard`
below turns a silently dropped certificate into a compile error. -/
def Seed202R78Gen011MinmaxUpper4Ids : List String :=
  ["v1/v0/seed202_r78_gen011/minmax_upper_4"]

#guard Seed202R78Gen011MinmaxUpper4Ids.length = 1

end Quitting.V0
