-- GENERATED by code/julia/scripts/certificates/v0_from_recorded.jl — do not edit.
-- Regenerate and `git diff --exit-code` to prove the Lean corpus is a
-- pure function of the JSON certificates.

import Formal.Certificates.Prelude

set_option maxRecDepth 8000
set_option maxHeartbeats 1000000

namespace Quitting.V0

-- Conditions of certificate `seed202_r78_gen011_all_continue`, one per declaration.
-- It says: at this profile player 1's solo-quit gain exceeds eps.

/-- Condition `solo_quit_gain_minus_eps` of `seed202_r78_gen011_all_continue`. -/
def seed202_r78_gen011_all_continue_c01 (_x1 x2 x3 x4 : ℝ) : Prop :=
  0 < 648571 / 1048576 + 7 / 51 * x4 - 147 / 17 * x3 + 17611 / 1632 * x3 * x4 - 13 / 3 * x2 + 2833 / 663 * x2 * x4 + 1613 / 102 * x2 * x3 - 1910917 / 109616 * x2 * x3 * x4

theorem seed202_r78_gen011_all_continue_c01_holds : seed202_r78_gen011_all_continue_c01 (0) (0) (0) (0) := by
  unfold seed202_r78_gen011_all_continue_c01
  norm_num

/-- against the all-continue profile (every x_j = 0, which never terminates and therefore pays everyone 0) player 1 gains more than eps = 400005/1048576 by quitting alone, so all-continue is not an eps-equilibrium (AKRS 2024 Thm 4.15, second hypothesis).

Stated as an existential over one tuple: a profile at which the
deviation gain beats eps exists, so no eps-equilibrium can sit
there. Machine-written. -/
theorem seed202_r78_gen011_all_continue :
    ∃ x1 x2 x3 x4 : ℝ,
      seed202_r78_gen011_all_continue_c01 x1 x2 x3 x4 :=
  ⟨0, 0, 0, 0,
   seed202_r78_gen011_all_continue_c01_holds⟩

/-- Certificate identifier proved in this module. The `#guard`
below turns a silently dropped certificate into a compile error. -/
def Seed202R78Gen011AllContinueIds : List String :=
  ["v1/v0/seed202_r78_gen011/all_continue"]

#guard Seed202R78Gen011AllContinueIds.length = 1

end Quitting.V0
