-- GENERATED by code/julia/scripts/certificates/v0_from_recorded.jl — do not edit.
-- Regenerate and `git diff --exit-code` to prove the Lean corpus is a
-- pure function of the JSON certificates.

import Formal.Certificates.Prelude

set_option maxRecDepth 8000
set_option maxHeartbeats 1000000

namespace Quitting.V0

-- Conditions of certificate `seed202_r78_gen011_minmax_upper_3`, one per declaration.
-- Together they say: against this punishment, quitting now and
-- waiting both pay player 3 at most the stated level.

/-- Condition `U_minus_a` of `seed202_r78_gen011_minmax_upper_3`. -/
def seed202_r78_gen011_minmax_upper_3_c01 (x1 x2 _x3 x4 : ℝ) : Prop :=
  0 ≤ -372999 / 155648 + 19 / 12 * x4 - 3 / 19 * x2 + 359 / 228 * x2 * x4 + 46 / 31 * x1 - 2903 / 2604 * x1 * x4 - 1370 / 589 * x1 * x2 - 1348175 / 1434804 * x1 * x2 * x4

/-- Condition `qU_minus_b` of `seed202_r78_gen011_minmax_upper_3`. -/
def seed202_r78_gen011_minmax_upper_3_c02 (x1 x2 _x3 x4 : ℝ) : Prop :=
  0 ≤ -1151239 / 155648 * x4 + 405241 / 155648 * x2 + 650247 / 155648 * x2 * x4 - 995591 / 155648 * x1 + 2240775 / 155648 * x1 * x4 + 684295 / 155648 * x1 * x2 - 5725205 / 466944 * x1 * x2 * x4

theorem seed202_r78_gen011_minmax_upper_3_c01_holds : seed202_r78_gen011_minmax_upper_3_c01 (0) (1) (0) (26505 / 32768) := by
  unfold seed202_r78_gen011_minmax_upper_3_c01
  norm_num

theorem seed202_r78_gen011_minmax_upper_3_c02_holds : seed202_r78_gen011_minmax_upper_3_c02 (0) (1) (0) (26505 / 32768) := by
  unfold seed202_r78_gen011_minmax_upper_3_c02
  norm_num

/-- the stationary punishment listed here holds player 3 to at most -217351/155648, so w_3 <= -217351/155648. Scope: this bounds the min-max value from above and is reported for the sandwich only; the refutation of branch (S.2) uses the lower bound alone.

Stated as an existential over one tuple: a punishment at this level
exists, so the min-max value is at most it. Machine-written. -/
theorem seed202_r78_gen011_minmax_upper_3 :
    ∃ x1 x2 x3 x4 : ℝ,
      seed202_r78_gen011_minmax_upper_3_c01 x1 x2 x3 x4 ∧
      seed202_r78_gen011_minmax_upper_3_c02 x1 x2 x3 x4 :=
  ⟨0, 1, 0, 26505 / 32768,
   seed202_r78_gen011_minmax_upper_3_c01_holds, seed202_r78_gen011_minmax_upper_3_c02_holds⟩

/-- Certificate identifier proved in this module. The `#guard`
below turns a silently dropped certificate into a compile error. -/
def Seed202R78Gen011MinmaxUpper3Ids : List String :=
  ["v1/v0/seed202_r78_gen011/minmax_upper_3"]

#guard Seed202R78Gen011MinmaxUpper3Ids.length = 1

end Quitting.V0
