-- GENERATED by code/julia/scripts/certificates/v0_from_recorded.jl — do not edit.
-- Regenerate and `git diff --exit-code` to prove the Lean corpus is a
-- pure function of the JSON certificates.

import Formal.Certificates.Prelude

set_option maxRecDepth 8000
set_option maxHeartbeats 1000000

namespace Quitting.V0

-- Conditions of certificate `seed202_r78_gen011_minmax_upper_2`, one per declaration.
-- Together they say: against this punishment, quitting now and
-- waiting both pay player 2 at most the stated level.

/-- Condition `U_minus_a` of `seed202_r78_gen011_minmax_upper_2`. -/
def seed202_r78_gen011_minmax_upper_2_c01 (x1 _x2 x3 x4 : ℝ) : Prop :=
  0 ≤ -13660711 / 16187392 + 17 / 29 * x4 + 13 / 19 * x3 - 5198 / 4959 * x3 * x4 - 5 / 22 * x1 - 4519 / 4147 * x1 * x4 + 6178 / 2717 * x1 * x3 + 379135 / 218196 * x1 * x3 * x4

/-- Condition `qU_minus_b` of `seed202_r78_gen011_minmax_upper_2`. -/
def seed202_r78_gen011_minmax_upper_2_c02 (x1 _x2 x3 x4 : ℝ) : Prop :=
  0 ≤ -110785063 / 16187392 * x4 + 2526681 / 16187392 * x3 + 78410279 / 16187392 * x3 * x4 + 2526681 / 16187392 * x1 + 1105323949 / 178061312 * x1 * x4 - 34901465 / 16187392 * x1 * x3 - 12706185521 / 3739287552 * x1 * x3 * x4

theorem seed202_r78_gen011_minmax_upper_2_c01_holds : seed202_r78_gen011_minmax_upper_2_c01 (2557 / 32768) (0) (1) (0) := by
  unfold seed202_r78_gen011_minmax_upper_2_c01
  norm_num

theorem seed202_r78_gen011_minmax_upper_2_c02_holds : seed202_r78_gen011_minmax_upper_2_c02 (2557 / 32768) (0) (1) (0) := by
  unfold seed202_r78_gen011_minmax_upper_2_c02
  norm_num

/-- the stationary punishment listed here holds player 2 to at most 2526681/16187392, so w_2 <= 2526681/16187392. Scope: this bounds the min-max value from above and is reported for the sandwich only; the refutation of branch (S.2) uses the lower bound alone.

Stated as an existential over one tuple: a punishment at this level
exists, so the min-max value is at most it. Machine-written. -/
theorem seed202_r78_gen011_minmax_upper_2 :
    ∃ x1 x2 x3 x4 : ℝ,
      seed202_r78_gen011_minmax_upper_2_c01 x1 x2 x3 x4 ∧
      seed202_r78_gen011_minmax_upper_2_c02 x1 x2 x3 x4 :=
  ⟨2557 / 32768, 0, 1, 0,
   seed202_r78_gen011_minmax_upper_2_c01_holds, seed202_r78_gen011_minmax_upper_2_c02_holds⟩

/-- Certificate identifier proved in this module. The `#guard`
below turns a silently dropped certificate into a compile error. -/
def Seed202R78Gen011MinmaxUpper2Ids : List String :=
  ["v1/v0/seed202_r78_gen011/minmax_upper_2"]

#guard Seed202R78Gen011MinmaxUpper2Ids.length = 1

end Quitting.V0
