-- GENERATED by code/julia/scripts/certificates/v0_from_recorded.jl — do not edit.
-- Regenerate and `git diff --exit-code` to prove the Lean corpus is a
-- pure function of the JSON certificates.

import Formal.Certificates.Prelude

set_option maxRecDepth 8000
set_option maxHeartbeats 1000000

namespace Quitting.V0


/-- Condition `quit_at_most_L` of `seed202_r78_gen011_minmax_lower_4`, with the sense the trace reads it in. The
certificate refutes the system in which all of them hold at once. -/
def seed202_r78_gen011_minmax_lower_4_f01 (x1 x2 x3 _x4 : ℝ) : Prop :=
  472569 / 262144 - 5 / 19 * x3 + 8 / 9 * x2 - 14603 / 5301 * x2 * x3 + 11 / 12 * x1 - 545 / 228 * x1 * x3 - 175 / 72 * x1 * x2 + 1966289 / 466488 * x1 * x2 * x3 ≤ 0

/-- Condition `wait_at_most_L` of `seed202_r78_gen011_minmax_lower_4`, with the sense the trace reads it in. The
certificate refutes the system in which all of them hold at once. -/
def seed202_r78_gen011_minmax_lower_4_f02 (x1 x2 x3 _x4 : ℝ) : Prop :=
  -838151 / 262144 * x3 + 734713 / 262144 * x2 + 281095 / 262144 * x2 * x3 + 1783289 / 262144 * x1 - 11393375 / 6029312 * x1 * x3 - 55330129 / 6553600 * x1 * x2 + 1321021141 / 452198400 * x1 * x2 * x3 ≤ 0

end Quitting.V0
