-- GENERATED by code/julia/scripts/certificates/v0_from_recorded.jl — do not edit.
-- Regenerate and `git diff --exit-code` to prove the Lean corpus is a
-- pure function of the JSON certificates.

import Formal.Certificates.Prelude
import Formal.Certificates.V0.Seed202R78Gen011MinmaxLower4.Defs
import Formal.Certificates.V0.Seed202R78Gen011MinmaxLower4.Part01
import Formal.Certificates.V0.Seed202R78Gen011MinmaxLower4.Part02
import Formal.Certificates.V0.Seed202R78Gen011MinmaxLower4.Part03
import Formal.Certificates.V0.Seed202R78Gen011MinmaxLower4.Part04

set_option maxRecDepth 8000
set_option maxHeartbeats 1000000

namespace Quitting.V0


/-- with L = -210425/262144, no stationary punishment z of player 4 satisfies both a(z) <= L and b(z) <= L*q(z), so the smallest level w_4 admitting one exceeds L; and v^4 >= w_4 unconditionally (docs/V0_MINIMAX.md 2.1). Coordinate x4 is pinned to 0: the punishment is played by the other players.

Proved by the recorded subdivision of the box: every leaf carries one
condition that the Bernstein corner-basis expansion makes strictly
positive there. Machine-written. -/
theorem seed202_r78_gen011_minmax_lower_4
    (x1 x2 x3 x4 : ℝ)
    (hlo1 : (0 : ℝ) ≤ x1)
    (hhi1 : x1 ≤ (1 : ℝ))
    (hlo2 : (0 : ℝ) ≤ x2)
    (hhi2 : x2 ≤ (1 : ℝ))
    (hlo3 : (0 : ℝ) ≤ x3)
    (hhi3 : x3 ≤ (1 : ℝ))
    (hlo4 : (0 : ℝ) ≤ x4)
    (hhi4 : x4 ≤ (0 : ℝ))
    : ¬ (
      seed202_r78_gen011_minmax_lower_4_f01 x1 x2 x3 x4 ∧
      seed202_r78_gen011_minmax_lower_4_f02 x1 x2 x3 x4) := by
  rintro ⟨c1, c2⟩
  obtain rfl : x4 = (0 : ℝ) := le_antisymm hhi4 hlo4
  rcases le_total x1 (1 / 2 : ℝ) with hs1 | hs1
  · rcases le_total x2 (1 / 2 : ℝ) with hs2 | hs2
    · exact seed202_r78_gen011_minmax_lower_4_sub001 x1 x2 x3 hlo1 hs1 hlo2 hs2 hlo3 hhi3 c1
    · rcases le_total x3 (1 / 2 : ℝ) with hs3 | hs3
      · exact seed202_r78_gen011_minmax_lower_4_sub002 x1 x2 x3 hlo1 hs1 hs2 hhi2 hlo3 hs3 c1
      · rcases le_total x1 (1 / 4 : ℝ) with hs4 | hs4
        · rcases le_total x2 (3 / 4 : ℝ) with hs5 | hs5
          · exact seed202_r78_gen011_minmax_lower_4_sub003 x1 x2 x3 hlo1 hs4 hs2 hs5 hs3 hhi3 c1
          · rcases le_total x3 (3 / 4 : ℝ) with hs6 | hs6
            · exact seed202_r78_gen011_minmax_lower_4_sub004 x1 x2 x3 hlo1 hs4 hs5 hhi2 hs3 hs6 c1
            · rcases le_total x1 (1 / 8 : ℝ) with hs7 | hs7
              · rcases le_total x2 (7 / 8 : ℝ) with hs8 | hs8
                · rcases le_total x3 (7 / 8 : ℝ) with hs9 | hs9
                  · exact seed202_r78_gen011_minmax_lower_4_sub005 x1 x2 x3 hlo1 hs7 hs5 hs8 hs6 hs9 c1
                  · rcases le_total x1 (1 / 16 : ℝ) with hs10 | hs10
                    · rcases le_total x2 (13 / 16 : ℝ) with hs11 | hs11
                      · exact seed202_r78_gen011_minmax_lower_4_sub006 x1 x2 x3 hlo1 hs10 hs5 hs11 hs9 hhi3 c1
                      · rcases le_total x3 (15 / 16 : ℝ) with hs12 | hs12
                        · exact seed202_r78_gen011_minmax_lower_4_sub007 x1 x2 x3 hlo1 hs10 hs11 hs8 hs9 hs12 c1
                        · rcases le_total x1 (1 / 32 : ℝ) with hs13 | hs13
                          · rcases le_total x2 (27 / 32 : ℝ) with hs14 | hs14
                            · rcases le_total x3 (31 / 32 : ℝ) with hs15 | hs15
                              · exact seed202_r78_gen011_minmax_lower_4_sub008 x1 x2 x3 hlo1 hs13 hs11 hs14 hs12 hs15 c1
                              · rcases le_total x1 (1 / 64 : ℝ) with hs16 | hs16
                                · rcases le_total x2 (53 / 64 : ℝ) with hs17 | hs17
                                  · rcases le_total x3 (63 / 64 : ℝ) with hs18 | hs18
                                    · exact seed202_r78_gen011_minmax_lower_4_sub009 x1 x2 x3 hlo1 hs16 hs11 hs17 hs15 hs18 c1
                                    · rcases le_total x1 (1 / 128 : ℝ) with hs19 | hs19
                                      · rcases le_total x2 (105 / 128 : ℝ) with hs20 | hs20
                                        · exact seed202_r78_gen011_minmax_lower_4_sub010 x1 x2 x3 hlo1 hs19 hs11 hs20 hs18 hhi3 c1
                                        · rcases le_total x3 (127 / 128 : ℝ) with hs21 | hs21
                                          · exact seed202_r78_gen011_minmax_lower_4_sub011 x1 x2 x3 hlo1 hs19 hs20 hs17 hs18 hs21 c1
                                          · rcases le_total x1 (1 / 256 : ℝ) with hs22 | hs22
                                            · rcases le_total x2 (211 / 256 : ℝ) with hs23 | hs23
                                              · exact seed202_r78_gen011_minmax_lower_4_sub012 x1 x2 x3 hlo1 hs22 hs20 hs23 hs21 hhi3 c1
                                              · rcases le_total x3 (255 / 256 : ℝ) with hs24 | hs24
                                                · exact seed202_r78_gen011_minmax_lower_4_sub013 x1 x2 x3 hlo1 hs22 hs23 hs17 hs21 hs24 c1
                                                · rcases le_total x1 (1 / 512 : ℝ) with hs25 | hs25
                                                  · rcases le_total x2 (423 / 512 : ℝ) with hs26 | hs26
                                                    · rcases le_total x3 (511 / 512 : ℝ) with hs27 | hs27
                                                      · exact seed202_r78_gen011_minmax_lower_4_sub014 x1 x2 x3 hlo1 hs25 hs23 hs26 hs24 hs27 c1
                                                      · rcases le_total x1 (1 / 1024 : ℝ) with hs28 | hs28
                                                        · rcases le_total x2 (845 / 1024 : ℝ) with hs29 | hs29
                                                          · rcases le_total x3 (1023 / 1024 : ℝ) with hs30 | hs30
                                                            · exact seed202_r78_gen011_minmax_lower_4_sub015 x1 x2 x3 hlo1 hs28 hs23 hs29 hs27 hs30 c1
                                                            · rcases le_total x1 (1 / 2048 : ℝ) with hs31 | hs31
                                                              · rcases le_total x2 (1689 / 2048 : ℝ) with hs32 | hs32
                                                                · exact seed202_r78_gen011_minmax_lower_4_sub016 x1 x2 x3 hlo1 hs31 hs23 hs32 hs30 hhi3 c1
                                                                · rcases le_total x3 (2047 / 2048 : ℝ) with hs33 | hs33
                                                                  · exact seed202_r78_gen011_minmax_lower_4_sub017 x1 x2 x3 hlo1 hs31 hs32 hs29 hs30 hs33 c1
                                                                  · rcases le_total x1 (1 / 4096 : ℝ) with hs34 | hs34
                                                                    · rcases le_total x2 (3379 / 4096 : ℝ) with hs35 | hs35
                                                                      · exact seed202_r78_gen011_minmax_lower_4_sub018 x1 x2 x3 hlo1 hs34 hs32 hs35 hs33 hhi3 c1
                                                                      · rcases le_total x3 (4095 / 4096 : ℝ) with hs36 | hs36
                                                                        · exact seed202_r78_gen011_minmax_lower_4_sub019 x1 x2 x3 hlo1 hs34 hs35 hs29 hs33 hs36 c1
                                                                        · rcases le_total x1 (1 / 8192 : ℝ) with hs37 | hs37
                                                                          · rcases le_total x2 (6759 / 8192 : ℝ) with hs38 | hs38
                                                                            · exact seed202_r78_gen011_minmax_lower_4_sub020 x1 x2 x3 hlo1 hs37 hs35 hs38 hs36 hhi3 c1
                                                                            · rcases le_total x3 (8191 / 8192 : ℝ) with hs39 | hs39
                                                                              · exact seed202_r78_gen011_minmax_lower_4_sub021 x1 x2 x3 hlo1 hs37 hs38 hs29 hs36 hs39 c1
                                                                              · rcases le_total x1 (1 / 16384 : ℝ) with hs40 | hs40
                                                                                · rcases le_total x2 (13519 / 16384 : ℝ) with hs41 | hs41
                                                                                  · rcases le_total x3 (16383 / 16384 : ℝ) with hs42 | hs42
                                                                                    · exact seed202_r78_gen011_minmax_lower_4_sub022 x1 x2 x3 hlo1 hs40 hs38 hs41 hs39 hs42 c1
                                                                                    · rcases le_total x1 (1 / 32768 : ℝ) with hs43 | hs43
                                                                                      · exact seed202_r78_gen011_minmax_lower_4_sub023 x1 x2 x3 hlo1 hs43 hs38 hs41 hs42 hhi3 c1 c2
                                                                                      · exact seed202_r78_gen011_minmax_lower_4_sub024 x1 x2 x3 hs43 hs40 hs38 hs41 hs42 hhi3 c1 c2
                                                                                  · exact seed202_r78_gen011_minmax_lower_4_sub025 x1 x2 x3 hlo1 hs40 hs41 hs29 hs39 hhi3 c2
                                                                                · exact seed202_r78_gen011_minmax_lower_4_sub026 x1 x2 x3 hs40 hs37 hs38 hs29 hs39 hhi3 c1 c2
                                                                          · exact seed202_r78_gen011_minmax_lower_4_sub027 x1 x2 x3 hs37 hs34 hs35 hs29 hs36 hhi3 c1 c2
                                                                    · exact seed202_r78_gen011_minmax_lower_4_sub028 x1 x2 x3 hs34 hs31 hs32 hs29 hs33 hhi3 c1 c2
                                                              · exact seed202_r78_gen011_minmax_lower_4_sub029 x1 x2 x3 hs31 hs28 hs23 hs29 hs30 hhi3 c1 c2
                                                          · exact seed202_r78_gen011_minmax_lower_4_sub030 x1 x2 x3 hlo1 hs28 hs29 hs26 hs27 hhi3 c2
                                                        · exact seed202_r78_gen011_minmax_lower_4_sub031 x1 x2 x3 hs28 hs25 hs23 hs26 hs27 hhi3 c1 c2
                                                    · exact seed202_r78_gen011_minmax_lower_4_sub032 x1 x2 x3 hlo1 hs25 hs26 hs17 hs24 hhi3 c2
                                                  · exact seed202_r78_gen011_minmax_lower_4_sub033 x1 x2 x3 hs25 hs22 hs23 hs17 hs24 hhi3 c1 c2
                                            · exact seed202_r78_gen011_minmax_lower_4_sub034 x1 x2 x3 hs22 hs19 hs20 hs17 hs21 hhi3 c1 c2
                                      · exact seed202_r78_gen011_minmax_lower_4_sub035 x1 x2 x3 hs19 hs16 hs11 hs17 hs18 hhi3 c1 c2
                                  · exact seed202_r78_gen011_minmax_lower_4_sub036 x1 x2 x3 hlo1 hs16 hs17 hs14 hs15 hhi3 c2
                                · exact seed202_r78_gen011_minmax_lower_4_sub037 x1 x2 x3 hs16 hs13 hs11 hs14 hs15 hhi3 c1 c2
                            · exact seed202_r78_gen011_minmax_lower_4_sub038 x1 x2 x3 hlo1 hs13 hs14 hs8 hs12 hhi3 c2
                          · exact seed202_r78_gen011_minmax_lower_4_sub039 x1 x2 x3 hs13 hs10 hs11 hs8 hs12 hhi3 c1 c2
                    · exact seed202_r78_gen011_minmax_lower_4_sub040 x1 x2 x3 hs10 hs7 hs5 hs8 hs9 hhi3 c1 c2
                · exact seed202_r78_gen011_minmax_lower_4_sub041 x1 x2 x3 hlo1 hs7 hs8 hhi2 hs6 hhi3 c2
              · exact seed202_r78_gen011_minmax_lower_4_sub042 x1 x2 x3 hs7 hs4 hs5 hhi2 hs6 hhi3 c1 c2
        · exact seed202_r78_gen011_minmax_lower_4_sub043 x1 x2 x3 hs4 hs1 hs2 hhi2 hs3 hhi3 c1 c2
  · exact seed202_r78_gen011_minmax_lower_4_sub044 x1 x2 x3 hs1 hhi1 hlo2 hhi2 hlo3 hhi3 c1 c2


/-- Certificate identifier proved in this module. The `#guard`
below turns a silently dropped certificate into a compile error. -/
def Seed202R78Gen011MinmaxLower4Ids : List String :=
  ["v1/v0/seed202_r78_gen011/minmax_lower_4"]

#guard Seed202R78Gen011MinmaxLower4Ids.length = 1

end Quitting.V0
