-- GENERATED by code/julia/scripts/certificates/v0_from_recorded.jl — do not edit.
-- Regenerate and `git diff --exit-code` to prove the Lean corpus is a
-- pure function of the JSON certificates.

import Formal.Certificates.Prelude
import Formal.Certificates.V0.Seed202R78Gen011MinmaxLower4.Defs

set_option maxRecDepth 8000
set_option maxHeartbeats 1000000

namespace Quitting.V0

theorem seed202_r78_gen011_minmax_lower_4_sub044
    (x1 x2 x3 : ℝ)
    (hlo1 : (1 / 2 : ℝ) ≤ x1)
    (hhi1 : x1 ≤ (1 : ℝ))
    (hlo2 : (0 : ℝ) ≤ x2)
    (hhi2 : x2 ≤ (1 : ℝ))
    (hlo3 : (0 : ℝ) ≤ x3)
    (hhi3 : x3 ≤ (1 : ℝ))
    (c1 : seed202_r78_gen011_minmax_lower_4_f01 x1 x2 x3 (0 : ℝ))
    (c2 : seed202_r78_gen011_minmax_lower_4_f02 x1 x2 x3 (0 : ℝ))
    : False := by
  simp only [seed202_r78_gen011_minmax_lower_4_f01, seed202_r78_gen011_minmax_lower_4_f02] at c1 c2
  rcases le_total x2 (1 / 2 : ℝ) with hs1 | hs1
  · -- `quit_at_most_L` ≥ 1380425 / 54788096 > 0 on x1 ∈ [1 / 2, 1], x2 ∈ [0, 1 / 2], x3 ∈ [0, 1]
    have d1lo : (0:ℝ) ≤ x1 - 1 / 2 := sub_nonneg.mpr hlo1
    have d1hi : (0:ℝ) ≤ 1 - x1 := sub_nonneg.mpr hhi1
    have d2lo : (0:ℝ) ≤ x2 - 0 := sub_nonneg.mpr hlo2
    have d2hi : (0:ℝ) ≤ 1 / 2 - x2 := sub_nonneg.mpr hs1
    have d3lo : (0:ℝ) ≤ x3 - 0 := sub_nonneg.mpr hlo3
    have d3hi : (0:ℝ) ≤ 1 - x3 := sub_nonneg.mpr hhi3
    linarith only [c1, mul_nonneg (mul_nonneg (d1hi) d2hi) d3hi, mul_nonneg (mul_nonneg (d1lo) d2hi) d3hi, mul_nonneg (mul_nonneg (d1hi) d2lo) d3hi, mul_nonneg (mul_nonneg (d1lo) d2lo) d3hi, mul_nonneg (mul_nonneg (d1hi) d2hi) d3lo, mul_nonneg (mul_nonneg (d1lo) d2hi) d3lo, mul_nonneg (mul_nonneg (d1hi) d2lo) d3lo, mul_nonneg (mul_nonneg (d1lo) d2lo) d3lo]
  · rcases le_total x3 (1 / 2 : ℝ) with hs2 | hs2
    · -- `quit_at_most_L` ≥ 1675699 / 2883584 > 0 on x1 ∈ [1 / 2, 1], x2 ∈ [1 / 2, 1], x3 ∈ [0, 1 / 2]
      have d1lo : (0:ℝ) ≤ x1 - 1 / 2 := sub_nonneg.mpr hlo1
      have d1hi : (0:ℝ) ≤ 1 - x1 := sub_nonneg.mpr hhi1
      have d2lo : (0:ℝ) ≤ x2 - 1 / 2 := sub_nonneg.mpr hs1
      have d2hi : (0:ℝ) ≤ 1 - x2 := sub_nonneg.mpr hhi2
      have d3lo : (0:ℝ) ≤ x3 - 0 := sub_nonneg.mpr hlo3
      have d3hi : (0:ℝ) ≤ 1 / 2 - x3 := sub_nonneg.mpr hs2
      linarith only [c1, mul_nonneg (mul_nonneg (d1hi) d2hi) d3hi, mul_nonneg (mul_nonneg (d1lo) d2hi) d3hi, mul_nonneg (mul_nonneg (d1hi) d2lo) d3hi, mul_nonneg (mul_nonneg (d1lo) d2lo) d3hi, mul_nonneg (mul_nonneg (d1hi) d2hi) d3lo, mul_nonneg (mul_nonneg (d1lo) d2hi) d3lo, mul_nonneg (mul_nonneg (d1hi) d2lo) d3lo, mul_nonneg (mul_nonneg (d1lo) d2lo) d3lo]
    · rcases le_total x1 (3 / 4 : ℝ) with hs3 | hs3
      · rcases le_total x2 (3 / 4 : ℝ) with hs4 | hs4
        · -- `quit_at_most_L` ≥ 65698007 / 1698430976 > 0 on x1 ∈ [1 / 2, 3 / 4], x2 ∈ [1 / 2, 3 / 4], x3 ∈ [1 / 2, 1]
          have d1lo : (0:ℝ) ≤ x1 - 1 / 2 := sub_nonneg.mpr hlo1
          have d1hi : (0:ℝ) ≤ 3 / 4 - x1 := sub_nonneg.mpr hs3
          have d2lo : (0:ℝ) ≤ x2 - 1 / 2 := sub_nonneg.mpr hs1
          have d2hi : (0:ℝ) ≤ 3 / 4 - x2 := sub_nonneg.mpr hs4
          have d3lo : (0:ℝ) ≤ x3 - 1 / 2 := sub_nonneg.mpr hs2
          have d3hi : (0:ℝ) ≤ 1 - x3 := sub_nonneg.mpr hhi3
          linarith only [c1, mul_nonneg (mul_nonneg (d1hi) d2hi) d3hi, mul_nonneg (mul_nonneg (d1lo) d2hi) d3hi, mul_nonneg (mul_nonneg (d1hi) d2lo) d3hi, mul_nonneg (mul_nonneg (d1lo) d2lo) d3hi, mul_nonneg (mul_nonneg (d1hi) d2hi) d3lo, mul_nonneg (mul_nonneg (d1lo) d2hi) d3lo, mul_nonneg (mul_nonneg (d1hi) d2lo) d3lo, mul_nonneg (mul_nonneg (d1lo) d2lo) d3lo]
        · -- `wait_at_most_L` ≥ 2862811 / 30146560 > 0 on x1 ∈ [1 / 2, 3 / 4], x2 ∈ [3 / 4, 1], x3 ∈ [1 / 2, 1]
          have d1lo : (0:ℝ) ≤ x1 - 1 / 2 := sub_nonneg.mpr hlo1
          have d1hi : (0:ℝ) ≤ 3 / 4 - x1 := sub_nonneg.mpr hs3
          have d2lo : (0:ℝ) ≤ x2 - 3 / 4 := sub_nonneg.mpr hs4
          have d2hi : (0:ℝ) ≤ 1 - x2 := sub_nonneg.mpr hhi2
          have d3lo : (0:ℝ) ≤ x3 - 1 / 2 := sub_nonneg.mpr hs2
          have d3hi : (0:ℝ) ≤ 1 - x3 := sub_nonneg.mpr hhi3
          linarith only [c2, mul_nonneg (mul_nonneg (d1hi) d2hi) d3hi, mul_nonneg (mul_nonneg (d1lo) d2hi) d3hi, mul_nonneg (mul_nonneg (d1hi) d2lo) d3hi, mul_nonneg (mul_nonneg (d1lo) d2lo) d3hi, mul_nonneg (mul_nonneg (d1hi) d2hi) d3lo, mul_nonneg (mul_nonneg (d1lo) d2hi) d3lo, mul_nonneg (mul_nonneg (d1hi) d2lo) d3lo, mul_nonneg (mul_nonneg (d1lo) d2lo) d3lo]
      · -- `wait_at_most_L` ≥ 272791 / 3932160 > 0 on x1 ∈ [3 / 4, 1], x2 ∈ [1 / 2, 1], x3 ∈ [1 / 2, 1]
        have d1lo : (0:ℝ) ≤ x1 - 3 / 4 := sub_nonneg.mpr hs3
        have d1hi : (0:ℝ) ≤ 1 - x1 := sub_nonneg.mpr hhi1
        have d2lo : (0:ℝ) ≤ x2 - 1 / 2 := sub_nonneg.mpr hs1
        have d2hi : (0:ℝ) ≤ 1 - x2 := sub_nonneg.mpr hhi2
        have d3lo : (0:ℝ) ≤ x3 - 1 / 2 := sub_nonneg.mpr hs2
        have d3hi : (0:ℝ) ≤ 1 - x3 := sub_nonneg.mpr hhi3
        linarith only [c2, mul_nonneg (mul_nonneg (d1hi) d2hi) d3hi, mul_nonneg (mul_nonneg (d1lo) d2hi) d3hi, mul_nonneg (mul_nonneg (d1hi) d2lo) d3hi, mul_nonneg (mul_nonneg (d1lo) d2lo) d3hi, mul_nonneg (mul_nonneg (d1hi) d2hi) d3lo, mul_nonneg (mul_nonneg (d1lo) d2hi) d3lo, mul_nonneg (mul_nonneg (d1hi) d2lo) d3lo, mul_nonneg (mul_nonneg (d1lo) d2lo) d3lo]

end Quitting.V0
