-- GENERATED by code/julia/scripts/certificates/c6_from_witness.jl — do not edit.
-- Regenerated for the public corpus: only seed202_r78_gen011.

import Formal.Certificates.Prelude

set_option maxRecDepth 8000

namespace Quitting.Sharpness

-- Conditions of certificate `seed202_r78_gen011_margin_161_1000`, one per declaration.
-- Together they say: the profile is in the stratified domain and no
-- player gains more than the stated deviation level.

/-- Condition `x1>=xmin` of `seed202_r78_gen011_margin_161_1000`. -/
def seed202_r78_gen011_c01 (x1 _x2 _x3 _x4 : ℝ) : Prop :=
  0 ≤ -1 / 1000 + x1

/-- Condition `x1<=1` of `seed202_r78_gen011_margin_161_1000`. -/
def seed202_r78_gen011_c02 (x1 _x2 _x3 _x4 : ℝ) : Prop :=
  0 ≤ 1 - x1

/-- Condition `x2>=xmin` of `seed202_r78_gen011_margin_161_1000`. -/
def seed202_r78_gen011_c03 (_x1 x2 _x3 _x4 : ℝ) : Prop :=
  0 ≤ -1 / 1000 + x2

/-- Condition `x2<=1` of `seed202_r78_gen011_margin_161_1000`. -/
def seed202_r78_gen011_c04 (_x1 x2 _x3 _x4 : ℝ) : Prop :=
  0 ≤ 1 - x2

/-- Condition `x4>=xmin` of `seed202_r78_gen011_margin_161_1000`. -/
def seed202_r78_gen011_c05 (_x1 _x2 _x3 x4 : ℝ) : Prop :=
  0 ≤ -1 / 1000 + x4

/-- Condition `x4<=1` of `seed202_r78_gen011_margin_161_1000`. -/
def seed202_r78_gen011_c06 (_x1 _x2 _x3 x4 : ℝ) : Prop :=
  0 ≤ 1 - x4

/-- Condition `pabs>=pmin` of `seed202_r78_gen011_margin_161_1000`. -/
def seed202_r78_gen011_c07 (x1 x2 _x3 x4 : ℝ) : Prop :=
  0 ≤ -1 / 100 + x4 + x2 - x2 * x4 + x1 - x1 * x4 - x1 * x2 + x1 * x2 * x4

/-- Condition `quit1` of `seed202_r78_gen011_margin_161_1000`. -/
def seed202_r78_gen011_c08 (x1 x2 _x3 x4 : ℝ) : Prop :=
  0 ≤ -1517 / 3000 * x4 - 8 / 17 * x4 ^ 2 + 1483 / 3000 * x2 + 1612757 / 663000 * x2 * x4 - 1267 / 442 * x2 * x4 ^ 2 + 3 * x2 ^ 2 - 2801 / 442 * x2 ^ 2 * x4 + 1475 / 442 * x2 ^ 2 * x4 ^ 2 + 161 / 1000 * x1 + 1517 / 3000 * x1 * x4 + 8 / 17 * x1 * x4 ^ 2 - 1483 / 3000 * x1 * x2 - 1612757 / 663000 * x1 * x2 * x4 + 1267 / 442 * x1 * x2 * x4 ^ 2 - 3 * x1 * x2 ^ 2 + 2801 / 442 * x1 * x2 ^ 2 * x4 - 1475 / 442 * x1 * x2 ^ 2 * x4 ^ 2

/-- Condition `cont1` of `seed202_r78_gen011_margin_161_1000`. -/
def seed202_r78_gen011_c09 (x1 x2 _x3 x4 : ℝ) : Prop :=
  0 ≤ 161 / 1000 * x4 ^ 2 + 161 / 500 * x2 * x4 - 161 / 500 * x2 * x4 ^ 2 + 161 / 1000 * x2 ^ 2 - 161 / 500 * x2 ^ 2 * x4 + 161 / 1000 * x2 ^ 2 * x4 ^ 2 + 2483 / 3000 * x1 * x4 + 5263 / 17000 * x1 * x4 ^ 2 - 517 / 3000 * x1 * x2 - 2039729 / 663000 * x1 * x2 * x4 + 352331 / 110500 * x1 * x2 * x4 ^ 2 - 3161 / 1000 * x1 * x2 ^ 2 + 735831 / 110500 * x1 * x2 ^ 2 * x4 - 773081 / 221000 * x1 * x2 ^ 2 * x4 ^ 2

/-- Condition `quit2` of `seed202_r78_gen011_margin_161_1000`. -/
def seed202_r78_gen011_c10 (x1 x2 _x3 x4 : ℝ) : Prop :=
  0 ≤ 6161 / 1000 * x4 + 17 / 29 * x4 ^ 2 + 161 / 1000 * x2 - 6161 / 1000 * x2 * x4 - 17 / 29 * x2 * x4 ^ 2 - 839 / 1000 * x1 - 1647859 / 319000 * x1 * x4 - 6950 / 4147 * x1 * x4 ^ 2 + 839 / 1000 * x1 * x2 + 1647859 / 319000 * x1 * x2 * x4 + 6950 / 4147 * x1 * x2 * x4 ^ 2 - 5 / 22 * x1 ^ 2 - 7153 / 8294 * x1 ^ 2 * x4 + 4519 / 4147 * x1 ^ 2 * x4 ^ 2 + 5 / 22 * x1 ^ 2 * x2 + 7153 / 8294 * x1 ^ 2 * x2 * x4 - 4519 / 4147 * x1 ^ 2 * x2 * x4 ^ 2

/-- Condition `cont2` of `seed202_r78_gen011_margin_161_1000`. -/
def seed202_r78_gen011_c11 (x1 x2 _x3 x4 : ℝ) : Prop :=
  0 ≤ 161 / 1000 * x4 ^ 2 - 5839 / 1000 * x2 * x4 - 21669 / 29000 * x2 * x4 ^ 2 + 161 / 500 * x1 * x4 - 161 / 500 * x1 * x4 ^ 2 + 1161 / 1000 * x1 * x2 + 1442423 / 319000 * x1 * x2 * x4 + 4142667 / 2073500 * x1 * x2 * x4 ^ 2 + 161 / 1000 * x1 ^ 2 - 161 / 500 * x1 ^ 2 * x4 + 161 / 1000 * x1 ^ 2 * x4 ^ 2 + 729 / 11000 * x1 ^ 2 * x2 + 2455917 / 2073500 * x1 ^ 2 * x2 * x4 - 5186667 / 4147000 * x1 ^ 2 * x2 * x4 ^ 2

/-- Condition `quit3` of `seed202_r78_gen011_margin_161_1000`. -/
def seed202_r78_gen011_c12 (x1 x2 _x3 x4 : ℝ) : Prop :=
  0 ≤ 5161 / 1000 * x4 + 19 / 12 * x4 ^ 2 - 4839 / 1000 * x2 - 117833 / 228000 * x2 * x4 - 1 / 114 * x2 * x4 ^ 2 - 3 / 19 * x2 ^ 2 + 395 / 228 * x2 ^ 2 * x4 - 359 / 228 * x2 ^ 2 * x4 ^ 2 + 4161 / 1000 * x1 - 845723 / 93000 * x1 * x4 - 1171 / 434 * x1 * x4 ^ 2 - 491829 / 589000 * x1 * x2 + 86583587 / 16492000 * x1 * x2 * x4 + 21997 / 119567 * x1 * x2 * x4 ^ 2 - 1277 / 589 * x1 * x2 ^ 2 - 82765 / 239134 * x1 * x2 ^ 2 * x4 + 601227 / 239134 * x1 * x2 ^ 2 * x4 ^ 2 + 46 / 31 * x1 ^ 2 - 6767 / 2604 * x1 ^ 2 * x4 + 2903 / 2604 * x1 ^ 2 * x4 ^ 2 - 2244 / 589 * x1 ^ 2 * x2 + 2858881 / 717402 * x1 ^ 2 * x2 * x4 - 125689 / 717402 * x1 ^ 2 * x2 * x4 ^ 2 + 1370 / 589 * x1 ^ 2 * x2 ^ 2 - 1989145 / 1434804 * x1 ^ 2 * x2 ^ 2 * x4 - 1348175 / 1434804 * x1 ^ 2 * x2 ^ 2 * x4 ^ 2

/-- Condition `quit4` of `seed202_r78_gen011_margin_161_1000`. -/
def seed202_r78_gen011_c13 (x1 x2 _x3 x4 : ℝ) : Prop :=
  0 ≤ 161 / 1000 * x4 + 1161 / 1000 * x2 - 1161 / 1000 * x2 * x4 - 8 / 9 * x2 ^ 2 + 8 / 9 * x2 ^ 2 * x4 + 5161 / 1000 * x1 - 5161 / 1000 * x1 * x4 - 77459 / 9000 * x1 * x2 + 77459 / 9000 * x1 * x2 * x4 + 239 / 72 * x1 * x2 ^ 2 - 239 / 72 * x1 * x2 ^ 2 * x4 - 11 / 12 * x1 ^ 2 + 11 / 12 * x1 ^ 2 * x4 + 241 / 72 * x1 ^ 2 * x2 - 241 / 72 * x1 ^ 2 * x2 * x4 - 175 / 72 * x1 ^ 2 * x2 ^ 2 + 175 / 72 * x1 ^ 2 * x2 ^ 2 * x4

/-- Condition `cont4` of `seed202_r78_gen011_margin_161_1000`. -/
def seed202_r78_gen011_c14 (x1 x2 _x3 x4 : ℝ) : Prop :=
  0 ≤ -839 / 1000 * x2 * x4 + 161 / 1000 * x2 ^ 2 + 6551 / 9000 * x2 ^ 2 * x4 - 4839 / 1000 * x1 * x4 + 161 / 500 * x1 * x2 + 71663 / 9000 * x1 * x2 * x4 - 161 / 500 * x1 * x2 ^ 2 - 26977 / 9000 * x1 * x2 ^ 2 * x4 + 161 / 1000 * x1 ^ 2 + 2267 / 3000 * x1 ^ 2 * x4 - 161 / 500 * x1 ^ 2 * x2 - 27227 / 9000 * x1 ^ 2 * x2 * x4 + 161 / 1000 * x1 ^ 2 * x2 ^ 2 + 10213 / 4500 * x1 ^ 2 * x2 ^ 2 * x4

theorem seed202_r78_gen011_c01_holds : seed202_r78_gen011_c01 (4477 / 500000) (1751 / 200000) (0) (1 / 1000) := by
  unfold seed202_r78_gen011_c01
  norm_num

theorem seed202_r78_gen011_c02_holds : seed202_r78_gen011_c02 (4477 / 500000) (1751 / 200000) (0) (1 / 1000) := by
  unfold seed202_r78_gen011_c02
  norm_num

theorem seed202_r78_gen011_c03_holds : seed202_r78_gen011_c03 (4477 / 500000) (1751 / 200000) (0) (1 / 1000) := by
  unfold seed202_r78_gen011_c03
  norm_num

theorem seed202_r78_gen011_c04_holds : seed202_r78_gen011_c04 (4477 / 500000) (1751 / 200000) (0) (1 / 1000) := by
  unfold seed202_r78_gen011_c04
  norm_num

theorem seed202_r78_gen011_c05_holds : seed202_r78_gen011_c05 (4477 / 500000) (1751 / 200000) (0) (1 / 1000) := by
  unfold seed202_r78_gen011_c05
  norm_num

theorem seed202_r78_gen011_c06_holds : seed202_r78_gen011_c06 (4477 / 500000) (1751 / 200000) (0) (1 / 1000) := by
  unfold seed202_r78_gen011_c06
  norm_num

theorem seed202_r78_gen011_c07_holds : seed202_r78_gen011_c07 (4477 / 500000) (1751 / 200000) (0) (1 / 1000) := by
  unfold seed202_r78_gen011_c07
  norm_num

theorem seed202_r78_gen011_c08_holds : seed202_r78_gen011_c08 (4477 / 500000) (1751 / 200000) (0) (1 / 1000) := by
  unfold seed202_r78_gen011_c08
  norm_num

theorem seed202_r78_gen011_c09_holds : seed202_r78_gen011_c09 (4477 / 500000) (1751 / 200000) (0) (1 / 1000) := by
  unfold seed202_r78_gen011_c09
  norm_num

theorem seed202_r78_gen011_c10_holds : seed202_r78_gen011_c10 (4477 / 500000) (1751 / 200000) (0) (1 / 1000) := by
  unfold seed202_r78_gen011_c10
  norm_num

theorem seed202_r78_gen011_c11_holds : seed202_r78_gen011_c11 (4477 / 500000) (1751 / 200000) (0) (1 / 1000) := by
  unfold seed202_r78_gen011_c11
  norm_num

theorem seed202_r78_gen011_c12_holds : seed202_r78_gen011_c12 (4477 / 500000) (1751 / 200000) (0) (1 / 1000) := by
  unfold seed202_r78_gen011_c12
  norm_num

theorem seed202_r78_gen011_c13_holds : seed202_r78_gen011_c13 (4477 / 500000) (1751 / 200000) (0) (1 / 1000) := by
  unfold seed202_r78_gen011_c13
  norm_num

theorem seed202_r78_gen011_c14_holds : seed202_r78_gen011_c14 (4477 / 500000) (1751 / 200000) (0) (1 / 1000) := by
  unfold seed202_r78_gen011_c14
  norm_num

/-- Certificate `v1/sharpness/seed202_r78_gen011/margin_161_1000`: sharpness witness (seed202_r78_gen011): this exact rational stationary profile lies in the stratified domain and leaves every player a deviation gain of at most 161/1000.

Stated as an existential over one tuple: the near-equilibrium set at
this deviation level is non-empty, so the certified lower bound on the
margin cannot be raised past it. Machine-written. -/
theorem seed202_r78_gen011_margin_161_1000 :
    ∃ x1 x2 x3 x4 : ℝ,
      seed202_r78_gen011_c01 x1 x2 x3 x4 ∧
      seed202_r78_gen011_c02 x1 x2 x3 x4 ∧
      seed202_r78_gen011_c03 x1 x2 x3 x4 ∧
      seed202_r78_gen011_c04 x1 x2 x3 x4 ∧
      seed202_r78_gen011_c05 x1 x2 x3 x4 ∧
      seed202_r78_gen011_c06 x1 x2 x3 x4 ∧
      seed202_r78_gen011_c07 x1 x2 x3 x4 ∧
      seed202_r78_gen011_c08 x1 x2 x3 x4 ∧
      seed202_r78_gen011_c09 x1 x2 x3 x4 ∧
      seed202_r78_gen011_c10 x1 x2 x3 x4 ∧
      seed202_r78_gen011_c11 x1 x2 x3 x4 ∧
      seed202_r78_gen011_c12 x1 x2 x3 x4 ∧
      seed202_r78_gen011_c13 x1 x2 x3 x4 ∧
      seed202_r78_gen011_c14 x1 x2 x3 x4 :=
  ⟨4477 / 500000, 1751 / 200000, 0, 1 / 1000,
   seed202_r78_gen011_c01_holds, seed202_r78_gen011_c02_holds, seed202_r78_gen011_c03_holds, seed202_r78_gen011_c04_holds, seed202_r78_gen011_c05_holds, seed202_r78_gen011_c06_holds, seed202_r78_gen011_c07_holds, seed202_r78_gen011_c08_holds, seed202_r78_gen011_c09_holds, seed202_r78_gen011_c10_holds, seed202_r78_gen011_c11_holds, seed202_r78_gen011_c12_holds, seed202_r78_gen011_c13_holds, seed202_r78_gen011_c14_holds⟩

/-- Certificate identifiers in this batch. The `#guard` below turns
a silently dropped certificate into a compile error. -/
def batch01Ids : List String :=
  ["v1/sharpness/seed202_r78_gen011/margin_161_1000"]

#guard batch01Ids.length = 1

end Quitting.Sharpness
