-- GENERATED by code/julia/scripts/certificates/l8_simultaneous.jl — do not edit.
-- Regenerated for the public corpus: only seed202_r78_gen011.

import Formal.Certificates.Prelude

set_option maxRecDepth 8000

namespace Quitting.SimultaneousQuit

/-- Certificate `v1/simultaneous_quit/seed202_r78_gen011/B12`: coalition {1, 2}: no strictly positive z solves M z = 0, where M is the principal submatrix of the unilateral matrix on players 1, 2 -- its (i,j) entry is the shifted payoff to the i-th of them when the j-th quits alone, so the system says every member of the coalition is indifferent while all of them quit at a positive rate. The conditions below are the linear forms (M^T y)_i with the payoff entries as their coefficients, and the point is the y that makes them non-negative and not all zero: any z > 0 with M z = 0 would then give 0 = <M z, y> = <z, M^T y> > 0. This is the hypothesis of (L8) for this coalition (docs/G3_MIXED_APS.md 12.2).

The players of the coalition are [1, 2]; `z1` .. `z2` are their quit rates, in that order. Machine-written. -/
theorem Seed202R78Gen011L8B12 :
    ∀ z1 z2 : ℝ,
      0 < z1 →
      0 < z2 →
      0 * z1 + 1 / 3 * z2 = 0 →
       - z1 + 0 * z2 = 0 →
      False := by
  intro z1 z2 h1 h2 e1 e2
  -- Combining the equations with the coefficients
  --   y = [0, -1]
  -- gives Σ_i (Mᵀy)_i · z_i = 0 with
  --   Mᵀy = [1, 0],
  -- every entry ≥ 0 and at least one > 0, against z > 0. That
  -- combination is rational and linear, so linarith finds one
  -- itself; y is recorded here and in the JSON as the reason the
  -- search cannot fail, not as an input Lean is trusted with.
  linarith

/-- Certificate `v1/simultaneous_quit/seed202_r78_gen011/B13`: coalition {1, 3}: no strictly positive z solves M z = 0, where M is the principal submatrix of the unilateral matrix on players 1, 3 -- its (i,j) entry is the shifted payoff to the i-th of them when the j-th quits alone, so the system says every member of the coalition is indifferent while all of them quit at a positive rate. The conditions below are the linear forms (M^T y)_i with the payoff entries as their coefficients, and the point is the y that makes them non-negative and not all zero: any z > 0 with M z = 0 would then give 0 = <M z, y> = <z, M^T y> > 0. This is the hypothesis of (L8) for this coalition (docs/G3_MIXED_APS.md 12.2).

The players of the coalition are [1, 3]; `z1` .. `z2` are their quit rates, in that order. Machine-written. -/
theorem Seed202R78Gen011L8B13 :
    ∀ z1 z2 : ℝ,
      0 < z1 →
      0 < z2 →
      0 * z1 + 5 * z2 = 0 →
      4 * z1 + 0 * z2 = 0 →
      False := by
  intro z1 z2 h1 h2 e1 e2
  -- Combining the equations with the coefficients
  --   y = [0, 1 / 4]
  -- gives Σ_i (Mᵀy)_i · z_i = 0 with
  --   Mᵀy = [1, 0],
  -- every entry ≥ 0 and at least one > 0, against z > 0. That
  -- combination is rational and linear, so linarith finds one
  -- itself; y is recorded here and in the JSON as the reason the
  -- search cannot fail, not as an input Lean is trusted with.
  linarith

/-- Certificate `v1/simultaneous_quit/seed202_r78_gen011/B23`: coalition {2, 3}: no strictly positive z solves M z = 0, where M is the principal submatrix of the unilateral matrix on players 2, 3 -- its (i,j) entry is the shifted payoff to the i-th of them when the j-th quits alone, so the system says every member of the coalition is indifferent while all of them quit at a positive rate. The conditions below are the linear forms (M^T y)_i with the payoff entries as their coefficients, and the point is the y that makes them non-negative and not all zero: any z > 0 with M z = 0 would then give 0 = <M z, y> = <z, M^T y> > 0. This is the hypothesis of (L8) for this coalition (docs/G3_MIXED_APS.md 12.2).

The players of the coalition are [2, 3]; `z1` .. `z2` are their quit rates, in that order. Machine-written. -/
theorem Seed202R78Gen011L8B23 :
    ∀ z1 z2 : ℝ,
      0 < z1 →
      0 < z2 →
      0 * z1 - z2 = 0 →
       - 5 * z1 + 0 * z2 = 0 →
      False := by
  intro z1 z2 h1 h2 e1 e2
  -- Combining the equations with the coefficients
  --   y = [0, -1 / 5]
  -- gives Σ_i (Mᵀy)_i · z_i = 0 with
  --   Mᵀy = [1, 0],
  -- every entry ≥ 0 and at least one > 0, against z > 0. That
  -- combination is rational and linear, so linarith finds one
  -- itself; y is recorded here and in the JSON as the reason the
  -- search cannot fail, not as an input Lean is trusted with.
  linarith

/-- Certificate `v1/simultaneous_quit/seed202_r78_gen011/B123`: coalition {1, 2, 3}: no strictly positive z solves M z = 0, where M is the principal submatrix of the unilateral matrix on players 1, 2, 3 -- its (i,j) entry is the shifted payoff to the i-th of them when the j-th quits alone, so the system says every member of the coalition is indifferent while all of them quit at a positive rate. The conditions below are the linear forms (M^T y)_i with the payoff entries as their coefficients, and the point is the y that makes them non-negative and not all zero: any z > 0 with M z = 0 would then give 0 = <M z, y> = <z, M^T y> > 0. This is the hypothesis of (L8) for this coalition (docs/G3_MIXED_APS.md 12.2).

The players of the coalition are [1, 2, 3]; `z1` .. `z3` are their quit rates, in that order. Machine-written. -/
theorem Seed202R78Gen011L8B123 :
    ∀ z1 z2 z3 : ℝ,
      0 < z1 →
      0 < z2 →
      0 < z3 →
      0 * z1 + 1 / 3 * z2 + 5 * z3 = 0 →
       - z1 + 0 * z2 - z3 = 0 →
      4 * z1 - 5 * z2 + 0 * z3 = 0 →
      False := by
  intro z1 z2 z3 h1 h2 h3 e1 e2 e3
  -- Combining the equations with the coefficients
  --   y = [15 / 71, 4 / 71, 1 / 71]
  -- gives Σ_i (Mᵀy)_i · z_i = 0 with
  --   Mᵀy = [0, 0, 1],
  -- every entry ≥ 0 and at least one > 0, against z > 0. That
  -- combination is rational and linear, so linarith finds one
  -- itself; y is recorded here and in the JSON as the reason the
  -- search cannot fail, not as an input Lean is trusted with.
  linarith

/-- Certificate `v1/simultaneous_quit/seed202_r78_gen011/B14`: coalition {1, 4}: no strictly positive z solves M z = 0, where M is the principal submatrix of the unilateral matrix on players 1, 4 -- its (i,j) entry is the shifted payoff to the i-th of them when the j-th quits alone, so the system says every member of the coalition is indifferent while all of them quit at a positive rate. The conditions below are the linear forms (M^T y)_i with the payoff entries as their coefficients, and the point is the y that makes them non-negative and not all zero: any z > 0 with M z = 0 would then give 0 = <M z, y> = <z, M^T y> > 0. This is the hypothesis of (L8) for this coalition (docs/G3_MIXED_APS.md 12.2).

The players of the coalition are [1, 4]; `z1` .. `z2` are their quit rates, in that order. Machine-written. -/
theorem Seed202R78Gen011L8B14 :
    ∀ z1 z2 : ℝ,
      0 < z1 →
      0 < z2 →
      0 * z1 - 2 / 3 * z2 = 0 →
      5 * z1 + 0 * z2 = 0 →
      False := by
  intro z1 z2 h1 h2 e1 e2
  -- Combining the equations with the coefficients
  --   y = [0, 1 / 5]
  -- gives Σ_i (Mᵀy)_i · z_i = 0 with
  --   Mᵀy = [1, 0],
  -- every entry ≥ 0 and at least one > 0, against z > 0. That
  -- combination is rational and linear, so linarith finds one
  -- itself; y is recorded here and in the JSON as the reason the
  -- search cannot fail, not as an input Lean is trusted with.
  linarith

/-- Certificate `v1/simultaneous_quit/seed202_r78_gen011/B24`: coalition {2, 4}: no strictly positive z solves M z = 0, where M is the principal submatrix of the unilateral matrix on players 2, 4 -- its (i,j) entry is the shifted payoff to the i-th of them when the j-th quits alone, so the system says every member of the coalition is indifferent while all of them quit at a positive rate. The conditions below are the linear forms (M^T y)_i with the payoff entries as their coefficients, and the point is the y that makes them non-negative and not all zero: any z > 0 with M z = 0 would then give 0 = <M z, y> = <z, M^T y> > 0. This is the hypothesis of (L8) for this coalition (docs/G3_MIXED_APS.md 12.2).

The players of the coalition are [2, 4]; `z1` .. `z2` are their quit rates, in that order. Machine-written. -/
theorem Seed202R78Gen011L8B24 :
    ∀ z1 z2 : ℝ,
      0 < z1 →
      0 < z2 →
      0 * z1 + 6 * z2 = 0 →
      z1 + 0 * z2 = 0 →
      False := by
  intro z1 z2 h1 h2 e1 e2
  -- Combining the equations with the coefficients
  --   y = [0, 1]
  -- gives Σ_i (Mᵀy)_i · z_i = 0 with
  --   Mᵀy = [1, 0],
  -- every entry ≥ 0 and at least one > 0, against z > 0. That
  -- combination is rational and linear, so linarith finds one
  -- itself; y is recorded here and in the JSON as the reason the
  -- search cannot fail, not as an input Lean is trusted with.
  linarith

/-- Certificate `v1/simultaneous_quit/seed202_r78_gen011/B124`: coalition {1, 2, 4}: no strictly positive z solves M z = 0, where M is the principal submatrix of the unilateral matrix on players 1, 2, 4 -- its (i,j) entry is the shifted payoff to the i-th of them when the j-th quits alone, so the system says every member of the coalition is indifferent while all of them quit at a positive rate. The conditions below are the linear forms (M^T y)_i with the payoff entries as their coefficients, and the point is the y that makes them non-negative and not all zero: any z > 0 with M z = 0 would then give 0 = <M z, y> = <z, M^T y> > 0. This is the hypothesis of (L8) for this coalition (docs/G3_MIXED_APS.md 12.2).

The players of the coalition are [1, 2, 4]; `z1` .. `z3` are their quit rates, in that order. Machine-written. -/
theorem Seed202R78Gen011L8B124 :
    ∀ z1 z2 z3 : ℝ,
      0 < z1 →
      0 < z2 →
      0 < z3 →
      0 * z1 + 1 / 3 * z2 - 2 / 3 * z3 = 0 →
       - z1 + 0 * z2 + 6 * z3 = 0 →
      5 * z1 + z2 + 0 * z3 = 0 →
      False := by
  intro z1 z2 z3 h1 h2 h3 e1 e2 e3
  -- Combining the equations with the coefficients
  --   y = [45 / 16, 5 / 16, 1 / 16]
  -- gives Σ_i (Mᵀy)_i · z_i = 0 with
  --   Mᵀy = [0, 1, 0],
  -- every entry ≥ 0 and at least one > 0, against z > 0. That
  -- combination is rational and linear, so linarith finds one
  -- itself; y is recorded here and in the JSON as the reason the
  -- search cannot fail, not as an input Lean is trusted with.
  linarith

/-- Certificate `v1/simultaneous_quit/seed202_r78_gen011/B34`: coalition {3, 4}: no strictly positive z solves M z = 0, where M is the principal submatrix of the unilateral matrix on players 3, 4 -- its (i,j) entry is the shifted payoff to the i-th of them when the j-th quits alone, so the system says every member of the coalition is indifferent while all of them quit at a positive rate. The conditions below are the linear forms (M^T y)_i with the payoff entries as their coefficients, and the point is the y that makes them non-negative and not all zero: any z > 0 with M z = 0 would then give 0 = <M z, y> = <z, M^T y> > 0. This is the hypothesis of (L8) for this coalition (docs/G3_MIXED_APS.md 12.2).

The players of the coalition are [3, 4]; `z1` .. `z2` are their quit rates, in that order. Machine-written. -/
theorem Seed202R78Gen011L8B34 :
    ∀ z1 z2 : ℝ,
      0 < z1 →
      0 < z2 →
      0 * z1 + 5 * z2 = 0 →
       - 5 * z1 + 0 * z2 = 0 →
      False := by
  intro z1 z2 h1 h2 e1 e2
  -- Combining the equations with the coefficients
  --   y = [0, -1 / 5]
  -- gives Σ_i (Mᵀy)_i · z_i = 0 with
  --   Mᵀy = [1, 0],
  -- every entry ≥ 0 and at least one > 0, against z > 0. That
  -- combination is rational and linear, so linarith finds one
  -- itself; y is recorded here and in the JSON as the reason the
  -- search cannot fail, not as an input Lean is trusted with.
  linarith

/-- Certificate `v1/simultaneous_quit/seed202_r78_gen011/B134`: coalition {1, 3, 4}: no strictly positive z solves M z = 0, where M is the principal submatrix of the unilateral matrix on players 1, 3, 4 -- its (i,j) entry is the shifted payoff to the i-th of them when the j-th quits alone, so the system says every member of the coalition is indifferent while all of them quit at a positive rate. The conditions below are the linear forms (M^T y)_i with the payoff entries as their coefficients, and the point is the y that makes them non-negative and not all zero: any z > 0 with M z = 0 would then give 0 = <M z, y> = <z, M^T y> > 0. This is the hypothesis of (L8) for this coalition (docs/G3_MIXED_APS.md 12.2).

The players of the coalition are [1, 3, 4]; `z1` .. `z3` are their quit rates, in that order. Machine-written. -/
theorem Seed202R78Gen011L8B134 :
    ∀ z1 z2 z3 : ℝ,
      0 < z1 →
      0 < z2 →
      0 < z3 →
      0 * z1 + 5 * z2 - 2 / 3 * z3 = 0 →
      4 * z1 + 0 * z2 + 5 * z3 = 0 →
      5 * z1 - 5 * z2 + 0 * z3 = 0 →
      False := by
  intro z1 z2 z3 h1 h2 h3 e1 e2 e3
  -- Combining the equations with the coefficients
  --   y = [15 / 83, 2 / 83, -8 / 415]
  -- gives Σ_i (Mᵀy)_i · z_i = 0 with
  --   Mᵀy = [0, 1, 0],
  -- every entry ≥ 0 and at least one > 0, against z > 0. That
  -- combination is rational and linear, so linarith finds one
  -- itself; y is recorded here and in the JSON as the reason the
  -- search cannot fail, not as an input Lean is trusted with.
  linarith

/-- Certificate `v1/simultaneous_quit/seed202_r78_gen011/B234`: coalition {2, 3, 4}: no strictly positive z solves M z = 0, where M is the principal submatrix of the unilateral matrix on players 2, 3, 4 -- its (i,j) entry is the shifted payoff to the i-th of them when the j-th quits alone, so the system says every member of the coalition is indifferent while all of them quit at a positive rate. The conditions below are the linear forms (M^T y)_i with the payoff entries as their coefficients, and the point is the y that makes them non-negative and not all zero: any z > 0 with M z = 0 would then give 0 = <M z, y> = <z, M^T y> > 0. This is the hypothesis of (L8) for this coalition (docs/G3_MIXED_APS.md 12.2).

The players of the coalition are [2, 3, 4]; `z1` .. `z3` are their quit rates, in that order. Machine-written. -/
theorem Seed202R78Gen011L8B234 :
    ∀ z1 z2 z3 : ℝ,
      0 < z1 →
      0 < z2 →
      0 < z3 →
      0 * z1 - z2 + 6 * z3 = 0 →
       - 5 * z1 + 0 * z2 + 5 * z3 = 0 →
      z1 - 5 * z2 + 0 * z3 = 0 →
      False := by
  intro z1 z2 z3 h1 h2 h3 e1 e2 e3
  -- Combining the equations with the coefficients
  --   y = [5 / 29, -1 / 145, -1 / 29]
  -- gives Σ_i (Mᵀy)_i · z_i = 0 with
  --   Mᵀy = [0, 0, 1],
  -- every entry ≥ 0 and at least one > 0, against z > 0. That
  -- combination is rational and linear, so linarith finds one
  -- itself; y is recorded here and in the JSON as the reason the
  -- search cannot fail, not as an input Lean is trusted with.
  linarith

/-- Certificate `v1/simultaneous_quit/seed202_r78_gen011/B1234`: coalition {1, 2, 3, 4}: no strictly positive z solves M z = 0, where M is the principal submatrix of the unilateral matrix on players 1, 2, 3, 4 -- its (i,j) entry is the shifted payoff to the i-th of them when the j-th quits alone, so the system says every member of the coalition is indifferent while all of them quit at a positive rate. The conditions below are the linear forms (M^T y)_i with the payoff entries as their coefficients, and the point is the y that makes them non-negative and not all zero: any z > 0 with M z = 0 would then give 0 = <M z, y> = <z, M^T y> > 0. This is the hypothesis of (L8) for this coalition (docs/G3_MIXED_APS.md 12.2).

The players of the coalition are [1, 2, 3, 4]; `z1` .. `z4` are their quit rates, in that order. Machine-written. -/
theorem Seed202R78Gen011L8B1234 :
    ∀ z1 z2 z3 z4 : ℝ,
      0 < z1 →
      0 < z2 →
      0 < z3 →
      0 < z4 →
      0 * z1 + 1 / 3 * z2 + 5 * z3 - 2 / 3 * z4 = 0 →
       - z1 + 0 * z2 - z3 + 6 * z4 = 0 →
      4 * z1 - 5 * z2 + 0 * z3 + 5 * z4 = 0 →
      5 * z1 + z2 - 5 * z3 + 0 * z4 = 0 →
      False := by
  intro z1 z2 z3 z4 h1 h2 h3 h4 e1 e2 e3 e4
  -- Combining the equations with the coefficients
  --   y = [537 / 2747, 33 / 2747, 32 / 2747, -19 / 2747]
  -- gives Σ_i (Mᵀy)_i · z_i = 0 with
  --   Mᵀy = [0, 0, 1, 0],
  -- every entry ≥ 0 and at least one > 0, against z > 0. That
  -- combination is rational and linear, so linarith finds one
  -- itself; y is recorded here and in the JSON as the reason the
  -- search cannot fail, not as an input Lean is trusted with.
  linarith

/-- Certificate identifiers in this batch. The `#guard` below turns
a silently dropped certificate into a compile error. -/
def batch01Ids : List String :=
  ["v1/simultaneous_quit/seed202_r78_gen011/B12",
   "v1/simultaneous_quit/seed202_r78_gen011/B13",
   "v1/simultaneous_quit/seed202_r78_gen011/B23",
   "v1/simultaneous_quit/seed202_r78_gen011/B123",
   "v1/simultaneous_quit/seed202_r78_gen011/B14",
   "v1/simultaneous_quit/seed202_r78_gen011/B24",
   "v1/simultaneous_quit/seed202_r78_gen011/B124",
   "v1/simultaneous_quit/seed202_r78_gen011/B34",
   "v1/simultaneous_quit/seed202_r78_gen011/B134",
   "v1/simultaneous_quit/seed202_r78_gen011/B234",
   "v1/simultaneous_quit/seed202_r78_gen011/B1234"]

#guard batch01Ids.length = 11

end Quitting.SimultaneousQuit
