-- GENERATED by code/julia/scripts/certificates/lean_emit.jl (via any certificate exporter) — do not edit.
-- Regenerate and `git diff --exit-code` to prove the Lean corpus is a
-- pure function of the JSON certificates.

-- Imports shared by every generated certificate batch. Options are
-- NOT set here: `set_option` does not cross module boundaries, so each
-- batch file carries its own.
import Mathlib.Tactic.LinearCombination
import Mathlib.Tactic.Linarith
import Mathlib.Data.Real.Basic
