-- GENERATED by code/julia/scripts/certificates/v0_from_recorded.jl — do not edit.
-- Regenerate and `git diff --exit-code` to prove the Lean corpus is a
-- pure function of the JSON certificates.

import Formal.Certificates.Prelude

set_option maxRecDepth 8000
set_option maxHeartbeats 1000000

namespace Quitting.V0


/-- Condition `quitdev_1` of `seed202_r78_gen011_face_1`, with the sense the trace reads it in. The
certificate refutes the system in which all of them hold at once. -/
def seed202_r78_gen011_face_1_f01 (x1 x2 x3 x4 : ℝ) : Prop :=
  -5642885 / 1048576 + 313 / 51 * x4 - 45 / 17 * x3 + 7819 / 1632 * x3 * x4 + 5 / 3 * x2 - 1145 / 663 * x2 * x4 + 1001 / 102 * x2 * x3 - 1253221 / 109616 * x2 * x3 * x4 + 5 * x1 - 313 / 51 * x1 * x4 + 45 / 17 * x1 * x3 - 7819 / 1632 * x1 * x3 * x4 - 5 / 3 * x1 * x2 + 1145 / 663 * x1 * x2 * x4 - 1001 / 102 * x1 * x2 * x3 + 1253221 / 109616 * x1 * x2 * x3 * x4 ≤ 0

/-- Condition `contdev_1` of `seed202_r78_gen011_face_1`, with the sense the trace reads it in. The
certificate refutes the system in which all of them hold at once. -/
def seed202_r78_gen011_face_1_f02 (x1 x2 x3 x4 : ℝ) : Prop :=
  -400005 / 1048576 - 74681 / 65536 * x1 + 7643 / 3342336 * x1 * x4 + 9789257 / 1114112 * x1 * x3 - 36533723 / 3342336 * x1 * x3 * x4 + 879403 / 196608 * x1 * x2 - 191726623 / 43450368 * x1 * x2 * x4 - 53321179 / 3342336 * x1 * x2 * x3 + 7889768427 / 448987136 * x1 * x2 * x3 * x4 ≤ 0

/-- Condition `quitdev_2` of `seed202_r78_gen011_face_1`, with the sense the trace reads it in. The
certificate refutes the system in which all of them hold at once. -/
def seed202_r78_gen011_face_1_f03 (x1 x2 x3 x4 : ℝ) : Prop :=
  -6691461 / 1048576 - 17 / 29 * x4 + 120 / 19 * x3 - 4720 / 4959 * x3 * x4 + 6 * x2 + 17 / 29 * x2 * x4 - 120 / 19 * x2 * x3 + 4720 / 4959 * x2 * x3 * x4 + 159 / 22 * x1 + 1880 / 4147 * x1 * x4 - 30631 / 2717 * x1 * x3 + 2609207 / 1527372 * x1 * x3 * x4 - 159 / 22 * x1 * x2 - 1880 / 4147 * x1 * x2 * x4 + 30631 / 2717 * x1 * x2 * x3 - 2609207 / 1527372 * x1 * x2 * x3 * x4 ≤ 0

/-- Condition `contdev_2` of `seed202_r78_gen011_face_1`, with the sense the trace reads it in. The
certificate refutes the system in which all of them hold at once. -/
def seed202_r78_gen011_face_1_f04 (x1 x2 x3 x4 : ℝ) : Prop :=
  -400005 / 1048576 - 2654795 / 3145728 * x2 + 677823103 / 91226112 * x2 * x4 + 31566737 / 59768832 * x2 * x3 - 30638427719 / 5199888384 * x2 * x3 * x4 - 13264583 / 34603008 * x1 * x2 - 95195407601 / 13045334016 * x1 * x2 * x4 + 37862058497 / 8546942976 * x1 * x2 * x3 + 2056265435995 / 400391405568 * x1 * x2 * x3 * x4 ≤ 0

/-- Condition `quitdev_3` of `seed202_r78_gen011_face_1`, with the sense the trace reads it in. The
certificate refutes the system in which all of them hold at once. -/
def seed202_r78_gen011_face_1_f05 (x1 x2 x3 x4 : ℝ) : Prop :=
  -5642885 / 1048576 - 19 / 12 * x4 + 5 * x3 + 19 / 12 * x3 * x4 + 193 / 19 * x2 - 8743 / 1824 * x2 * x4 - 193 / 19 * x2 * x3 + 8743 / 1824 * x2 * x3 * x4 - 15 / 31 * x1 + 21131 / 2604 * x1 * x4 + 15 / 31 * x1 * x3 - 21131 / 2604 * x1 * x3 * x4 - 397 / 589 * x1 * x2 - 15017463 / 3826144 * x1 * x2 * x4 + 397 / 589 * x1 * x2 * x3 + 15017463 / 3826144 * x1 * x2 * x3 * x4 ≤ 0

/-- Condition `contdev_3` of `seed202_r78_gen011_face_1`, with the sense the trace reads it in. The
certificate refutes the system in which all of them hold at once. -/
def seed202_r78_gen011_face_1_f06 (x1 x2 x3 x4 : ℝ) : Prop :=
  -400005 / 1048576 - 628215 / 262144 * x3 + 7061989 / 786432 * x3 * x4 - 13754027 / 4980736 * x2 * x3 - 38896639 / 14942208 * x2 * x3 * x4 + 64039145 / 8126464 * x1 * x3 - 2647087901 / 170655744 * x1 * x3 * x4 - 1037961547 / 154402816 * x1 * x2 * x3 + 354855698041 / 31343771648 * x1 * x2 * x3 * x4 ≤ 0

/-- Condition `quitdev_4` of `seed202_r78_gen011_face_1`, with the sense the trace reads it in. The
certificate refutes the system in which all of them hold at once. -/
def seed202_r78_gen011_face_1_f07 (x1 x2 x3 x4 : ℝ) : Prop :=
  -5642885 / 1048576 + 5 * x4 + 185 / 19 * x3 - 185 / 19 * x3 * x4 + 44 / 9 * x2 - 44 / 9 * x2 * x4 - 450787 / 42408 * x2 * x3 + 450787 / 42408 * x2 * x3 * x4 + 11 / 12 * x1 - 11 / 12 * x1 * x4 - 38299 / 5244 * x1 * x3 + 38299 / 5244 * x1 * x3 * x4 - 1423 / 1800 * x1 * x2 + 1423 / 1800 * x1 * x2 * x4 + 1085860103 / 134115300 * x1 * x2 * x3 - 1085860103 / 134115300 * x1 * x2 * x3 * x4 ≤ 0

/-- Condition `contdev_4` of `seed202_r78_gen011_face_1`, with the sense the trace reads it in. The
certificate refutes the system in which all of them hold at once. -/
def seed202_r78_gen011_face_1_f08 (x1 x2 x3 x4 : ℝ) : Prop :=
  -400005 / 1048576 - 472569 / 262144 * x4 - 14614149 / 4980736 * x3 * x4 + 4515265 / 2359296 * x2 * x4 + 5318173427 / 1389625344 * x2 * x3 * x4 + 4628971 / 786432 * x1 * x4 + 172071385 / 343670784 * x1 * x3 * x4 - 354611161 / 58982400 * x1 * x2 * x4 - 11371342904783 / 8789380300800 * x1 * x2 * x3 * x4 ≤ 0

end Quitting.V0
