-- GENERATED by code/julia/scripts/certificates/v0_from_recorded.jl — do not edit.
-- Regenerate and `git diff --exit-code` to prove the Lean corpus is a
-- pure function of the JSON certificates.

import Formal.Certificates.Prelude
import Formal.Certificates.V0.Seed202R78Gen011Face1.Defs
import Formal.Certificates.V0.Seed202R78Gen011Face1.Part01
import Formal.Certificates.V0.Seed202R78Gen011Face1.Part02
import Formal.Certificates.V0.Seed202R78Gen011Face1.Part03
import Formal.Certificates.V0.Seed202R78Gen011Face1.Part04
import Formal.Certificates.V0.Seed202R78Gen011Face1.Part05
import Formal.Certificates.V0.Seed202R78Gen011Face1.Part06

set_option maxRecDepth 8000
set_option maxHeartbeats 1000000

namespace Quitting.V0


/-- on the face {x1 = 1} of the stage-1 profile cube no point leaves all 2N stage-1 deviation gains at most eps = 400005/1048576; the unknown continuation values are replaced by the certified min-max lower bounds (continue-deviations) and by max(0, max_S r^S_k) (quit-deviations), both of which only lower the gains. Termination with probability one at stage 1 forces some x_i = 1, so the four faces are the whole case enumeration.

Proved by the recorded subdivision of the box: every leaf carries one
condition that the Bernstein corner-basis expansion makes strictly
positive there. Machine-written. -/
theorem seed202_r78_gen011_face_1
    (x1 x2 x3 x4 : ℝ)
    (hlo1 : (1 : ℝ) ≤ x1)
    (hhi1 : x1 ≤ (1 : ℝ))
    (hlo2 : (0 : ℝ) ≤ x2)
    (hhi2 : x2 ≤ (1 : ℝ))
    (hlo3 : (0 : ℝ) ≤ x3)
    (hhi3 : x3 ≤ (1 : ℝ))
    (hlo4 : (0 : ℝ) ≤ x4)
    (hhi4 : x4 ≤ (1 : ℝ))
    : ¬ (
      seed202_r78_gen011_face_1_f01 x1 x2 x3 x4 ∧
      seed202_r78_gen011_face_1_f02 x1 x2 x3 x4 ∧
      seed202_r78_gen011_face_1_f03 x1 x2 x3 x4 ∧
      seed202_r78_gen011_face_1_f04 x1 x2 x3 x4 ∧
      seed202_r78_gen011_face_1_f05 x1 x2 x3 x4 ∧
      seed202_r78_gen011_face_1_f06 x1 x2 x3 x4 ∧
      seed202_r78_gen011_face_1_f07 x1 x2 x3 x4 ∧
      seed202_r78_gen011_face_1_f08 x1 x2 x3 x4) := by
  rintro ⟨_, c2, c3, c4, c5, c6, _, c8⟩
  obtain rfl : x1 = (1 : ℝ) := le_antisymm hhi1 hlo1
  rcases le_total x2 (1 / 2 : ℝ) with hs1 | hs1
  · rcases le_total x3 (1 / 2 : ℝ) with hs2 | hs2
    · rcases le_total x4 (1 / 2 : ℝ) with hs3 | hs3
      · rcases le_total x2 (1 / 4 : ℝ) with hs4 | hs4
        · rcases le_total x3 (1 / 4 : ℝ) with hs5 | hs5
          · rcases le_total x4 (1 / 4 : ℝ) with hs6 | hs6
            · rcases le_total x2 (1 / 8 : ℝ) with hs7 | hs7
              · exact seed202_r78_gen011_face_1_sub001 x2 x3 x4 hlo2 hs7 hlo3 hs5 hlo4 hs6 c3 c6 c8
              · rcases le_total x3 (1 / 8 : ℝ) with hs8 | hs8
                · exact seed202_r78_gen011_face_1_sub002 x2 x3 x4 hs7 hs4 hlo3 hs8 hlo4 hs6 c3
                · rcases le_total x4 (1 / 8 : ℝ) with hs9 | hs9
                  · exact seed202_r78_gen011_face_1_sub003 x2 x3 x4 hs7 hs4 hs8 hs5 hlo4 hs9 c2 c3 c6
                  · rcases le_total x2 (3 / 16 : ℝ) with hs10 | hs10
                    · exact seed202_r78_gen011_face_1_sub004 x2 x3 x4 hs7 hs10 hs8 hs5 hs9 hs6 c3 c6 c8
                    · rcases le_total x3 (3 / 16 : ℝ) with hs11 | hs11
                      · rcases le_total x4 (3 / 16 : ℝ) with hs12 | hs12
                        · rcases le_total x2 (7 / 32 : ℝ) with hs13 | hs13
                          · exact seed202_r78_gen011_face_1_sub005 x2 x3 x4 hs10 hs13 hs8 hs11 hs9 hs12 c3 c6 c8
                          · rcases le_total x3 (5 / 32 : ℝ) with hs14 | hs14
                            · rcases le_total x4 (5 / 32 : ℝ) with hs15 | hs15
                              · rcases le_total x2 (15 / 64 : ℝ) with hs16 | hs16
                                · exact seed202_r78_gen011_face_1_sub006 x2 x3 x4 hs13 hs16 hs8 hs14 hs9 hs15 c3 c6 c8
                                · rcases le_total x3 (9 / 64 : ℝ) with hs17 | hs17
                                  · exact seed202_r78_gen011_face_1_sub007 x2 x3 x4 hs16 hs4 hs8 hs17 hs9 hs15 c3
                                  · rcases le_total x4 (9 / 64 : ℝ) with hs18 | hs18
                                    · rcases le_total x2 (31 / 128 : ℝ) with hs19 | hs19
                                      · rcases le_total x3 (19 / 128 : ℝ) with hs20 | hs20
                                        · rcases le_total x4 (17 / 128 : ℝ) with hs21 | hs21
                                          · exact seed202_r78_gen011_face_1_sub008 x2 x3 x4 hs16 hs19 hs17 hs20 hs9 hs21 c2 c3 c6
                                          · rcases le_total x2 (61 / 256 : ℝ) with hs22 | hs22
                                            · exact seed202_r78_gen011_face_1_sub009 x2 x3 x4 hs16 hs22 hs17 hs20 hs21 hs18 c3 c6 c8
                                            · rcases le_total x3 (37 / 256 : ℝ) with hs23 | hs23
                                              · exact seed202_r78_gen011_face_1_sub010 x2 x3 x4 hs22 hs19 hs17 hs23 hs21 hs18 c3
                                              · rcases le_total x4 (35 / 256 : ℝ) with hs24 | hs24
                                                · rcases le_total x2 (123 / 512 : ℝ) with hs25 | hs25
                                                  · rcases le_total x3 (75 / 512 : ℝ) with hs26 | hs26
                                                    · rcases le_total x4 (69 / 512 : ℝ) with hs27 | hs27
                                                      · rcases le_total x2 (245 / 1024 : ℝ) with hs28 | hs28
                                                        · rcases le_total x3 (149 / 1024 : ℝ) with hs29 | hs29
                                                          · exact seed202_r78_gen011_face_1_sub011 x2 x3 x4 hs22 hs28 hs23 hs29 hs21 hs27 c3
                                                          · rcases le_total x4 (137 / 1024 : ℝ) with hs30 | hs30
                                                            · exact seed202_r78_gen011_face_1_sub012 x2 x3 x4 hs22 hs28 hs29 hs26 hs21 hs30 c2 c3 c6
                                                            · exact seed202_r78_gen011_face_1_sub013 x2 x3 x4 hs22 hs28 hs29 hs26 hs30 hs27 c2 c3 c6 c8
                                                        · rcases le_total x3 (149 / 1024 : ℝ) with hs29 | hs29
                                                          · exact seed202_r78_gen011_face_1_sub014 x2 x3 x4 hs28 hs25 hs23 hs29 hs21 hs27 c3
                                                          · rcases le_total x4 (137 / 1024 : ℝ) with hs30 | hs30
                                                            · exact seed202_r78_gen011_face_1_sub015 x2 x3 x4 hs28 hs25 hs29 hs26 hs21 hs30 c2
                                                            · rcases le_total x2 (491 / 2048 : ℝ) with hs31 | hs31
                                                              · rcases le_total x3 (299 / 2048 : ℝ) with hs32 | hs32
                                                                · rcases le_total x4 (275 / 2048 : ℝ) with hs33 | hs33
                                                                  · exact seed202_r78_gen011_face_1_sub016 x2 x3 x4 hs28 hs31 hs29 hs32 hs30 hs33 c2 c3
                                                                  · rcases le_total x2 (981 / 4096 : ℝ) with hs34 | hs34
                                                                    · rcases le_total x3 (597 / 4096 : ℝ) with hs35 | hs35
                                                                      · exact seed202_r78_gen011_face_1_sub017 x2 x3 x4 hs28 hs34 hs29 hs35 hs33 hs27 c2 c3 c8
                                                                      · exact seed202_r78_gen011_face_1_sub018 x2 x3 x4 hs28 hs34 hs35 hs32 hs33 hs27 c2 c3 c8
                                                                    · exact seed202_r78_gen011_face_1_sub019 x2 x3 x4 hs34 hs31 hs29 hs32 hs33 hs27 c2 c3 c8
                                                                · exact seed202_r78_gen011_face_1_sub020 x2 x3 x4 hs28 hs31 hs32 hs26 hs30 hs27 c2
                                                              · exact seed202_r78_gen011_face_1_sub021 x2 x3 x4 hs31 hs25 hs29 hs26 hs30 hs27 c2 c3 c8
                                                      · exact seed202_r78_gen011_face_1_sub022 x2 x3 x4 hs22 hs25 hs23 hs26 hs27 hs24 c8
                                                    · exact seed202_r78_gen011_face_1_sub023 x2 x3 x4 hs22 hs25 hs26 hs20 hs21 hs24 c2 c6 c8
                                                  · exact seed202_r78_gen011_face_1_sub024 x2 x3 x4 hs25 hs19 hs23 hs20 hs21 hs24 c2 c3 c8
                                                · exact seed202_r78_gen011_face_1_sub025 x2 x3 x4 hs22 hs19 hs23 hs20 hs24 hs18 c8
                                        · exact seed202_r78_gen011_face_1_sub026 x2 x3 x4 hs16 hs19 hs20 hs14 hs9 hs18 c2 c6 c8
                                      · exact seed202_r78_gen011_face_1_sub027 x2 x3 x4 hs19 hs4 hs17 hs14 hs9 hs18 c2 c3 c8
                                    · exact seed202_r78_gen011_face_1_sub028 x2 x3 x4 hs16 hs4 hs17 hs14 hs18 hs15 c8
                              · exact seed202_r78_gen011_face_1_sub029 x2 x3 x4 hs13 hs4 hs8 hs14 hs15 hs12 c8
                            · exact seed202_r78_gen011_face_1_sub030 x2 x3 x4 hs13 hs4 hs14 hs11 hs9 hs12 c2 c6 c8
                        · exact seed202_r78_gen011_face_1_sub031 x2 x3 x4 hs10 hs4 hs8 hs11 hs12 hs6 c8
                      · exact seed202_r78_gen011_face_1_sub032 x2 x3 x4 hs10 hs4 hs11 hs5 hs9 hs6 c6 c8
            · exact seed202_r78_gen011_face_1_sub033 x2 x3 x4 hlo2 hs4 hlo3 hs5 hs6 hs3 c8
          · exact seed202_r78_gen011_face_1_sub034 x2 x3 x4 hlo2 hs4 hs5 hs2 hlo4 hs3 c6 c8
        · rcases le_total x3 (1 / 4 : ℝ) with hs5 | hs5
          · rcases le_total x4 (1 / 4 : ℝ) with hs6 | hs6
            · rcases le_total x2 (3 / 8 : ℝ) with hs7 | hs7
              · rcases le_total x3 (1 / 8 : ℝ) with hs8 | hs8
                · exact seed202_r78_gen011_face_1_sub035 x2 x3 x4 hs4 hs7 hlo3 hs8 hlo4 hs6 c2 c3 c8
                · rcases le_total x4 (1 / 8 : ℝ) with hs9 | hs9
                  · exact seed202_r78_gen011_face_1_sub036 x2 x3 x4 hs4 hs7 hs8 hs5 hlo4 hs9 c2 c3
                  · rcases le_total x2 (5 / 16 : ℝ) with hs10 | hs10
                    · rcases le_total x3 (3 / 16 : ℝ) with hs11 | hs11
                      · rcases le_total x4 (3 / 16 : ℝ) with hs12 | hs12
                        · rcases le_total x2 (9 / 32 : ℝ) with hs13 | hs13
                          · exact seed202_r78_gen011_face_1_sub037 x2 x3 x4 hs4 hs13 hs8 hs11 hs9 hs12 c2 c3 c8
                          · exact seed202_r78_gen011_face_1_sub038 x2 x3 x4 hs13 hs10 hs8 hs11 hs9 hs12 c2 c3 c8
                        · exact seed202_r78_gen011_face_1_sub039 x2 x3 x4 hs4 hs10 hs8 hs11 hs12 hs6 c8
                      · exact seed202_r78_gen011_face_1_sub040 x2 x3 x4 hs4 hs10 hs11 hs5 hs9 hs6 c2 c8
                    · exact seed202_r78_gen011_face_1_sub041 x2 x3 x4 hs10 hs7 hs8 hs5 hs9 hs6 c2 c8
              · exact seed202_r78_gen011_face_1_sub042 x2 x3 x4 hs7 hs1 hlo3 hs5 hlo4 hs6 c2 c3 c8
            · exact seed202_r78_gen011_face_1_sub043 x2 x3 x4 hs4 hs1 hlo3 hs5 hs6 hs3 c8
          · exact seed202_r78_gen011_face_1_sub044 x2 x3 x4 hs4 hs1 hs5 hs2 hlo4 hs3 c2 c8
      · exact seed202_r78_gen011_face_1_sub045 x2 x3 x4 hlo2 hs1 hlo3 hs2 hs3 hhi4 c8
    · exact seed202_r78_gen011_face_1_sub046 x2 x3 x4 hlo2 hs1 hs2 hhi3 hlo4 hhi4 c2 c4 c6 c8
  · rcases le_total x3 (1 / 2 : ℝ) with hs2 | hs2
    · rcases le_total x4 (1 / 2 : ℝ) with hs3 | hs3
      · rcases le_total x2 (3 / 4 : ℝ) with hs4 | hs4
        · rcases le_total x3 (1 / 4 : ℝ) with hs5 | hs5
          · exact seed202_r78_gen011_face_1_sub047 x2 x3 x4 hs1 hs4 hlo3 hs5 hlo4 hs3 c2 c5 c8
          · rcases le_total x4 (1 / 4 : ℝ) with hs6 | hs6
            · exact seed202_r78_gen011_face_1_sub048 x2 x3 x4 hs1 hs4 hs5 hs2 hlo4 hs6 c2 c4
            · rcases le_total x2 (5 / 8 : ℝ) with hs7 | hs7
              · rcases le_total x3 (3 / 8 : ℝ) with hs8 | hs8
                · exact seed202_r78_gen011_face_1_sub049 x2 x3 x4 hs1 hs7 hs5 hs8 hs6 hs3 c2 c5 c8
                · exact seed202_r78_gen011_face_1_sub050 x2 x3 x4 hs1 hs7 hs8 hs2 hs6 hs3 c2 c4 c5 c8
              · exact seed202_r78_gen011_face_1_sub051 x2 x3 x4 hs7 hs4 hs5 hs2 hs6 hs3 c4 c5
        · exact seed202_r78_gen011_face_1_sub052 x2 x3 x4 hs4 hhi2 hlo3 hs2 hlo4 hs3 c5
      · exact seed202_r78_gen011_face_1_sub053 x2 x3 x4 hs1 hhi2 hlo3 hs2 hs3 hhi4 c5 c8
    · exact seed202_r78_gen011_face_1_sub054 x2 x3 x4 hs1 hhi2 hs2 hhi3 hlo4 hhi4 c4


/-- Certificate identifier proved in this module. The `#guard`
below turns a silently dropped certificate into a compile error. -/
def Seed202R78Gen011Face1Ids : List String :=
  ["v1/v0/seed202_r78_gen011/face_1"]

#guard Seed202R78Gen011Face1Ids.length = 1

end Quitting.V0
