-- GENERATED by code/julia/scripts/certificates/v0_from_recorded.jl — do not edit.
-- Regenerate and `git diff --exit-code` to prove the Lean corpus is a
-- pure function of the JSON certificates.

import Formal.Certificates.Prelude
import Formal.Certificates.V0.Seed202R78Gen011Face1.Defs

set_option maxRecDepth 8000
set_option maxHeartbeats 1000000

namespace Quitting.V0

theorem seed202_r78_gen011_face_1_sub051
    (x2 x3 x4 : ℝ)
    (hlo2 : (5 / 8 : ℝ) ≤ x2)
    (hhi2 : x2 ≤ (3 / 4 : ℝ))
    (hlo3 : (1 / 4 : ℝ) ≤ x3)
    (hhi3 : x3 ≤ (1 / 2 : ℝ))
    (hlo4 : (1 / 4 : ℝ) ≤ x4)
    (hhi4 : x4 ≤ (1 / 2 : ℝ))
    (c4 : seed202_r78_gen011_face_1_f04 (1 : ℝ) x2 x3 x4)
    (c5 : seed202_r78_gen011_face_1_f05 (1 : ℝ) x2 x3 x4)
    : False := by
  simp only [seed202_r78_gen011_face_1_f04, seed202_r78_gen011_face_1_f05] at c4 c5
  rcases le_total x3 (3 / 8 : ℝ) with hs1 | hs1
  · -- `quitdev_3` ≥ 1284662725 / 19796066304 > 0 on x2 ∈ [5 / 8, 3 / 4], x3 ∈ [1 / 4, 3 / 8], x4 ∈ [1 / 4, 1 / 2]
    have d2lo : (0:ℝ) ≤ x2 - 5 / 8 := sub_nonneg.mpr hlo2
    have d2hi : (0:ℝ) ≤ 3 / 4 - x2 := sub_nonneg.mpr hhi2
    have d3lo : (0:ℝ) ≤ x3 - 1 / 4 := sub_nonneg.mpr hlo3
    have d3hi : (0:ℝ) ≤ 3 / 8 - x3 := sub_nonneg.mpr hs1
    have d4lo : (0:ℝ) ≤ x4 - 1 / 4 := sub_nonneg.mpr hlo4
    have d4hi : (0:ℝ) ≤ 1 / 2 - x4 := sub_nonneg.mpr hhi4
    linarith only [c5, mul_nonneg (mul_nonneg (d2hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d2lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d2hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d2lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d2hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d2lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d2hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d2lo) d3lo) d4lo]
  · rcases le_total x4 (3 / 8 : ℝ) with hs2 | hs2
    · rcases le_total x2 (11 / 16 : ℝ) with hs3 | hs3
      · rcases le_total x3 (7 / 16 : ℝ) with hs4 | hs4
        · -- `quitdev_3` ≥ 133675671 / 6598688768 > 0 on x2 ∈ [5 / 8, 11 / 16], x3 ∈ [3 / 8, 7 / 16], x4 ∈ [1 / 4, 3 / 8]
          have d2lo : (0:ℝ) ≤ x2 - 5 / 8 := sub_nonneg.mpr hlo2
          have d2hi : (0:ℝ) ≤ 11 / 16 - x2 := sub_nonneg.mpr hs3
          have d3lo : (0:ℝ) ≤ x3 - 3 / 8 := sub_nonneg.mpr hs1
          have d3hi : (0:ℝ) ≤ 7 / 16 - x3 := sub_nonneg.mpr hs4
          have d4lo : (0:ℝ) ≤ x4 - 1 / 4 := sub_nonneg.mpr hlo4
          have d4hi : (0:ℝ) ≤ 3 / 8 - x4 := sub_nonneg.mpr hs2
          linarith only [c5, mul_nonneg (mul_nonneg (d2hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d2lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d2hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d2lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d2hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d2lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d2hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d2lo) d3lo) d4lo]
        · -- `contdev_2` ≥ 24106165 / 149946368 > 0 on x2 ∈ [5 / 8, 11 / 16], x3 ∈ [7 / 16, 1 / 2], x4 ∈ [1 / 4, 3 / 8]
          have d2lo : (0:ℝ) ≤ x2 - 5 / 8 := sub_nonneg.mpr hlo2
          have d2hi : (0:ℝ) ≤ 11 / 16 - x2 := sub_nonneg.mpr hs3
          have d3lo : (0:ℝ) ≤ x3 - 7 / 16 := sub_nonneg.mpr hs4
          have d3hi : (0:ℝ) ≤ 1 / 2 - x3 := sub_nonneg.mpr hhi3
          have d4lo : (0:ℝ) ≤ x4 - 1 / 4 := sub_nonneg.mpr hlo4
          have d4hi : (0:ℝ) ≤ 3 / 8 - x4 := sub_nonneg.mpr hs2
          linarith only [c4, mul_nonneg (mul_nonneg (d2hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d2lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d2hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d2lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d2hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d2lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d2hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d2lo) d3lo) d4lo]
      · -- `contdev_2` ≥ 103773 / 7340032 > 0 on x2 ∈ [11 / 16, 3 / 4], x3 ∈ [3 / 8, 1 / 2], x4 ∈ [1 / 4, 3 / 8]
        have d2lo : (0:ℝ) ≤ x2 - 11 / 16 := sub_nonneg.mpr hs3
        have d2hi : (0:ℝ) ≤ 3 / 4 - x2 := sub_nonneg.mpr hhi2
        have d3lo : (0:ℝ) ≤ x3 - 3 / 8 := sub_nonneg.mpr hs1
        have d3hi : (0:ℝ) ≤ 1 / 2 - x3 := sub_nonneg.mpr hhi3
        have d4lo : (0:ℝ) ≤ x4 - 1 / 4 := sub_nonneg.mpr hlo4
        have d4hi : (0:ℝ) ≤ 3 / 8 - x4 := sub_nonneg.mpr hs2
        linarith only [c4, mul_nonneg (mul_nonneg (d2hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d2lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d2hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d2lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d2hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d2lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d2hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d2lo) d3lo) d4lo]
    · -- `quitdev_3` ≥ 285601943 / 6598688768 > 0 on x2 ∈ [5 / 8, 3 / 4], x3 ∈ [3 / 8, 1 / 2], x4 ∈ [3 / 8, 1 / 2]
      have d2lo : (0:ℝ) ≤ x2 - 5 / 8 := sub_nonneg.mpr hlo2
      have d2hi : (0:ℝ) ≤ 3 / 4 - x2 := sub_nonneg.mpr hhi2
      have d3lo : (0:ℝ) ≤ x3 - 3 / 8 := sub_nonneg.mpr hs1
      have d3hi : (0:ℝ) ≤ 1 / 2 - x3 := sub_nonneg.mpr hhi3
      have d4lo : (0:ℝ) ≤ x4 - 3 / 8 := sub_nonneg.mpr hs2
      have d4hi : (0:ℝ) ≤ 1 / 2 - x4 := sub_nonneg.mpr hhi4
      linarith only [c5, mul_nonneg (mul_nonneg (d2hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d2lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d2hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d2lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d2hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d2lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d2hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d2lo) d3lo) d4lo]

theorem seed202_r78_gen011_face_1_sub052
    (x2 x3 x4 : ℝ)
    (hlo2 : (3 / 4 : ℝ) ≤ x2)
    (hhi2 : x2 ≤ (1 : ℝ))
    (hlo3 : (0 : ℝ) ≤ x3)
    (hhi3 : x3 ≤ (1 / 2 : ℝ))
    (hlo4 : (0 : ℝ) ≤ x4)
    (hhi4 : x4 ≤ (1 / 2 : ℝ))
    (c5 : seed202_r78_gen011_face_1_f05 (1 : ℝ) x2 x3 x4)
    : False := by
  simp only [seed202_r78_gen011_face_1_f05] at c5
  -- `quitdev_3` ≥ 8536820165 / 19796066304 > 0 on x2 ∈ [3 / 4, 1], x3 ∈ [0, 1 / 2], x4 ∈ [0, 1 / 2]
  have d2lo : (0:ℝ) ≤ x2 - 3 / 4 := sub_nonneg.mpr hlo2
  have d2hi : (0:ℝ) ≤ 1 - x2 := sub_nonneg.mpr hhi2
  have d3lo : (0:ℝ) ≤ x3 - 0 := sub_nonneg.mpr hlo3
  have d3hi : (0:ℝ) ≤ 1 / 2 - x3 := sub_nonneg.mpr hhi3
  have d4lo : (0:ℝ) ≤ x4 - 0 := sub_nonneg.mpr hlo4
  have d4hi : (0:ℝ) ≤ 1 / 2 - x4 := sub_nonneg.mpr hhi4
  linarith only [c5, mul_nonneg (mul_nonneg (d2hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d2lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d2hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d2lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d2hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d2lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d2hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d2lo) d3lo) d4lo]

theorem seed202_r78_gen011_face_1_sub053
    (x2 x3 x4 : ℝ)
    (hlo2 : (1 / 2 : ℝ) ≤ x2)
    (hhi2 : x2 ≤ (1 : ℝ))
    (hlo3 : (0 : ℝ) ≤ x3)
    (hhi3 : x3 ≤ (1 / 2 : ℝ))
    (hlo4 : (1 / 2 : ℝ) ≤ x4)
    (hhi4 : x4 ≤ (1 : ℝ))
    (c5 : seed202_r78_gen011_face_1_f05 (1 : ℝ) x2 x3 x4)
    (c8 : seed202_r78_gen011_face_1_f08 (1 : ℝ) x2 x3 x4)
    : False := by
  simp only [seed202_r78_gen011_face_1_f05, seed202_r78_gen011_face_1_f08] at c5 c8
  rcases le_total x2 (3 / 4 : ℝ) with hs1 | hs1
  · rcases le_total x3 (1 / 4 : ℝ) with hs2 | hs2
    · -- `contdev_4` ≥ 7136438101 / 126012620800 > 0 on x2 ∈ [1 / 2, 3 / 4], x3 ∈ [0, 1 / 4], x4 ∈ [1 / 2, 1]
      have d2lo : (0:ℝ) ≤ x2 - 1 / 2 := sub_nonneg.mpr hlo2
      have d2hi : (0:ℝ) ≤ 3 / 4 - x2 := sub_nonneg.mpr hs1
      have d3lo : (0:ℝ) ≤ x3 - 0 := sub_nonneg.mpr hlo3
      have d3hi : (0:ℝ) ≤ 1 / 4 - x3 := sub_nonneg.mpr hs2
      have d4lo : (0:ℝ) ≤ x4 - 1 / 2 := sub_nonneg.mpr hlo4
      have d4hi : (0:ℝ) ≤ 1 - x4 := sub_nonneg.mpr hhi4
      linarith only [c8, mul_nonneg (mul_nonneg (d2hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d2lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d2hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d2lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d2hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d2lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d2hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d2lo) d3lo) d4lo]
    · rcases le_total x4 (3 / 4 : ℝ) with hs3 | hs3
      · rcases le_total x2 (5 / 8 : ℝ) with hs4 | hs4
        · -- `contdev_4` ≥ 12621066547 / 75607572480 > 0 on x2 ∈ [1 / 2, 5 / 8], x3 ∈ [1 / 4, 1 / 2], x4 ∈ [1 / 2, 3 / 4]
          have d2lo : (0:ℝ) ≤ x2 - 1 / 2 := sub_nonneg.mpr hlo2
          have d2hi : (0:ℝ) ≤ 5 / 8 - x2 := sub_nonneg.mpr hs4
          have d3lo : (0:ℝ) ≤ x3 - 1 / 4 := sub_nonneg.mpr hs2
          have d3hi : (0:ℝ) ≤ 1 / 2 - x3 := sub_nonneg.mpr hhi3
          have d4lo : (0:ℝ) ≤ x4 - 1 / 2 := sub_nonneg.mpr hlo4
          have d4hi : (0:ℝ) ≤ 3 / 4 - x4 := sub_nonneg.mpr hs3
          linarith only [c8, mul_nonneg (mul_nonneg (d2hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d2lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d2hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d2lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d2hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d2lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d2hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d2lo) d3lo) d4lo]
        · -- `quitdev_3` ≥ 2196220357 / 19796066304 > 0 on x2 ∈ [5 / 8, 3 / 4], x3 ∈ [1 / 4, 1 / 2], x4 ∈ [1 / 2, 3 / 4]
          have d2lo : (0:ℝ) ≤ x2 - 5 / 8 := sub_nonneg.mpr hs4
          have d2hi : (0:ℝ) ≤ 3 / 4 - x2 := sub_nonneg.mpr hs1
          have d3lo : (0:ℝ) ≤ x3 - 1 / 4 := sub_nonneg.mpr hs2
          have d3hi : (0:ℝ) ≤ 1 / 2 - x3 := sub_nonneg.mpr hhi3
          have d4lo : (0:ℝ) ≤ x4 - 1 / 2 := sub_nonneg.mpr hlo4
          have d4hi : (0:ℝ) ≤ 3 / 4 - x4 := sub_nonneg.mpr hs3
          linarith only [c5, mul_nonneg (mul_nonneg (d2hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d2lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d2hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d2lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d2hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d2lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d2hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d2lo) d3lo) d4lo]
      · -- `quitdev_3` ≥ 410376343 / 6598688768 > 0 on x2 ∈ [1 / 2, 3 / 4], x3 ∈ [1 / 4, 1 / 2], x4 ∈ [3 / 4, 1]
        have d2lo : (0:ℝ) ≤ x2 - 1 / 2 := sub_nonneg.mpr hlo2
        have d2hi : (0:ℝ) ≤ 3 / 4 - x2 := sub_nonneg.mpr hs1
        have d3lo : (0:ℝ) ≤ x3 - 1 / 4 := sub_nonneg.mpr hs2
        have d3hi : (0:ℝ) ≤ 1 / 2 - x3 := sub_nonneg.mpr hhi3
        have d4lo : (0:ℝ) ≤ x4 - 3 / 4 := sub_nonneg.mpr hs3
        have d4hi : (0:ℝ) ≤ 1 - x4 := sub_nonneg.mpr hhi4
        linarith only [c5, mul_nonneg (mul_nonneg (d2hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d2lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d2hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d2lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d2hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d2lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d2hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d2lo) d3lo) d4lo]
  · -- `quitdev_3` ≥ 274229659 / 638582784 > 0 on x2 ∈ [3 / 4, 1], x3 ∈ [0, 1 / 2], x4 ∈ [1 / 2, 1]
    have d2lo : (0:ℝ) ≤ x2 - 3 / 4 := sub_nonneg.mpr hs1
    have d2hi : (0:ℝ) ≤ 1 - x2 := sub_nonneg.mpr hhi2
    have d3lo : (0:ℝ) ≤ x3 - 0 := sub_nonneg.mpr hlo3
    have d3hi : (0:ℝ) ≤ 1 / 2 - x3 := sub_nonneg.mpr hhi3
    have d4lo : (0:ℝ) ≤ x4 - 1 / 2 := sub_nonneg.mpr hlo4
    have d4hi : (0:ℝ) ≤ 1 - x4 := sub_nonneg.mpr hhi4
    linarith only [c5, mul_nonneg (mul_nonneg (d2hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d2lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d2hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d2lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d2hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d2lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d2hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d2lo) d3lo) d4lo]

theorem seed202_r78_gen011_face_1_sub054
    (x2 x3 x4 : ℝ)
    (hlo2 : (1 / 2 : ℝ) ≤ x2)
    (hhi2 : x2 ≤ (1 : ℝ))
    (hlo3 : (1 / 2 : ℝ) ≤ x3)
    (hhi3 : x3 ≤ (1 : ℝ))
    (hlo4 : (0 : ℝ) ≤ x4)
    (hhi4 : x4 ≤ (1 : ℝ))
    (c4 : seed202_r78_gen011_face_1_f04 (1 : ℝ) x2 x3 x4)
    : False := by
  simp only [seed202_r78_gen011_face_1_f04] at c4
  -- `contdev_2` ≥ 127749619 / 1049624576 > 0 on x2 ∈ [1 / 2, 1], x3 ∈ [1 / 2, 1], x4 ∈ [0, 1]
  have d2lo : (0:ℝ) ≤ x2 - 1 / 2 := sub_nonneg.mpr hlo2
  have d2hi : (0:ℝ) ≤ 1 - x2 := sub_nonneg.mpr hhi2
  have d3lo : (0:ℝ) ≤ x3 - 1 / 2 := sub_nonneg.mpr hlo3
  have d3hi : (0:ℝ) ≤ 1 - x3 := sub_nonneg.mpr hhi3
  have d4lo : (0:ℝ) ≤ x4 - 0 := sub_nonneg.mpr hlo4
  have d4hi : (0:ℝ) ≤ 1 - x4 := sub_nonneg.mpr hhi4
  linarith only [c4, mul_nonneg (mul_nonneg (d2hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d2lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d2hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d2lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d2hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d2lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d2hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d2lo) d3lo) d4lo]

end Quitting.V0
