-- GENERATED by code/julia/scripts/certificates/v0_from_recorded.jl — do not edit.
-- Regenerate and `git diff --exit-code` to prove the Lean corpus is a
-- pure function of the JSON certificates.

import Formal.Certificates.Prelude

set_option maxRecDepth 8000
set_option maxHeartbeats 1000000

namespace Quitting.V0


/-- Condition `quit_at_most_L` of `seed202_r78_gen011_minmax_lower_1`, with the sense the trace reads it in. The
certificate refutes the system in which all of them hold at once. -/
def seed202_r78_gen011_minmax_lower_1_f01 (_x1 x2 x3 x4 : ℝ) : Prop :=
  74681 / 65536 + 8 / 17 * x4 - 45 / 17 * x3 + 1337 / 544 * x3 * x4 - 3 * x2 + 1475 / 442 * x2 * x4 + 113 / 17 * x2 * x3 - 24475 / 3536 * x2 * x3 * x4 ≤ 0

/-- Condition `wait_at_most_L` of `seed202_r78_gen011_minmax_lower_1`, with the sense the trace reads it in. The
certificate refutes the system in which all of them hold at once. -/
def seed202_r78_gen011_minmax_lower_1_f02 (_x1 x2 x3 x4 : ℝ) : Prop :=
  92971 / 196608 * x4 + 402361 / 65536 * x3 - 1665835 / 196608 * x3 * x4 + 289579 / 196608 * x2 - 2748719 / 2555904 * x2 * x4 - 1829675 / 196608 * x2 * x3 + 281295931 / 26411008 * x2 * x3 * x4 ≤ 0

end Quitting.V0
