-- GENERATED by code/julia/scripts/certificates/v0_from_recorded.jl — do not edit.
-- Regenerate and `git diff --exit-code` to prove the Lean corpus is a
-- pure function of the JSON certificates.

import Formal.Certificates.Prelude
import Formal.Certificates.V0.Seed202R78Gen011MinmaxLower1.Defs
import Formal.Certificates.V0.Seed202R78Gen011MinmaxLower1.Part01

set_option maxRecDepth 8000
set_option maxHeartbeats 1000000

namespace Quitting.V0


/-- with L = -9145/65536, no stationary punishment z of player 1 satisfies both a(z) <= L and b(z) <= L*q(z), so the smallest level w_1 admitting one exceeds L; and v^1 >= w_1 unconditionally (docs/V0_MINIMAX.md 2.1). Coordinate x1 is pinned to 0: the punishment is played by the other players.

Proved by the recorded subdivision of the box: every leaf carries one
condition that the Bernstein corner-basis expansion makes strictly
positive there. Machine-written. -/
theorem seed202_r78_gen011_minmax_lower_1
    (x1 x2 x3 x4 : ℝ)
    (hlo1 : (0 : ℝ) ≤ x1)
    (hhi1 : x1 ≤ (0 : ℝ))
    (hlo2 : (0 : ℝ) ≤ x2)
    (hhi2 : x2 ≤ (1 : ℝ))
    (hlo3 : (0 : ℝ) ≤ x3)
    (hhi3 : x3 ≤ (1 : ℝ))
    (hlo4 : (0 : ℝ) ≤ x4)
    (hhi4 : x4 ≤ (1 : ℝ))
    : ¬ (
      seed202_r78_gen011_minmax_lower_1_f01 x1 x2 x3 x4 ∧
      seed202_r78_gen011_minmax_lower_1_f02 x1 x2 x3 x4) := by
  rintro ⟨c1, c2⟩
  obtain rfl : x1 = (0 : ℝ) := le_antisymm hhi1 hlo1
  rcases le_total x2 (1 / 2 : ℝ) with hs1 | hs1
  · exact seed202_r78_gen011_minmax_lower_1_sub001 x2 x3 x4 hlo2 hs1 hlo3 hhi3 hlo4 hhi4 c1 c2
  · rcases le_total x3 (1 / 2 : ℝ) with hs2 | hs2
    · rcases le_total x4 (1 / 2 : ℝ) with hs3 | hs3
      · rcases le_total x2 (3 / 4 : ℝ) with hs4 | hs4
        · exact seed202_r78_gen011_minmax_lower_1_sub002 x2 x3 x4 hs1 hs4 hlo3 hs2 hlo4 hs3 c2
        · rcases le_total x3 (1 / 4 : ℝ) with hs5 | hs5
          · exact seed202_r78_gen011_minmax_lower_1_sub003 x2 x3 x4 hs4 hhi2 hlo3 hs5 hlo4 hs3 c2
          · rcases le_total x4 (1 / 4 : ℝ) with hs6 | hs6
            · rcases le_total x2 (7 / 8 : ℝ) with hs7 | hs7
              · exact seed202_r78_gen011_minmax_lower_1_sub004 x2 x3 x4 hs4 hs7 hs5 hs2 hlo4 hs6 c2
              · rcases le_total x3 (3 / 8 : ℝ) with hs8 | hs8
                · exact seed202_r78_gen011_minmax_lower_1_sub005 x2 x3 x4 hs7 hhi2 hs5 hs8 hlo4 hs6 c2
                · rcases le_total x4 (1 / 8 : ℝ) with hs9 | hs9
                  · rcases le_total x2 (15 / 16 : ℝ) with hs10 | hs10
                    · exact seed202_r78_gen011_minmax_lower_1_sub006 x2 x3 x4 hs7 hs10 hs8 hs2 hlo4 hs9 c2
                    · rcases le_total x3 (7 / 16 : ℝ) with hs11 | hs11
                      · exact seed202_r78_gen011_minmax_lower_1_sub007 x2 x3 x4 hs10 hhi2 hs8 hs11 hlo4 hs9 c2
                      · rcases le_total x4 (1 / 16 : ℝ) with hs12 | hs12
                        · rcases le_total x2 (31 / 32 : ℝ) with hs13 | hs13
                          · exact seed202_r78_gen011_minmax_lower_1_sub008 x2 x3 x4 hs10 hs13 hs11 hs2 hlo4 hs12 c1 c2
                          · rcases le_total x3 (15 / 32 : ℝ) with hs14 | hs14
                            · rcases le_total x4 (1 / 32 : ℝ) with hs15 | hs15
                              · rcases le_total x2 (63 / 64 : ℝ) with hs16 | hs16
                                · exact seed202_r78_gen011_minmax_lower_1_sub009 x2 x3 x4 hs13 hs16 hs11 hs14 hlo4 hs15 c2
                                · rcases le_total x3 (29 / 64 : ℝ) with hs17 | hs17
                                  · exact seed202_r78_gen011_minmax_lower_1_sub010 x2 x3 x4 hs16 hhi2 hs11 hs17 hlo4 hs15 c2
                                  · rcases le_total x4 (1 / 64 : ℝ) with hs18 | hs18
                                    · rcases le_total x2 (127 / 128 : ℝ) with hs19 | hs19
                                      · exact seed202_r78_gen011_minmax_lower_1_sub011 x2 x3 x4 hs16 hs19 hs17 hs14 hlo4 hs18 c2
                                      · rcases le_total x3 (59 / 128 : ℝ) with hs20 | hs20
                                        · exact seed202_r78_gen011_minmax_lower_1_sub012 x2 x3 x4 hs19 hhi2 hs17 hs20 hlo4 hs18 c2
                                        · rcases le_total x4 (1 / 128 : ℝ) with hs21 | hs21
                                          · rcases le_total x2 (255 / 256 : ℝ) with hs22 | hs22
                                            · exact seed202_r78_gen011_minmax_lower_1_sub013 x2 x3 x4 hs19 hs22 hs20 hs14 hlo4 hs21 c1 c2
                                            · exact seed202_r78_gen011_minmax_lower_1_sub014 x2 x3 x4 hs22 hhi2 hs20 hs14 hlo4 hs21 c1 c2
                                          · exact seed202_r78_gen011_minmax_lower_1_sub015 x2 x3 x4 hs19 hhi2 hs20 hs14 hs21 hs18 c1 c2
                                    · exact seed202_r78_gen011_minmax_lower_1_sub016 x2 x3 x4 hs16 hhi2 hs17 hs14 hs18 hs15 c1 c2
                              · exact seed202_r78_gen011_minmax_lower_1_sub017 x2 x3 x4 hs13 hhi2 hs11 hs14 hs15 hs12 c2
                            · exact seed202_r78_gen011_minmax_lower_1_sub018 x2 x3 x4 hs13 hhi2 hs14 hs2 hlo4 hs12 c1
                        · exact seed202_r78_gen011_minmax_lower_1_sub019 x2 x3 x4 hs10 hhi2 hs11 hs2 hs12 hs9 c1
                  · exact seed202_r78_gen011_minmax_lower_1_sub020 x2 x3 x4 hs7 hhi2 hs8 hs2 hs9 hs6 c1 c2
            · exact seed202_r78_gen011_minmax_lower_1_sub021 x2 x3 x4 hs4 hhi2 hs5 hs2 hs6 hs3 c2
      · exact seed202_r78_gen011_minmax_lower_1_sub022 x2 x3 x4 hs1 hhi2 hlo3 hs2 hs3 hhi4 c1
    · exact seed202_r78_gen011_minmax_lower_1_sub023 x2 x3 x4 hs1 hhi2 hs2 hhi3 hlo4 hhi4 c1 c2


/-- Certificate identifier proved in this module. The `#guard`
below turns a silently dropped certificate into a compile error. -/
def Seed202R78Gen011MinmaxLower1Ids : List String :=
  ["v1/v0/seed202_r78_gen011/minmax_lower_1"]

#guard Seed202R78Gen011MinmaxLower1Ids.length = 1

end Quitting.V0
