-- GENERATED by code/julia/scripts/certificates/v0_from_recorded.jl — do not edit.
-- Regenerate and `git diff --exit-code` to prove the Lean corpus is a
-- pure function of the JSON certificates.

import Formal.Certificates.Prelude

set_option maxRecDepth 8000
set_option maxHeartbeats 1000000

namespace Quitting.V0

-- Conditions of certificate `seed202_r78_gen011_minmax_upper_1`, one per declaration.
-- Together they say: against this punishment, quitting now and
-- waiting both pay player 1 at most the stated level.

/-- Condition `U_minus_a` of `seed202_r78_gen011_minmax_upper_1`. -/
def seed202_r78_gen011_minmax_upper_1_c01 (_x1 x2 x3 x4 : ℝ) : Prop :=
  0 ≤ -9335 / 8192 - 8 / 17 * x4 + 45 / 17 * x3 - 1337 / 544 * x3 * x4 + 3 * x2 - 1475 / 442 * x2 * x4 - 113 / 17 * x2 * x3 + 24475 / 3536 * x2 * x3 * x4

/-- Condition `qU_minus_b` of `seed202_r78_gen011_minmax_upper_1`. -/
def seed202_r78_gen011_minmax_upper_1_c02 (_x1 x2 x3 x4 : ℝ) : Prop :=
  0 ≤ -11621 / 24576 * x4 - 50295 / 8192 * x3 + 208229 / 24576 * x3 * x4 - 36197 / 24576 * x2 + 343585 / 319488 * x2 * x4 + 228709 / 24576 * x2 * x3 - 35161941 / 3301376 * x2 * x3 * x4

theorem seed202_r78_gen011_minmax_upper_1_c01_holds : seed202_r78_gen011_minmax_upper_1_c01 (0) (1) (15241 / 32768) (0) := by
  unfold seed202_r78_gen011_minmax_upper_1_c01
  norm_num

theorem seed202_r78_gen011_minmax_upper_1_c02_holds : seed202_r78_gen011_minmax_upper_1_c02 (0) (1) (15241 / 32768) (0) := by
  unfold seed202_r78_gen011_minmax_upper_1_c02
  norm_num

/-- the stationary punishment listed here holds player 1 to at most -1143/8192, so w_1 <= -1143/8192. Scope: this bounds the min-max value from above and is reported for the sandwich only; the refutation of branch (S.2) uses the lower bound alone.

Stated as an existential over one tuple: a punishment at this level
exists, so the min-max value is at most it. Machine-written. -/
theorem seed202_r78_gen011_minmax_upper_1 :
    ∃ x1 x2 x3 x4 : ℝ,
      seed202_r78_gen011_minmax_upper_1_c01 x1 x2 x3 x4 ∧
      seed202_r78_gen011_minmax_upper_1_c02 x1 x2 x3 x4 :=
  ⟨0, 1, 15241 / 32768, 0,
   seed202_r78_gen011_minmax_upper_1_c01_holds, seed202_r78_gen011_minmax_upper_1_c02_holds⟩

/-- Certificate identifier proved in this module. The `#guard`
below turns a silently dropped certificate into a compile error. -/
def Seed202R78Gen011MinmaxUpper1Ids : List String :=
  ["v1/v0/seed202_r78_gen011/minmax_upper_1"]

#guard Seed202R78Gen011MinmaxUpper1Ids.length = 1

end Quitting.V0
