-- GENERATED by code/julia/scripts/certificates/v0_from_recorded.jl — do not edit.
-- Regenerate and `git diff --exit-code` to prove the Lean corpus is a
-- pure function of the JSON certificates.

import Formal.Certificates.Prelude
import Formal.Certificates.V0.Seed202R78Gen011Face3.Defs
import Formal.Certificates.V0.Seed202R78Gen011Face3.Part01
import Formal.Certificates.V0.Seed202R78Gen011Face3.Part02
import Formal.Certificates.V0.Seed202R78Gen011Face3.Part03

set_option maxRecDepth 8000
set_option maxHeartbeats 1000000

namespace Quitting.V0


/-- on the face {x3 = 1} of the stage-1 profile cube no point leaves all 2N stage-1 deviation gains at most eps = 400005/1048576; the unknown continuation values are replaced by the certified min-max lower bounds (continue-deviations) and by max(0, max_S r^S_k) (quit-deviations), both of which only lower the gains. Termination with probability one at stage 1 forces some x_i = 1, so the four faces are the whole case enumeration.

Proved by the recorded subdivision of the box: every leaf carries one
condition that the Bernstein corner-basis expansion makes strictly
positive there. Machine-written. -/
theorem seed202_r78_gen011_face_3
    (x1 x2 x3 x4 : ℝ)
    (hlo1 : (0 : ℝ) ≤ x1)
    (hhi1 : x1 ≤ (1 : ℝ))
    (hlo2 : (0 : ℝ) ≤ x2)
    (hhi2 : x2 ≤ (1 : ℝ))
    (hlo3 : (1 : ℝ) ≤ x3)
    (hhi3 : x3 ≤ (1 : ℝ))
    (hlo4 : (0 : ℝ) ≤ x4)
    (hhi4 : x4 ≤ (1 : ℝ))
    : ¬ (
      seed202_r78_gen011_face_3_f01 x1 x2 x3 x4 ∧
      seed202_r78_gen011_face_3_f02 x1 x2 x3 x4 ∧
      seed202_r78_gen011_face_3_f03 x1 x2 x3 x4 ∧
      seed202_r78_gen011_face_3_f04 x1 x2 x3 x4 ∧
      seed202_r78_gen011_face_3_f05 x1 x2 x3 x4 ∧
      seed202_r78_gen011_face_3_f06 x1 x2 x3 x4 ∧
      seed202_r78_gen011_face_3_f07 x1 x2 x3 x4 ∧
      seed202_r78_gen011_face_3_f08 x1 x2 x3 x4) := by
  rintro ⟨c1, c2, _, c4, _, c6, c7, c8⟩
  obtain rfl : x3 = (1 : ℝ) := le_antisymm hhi3 hlo3
  rcases le_total x1 (1 / 2 : ℝ) with hs1 | hs1
  · rcases le_total x2 (1 / 2 : ℝ) with hs2 | hs2
    · exact seed202_r78_gen011_face_3_sub001 x1 x2 x4 hlo1 hs1 hlo2 hs2 hlo4 hhi4 c1 c2 c4 c6 c7
    · rcases le_total x4 (1 / 2 : ℝ) with hs3 | hs3
      · rcases le_total x1 (1 / 4 : ℝ) with hs4 | hs4
        · rcases le_total x2 (3 / 4 : ℝ) with hs5 | hs5
          · rcases le_total x4 (1 / 4 : ℝ) with hs6 | hs6
            · rcases le_total x1 (1 / 8 : ℝ) with hs7 | hs7
              · exact seed202_r78_gen011_face_3_sub002 x1 x2 x4 hlo1 hs7 hs2 hs5 hlo4 hs6 c1 c7
              · rcases le_total x2 (5 / 8 : ℝ) with hs8 | hs8
                · exact seed202_r78_gen011_face_3_sub003 x1 x2 x4 hs7 hs4 hs2 hs8 hlo4 hs6 c7
                · rcases le_total x4 (1 / 8 : ℝ) with hs9 | hs9
                  · rcases le_total x1 (3 / 16 : ℝ) with hs10 | hs10
                    · exact seed202_r78_gen011_face_3_sub004 x1 x2 x4 hs7 hs10 hs8 hs5 hlo4 hs9 c1 c7
                    · exact seed202_r78_gen011_face_3_sub005 x1 x2 x4 hs10 hs4 hs8 hs5 hlo4 hs9 c1 c4 c7
                  · exact seed202_r78_gen011_face_3_sub006 x1 x2 x4 hs7 hs4 hs8 hs5 hs9 hs6 c1 c4 c7
            · exact seed202_r78_gen011_face_3_sub007 x1 x2 x4 hlo1 hs4 hs2 hs5 hs6 hs3 c1 c4 c7
          · exact seed202_r78_gen011_face_3_sub008 x1 x2 x4 hlo1 hs4 hs5 hhi2 hlo4 hs3 c1
        · exact seed202_r78_gen011_face_3_sub009 x1 x2 x4 hs4 hs1 hs2 hhi2 hlo4 hs3 c1 c4 c7
      · exact seed202_r78_gen011_face_3_sub010 x1 x2 x4 hlo1 hs1 hs2 hhi2 hs3 hhi4 c1 c4 c7
  · rcases le_total x2 (1 / 2 : ℝ) with hs2 | hs2
    · rcases le_total x4 (1 / 2 : ℝ) with hs3 | hs3
      · exact seed202_r78_gen011_face_3_sub011 x1 x2 x4 hs1 hhi1 hlo2 hs2 hlo4 hs3 c2 c4
      · rcases le_total x1 (3 / 4 : ℝ) with hs4 | hs4
        · exact seed202_r78_gen011_face_3_sub012 x1 x2 x4 hs1 hs4 hlo2 hs2 hs3 hhi4 c1 c4 c6
        · rcases le_total x2 (1 / 4 : ℝ) with hs5 | hs5
          · rcases le_total x4 (3 / 4 : ℝ) with hs6 | hs6
            · exact seed202_r78_gen011_face_3_sub013 x1 x2 x4 hs4 hhi1 hlo2 hs5 hs3 hs6 c4 c6 c8
            · rcases le_total x1 (7 / 8 : ℝ) with hs7 | hs7
              · rcases le_total x2 (1 / 8 : ℝ) with hs8 | hs8
                · exact seed202_r78_gen011_face_3_sub014 x1 x2 x4 hs4 hs7 hlo2 hs8 hs6 hhi4 c1 c6 c8
                · exact seed202_r78_gen011_face_3_sub015 x1 x2 x4 hs4 hs7 hs8 hs5 hs6 hhi4 c1 c4 c6 c8
              · exact seed202_r78_gen011_face_3_sub016 x1 x2 x4 hs7 hhi1 hlo2 hs5 hs6 hhi4 c8
          · exact seed202_r78_gen011_face_3_sub017 x1 x2 x4 hs4 hhi1 hs5 hs2 hs3 hhi4 c4
    · exact seed202_r78_gen011_face_3_sub018 x1 x2 x4 hs1 hhi1 hs2 hhi2 hlo4 hhi4 c4


/-- Certificate identifier proved in this module. The `#guard`
below turns a silently dropped certificate into a compile error. -/
def Seed202R78Gen011Face3Ids : List String :=
  ["v1/v0/seed202_r78_gen011/face_3"]

#guard Seed202R78Gen011Face3Ids.length = 1

end Quitting.V0
