-- GENERATED by code/julia/scripts/certificates/v0_from_recorded.jl — do not edit.
-- Regenerate and `git diff --exit-code` to prove the Lean corpus is a
-- pure function of the JSON certificates.

import Formal.Certificates.Prelude
import Formal.Certificates.V0.Seed202R78Gen011Face3.Defs

set_option maxRecDepth 8000
set_option maxHeartbeats 1000000

namespace Quitting.V0

theorem seed202_r78_gen011_face_3_sub016
    (x1 x2 x4 : ℝ)
    (hlo1 : (7 / 8 : ℝ) ≤ x1)
    (hhi1 : x1 ≤ (1 : ℝ))
    (hlo2 : (0 : ℝ) ≤ x2)
    (hhi2 : x2 ≤ (1 / 4 : ℝ))
    (hlo4 : (3 / 4 : ℝ) ≤ x4)
    (hhi4 : x4 ≤ (1 : ℝ))
    (c8 : seed202_r78_gen011_face_3_f08 x1 x2 (1 : ℝ) x4)
    : False := by
  simp only [seed202_r78_gen011_face_3_f08] at c8
  -- `contdev_4` ≥ 105450543887 / 781278248960 > 0 on x1 ∈ [7 / 8, 1], x2 ∈ [0, 1 / 4], x4 ∈ [3 / 4, 1]
  have d1lo : (0:ℝ) ≤ x1 - 7 / 8 := sub_nonneg.mpr hlo1
  have d1hi : (0:ℝ) ≤ 1 - x1 := sub_nonneg.mpr hhi1
  have d2lo : (0:ℝ) ≤ x2 - 0 := sub_nonneg.mpr hlo2
  have d2hi : (0:ℝ) ≤ 1 / 4 - x2 := sub_nonneg.mpr hhi2
  have d4lo : (0:ℝ) ≤ x4 - 3 / 4 := sub_nonneg.mpr hlo4
  have d4hi : (0:ℝ) ≤ 1 - x4 := sub_nonneg.mpr hhi4
  linarith only [c8, mul_nonneg (mul_nonneg (d1hi) d2hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d2hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d2lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d2lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d2hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d2hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d2lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d2lo) d4lo]

theorem seed202_r78_gen011_face_3_sub017
    (x1 x2 x4 : ℝ)
    (hlo1 : (3 / 4 : ℝ) ≤ x1)
    (hhi1 : x1 ≤ (1 : ℝ))
    (hlo2 : (1 / 4 : ℝ) ≤ x2)
    (hhi2 : x2 ≤ (1 / 2 : ℝ))
    (hlo4 : (1 / 2 : ℝ) ≤ x4)
    (hhi4 : x4 ≤ (1 : ℝ))
    (c4 : seed202_r78_gen011_face_3_f04 x1 x2 (1 : ℝ) x4)
    : False := by
  simp only [seed202_r78_gen011_face_3_f04] at c4
  -- `contdev_2` ≥ 18331973 / 66060288 > 0 on x1 ∈ [3 / 4, 1], x2 ∈ [1 / 4, 1 / 2], x4 ∈ [1 / 2, 1]
  have d1lo : (0:ℝ) ≤ x1 - 3 / 4 := sub_nonneg.mpr hlo1
  have d1hi : (0:ℝ) ≤ 1 - x1 := sub_nonneg.mpr hhi1
  have d2lo : (0:ℝ) ≤ x2 - 1 / 4 := sub_nonneg.mpr hlo2
  have d2hi : (0:ℝ) ≤ 1 / 2 - x2 := sub_nonneg.mpr hhi2
  have d4lo : (0:ℝ) ≤ x4 - 1 / 2 := sub_nonneg.mpr hlo4
  have d4hi : (0:ℝ) ≤ 1 - x4 := sub_nonneg.mpr hhi4
  linarith only [c4, mul_nonneg (mul_nonneg (d1hi) d2hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d2hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d2lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d2lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d2hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d2hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d2lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d2lo) d4lo]

theorem seed202_r78_gen011_face_3_sub018
    (x1 x2 x4 : ℝ)
    (hlo1 : (1 / 2 : ℝ) ≤ x1)
    (hhi1 : x1 ≤ (1 : ℝ))
    (hlo2 : (1 / 2 : ℝ) ≤ x2)
    (hhi2 : x2 ≤ (1 : ℝ))
    (hlo4 : (0 : ℝ) ≤ x4)
    (hhi4 : x4 ≤ (1 : ℝ))
    (c4 : seed202_r78_gen011_face_3_f04 x1 x2 (1 : ℝ) x4)
    : False := by
  simp only [seed202_r78_gen011_face_3_f04] at c4
  -- `contdev_2` ≥ 122317229 / 258998272 > 0 on x1 ∈ [1 / 2, 1], x2 ∈ [1 / 2, 1], x4 ∈ [0, 1]
  have d1lo : (0:ℝ) ≤ x1 - 1 / 2 := sub_nonneg.mpr hlo1
  have d1hi : (0:ℝ) ≤ 1 - x1 := sub_nonneg.mpr hhi1
  have d2lo : (0:ℝ) ≤ x2 - 1 / 2 := sub_nonneg.mpr hlo2
  have d2hi : (0:ℝ) ≤ 1 - x2 := sub_nonneg.mpr hhi2
  have d4lo : (0:ℝ) ≤ x4 - 0 := sub_nonneg.mpr hlo4
  have d4hi : (0:ℝ) ≤ 1 - x4 := sub_nonneg.mpr hhi4
  linarith only [c4, mul_nonneg (mul_nonneg (d1hi) d2hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d2hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d2lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d2lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d2hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d2hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d2lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d2lo) d4lo]

end Quitting.V0
