-- GENERATED by code/julia/scripts/certificates/front_a_witness.jl — do not edit.
-- Regenerated for the public corpus: only seed202_r78_gen011.

import Formal.Certificates.Prelude

set_option maxRecDepth 8000

namespace Quitting.FrontA

/-- Continuation weight of the objecting player at the profile of `Seed202R78Gen011FrontAK1`. -/
noncomputable def Seed202R78Gen011FrontAK1_z (_c1 _c2 _c3 _c4 x1 _x2 x3 x4 : ℝ) : ℝ :=
  1 - x4 - x3 + x3 * x4 - x1 + x1 * x4 + x1 * x3 - x1 * x3 * x4

/-- Deviation gain of the objecting player of `Seed202R78Gen011FrontAK1`, in the continuation `c` and the profile `x`. -/
noncomputable def Seed202R78Gen011FrontAK1_D (_c1 c2 _c3 _c4 x1 _x2 x3 x4 : ℝ) : ℝ :=
  1 - 220 / 29 * x4 - 13 / 19 * x3 + 29993 / 4959 * x3 * x4 + 5 / 22 * x1 + 30909 / 4147 * x1 * x4 - 11612 / 2717 * x1 * x3 - 8082397 / 1527372 * x1 * x3 * x4 - c2 + c2 * x4 + c2 * x3 - c2 * x3 * x4 + c2 * x1 - c2 * x1 * x4 - c2 * x1 * x3 + c2 * x1 * x3 * x4

/-- The continuation drops out of the deviation gain at this profile: the weight it
carries is zero. Machine-written. -/
theorem Seed202R78Gen011FrontAK1_z_holds :
    Seed202R78Gen011FrontAK1_z 0 0 0 0 1 0 0 0 = 0 := by
  unfold Seed202R78Gen011FrontAK1_z
  norm_num

/-- Certificate `v1/front_a/seed202_r78_gen011/K1`: front [A], coalition {1}: the profile in which exactly these players quit outright is not a Nash equilibrium of the stage game G(c), for ANY continuation vector c. Player 2 is a stayer who strictly gains by quitting: the deviation gain D_2 of src/stage.jl is positive at the profile, while the stage-Nash conditions require it to be at most zero. The two conditions below are that deviation gain and the weight z_2(x) = prod_{j != i} (1 - x_j) with which the continuation enters it. D_i is affine in c_i with coefficient -z_i and involves no other c_j, so z_i = 0 at this profile makes the value a constant and the sign unconditional -- in particular the lone-quitter branch of case T, which needs c in W_0 and hence (R2), is not used here. Coefficients are the payoff entries, so substituting the point is a check about this game (docs/G3_MIXED_APS.md 12.15(b), 12.20).

Universally quantified over the continuation: the coalition's own
quitting drives the objector's continuation weight to zero, so the
sign below does not depend on what play would have been worth had
it gone on. Machine-written. -/
theorem Seed202R78Gen011FrontAK1 :
    ∀ c1 c2 c3 c4 : ℝ,
      0 < Seed202R78Gen011FrontAK1_D c1 c2 c3 c4 1 0 0 0 := by
  intro c1 c2 c3 c4
  unfold Seed202R78Gen011FrontAK1_D
  norm_num

/-- Continuation weight of the objecting player at the profile of `Seed202R78Gen011FrontAK2`. -/
noncomputable def Seed202R78Gen011FrontAK2_z (_c1 _c2 _c3 _c4 x1 x2 _x3 x4 : ℝ) : ℝ :=
  1 - x4 - x2 + x2 * x4 - x1 + x1 * x4 + x1 * x2 - x1 * x2 * x4

/-- Deviation gain of the objecting player of `Seed202R78Gen011FrontAK2`, in the continuation `c` and the profile `x`. -/
noncomputable def Seed202R78Gen011FrontAK2_D (_c1 _c2 c3 _c4 x1 x2 _x3 x4 : ℝ) : ℝ :=
  1 - 91 / 12 * x4 + 79 / 19 * x2 + 2201 / 1824 * x2 * x4 - 201 / 31 * x1 + 36755 / 2604 * x1 * x4 + 3137 / 589 * x1 * x2 - 37974327 / 3826144 * x1 * x2 * x4 - c3 + c3 * x4 + c3 * x2 - c3 * x2 * x4 + c3 * x1 - c3 * x1 * x4 - c3 * x1 * x2 + c3 * x1 * x2 * x4

/-- The continuation drops out of the deviation gain at this profile: the weight it
carries is zero. Machine-written. -/
theorem Seed202R78Gen011FrontAK2_z_holds :
    Seed202R78Gen011FrontAK2_z 0 0 0 0 0 1 0 0 = 0 := by
  unfold Seed202R78Gen011FrontAK2_z
  norm_num

/-- Certificate `v1/front_a/seed202_r78_gen011/K2`: front [A], coalition {2}: the profile in which exactly these players quit outright is not a Nash equilibrium of the stage game G(c), for ANY continuation vector c. Player 3 is a stayer who strictly gains by quitting: the deviation gain D_3 of src/stage.jl is positive at the profile, while the stage-Nash conditions require it to be at most zero. The two conditions below are that deviation gain and the weight z_3(x) = prod_{j != i} (1 - x_j) with which the continuation enters it. D_i is affine in c_i with coefficient -z_i and involves no other c_j, so z_i = 0 at this profile makes the value a constant and the sign unconditional -- in particular the lone-quitter branch of case T, which needs c in W_0 and hence (R2), is not used here. Coefficients are the payoff entries, so substituting the point is a check about this game (docs/G3_MIXED_APS.md 12.15(b), 12.20).

Universally quantified over the continuation: the coalition's own
quitting drives the objector's continuation weight to zero, so the
sign below does not depend on what play would have been worth had
it gone on. Machine-written. -/
theorem Seed202R78Gen011FrontAK2 :
    ∀ c1 c2 c3 c4 : ℝ,
      0 < Seed202R78Gen011FrontAK2_D c1 c2 c3 c4 0 1 0 0 := by
  intro c1 c2 c3 c4
  unfold Seed202R78Gen011FrontAK2_D
  norm_num

/-- Continuation weight of the objecting player at the profile of `Seed202R78Gen011FrontAK12`. -/
noncomputable def Seed202R78Gen011FrontAK12_z (_c1 _c2 _c3 _c4 _x1 x2 x3 x4 : ℝ) : ℝ :=
  1 - x4 - x3 + x3 * x4 - x2 + x2 * x4 + x2 * x3 - x2 * x3 * x4

/-- Deviation gain of the objecting player of `Seed202R78Gen011FrontAK12`, in the continuation `c` and the profile `x`. -/
noncomputable def Seed202R78Gen011FrontAK12_D (c1 _c2 _c3 _c4 _x1 x2 x3 x4 : ℝ) : ℝ :=
  1 + 7 / 51 * x4 - 147 / 17 * x3 + 17611 / 1632 * x3 * x4 - 13 / 3 * x2 + 2833 / 663 * x2 * x4 + 1613 / 102 * x2 * x3 - 1910917 / 109616 * x2 * x3 * x4 - c1 + c1 * x4 + c1 * x3 - c1 * x3 * x4 + c1 * x2 - c1 * x2 * x4 - c1 * x2 * x3 + c1 * x2 * x3 * x4

/-- The continuation drops out of the deviation gain at this profile: the weight it
carries is zero. Machine-written. -/
theorem Seed202R78Gen011FrontAK12_z_holds :
    Seed202R78Gen011FrontAK12_z 0 0 0 0 1 1 0 0 = 0 := by
  unfold Seed202R78Gen011FrontAK12_z
  norm_num

/-- Certificate `v1/front_a/seed202_r78_gen011/K12`: front [A], coalition {1,2}: the profile in which exactly these players quit outright is not a Nash equilibrium of the stage game G(c), for ANY continuation vector c. Player 1 is a member of the coalition who strictly gains by staying: the deviation gain D_1 of src/stage.jl is negative at the profile, while the stage-Nash conditions require it to be at least zero. The two conditions below are that deviation gain and the weight z_1(x) = prod_{j != i} (1 - x_j) with which the continuation enters it. D_i is affine in c_i with coefficient -z_i and involves no other c_j, so z_i = 0 at this profile makes the value a constant and the sign unconditional -- in particular the lone-quitter branch of case T, which needs c in W_0 and hence (R2), is not used here. Coefficients are the payoff entries, so substituting the point is a check about this game (docs/G3_MIXED_APS.md 12.15(b), 12.20).

Universally quantified over the continuation: the coalition's own
quitting drives the objector's continuation weight to zero, so the
sign below does not depend on what play would have been worth had
it gone on. Machine-written. -/
theorem Seed202R78Gen011FrontAK12 :
    ∀ c1 c2 c3 c4 : ℝ,
      Seed202R78Gen011FrontAK12_D c1 c2 c3 c4 1 1 0 0 < 0 := by
  intro c1 c2 c3 c4
  unfold Seed202R78Gen011FrontAK12_D
  norm_num

/-- Continuation weight of the objecting player at the profile of `Seed202R78Gen011FrontAK3`. -/
noncomputable def Seed202R78Gen011FrontAK3_z (_c1 _c2 _c3 _c4 x1 _x2 x3 x4 : ℝ) : ℝ :=
  1 - x4 - x3 + x3 * x4 - x1 + x1 * x4 + x1 * x3 - x1 * x3 * x4

/-- Deviation gain of the objecting player of `Seed202R78Gen011FrontAK3`, in the continuation `c` and the profile `x`. -/
noncomputable def Seed202R78Gen011FrontAK3_D (_c1 c2 _c3 _c4 x1 _x2 x3 x4 : ℝ) : ℝ :=
  1 - 220 / 29 * x4 - 13 / 19 * x3 + 29993 / 4959 * x3 * x4 + 5 / 22 * x1 + 30909 / 4147 * x1 * x4 - 11612 / 2717 * x1 * x3 - 8082397 / 1527372 * x1 * x3 * x4 - c2 + c2 * x4 + c2 * x3 - c2 * x3 * x4 + c2 * x1 - c2 * x1 * x4 - c2 * x1 * x3 + c2 * x1 * x3 * x4

/-- The continuation drops out of the deviation gain at this profile: the weight it
carries is zero. Machine-written. -/
theorem Seed202R78Gen011FrontAK3_z_holds :
    Seed202R78Gen011FrontAK3_z 0 0 0 0 0 0 1 0 = 0 := by
  unfold Seed202R78Gen011FrontAK3_z
  norm_num

/-- Certificate `v1/front_a/seed202_r78_gen011/K3`: front [A], coalition {3}: the profile in which exactly these players quit outright is not a Nash equilibrium of the stage game G(c), for ANY continuation vector c. Player 2 is a stayer who strictly gains by quitting: the deviation gain D_2 of src/stage.jl is positive at the profile, while the stage-Nash conditions require it to be at most zero. The two conditions below are that deviation gain and the weight z_2(x) = prod_{j != i} (1 - x_j) with which the continuation enters it. D_i is affine in c_i with coefficient -z_i and involves no other c_j, so z_i = 0 at this profile makes the value a constant and the sign unconditional -- in particular the lone-quitter branch of case T, which needs c in W_0 and hence (R2), is not used here. Coefficients are the payoff entries, so substituting the point is a check about this game (docs/G3_MIXED_APS.md 12.15(b), 12.20).

Universally quantified over the continuation: the coalition's own
quitting drives the objector's continuation weight to zero, so the
sign below does not depend on what play would have been worth had
it gone on. Machine-written. -/
theorem Seed202R78Gen011FrontAK3 :
    ∀ c1 c2 c3 c4 : ℝ,
      0 < Seed202R78Gen011FrontAK3_D c1 c2 c3 c4 0 0 1 0 := by
  intro c1 c2 c3 c4
  unfold Seed202R78Gen011FrontAK3_D
  norm_num

/-- Continuation weight of the objecting player at the profile of `Seed202R78Gen011FrontAK13`. -/
noncomputable def Seed202R78Gen011FrontAK13_z (_c1 _c2 _c3 _c4 _x1 x2 x3 x4 : ℝ) : ℝ :=
  1 - x4 - x3 + x3 * x4 - x2 + x2 * x4 + x2 * x3 - x2 * x3 * x4

/-- Deviation gain of the objecting player of `Seed202R78Gen011FrontAK13`, in the continuation `c` and the profile `x`. -/
noncomputable def Seed202R78Gen011FrontAK13_D (c1 _c2 _c3 _c4 _x1 x2 x3 x4 : ℝ) : ℝ :=
  1 + 7 / 51 * x4 - 147 / 17 * x3 + 17611 / 1632 * x3 * x4 - 13 / 3 * x2 + 2833 / 663 * x2 * x4 + 1613 / 102 * x2 * x3 - 1910917 / 109616 * x2 * x3 * x4 - c1 + c1 * x4 + c1 * x3 - c1 * x3 * x4 + c1 * x2 - c1 * x2 * x4 - c1 * x2 * x3 + c1 * x2 * x3 * x4

/-- The continuation drops out of the deviation gain at this profile: the weight it
carries is zero. Machine-written. -/
theorem Seed202R78Gen011FrontAK13_z_holds :
    Seed202R78Gen011FrontAK13_z 0 0 0 0 1 0 1 0 = 0 := by
  unfold Seed202R78Gen011FrontAK13_z
  norm_num

/-- Certificate `v1/front_a/seed202_r78_gen011/K13`: front [A], coalition {1,3}: the profile in which exactly these players quit outright is not a Nash equilibrium of the stage game G(c), for ANY continuation vector c. Player 1 is a member of the coalition who strictly gains by staying: the deviation gain D_1 of src/stage.jl is negative at the profile, while the stage-Nash conditions require it to be at least zero. The two conditions below are that deviation gain and the weight z_1(x) = prod_{j != i} (1 - x_j) with which the continuation enters it. D_i is affine in c_i with coefficient -z_i and involves no other c_j, so z_i = 0 at this profile makes the value a constant and the sign unconditional -- in particular the lone-quitter branch of case T, which needs c in W_0 and hence (R2), is not used here. Coefficients are the payoff entries, so substituting the point is a check about this game (docs/G3_MIXED_APS.md 12.15(b), 12.20).

Universally quantified over the continuation: the coalition's own
quitting drives the objector's continuation weight to zero, so the
sign below does not depend on what play would have been worth had
it gone on. Machine-written. -/
theorem Seed202R78Gen011FrontAK13 :
    ∀ c1 c2 c3 c4 : ℝ,
      Seed202R78Gen011FrontAK13_D c1 c2 c3 c4 1 0 1 0 < 0 := by
  intro c1 c2 c3 c4
  unfold Seed202R78Gen011FrontAK13_D
  norm_num

/-- Continuation weight of the objecting player at the profile of `Seed202R78Gen011FrontAK23`. -/
noncomputable def Seed202R78Gen011FrontAK23_z (_c1 _c2 _c3 _c4 _x1 x2 x3 x4 : ℝ) : ℝ :=
  1 - x4 - x3 + x3 * x4 - x2 + x2 * x4 + x2 * x3 - x2 * x3 * x4

/-- Deviation gain of the objecting player of `Seed202R78Gen011FrontAK23`, in the continuation `c` and the profile `x`. -/
noncomputable def Seed202R78Gen011FrontAK23_D (c1 _c2 _c3 _c4 _x1 x2 x3 x4 : ℝ) : ℝ :=
  1 + 7 / 51 * x4 - 147 / 17 * x3 + 17611 / 1632 * x3 * x4 - 13 / 3 * x2 + 2833 / 663 * x2 * x4 + 1613 / 102 * x2 * x3 - 1910917 / 109616 * x2 * x3 * x4 - c1 + c1 * x4 + c1 * x3 - c1 * x3 * x4 + c1 * x2 - c1 * x2 * x4 - c1 * x2 * x3 + c1 * x2 * x3 * x4

/-- The continuation drops out of the deviation gain at this profile: the weight it
carries is zero. Machine-written. -/
theorem Seed202R78Gen011FrontAK23_z_holds :
    Seed202R78Gen011FrontAK23_z 0 0 0 0 0 1 1 0 = 0 := by
  unfold Seed202R78Gen011FrontAK23_z
  norm_num

/-- Certificate `v1/front_a/seed202_r78_gen011/K23`: front [A], coalition {2,3}: the profile in which exactly these players quit outright is not a Nash equilibrium of the stage game G(c), for ANY continuation vector c. Player 1 is a stayer who strictly gains by quitting: the deviation gain D_1 of src/stage.jl is positive at the profile, while the stage-Nash conditions require it to be at most zero. The two conditions below are that deviation gain and the weight z_1(x) = prod_{j != i} (1 - x_j) with which the continuation enters it. D_i is affine in c_i with coefficient -z_i and involves no other c_j, so z_i = 0 at this profile makes the value a constant and the sign unconditional -- in particular the lone-quitter branch of case T, which needs c in W_0 and hence (R2), is not used here. Coefficients are the payoff entries, so substituting the point is a check about this game (docs/G3_MIXED_APS.md 12.15(b), 12.20).

Universally quantified over the continuation: the coalition's own
quitting drives the objector's continuation weight to zero, so the
sign below does not depend on what play would have been worth had
it gone on. Machine-written. -/
theorem Seed202R78Gen011FrontAK23 :
    ∀ c1 c2 c3 c4 : ℝ,
      0 < Seed202R78Gen011FrontAK23_D c1 c2 c3 c4 0 1 1 0 := by
  intro c1 c2 c3 c4
  unfold Seed202R78Gen011FrontAK23_D
  norm_num

/-- Continuation weight of the objecting player at the profile of `Seed202R78Gen011FrontAK123`. -/
noncomputable def Seed202R78Gen011FrontAK123_z (_c1 _c2 _c3 _c4 x1 _x2 x3 x4 : ℝ) : ℝ :=
  1 - x4 - x3 + x3 * x4 - x1 + x1 * x4 + x1 * x3 - x1 * x3 * x4

/-- Deviation gain of the objecting player of `Seed202R78Gen011FrontAK123`, in the continuation `c` and the profile `x`. -/
noncomputable def Seed202R78Gen011FrontAK123_D (_c1 c2 _c3 _c4 x1 _x2 x3 x4 : ℝ) : ℝ :=
  1 - 220 / 29 * x4 - 13 / 19 * x3 + 29993 / 4959 * x3 * x4 + 5 / 22 * x1 + 30909 / 4147 * x1 * x4 - 11612 / 2717 * x1 * x3 - 8082397 / 1527372 * x1 * x3 * x4 - c2 + c2 * x4 + c2 * x3 - c2 * x3 * x4 + c2 * x1 - c2 * x1 * x4 - c2 * x1 * x3 + c2 * x1 * x3 * x4

/-- The continuation drops out of the deviation gain at this profile: the weight it
carries is zero. Machine-written. -/
theorem Seed202R78Gen011FrontAK123_z_holds :
    Seed202R78Gen011FrontAK123_z 0 0 0 0 1 1 1 0 = 0 := by
  unfold Seed202R78Gen011FrontAK123_z
  norm_num

/-- Certificate `v1/front_a/seed202_r78_gen011/K123`: front [A], coalition {1,2,3}: the profile in which exactly these players quit outright is not a Nash equilibrium of the stage game G(c), for ANY continuation vector c. Player 2 is a member of the coalition who strictly gains by staying: the deviation gain D_2 of src/stage.jl is negative at the profile, while the stage-Nash conditions require it to be at least zero. The two conditions below are that deviation gain and the weight z_2(x) = prod_{j != i} (1 - x_j) with which the continuation enters it. D_i is affine in c_i with coefficient -z_i and involves no other c_j, so z_i = 0 at this profile makes the value a constant and the sign unconditional -- in particular the lone-quitter branch of case T, which needs c in W_0 and hence (R2), is not used here. Coefficients are the payoff entries, so substituting the point is a check about this game (docs/G3_MIXED_APS.md 12.15(b), 12.20).

Universally quantified over the continuation: the coalition's own
quitting drives the objector's continuation weight to zero, so the
sign below does not depend on what play would have been worth had
it gone on. Machine-written. -/
theorem Seed202R78Gen011FrontAK123 :
    ∀ c1 c2 c3 c4 : ℝ,
      Seed202R78Gen011FrontAK123_D c1 c2 c3 c4 1 1 1 0 < 0 := by
  intro c1 c2 c3 c4
  unfold Seed202R78Gen011FrontAK123_D
  norm_num

/-- Continuation weight of the objecting player at the profile of `Seed202R78Gen011FrontAK4`. -/
noncomputable def Seed202R78Gen011FrontAK4_z (_c1 _c2 _c3 _c4 _x1 x2 x3 x4 : ℝ) : ℝ :=
  1 - x4 - x3 + x3 * x4 - x2 + x2 * x4 + x2 * x3 - x2 * x3 * x4

/-- Deviation gain of the objecting player of `Seed202R78Gen011FrontAK4`, in the continuation `c` and the profile `x`. -/
noncomputable def Seed202R78Gen011FrontAK4_D (c1 _c2 _c3 _c4 _x1 x2 x3 x4 : ℝ) : ℝ :=
  1 + 7 / 51 * x4 - 147 / 17 * x3 + 17611 / 1632 * x3 * x4 - 13 / 3 * x2 + 2833 / 663 * x2 * x4 + 1613 / 102 * x2 * x3 - 1910917 / 109616 * x2 * x3 * x4 - c1 + c1 * x4 + c1 * x3 - c1 * x3 * x4 + c1 * x2 - c1 * x2 * x4 - c1 * x2 * x3 + c1 * x2 * x3 * x4

/-- The continuation drops out of the deviation gain at this profile: the weight it
carries is zero. Machine-written. -/
theorem Seed202R78Gen011FrontAK4_z_holds :
    Seed202R78Gen011FrontAK4_z 0 0 0 0 0 0 0 1 = 0 := by
  unfold Seed202R78Gen011FrontAK4_z
  norm_num

/-- Certificate `v1/front_a/seed202_r78_gen011/K4`: front [A], coalition {4}: the profile in which exactly these players quit outright is not a Nash equilibrium of the stage game G(c), for ANY continuation vector c. Player 1 is a stayer who strictly gains by quitting: the deviation gain D_1 of src/stage.jl is positive at the profile, while the stage-Nash conditions require it to be at most zero. The two conditions below are that deviation gain and the weight z_1(x) = prod_{j != i} (1 - x_j) with which the continuation enters it. D_i is affine in c_i with coefficient -z_i and involves no other c_j, so z_i = 0 at this profile makes the value a constant and the sign unconditional -- in particular the lone-quitter branch of case T, which needs c in W_0 and hence (R2), is not used here. Coefficients are the payoff entries, so substituting the point is a check about this game (docs/G3_MIXED_APS.md 12.15(b), 12.20).

Universally quantified over the continuation: the coalition's own
quitting drives the objector's continuation weight to zero, so the
sign below does not depend on what play would have been worth had
it gone on. Machine-written. -/
theorem Seed202R78Gen011FrontAK4 :
    ∀ c1 c2 c3 c4 : ℝ,
      0 < Seed202R78Gen011FrontAK4_D c1 c2 c3 c4 0 0 0 1 := by
  intro c1 c2 c3 c4
  unfold Seed202R78Gen011FrontAK4_D
  norm_num

/-- Continuation weight of the objecting player at the profile of `Seed202R78Gen011FrontAK14`. -/
noncomputable def Seed202R78Gen011FrontAK14_z (_c1 _c2 _c3 _c4 x1 _x2 x3 x4 : ℝ) : ℝ :=
  1 - x4 - x3 + x3 * x4 - x1 + x1 * x4 + x1 * x3 - x1 * x3 * x4

/-- Deviation gain of the objecting player of `Seed202R78Gen011FrontAK14`, in the continuation `c` and the profile `x`. -/
noncomputable def Seed202R78Gen011FrontAK14_D (_c1 c2 _c3 _c4 x1 _x2 x3 x4 : ℝ) : ℝ :=
  1 - 220 / 29 * x4 - 13 / 19 * x3 + 29993 / 4959 * x3 * x4 + 5 / 22 * x1 + 30909 / 4147 * x1 * x4 - 11612 / 2717 * x1 * x3 - 8082397 / 1527372 * x1 * x3 * x4 - c2 + c2 * x4 + c2 * x3 - c2 * x3 * x4 + c2 * x1 - c2 * x1 * x4 - c2 * x1 * x3 + c2 * x1 * x3 * x4

/-- The continuation drops out of the deviation gain at this profile: the weight it
carries is zero. Machine-written. -/
theorem Seed202R78Gen011FrontAK14_z_holds :
    Seed202R78Gen011FrontAK14_z 0 0 0 0 1 0 0 1 = 0 := by
  unfold Seed202R78Gen011FrontAK14_z
  norm_num

/-- Certificate `v1/front_a/seed202_r78_gen011/K14`: front [A], coalition {1,4}: the profile in which exactly these players quit outright is not a Nash equilibrium of the stage game G(c), for ANY continuation vector c. Player 2 is a stayer who strictly gains by quitting: the deviation gain D_2 of src/stage.jl is positive at the profile, while the stage-Nash conditions require it to be at most zero. The two conditions below are that deviation gain and the weight z_2(x) = prod_{j != i} (1 - x_j) with which the continuation enters it. D_i is affine in c_i with coefficient -z_i and involves no other c_j, so z_i = 0 at this profile makes the value a constant and the sign unconditional -- in particular the lone-quitter branch of case T, which needs c in W_0 and hence (R2), is not used here. Coefficients are the payoff entries, so substituting the point is a check about this game (docs/G3_MIXED_APS.md 12.15(b), 12.20).

Universally quantified over the continuation: the coalition's own
quitting drives the objector's continuation weight to zero, so the
sign below does not depend on what play would have been worth had
it gone on. Machine-written. -/
theorem Seed202R78Gen011FrontAK14 :
    ∀ c1 c2 c3 c4 : ℝ,
      0 < Seed202R78Gen011FrontAK14_D c1 c2 c3 c4 1 0 0 1 := by
  intro c1 c2 c3 c4
  unfold Seed202R78Gen011FrontAK14_D
  norm_num

/-- Continuation weight of the objecting player at the profile of `Seed202R78Gen011FrontAK24`. -/
noncomputable def Seed202R78Gen011FrontAK24_z (_c1 _c2 _c3 _c4 _x1 x2 x3 x4 : ℝ) : ℝ :=
  1 - x4 - x3 + x3 * x4 - x2 + x2 * x4 + x2 * x3 - x2 * x3 * x4

/-- Deviation gain of the objecting player of `Seed202R78Gen011FrontAK24`, in the continuation `c` and the profile `x`. -/
noncomputable def Seed202R78Gen011FrontAK24_D (c1 _c2 _c3 _c4 _x1 x2 x3 x4 : ℝ) : ℝ :=
  1 + 7 / 51 * x4 - 147 / 17 * x3 + 17611 / 1632 * x3 * x4 - 13 / 3 * x2 + 2833 / 663 * x2 * x4 + 1613 / 102 * x2 * x3 - 1910917 / 109616 * x2 * x3 * x4 - c1 + c1 * x4 + c1 * x3 - c1 * x3 * x4 + c1 * x2 - c1 * x2 * x4 - c1 * x2 * x3 + c1 * x2 * x3 * x4

/-- The continuation drops out of the deviation gain at this profile: the weight it
carries is zero. Machine-written. -/
theorem Seed202R78Gen011FrontAK24_z_holds :
    Seed202R78Gen011FrontAK24_z 0 0 0 0 0 1 0 1 = 0 := by
  unfold Seed202R78Gen011FrontAK24_z
  norm_num

/-- Certificate `v1/front_a/seed202_r78_gen011/K24`: front [A], coalition {2,4}: the profile in which exactly these players quit outright is not a Nash equilibrium of the stage game G(c), for ANY continuation vector c. Player 1 is a stayer who strictly gains by quitting: the deviation gain D_1 of src/stage.jl is positive at the profile, while the stage-Nash conditions require it to be at most zero. The two conditions below are that deviation gain and the weight z_1(x) = prod_{j != i} (1 - x_j) with which the continuation enters it. D_i is affine in c_i with coefficient -z_i and involves no other c_j, so z_i = 0 at this profile makes the value a constant and the sign unconditional -- in particular the lone-quitter branch of case T, which needs c in W_0 and hence (R2), is not used here. Coefficients are the payoff entries, so substituting the point is a check about this game (docs/G3_MIXED_APS.md 12.15(b), 12.20).

Universally quantified over the continuation: the coalition's own
quitting drives the objector's continuation weight to zero, so the
sign below does not depend on what play would have been worth had
it gone on. Machine-written. -/
theorem Seed202R78Gen011FrontAK24 :
    ∀ c1 c2 c3 c4 : ℝ,
      0 < Seed202R78Gen011FrontAK24_D c1 c2 c3 c4 0 1 0 1 := by
  intro c1 c2 c3 c4
  unfold Seed202R78Gen011FrontAK24_D
  norm_num

/-- Continuation weight of the objecting player at the profile of `Seed202R78Gen011FrontAK124`. -/
noncomputable def Seed202R78Gen011FrontAK124_z (_c1 _c2 _c3 _c4 x1 x2 _x3 x4 : ℝ) : ℝ :=
  1 - x4 - x2 + x2 * x4 - x1 + x1 * x4 + x1 * x2 - x1 * x2 * x4

/-- Deviation gain of the objecting player of `Seed202R78Gen011FrontAK124`, in the continuation `c` and the profile `x`. -/
noncomputable def Seed202R78Gen011FrontAK124_D (_c1 _c2 c3 _c4 x1 x2 _x3 x4 : ℝ) : ℝ :=
  1 - 91 / 12 * x4 + 79 / 19 * x2 + 2201 / 1824 * x2 * x4 - 201 / 31 * x1 + 36755 / 2604 * x1 * x4 + 3137 / 589 * x1 * x2 - 37974327 / 3826144 * x1 * x2 * x4 - c3 + c3 * x4 + c3 * x2 - c3 * x2 * x4 + c3 * x1 - c3 * x1 * x4 - c3 * x1 * x2 + c3 * x1 * x2 * x4

/-- The continuation drops out of the deviation gain at this profile: the weight it
carries is zero. Machine-written. -/
theorem Seed202R78Gen011FrontAK124_z_holds :
    Seed202R78Gen011FrontAK124_z 0 0 0 0 1 1 0 1 = 0 := by
  unfold Seed202R78Gen011FrontAK124_z
  norm_num

/-- Certificate `v1/front_a/seed202_r78_gen011/K124`: front [A], coalition {1,2,4}: the profile in which exactly these players quit outright is not a Nash equilibrium of the stage game G(c), for ANY continuation vector c. Player 3 is a stayer who strictly gains by quitting: the deviation gain D_3 of src/stage.jl is positive at the profile, while the stage-Nash conditions require it to be at most zero. The two conditions below are that deviation gain and the weight z_3(x) = prod_{j != i} (1 - x_j) with which the continuation enters it. D_i is affine in c_i with coefficient -z_i and involves no other c_j, so z_i = 0 at this profile makes the value a constant and the sign unconditional -- in particular the lone-quitter branch of case T, which needs c in W_0 and hence (R2), is not used here. Coefficients are the payoff entries, so substituting the point is a check about this game (docs/G3_MIXED_APS.md 12.15(b), 12.20).

Universally quantified over the continuation: the coalition's own
quitting drives the objector's continuation weight to zero, so the
sign below does not depend on what play would have been worth had
it gone on. Machine-written. -/
theorem Seed202R78Gen011FrontAK124 :
    ∀ c1 c2 c3 c4 : ℝ,
      0 < Seed202R78Gen011FrontAK124_D c1 c2 c3 c4 1 1 0 1 := by
  intro c1 c2 c3 c4
  unfold Seed202R78Gen011FrontAK124_D
  norm_num

/-- Continuation weight of the objecting player at the profile of `Seed202R78Gen011FrontAK34`. -/
noncomputable def Seed202R78Gen011FrontAK34_z (_c1 _c2 _c3 _c4 _x1 x2 x3 x4 : ℝ) : ℝ :=
  1 - x4 - x3 + x3 * x4 - x2 + x2 * x4 + x2 * x3 - x2 * x3 * x4

/-- Deviation gain of the objecting player of `Seed202R78Gen011FrontAK34`, in the continuation `c` and the profile `x`. -/
noncomputable def Seed202R78Gen011FrontAK34_D (c1 _c2 _c3 _c4 _x1 x2 x3 x4 : ℝ) : ℝ :=
  1 + 7 / 51 * x4 - 147 / 17 * x3 + 17611 / 1632 * x3 * x4 - 13 / 3 * x2 + 2833 / 663 * x2 * x4 + 1613 / 102 * x2 * x3 - 1910917 / 109616 * x2 * x3 * x4 - c1 + c1 * x4 + c1 * x3 - c1 * x3 * x4 + c1 * x2 - c1 * x2 * x4 - c1 * x2 * x3 + c1 * x2 * x3 * x4

/-- The continuation drops out of the deviation gain at this profile: the weight it
carries is zero. Machine-written. -/
theorem Seed202R78Gen011FrontAK34_z_holds :
    Seed202R78Gen011FrontAK34_z 0 0 0 0 0 0 1 1 = 0 := by
  unfold Seed202R78Gen011FrontAK34_z
  norm_num

/-- Certificate `v1/front_a/seed202_r78_gen011/K34`: front [A], coalition {3,4}: the profile in which exactly these players quit outright is not a Nash equilibrium of the stage game G(c), for ANY continuation vector c. Player 1 is a stayer who strictly gains by quitting: the deviation gain D_1 of src/stage.jl is positive at the profile, while the stage-Nash conditions require it to be at most zero. The two conditions below are that deviation gain and the weight z_1(x) = prod_{j != i} (1 - x_j) with which the continuation enters it. D_i is affine in c_i with coefficient -z_i and involves no other c_j, so z_i = 0 at this profile makes the value a constant and the sign unconditional -- in particular the lone-quitter branch of case T, which needs c in W_0 and hence (R2), is not used here. Coefficients are the payoff entries, so substituting the point is a check about this game (docs/G3_MIXED_APS.md 12.15(b), 12.20).

Universally quantified over the continuation: the coalition's own
quitting drives the objector's continuation weight to zero, so the
sign below does not depend on what play would have been worth had
it gone on. Machine-written. -/
theorem Seed202R78Gen011FrontAK34 :
    ∀ c1 c2 c3 c4 : ℝ,
      0 < Seed202R78Gen011FrontAK34_D c1 c2 c3 c4 0 0 1 1 := by
  intro c1 c2 c3 c4
  unfold Seed202R78Gen011FrontAK34_D
  norm_num

/-- Continuation weight of the objecting player at the profile of `Seed202R78Gen011FrontAK134`. -/
noncomputable def Seed202R78Gen011FrontAK134_z (_c1 _c2 _c3 _c4 x1 x2 x3 _x4 : ℝ) : ℝ :=
  1 - x3 - x2 + x2 * x3 - x1 + x1 * x3 + x1 * x2 - x1 * x2 * x3

/-- Deviation gain of the objecting player of `Seed202R78Gen011FrontAK134`, in the continuation `c` and the profile `x`. -/
noncomputable def Seed202R78Gen011FrontAK134_D (_c1 _c2 _c3 c4 x1 x2 x3 _x4 : ℝ) : ℝ :=
  1 + 71 / 19 * x3 - 10 / 9 * x2 - 196339 / 42408 * x2 * x3 - 61 / 12 * x1 - 6835 / 5244 * x1 * x3 + 9377 / 1800 * x1 * x2 + 281168303 / 134115300 * x1 * x2 * x3 - c4 + c4 * x3 + c4 * x2 - c4 * x2 * x3 + c4 * x1 - c4 * x1 * x3 - c4 * x1 * x2 + c4 * x1 * x2 * x3

/-- The continuation drops out of the deviation gain at this profile: the weight it
carries is zero. Machine-written. -/
theorem Seed202R78Gen011FrontAK134_z_holds :
    Seed202R78Gen011FrontAK134_z 0 0 0 0 1 0 1 1 = 0 := by
  unfold Seed202R78Gen011FrontAK134_z
  norm_num

/-- Certificate `v1/front_a/seed202_r78_gen011/K134`: front [A], coalition {1,3,4}: the profile in which exactly these players quit outright is not a Nash equilibrium of the stage game G(c), for ANY continuation vector c. Player 4 is a member of the coalition who strictly gains by staying: the deviation gain D_4 of src/stage.jl is negative at the profile, while the stage-Nash conditions require it to be at least zero. The two conditions below are that deviation gain and the weight z_4(x) = prod_{j != i} (1 - x_j) with which the continuation enters it. D_i is affine in c_i with coefficient -z_i and involves no other c_j, so z_i = 0 at this profile makes the value a constant and the sign unconditional -- in particular the lone-quitter branch of case T, which needs c in W_0 and hence (R2), is not used here. Coefficients are the payoff entries, so substituting the point is a check about this game (docs/G3_MIXED_APS.md 12.15(b), 12.20).

Universally quantified over the continuation: the coalition's own
quitting drives the objector's continuation weight to zero, so the
sign below does not depend on what play would have been worth had
it gone on. Machine-written. -/
theorem Seed202R78Gen011FrontAK134 :
    ∀ c1 c2 c3 c4 : ℝ,
      Seed202R78Gen011FrontAK134_D c1 c2 c3 c4 1 0 1 1 < 0 := by
  intro c1 c2 c3 c4
  unfold Seed202R78Gen011FrontAK134_D
  norm_num

/-- Continuation weight of the objecting player at the profile of `Seed202R78Gen011FrontAK234`. -/
noncomputable def Seed202R78Gen011FrontAK234_z (_c1 _c2 _c3 _c4 _x1 x2 x3 x4 : ℝ) : ℝ :=
  1 - x4 - x3 + x3 * x4 - x2 + x2 * x4 + x2 * x3 - x2 * x3 * x4

/-- Deviation gain of the objecting player of `Seed202R78Gen011FrontAK234`, in the continuation `c` and the profile `x`. -/
noncomputable def Seed202R78Gen011FrontAK234_D (c1 _c2 _c3 _c4 _x1 x2 x3 x4 : ℝ) : ℝ :=
  1 + 7 / 51 * x4 - 147 / 17 * x3 + 17611 / 1632 * x3 * x4 - 13 / 3 * x2 + 2833 / 663 * x2 * x4 + 1613 / 102 * x2 * x3 - 1910917 / 109616 * x2 * x3 * x4 - c1 + c1 * x4 + c1 * x3 - c1 * x3 * x4 + c1 * x2 - c1 * x2 * x4 - c1 * x2 * x3 + c1 * x2 * x3 * x4

/-- The continuation drops out of the deviation gain at this profile: the weight it
carries is zero. Machine-written. -/
theorem Seed202R78Gen011FrontAK234_z_holds :
    Seed202R78Gen011FrontAK234_z 0 0 0 0 0 1 1 1 = 0 := by
  unfold Seed202R78Gen011FrontAK234_z
  norm_num

/-- Certificate `v1/front_a/seed202_r78_gen011/K234`: front [A], coalition {2,3,4}: the profile in which exactly these players quit outright is not a Nash equilibrium of the stage game G(c), for ANY continuation vector c. Player 1 is a stayer who strictly gains by quitting: the deviation gain D_1 of src/stage.jl is positive at the profile, while the stage-Nash conditions require it to be at most zero. The two conditions below are that deviation gain and the weight z_1(x) = prod_{j != i} (1 - x_j) with which the continuation enters it. D_i is affine in c_i with coefficient -z_i and involves no other c_j, so z_i = 0 at this profile makes the value a constant and the sign unconditional -- in particular the lone-quitter branch of case T, which needs c in W_0 and hence (R2), is not used here. Coefficients are the payoff entries, so substituting the point is a check about this game (docs/G3_MIXED_APS.md 12.15(b), 12.20).

Universally quantified over the continuation: the coalition's own
quitting drives the objector's continuation weight to zero, so the
sign below does not depend on what play would have been worth had
it gone on. Machine-written. -/
theorem Seed202R78Gen011FrontAK234 :
    ∀ c1 c2 c3 c4 : ℝ,
      0 < Seed202R78Gen011FrontAK234_D c1 c2 c3 c4 0 1 1 1 := by
  intro c1 c2 c3 c4
  unfold Seed202R78Gen011FrontAK234_D
  norm_num

/-- Continuation weight of the objecting player at the profile of `Seed202R78Gen011FrontAK1234`. -/
noncomputable def Seed202R78Gen011FrontAK1234_z (_c1 _c2 _c3 _c4 x1 _x2 x3 x4 : ℝ) : ℝ :=
  1 - x4 - x3 + x3 * x4 - x1 + x1 * x4 + x1 * x3 - x1 * x3 * x4

/-- Deviation gain of the objecting player of `Seed202R78Gen011FrontAK1234`, in the continuation `c` and the profile `x`. -/
noncomputable def Seed202R78Gen011FrontAK1234_D (_c1 c2 _c3 _c4 x1 _x2 x3 x4 : ℝ) : ℝ :=
  1 - 220 / 29 * x4 - 13 / 19 * x3 + 29993 / 4959 * x3 * x4 + 5 / 22 * x1 + 30909 / 4147 * x1 * x4 - 11612 / 2717 * x1 * x3 - 8082397 / 1527372 * x1 * x3 * x4 - c2 + c2 * x4 + c2 * x3 - c2 * x3 * x4 + c2 * x1 - c2 * x1 * x4 - c2 * x1 * x3 + c2 * x1 * x3 * x4

/-- The continuation drops out of the deviation gain at this profile: the weight it
carries is zero. Machine-written. -/
theorem Seed202R78Gen011FrontAK1234_z_holds :
    Seed202R78Gen011FrontAK1234_z 0 0 0 0 1 1 1 1 = 0 := by
  unfold Seed202R78Gen011FrontAK1234_z
  norm_num

/-- Certificate `v1/front_a/seed202_r78_gen011/K1234`: front [A], coalition {1,2,3,4}: the profile in which exactly these players quit outright is not a Nash equilibrium of the stage game G(c), for ANY continuation vector c. Player 2 is a member of the coalition who strictly gains by staying: the deviation gain D_2 of src/stage.jl is negative at the profile, while the stage-Nash conditions require it to be at least zero. The two conditions below are that deviation gain and the weight z_2(x) = prod_{j != i} (1 - x_j) with which the continuation enters it. D_i is affine in c_i with coefficient -z_i and involves no other c_j, so z_i = 0 at this profile makes the value a constant and the sign unconditional -- in particular the lone-quitter branch of case T, which needs c in W_0 and hence (R2), is not used here. Coefficients are the payoff entries, so substituting the point is a check about this game (docs/G3_MIXED_APS.md 12.15(b), 12.20).

Universally quantified over the continuation: the coalition's own
quitting drives the objector's continuation weight to zero, so the
sign below does not depend on what play would have been worth had
it gone on. Machine-written. -/
theorem Seed202R78Gen011FrontAK1234 :
    ∀ c1 c2 c3 c4 : ℝ,
      Seed202R78Gen011FrontAK1234_D c1 c2 c3 c4 1 1 1 1 < 0 := by
  intro c1 c2 c3 c4
  unfold Seed202R78Gen011FrontAK1234_D
  norm_num
/-- Certificate identifiers in this batch. The `#guard` below turns
a silently dropped certificate into a compile error. -/
def batch01Ids : List String :=
  ["v1/front_a/seed202_r78_gen011/K1",
   "v1/front_a/seed202_r78_gen011/K2",
   "v1/front_a/seed202_r78_gen011/K12",
   "v1/front_a/seed202_r78_gen011/K3",
   "v1/front_a/seed202_r78_gen011/K13",
   "v1/front_a/seed202_r78_gen011/K23",
   "v1/front_a/seed202_r78_gen011/K123",
   "v1/front_a/seed202_r78_gen011/K4",
   "v1/front_a/seed202_r78_gen011/K14",
   "v1/front_a/seed202_r78_gen011/K24",
   "v1/front_a/seed202_r78_gen011/K124",
   "v1/front_a/seed202_r78_gen011/K34",
   "v1/front_a/seed202_r78_gen011/K134",
   "v1/front_a/seed202_r78_gen011/K234",
   "v1/front_a/seed202_r78_gen011/K1234"]

#guard batch01Ids.length = 15

end Quitting.FrontA
