-- GENERATED by code/julia/scripts/certificates/v0_from_recorded.jl — do not edit.
-- Regenerate and `git diff --exit-code` to prove the Lean corpus is a
-- pure function of the JSON certificates.

import Formal.Certificates.Prelude

set_option maxRecDepth 8000
set_option maxHeartbeats 1000000

namespace Quitting.V0


/-- Condition `quit_at_most_L` of `seed202_r78_gen011_minmax_lower_2`, with the sense the trace reads it in. The
certificate refutes the system in which all of them hold at once. -/
def seed202_r78_gen011_minmax_lower_2_f01 (x1 _x2 x3 x4 : ℝ) : Prop :=
  2654795 / 3145728 - 17 / 29 * x4 - 13 / 19 * x3 + 5198 / 4959 * x3 * x4 + 5 / 22 * x1 + 4519 / 4147 * x1 * x4 - 6178 / 2717 * x1 * x3 - 379135 / 218196 * x1 * x3 * x4 ≤ 0

/-- Condition `wait_at_most_L` of `seed202_r78_gen011_minmax_lower_2`, with the sense the trace reads it in. The
certificate refutes the system in which all of them hold at once. -/
def seed202_r78_gen011_minmax_lower_2_f02 (x1 _x2 x3 x4 : ℝ) : Prop :=
  21529163 / 3145728 * x4 - 490933 / 3145728 * x3 - 15237707 / 3145728 * x3 * x4 - 490933 / 3145728 * x1 - 214800697 / 34603008 * x1 * x4 + 6782389 / 3145728 * x1 * x3 + 274359685 / 80740352 * x1 * x3 * x4 ≤ 0

end Quitting.V0
