-- GENERATED by code/julia/scripts/certificates/v0_from_recorded.jl — do not edit.
-- Regenerate and `git diff --exit-code` to prove the Lean corpus is a
-- pure function of the JSON certificates.

import Formal.Certificates.Prelude
import Formal.Certificates.V0.Seed202R78Gen011MinmaxLower2.Defs
import Formal.Certificates.V0.Seed202R78Gen011MinmaxLower2.Part01

set_option maxRecDepth 8000
set_option maxHeartbeats 1000000

namespace Quitting.V0


/-- with L = 490933/3145728, no stationary punishment z of player 2 satisfies both a(z) <= L and b(z) <= L*q(z), so the smallest level w_2 admitting one exceeds L; and v^2 >= w_2 unconditionally (docs/V0_MINIMAX.md 2.1). Coordinate x2 is pinned to 0: the punishment is played by the other players.

Proved by the recorded subdivision of the box: every leaf carries one
condition that the Bernstein corner-basis expansion makes strictly
positive there. Machine-written. -/
theorem seed202_r78_gen011_minmax_lower_2
    (x1 x2 x3 x4 : ℝ)
    (hlo1 : (0 : ℝ) ≤ x1)
    (hhi1 : x1 ≤ (1 : ℝ))
    (hlo2 : (0 : ℝ) ≤ x2)
    (hhi2 : x2 ≤ (0 : ℝ))
    (hlo3 : (0 : ℝ) ≤ x3)
    (hhi3 : x3 ≤ (1 : ℝ))
    (hlo4 : (0 : ℝ) ≤ x4)
    (hhi4 : x4 ≤ (1 : ℝ))
    : ¬ (
      seed202_r78_gen011_minmax_lower_2_f01 x1 x2 x3 x4 ∧
      seed202_r78_gen011_minmax_lower_2_f02 x1 x2 x3 x4) := by
  rintro ⟨c1, c2⟩
  obtain rfl : x2 = (0 : ℝ) := le_antisymm hhi2 hlo2
  rcases le_total x1 (1 / 2 : ℝ) with hs1 | hs1
  · rcases le_total x3 (1 / 2 : ℝ) with hs2 | hs2
    · exact seed202_r78_gen011_minmax_lower_2_sub001 x1 x3 x4 hlo1 hs1 hlo3 hs2 hlo4 hhi4 c1
    · rcases le_total x4 (1 / 2 : ℝ) with hs3 | hs3
      · rcases le_total x1 (1 / 4 : ℝ) with hs4 | hs4
        · rcases le_total x3 (3 / 4 : ℝ) with hs5 | hs5
          · exact seed202_r78_gen011_minmax_lower_2_sub002 x1 x3 x4 hlo1 hs4 hs2 hs5 hlo4 hs3 c1 c2
          · rcases le_total x4 (1 / 4 : ℝ) with hs6 | hs6
            · rcases le_total x1 (1 / 8 : ℝ) with hs7 | hs7
              · rcases le_total x3 (7 / 8 : ℝ) with hs8 | hs8
                · exact seed202_r78_gen011_minmax_lower_2_sub003 x1 x3 x4 hlo1 hs7 hs5 hs8 hlo4 hs6 c1
                · rcases le_total x4 (1 / 8 : ℝ) with hs9 | hs9
                  · rcases le_total x1 (1 / 16 : ℝ) with hs10 | hs10
                    · exact seed202_r78_gen011_minmax_lower_2_sub004 x1 x3 x4 hlo1 hs10 hs8 hhi3 hlo4 hs9 c1
                    · rcases le_total x3 (15 / 16 : ℝ) with hs11 | hs11
                      · exact seed202_r78_gen011_minmax_lower_2_sub005 x1 x3 x4 hs10 hs7 hs8 hs11 hlo4 hs9 c1 c2
                      · rcases le_total x4 (1 / 16 : ℝ) with hs12 | hs12
                        · rcases le_total x1 (3 / 32 : ℝ) with hs13 | hs13
                          · rcases le_total x3 (31 / 32 : ℝ) with hs14 | hs14
                            · exact seed202_r78_gen011_minmax_lower_2_sub006 x1 x3 x4 hs10 hs13 hs11 hs14 hlo4 hs12 c1 c2
                            · exact seed202_r78_gen011_minmax_lower_2_sub007 x1 x3 x4 hs10 hs13 hs14 hhi3 hlo4 hs12 c1 c2
                          · exact seed202_r78_gen011_minmax_lower_2_sub008 x1 x3 x4 hs13 hs7 hs11 hhi3 hlo4 hs12 c2
                        · exact seed202_r78_gen011_minmax_lower_2_sub009 x1 x3 x4 hs10 hs7 hs11 hhi3 hs12 hs9 c2
                  · exact seed202_r78_gen011_minmax_lower_2_sub010 x1 x3 x4 hlo1 hs7 hs8 hhi3 hs9 hs6 c2
              · exact seed202_r78_gen011_minmax_lower_2_sub011 x1 x3 x4 hs7 hs4 hs5 hhi3 hlo4 hs6 c2
            · exact seed202_r78_gen011_minmax_lower_2_sub012 x1 x3 x4 hlo1 hs4 hs5 hhi3 hs6 hs3 c2
        · exact seed202_r78_gen011_minmax_lower_2_sub013 x1 x3 x4 hs4 hs1 hs2 hhi3 hlo4 hs3 c2
      · exact seed202_r78_gen011_minmax_lower_2_sub014 x1 x3 x4 hlo1 hs1 hs2 hhi3 hs3 hhi4 c2
  · exact seed202_r78_gen011_minmax_lower_2_sub015 x1 x3 x4 hs1 hhi1 hlo3 hhi3 hlo4 hhi4 c1 c2


/-- Certificate identifier proved in this module. The `#guard`
below turns a silently dropped certificate into a compile error. -/
def Seed202R78Gen011MinmaxLower2Ids : List String :=
  ["v1/v0/seed202_r78_gen011/minmax_lower_2"]

#guard Seed202R78Gen011MinmaxLower2Ids.length = 1

end Quitting.V0
