-- GENERATED by code/julia/scripts/certificates/v0_from_recorded.jl — do not edit.
-- Regenerate and `git diff --exit-code` to prove the Lean corpus is a
-- pure function of the JSON certificates.

import Formal.Certificates.Prelude
import Formal.Certificates.V0.Seed202R78Gen011MinmaxLower2.Defs

set_option maxRecDepth 8000
set_option maxHeartbeats 1000000

namespace Quitting.V0

theorem seed202_r78_gen011_minmax_lower_2_sub001
    (x1 x3 x4 : ℝ)
    (hlo1 : (0 : ℝ) ≤ x1)
    (hhi1 : x1 ≤ (1 / 2 : ℝ))
    (hlo3 : (0 : ℝ) ≤ x3)
    (hhi3 : x3 ≤ (1 / 2 : ℝ))
    (hlo4 : (0 : ℝ) ≤ x4)
    (hhi4 : x4 ≤ (1 : ℝ))
    (c1 : seed202_r78_gen011_minmax_lower_2_f01 x1 (0 : ℝ) x3 x4)
    : False := by
  simp only [seed202_r78_gen011_minmax_lower_2_f01] at c1
  -- `quit_at_most_L` ≥ 401790463 / 8546942976 > 0 on x1 ∈ [0, 1 / 2], x3 ∈ [0, 1 / 2], x4 ∈ [0, 1]
  have d1lo : (0:ℝ) ≤ x1 - 0 := sub_nonneg.mpr hlo1
  have d1hi : (0:ℝ) ≤ 1 / 2 - x1 := sub_nonneg.mpr hhi1
  have d3lo : (0:ℝ) ≤ x3 - 0 := sub_nonneg.mpr hlo3
  have d3hi : (0:ℝ) ≤ 1 / 2 - x3 := sub_nonneg.mpr hhi3
  have d4lo : (0:ℝ) ≤ x4 - 0 := sub_nonneg.mpr hlo4
  have d4hi : (0:ℝ) ≤ 1 - x4 := sub_nonneg.mpr hhi4
  linarith only [c1, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]

theorem seed202_r78_gen011_minmax_lower_2_sub002
    (x1 x3 x4 : ℝ)
    (hlo1 : (0 : ℝ) ≤ x1)
    (hhi1 : x1 ≤ (1 / 4 : ℝ))
    (hlo3 : (1 / 2 : ℝ) ≤ x3)
    (hhi3 : x3 ≤ (3 / 4 : ℝ))
    (hlo4 : (0 : ℝ) ≤ x4)
    (hhi4 : x4 ≤ (1 / 2 : ℝ))
    (c1 : seed202_r78_gen011_minmax_lower_2_f01 x1 (0 : ℝ) x3 x4)
    (c2 : seed202_r78_gen011_minmax_lower_2_f02 x1 (0 : ℝ) x3 x4)
    : False := by
  simp only [seed202_r78_gen011_minmax_lower_2_f01, seed202_r78_gen011_minmax_lower_2_f02] at c1 c2
  rcases le_total x4 (1 / 4 : ℝ) with hs1 | hs1
  · rcases le_total x1 (1 / 8 : ℝ) with hs2 | hs2
    · -- `quit_at_most_L` ≥ 1247991295 / 8546942976 > 0 on x1 ∈ [0, 1 / 8], x3 ∈ [1 / 2, 3 / 4], x4 ∈ [0, 1 / 4]
      have d1lo : (0:ℝ) ≤ x1 - 0 := sub_nonneg.mpr hlo1
      have d1hi : (0:ℝ) ≤ 1 / 8 - x1 := sub_nonneg.mpr hs2
      have d3lo : (0:ℝ) ≤ x3 - 1 / 2 := sub_nonneg.mpr hlo3
      have d3hi : (0:ℝ) ≤ 3 / 4 - x3 := sub_nonneg.mpr hhi3
      have d4lo : (0:ℝ) ≤ x4 - 0 := sub_nonneg.mpr hlo4
      have d4hi : (0:ℝ) ≤ 1 / 4 - x4 := sub_nonneg.mpr hs1
      linarith only [c1, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
    · -- `wait_at_most_L` ≥ 624353 / 16777216 > 0 on x1 ∈ [1 / 8, 1 / 4], x3 ∈ [1 / 2, 3 / 4], x4 ∈ [0, 1 / 4]
      have d1lo : (0:ℝ) ≤ x1 - 1 / 8 := sub_nonneg.mpr hs2
      have d1hi : (0:ℝ) ≤ 1 / 4 - x1 := sub_nonneg.mpr hhi1
      have d3lo : (0:ℝ) ≤ x3 - 1 / 2 := sub_nonneg.mpr hlo3
      have d3hi : (0:ℝ) ≤ 3 / 4 - x3 := sub_nonneg.mpr hhi3
      have d4lo : (0:ℝ) ≤ x4 - 0 := sub_nonneg.mpr hlo4
      have d4hi : (0:ℝ) ≤ 1 / 4 - x4 := sub_nonneg.mpr hs1
      linarith only [c2, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
  · -- `wait_at_most_L` ≥ 34512335 / 50331648 > 0 on x1 ∈ [0, 1 / 4], x3 ∈ [1 / 2, 3 / 4], x4 ∈ [1 / 4, 1 / 2]
    have d1lo : (0:ℝ) ≤ x1 - 0 := sub_nonneg.mpr hlo1
    have d1hi : (0:ℝ) ≤ 1 / 4 - x1 := sub_nonneg.mpr hhi1
    have d3lo : (0:ℝ) ≤ x3 - 1 / 2 := sub_nonneg.mpr hlo3
    have d3hi : (0:ℝ) ≤ 3 / 4 - x3 := sub_nonneg.mpr hhi3
    have d4lo : (0:ℝ) ≤ x4 - 1 / 4 := sub_nonneg.mpr hs1
    have d4hi : (0:ℝ) ≤ 1 / 2 - x4 := sub_nonneg.mpr hhi4
    linarith only [c2, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]

theorem seed202_r78_gen011_minmax_lower_2_sub003
    (x1 x3 x4 : ℝ)
    (hlo1 : (0 : ℝ) ≤ x1)
    (hhi1 : x1 ≤ (1 / 8 : ℝ))
    (hlo3 : (3 / 4 : ℝ) ≤ x3)
    (hhi3 : x3 ≤ (7 / 8 : ℝ))
    (hlo4 : (0 : ℝ) ≤ x4)
    (hhi4 : x4 ≤ (1 / 4 : ℝ))
    (c1 : seed202_r78_gen011_minmax_lower_2_f01 x1 (0 : ℝ) x3 x4)
    : False := by
  simp only [seed202_r78_gen011_minmax_lower_2_f01] at c1
  -- `quit_at_most_L` ≥ 213341695 / 8546942976 > 0 on x1 ∈ [0, 1 / 8], x3 ∈ [3 / 4, 7 / 8], x4 ∈ [0, 1 / 4]
  have d1lo : (0:ℝ) ≤ x1 - 0 := sub_nonneg.mpr hlo1
  have d1hi : (0:ℝ) ≤ 1 / 8 - x1 := sub_nonneg.mpr hhi1
  have d3lo : (0:ℝ) ≤ x3 - 3 / 4 := sub_nonneg.mpr hlo3
  have d3hi : (0:ℝ) ≤ 7 / 8 - x3 := sub_nonneg.mpr hhi3
  have d4lo : (0:ℝ) ≤ x4 - 0 := sub_nonneg.mpr hlo4
  have d4hi : (0:ℝ) ≤ 1 / 4 - x4 := sub_nonneg.mpr hhi4
  linarith only [c1, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]

theorem seed202_r78_gen011_minmax_lower_2_sub004
    (x1 x3 x4 : ℝ)
    (hlo1 : (0 : ℝ) ≤ x1)
    (hhi1 : x1 ≤ (1 / 16 : ℝ))
    (hlo3 : (7 / 8 : ℝ) ≤ x3)
    (hhi3 : x3 ≤ (1 : ℝ))
    (hlo4 : (0 : ℝ) ≤ x4)
    (hhi4 : x4 ≤ (1 / 8 : ℝ))
    (c1 : seed202_r78_gen011_minmax_lower_2_f01 x1 (0 : ℝ) x3 x4)
    : False := by
  simp only [seed202_r78_gen011_minmax_lower_2_f01] at c1
  -- `quit_at_most_L` ≥ 24720989 / 776994816 > 0 on x1 ∈ [0, 1 / 16], x3 ∈ [7 / 8, 1], x4 ∈ [0, 1 / 8]
  have d1lo : (0:ℝ) ≤ x1 - 0 := sub_nonneg.mpr hlo1
  have d1hi : (0:ℝ) ≤ 1 / 16 - x1 := sub_nonneg.mpr hhi1
  have d3lo : (0:ℝ) ≤ x3 - 7 / 8 := sub_nonneg.mpr hlo3
  have d3hi : (0:ℝ) ≤ 1 - x3 := sub_nonneg.mpr hhi3
  have d4lo : (0:ℝ) ≤ x4 - 0 := sub_nonneg.mpr hlo4
  have d4hi : (0:ℝ) ≤ 1 / 8 - x4 := sub_nonneg.mpr hhi4
  linarith only [c1, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]

theorem seed202_r78_gen011_minmax_lower_2_sub005
    (x1 x3 x4 : ℝ)
    (hlo1 : (1 / 16 : ℝ) ≤ x1)
    (hhi1 : x1 ≤ (1 / 8 : ℝ))
    (hlo3 : (7 / 8 : ℝ) ≤ x3)
    (hhi3 : x3 ≤ (15 / 16 : ℝ))
    (hlo4 : (0 : ℝ) ≤ x4)
    (hhi4 : x4 ≤ (1 / 8 : ℝ))
    (c1 : seed202_r78_gen011_minmax_lower_2_f01 x1 (0 : ℝ) x3 x4)
    (c2 : seed202_r78_gen011_minmax_lower_2_f02 x1 (0 : ℝ) x3 x4)
    : False := by
  simp only [seed202_r78_gen011_minmax_lower_2_f01, seed202_r78_gen011_minmax_lower_2_f02] at c1 c2
  rcases le_total x4 (1 / 16 : ℝ) with hs1 | hs1
  · rcases le_total x1 (3 / 32 : ℝ) with hs2 | hs2
    · -- `quit_at_most_L` ≥ 204678655 / 8546942976 > 0 on x1 ∈ [1 / 16, 3 / 32], x3 ∈ [7 / 8, 15 / 16], x4 ∈ [0, 1 / 16]
      have d1lo : (0:ℝ) ≤ x1 - 1 / 16 := sub_nonneg.mpr hlo1
      have d1hi : (0:ℝ) ≤ 3 / 32 - x1 := sub_nonneg.mpr hs2
      have d3lo : (0:ℝ) ≤ x3 - 7 / 8 := sub_nonneg.mpr hlo3
      have d3hi : (0:ℝ) ≤ 15 / 16 - x3 := sub_nonneg.mpr hhi3
      have d4lo : (0:ℝ) ≤ x4 - 0 := sub_nonneg.mpr hlo4
      have d4hi : (0:ℝ) ≤ 1 / 16 - x4 := sub_nonneg.mpr hs1
      linarith only [c1, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
    · -- `wait_at_most_L` ≥ 20678785 / 805306368 > 0 on x1 ∈ [3 / 32, 1 / 8], x3 ∈ [7 / 8, 15 / 16], x4 ∈ [0, 1 / 16]
      have d1lo : (0:ℝ) ≤ x1 - 3 / 32 := sub_nonneg.mpr hs2
      have d1hi : (0:ℝ) ≤ 1 / 8 - x1 := sub_nonneg.mpr hhi1
      have d3lo : (0:ℝ) ≤ x3 - 7 / 8 := sub_nonneg.mpr hlo3
      have d3hi : (0:ℝ) ≤ 15 / 16 - x3 := sub_nonneg.mpr hhi3
      have d4lo : (0:ℝ) ≤ x4 - 0 := sub_nonneg.mpr hlo4
      have d4hi : (0:ℝ) ≤ 1 / 16 - x4 := sub_nonneg.mpr hs1
      linarith only [c2, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
  · -- `wait_at_most_L` ≥ 101580751441 / 992137445376 > 0 on x1 ∈ [1 / 16, 1 / 8], x3 ∈ [7 / 8, 15 / 16], x4 ∈ [1 / 16, 1 / 8]
    have d1lo : (0:ℝ) ≤ x1 - 1 / 16 := sub_nonneg.mpr hlo1
    have d1hi : (0:ℝ) ≤ 1 / 8 - x1 := sub_nonneg.mpr hhi1
    have d3lo : (0:ℝ) ≤ x3 - 7 / 8 := sub_nonneg.mpr hlo3
    have d3hi : (0:ℝ) ≤ 15 / 16 - x3 := sub_nonneg.mpr hhi3
    have d4lo : (0:ℝ) ≤ x4 - 1 / 16 := sub_nonneg.mpr hs1
    have d4hi : (0:ℝ) ≤ 1 / 8 - x4 := sub_nonneg.mpr hhi4
    linarith only [c2, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]

theorem seed202_r78_gen011_minmax_lower_2_sub006
    (x1 x3 x4 : ℝ)
    (hlo1 : (1 / 16 : ℝ) ≤ x1)
    (hhi1 : x1 ≤ (3 / 32 : ℝ))
    (hlo3 : (15 / 16 : ℝ) ≤ x3)
    (hhi3 : x3 ≤ (31 / 32 : ℝ))
    (hlo4 : (0 : ℝ) ≤ x4)
    (hhi4 : x4 ≤ (1 / 16 : ℝ))
    (c1 : seed202_r78_gen011_minmax_lower_2_f01 x1 (0 : ℝ) x3 x4)
    (c2 : seed202_r78_gen011_minmax_lower_2_f02 x1 (0 : ℝ) x3 x4)
    : False := by
  simp only [seed202_r78_gen011_minmax_lower_2_f01, seed202_r78_gen011_minmax_lower_2_f02] at c1 c2
  rcases le_total x4 (1 / 32 : ℝ) with hs1 | hs1
  · rcases le_total x1 (5 / 64 : ℝ) with hs2 | hs2
    · -- `quit_at_most_L` ≥ 228815359 / 8546942976 > 0 on x1 ∈ [1 / 16, 5 / 64], x3 ∈ [15 / 16, 31 / 32], x4 ∈ [0, 1 / 32]
      have d1lo : (0:ℝ) ≤ x1 - 1 / 16 := sub_nonneg.mpr hlo1
      have d1hi : (0:ℝ) ≤ 5 / 64 - x1 := sub_nonneg.mpr hs2
      have d3lo : (0:ℝ) ≤ x3 - 15 / 16 := sub_nonneg.mpr hlo3
      have d3hi : (0:ℝ) ≤ 31 / 32 - x3 := sub_nonneg.mpr hhi3
      have d4lo : (0:ℝ) ≤ x4 - 0 := sub_nonneg.mpr hlo4
      have d4hi : (0:ℝ) ≤ 1 / 32 - x4 := sub_nonneg.mpr hs1
      linarith only [c1, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
    · rcases le_total x3 (61 / 64 : ℝ) with hs3 | hs3
      · -- `quit_at_most_L` ≥ 84836863 / 8546942976 > 0 on x1 ∈ [5 / 64, 3 / 32], x3 ∈ [15 / 16, 61 / 64], x4 ∈ [0, 1 / 32]
        have d1lo : (0:ℝ) ≤ x1 - 5 / 64 := sub_nonneg.mpr hs2
        have d1hi : (0:ℝ) ≤ 3 / 32 - x1 := sub_nonneg.mpr hhi1
        have d3lo : (0:ℝ) ≤ x3 - 15 / 16 := sub_nonneg.mpr hlo3
        have d3hi : (0:ℝ) ≤ 61 / 64 - x3 := sub_nonneg.mpr hs3
        have d4lo : (0:ℝ) ≤ x4 - 0 := sub_nonneg.mpr hlo4
        have d4hi : (0:ℝ) ≤ 1 / 32 - x4 := sub_nonneg.mpr hs1
        linarith only [c1, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
      · rcases le_total x4 (1 / 64 : ℝ) with hs4 | hs4
        · rcases le_total x1 (11 / 128 : ℝ) with hs5 | hs5
          · -- `quit_at_most_L` ≥ 8809565 / 776994816 > 0 on x1 ∈ [5 / 64, 11 / 128], x3 ∈ [61 / 64, 31 / 32], x4 ∈ [0, 1 / 64]
            have d1lo : (0:ℝ) ≤ x1 - 5 / 64 := sub_nonneg.mpr hs2
            have d1hi : (0:ℝ) ≤ 11 / 128 - x1 := sub_nonneg.mpr hs5
            have d3lo : (0:ℝ) ≤ x3 - 61 / 64 := sub_nonneg.mpr hs3
            have d3hi : (0:ℝ) ≤ 31 / 32 - x3 := sub_nonneg.mpr hhi3
            have d4lo : (0:ℝ) ≤ x4 - 0 := sub_nonneg.mpr hlo4
            have d4hi : (0:ℝ) ≤ 1 / 64 - x4 := sub_nonneg.mpr hs4
            linarith only [c1, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
          · -- `wait_at_most_L` ≥ 372161323 / 25769803776 > 0 on x1 ∈ [11 / 128, 3 / 32], x3 ∈ [61 / 64, 31 / 32], x4 ∈ [0, 1 / 64]
            have d1lo : (0:ℝ) ≤ x1 - 11 / 128 := sub_nonneg.mpr hs5
            have d1hi : (0:ℝ) ≤ 3 / 32 - x1 := sub_nonneg.mpr hhi1
            have d3lo : (0:ℝ) ≤ x3 - 61 / 64 := sub_nonneg.mpr hs3
            have d3hi : (0:ℝ) ≤ 31 / 32 - x3 := sub_nonneg.mpr hhi3
            have d4lo : (0:ℝ) ≤ x4 - 0 := sub_nonneg.mpr hlo4
            have d4hi : (0:ℝ) ≤ 1 / 64 - x4 := sub_nonneg.mpr hs4
            linarith only [c2, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
        · -- `quit_at_most_L` ≥ 44656945 / 25640828928 > 0 on x1 ∈ [5 / 64, 3 / 32], x3 ∈ [61 / 64, 31 / 32], x4 ∈ [1 / 64, 1 / 32]
          have d1lo : (0:ℝ) ≤ x1 - 5 / 64 := sub_nonneg.mpr hs2
          have d1hi : (0:ℝ) ≤ 3 / 32 - x1 := sub_nonneg.mpr hhi1
          have d3lo : (0:ℝ) ≤ x3 - 61 / 64 := sub_nonneg.mpr hs3
          have d3hi : (0:ℝ) ≤ 31 / 32 - x3 := sub_nonneg.mpr hhi3
          have d4lo : (0:ℝ) ≤ x4 - 1 / 64 := sub_nonneg.mpr hs4
          have d4hi : (0:ℝ) ≤ 1 / 32 - x4 := sub_nonneg.mpr hs1
          linarith only [c1, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
  · -- `quit_at_most_L` ≥ 194328677 / 25640828928 > 0 on x1 ∈ [1 / 16, 3 / 32], x3 ∈ [15 / 16, 31 / 32], x4 ∈ [1 / 32, 1 / 16]
    have d1lo : (0:ℝ) ≤ x1 - 1 / 16 := sub_nonneg.mpr hlo1
    have d1hi : (0:ℝ) ≤ 3 / 32 - x1 := sub_nonneg.mpr hhi1
    have d3lo : (0:ℝ) ≤ x3 - 15 / 16 := sub_nonneg.mpr hlo3
    have d3hi : (0:ℝ) ≤ 31 / 32 - x3 := sub_nonneg.mpr hhi3
    have d4lo : (0:ℝ) ≤ x4 - 1 / 32 := sub_nonneg.mpr hs1
    have d4hi : (0:ℝ) ≤ 1 / 16 - x4 := sub_nonneg.mpr hhi4
    linarith only [c1, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]

theorem seed202_r78_gen011_minmax_lower_2_sub007
    (x1 x3 x4 : ℝ)
    (hlo1 : (1 / 16 : ℝ) ≤ x1)
    (hhi1 : x1 ≤ (3 / 32 : ℝ))
    (hlo3 : (31 / 32 : ℝ) ≤ x3)
    (hhi3 : x3 ≤ (1 : ℝ))
    (hlo4 : (0 : ℝ) ≤ x4)
    (hhi4 : x4 ≤ (1 / 16 : ℝ))
    (c1 : seed202_r78_gen011_minmax_lower_2_f01 x1 (0 : ℝ) x3 x4)
    (c2 : seed202_r78_gen011_minmax_lower_2_f02 x1 (0 : ℝ) x3 x4)
    : False := by
  simp only [seed202_r78_gen011_minmax_lower_2_f01, seed202_r78_gen011_minmax_lower_2_f02] at c1 c2
  rcases le_total x4 (1 / 32 : ℝ) with hs1 | hs1
  · rcases le_total x1 (5 / 64 : ℝ) with hs2 | hs2
    · rcases le_total x3 (63 / 64 : ℝ) with hs3 | hs3
      · -- `quit_at_most_L` ≥ 113718271 / 8546942976 > 0 on x1 ∈ [1 / 16, 5 / 64], x3 ∈ [31 / 32, 63 / 64], x4 ∈ [0, 1 / 32]
        have d1lo : (0:ℝ) ≤ x1 - 1 / 16 := sub_nonneg.mpr hlo1
        have d1hi : (0:ℝ) ≤ 5 / 64 - x1 := sub_nonneg.mpr hs2
        have d3lo : (0:ℝ) ≤ x3 - 31 / 32 := sub_nonneg.mpr hlo3
        have d3hi : (0:ℝ) ≤ 63 / 64 - x3 := sub_nonneg.mpr hs3
        have d4lo : (0:ℝ) ≤ x4 - 0 := sub_nonneg.mpr hlo4
        have d4hi : (0:ℝ) ≤ 1 / 32 - x4 := sub_nonneg.mpr hs1
        linarith only [c1, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
      · rcases le_total x4 (1 / 64 : ℝ) with hs4 | hs4
        · rcases le_total x1 (9 / 128 : ℝ) with hs5 | hs5
          · -- `quit_at_most_L` ≥ 12297821 / 776994816 > 0 on x1 ∈ [1 / 16, 9 / 128], x3 ∈ [63 / 64, 1], x4 ∈ [0, 1 / 64]
            have d1lo : (0:ℝ) ≤ x1 - 1 / 16 := sub_nonneg.mpr hlo1
            have d1hi : (0:ℝ) ≤ 9 / 128 - x1 := sub_nonneg.mpr hs5
            have d3lo : (0:ℝ) ≤ x3 - 63 / 64 := sub_nonneg.mpr hs3
            have d3hi : (0:ℝ) ≤ 1 - x3 := sub_nonneg.mpr hhi3
            have d4lo : (0:ℝ) ≤ x4 - 0 := sub_nonneg.mpr hlo4
            have d4hi : (0:ℝ) ≤ 1 / 64 - x4 := sub_nonneg.mpr hs4
            linarith only [c1, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
          · rcases le_total x3 (127 / 128 : ℝ) with hs6 | hs6
            · -- `quit_at_most_L` ≥ 56169727 / 8546942976 > 0 on x1 ∈ [9 / 128, 5 / 64], x3 ∈ [63 / 64, 127 / 128], x4 ∈ [0, 1 / 64]
              have d1lo : (0:ℝ) ≤ x1 - 9 / 128 := sub_nonneg.mpr hs5
              have d1hi : (0:ℝ) ≤ 5 / 64 - x1 := sub_nonneg.mpr hs2
              have d3lo : (0:ℝ) ≤ x3 - 63 / 64 := sub_nonneg.mpr hs3
              have d3hi : (0:ℝ) ≤ 127 / 128 - x3 := sub_nonneg.mpr hs6
              have d4lo : (0:ℝ) ≤ x4 - 0 := sub_nonneg.mpr hlo4
              have d4hi : (0:ℝ) ≤ 1 / 64 - x4 := sub_nonneg.mpr hs4
              linarith only [c1, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
            · rcases le_total x4 (1 / 128 : ℝ) with hs7 | hs7
              · rcases le_total x1 (19 / 256 : ℝ) with hs8 | hs8
                · -- `quit_at_most_L` ≥ 6086237 / 776994816 > 0 on x1 ∈ [9 / 128, 19 / 256], x3 ∈ [127 / 128, 1], x4 ∈ [0, 1 / 128]
                  have d1lo : (0:ℝ) ≤ x1 - 9 / 128 := sub_nonneg.mpr hs5
                  have d1hi : (0:ℝ) ≤ 19 / 256 - x1 := sub_nonneg.mpr hs8
                  have d3lo : (0:ℝ) ≤ x3 - 127 / 128 := sub_nonneg.mpr hs6
                  have d3hi : (0:ℝ) ≤ 1 - x3 := sub_nonneg.mpr hhi3
                  have d4lo : (0:ℝ) ≤ x4 - 0 := sub_nonneg.mpr hlo4
                  have d4hi : (0:ℝ) ≤ 1 / 128 - x4 := sub_nonneg.mpr hs7
                  linarith only [c1, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
                · rcases le_total x3 (255 / 256 : ℝ) with hs9 | hs9
                  · -- `quit_at_most_L` ≥ 27395455 / 8546942976 > 0 on x1 ∈ [19 / 256, 5 / 64], x3 ∈ [127 / 128, 255 / 256], x4 ∈ [0, 1 / 128]
                    have d1lo : (0:ℝ) ≤ x1 - 19 / 256 := sub_nonneg.mpr hs8
                    have d1hi : (0:ℝ) ≤ 5 / 64 - x1 := sub_nonneg.mpr hs2
                    have d3lo : (0:ℝ) ≤ x3 - 127 / 128 := sub_nonneg.mpr hs6
                    have d3hi : (0:ℝ) ≤ 255 / 256 - x3 := sub_nonneg.mpr hs9
                    have d4lo : (0:ℝ) ≤ x4 - 0 := sub_nonneg.mpr hlo4
                    have d4hi : (0:ℝ) ≤ 1 / 128 - x4 := sub_nonneg.mpr hs7
                    linarith only [c1, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
                  · rcases le_total x4 (1 / 256 : ℝ) with hs10 | hs10
                    · rcases le_total x1 (39 / 512 : ℝ) with hs11 | hs11
                      · -- `quit_at_most_L` ≥ 229265 / 59768832 > 0 on x1 ∈ [19 / 256, 39 / 512], x3 ∈ [255 / 256, 1], x4 ∈ [0, 1 / 256]
                        have d1lo : (0:ℝ) ≤ x1 - 19 / 256 := sub_nonneg.mpr hs8
                        have d1hi : (0:ℝ) ≤ 39 / 512 - x1 := sub_nonneg.mpr hs11
                        have d3lo : (0:ℝ) ≤ x3 - 255 / 256 := sub_nonneg.mpr hs9
                        have d3hi : (0:ℝ) ≤ 1 - x3 := sub_nonneg.mpr hhi3
                        have d4lo : (0:ℝ) ≤ x4 - 0 := sub_nonneg.mpr hlo4
                        have d4hi : (0:ℝ) ≤ 1 / 256 - x4 := sub_nonneg.mpr hs10
                        linarith only [c1, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
                      · rcases le_total x3 (511 / 512 : ℝ) with hs12 | hs12
                        · -- `quit_at_most_L` ≥ 13008319 / 8546942976 > 0 on x1 ∈ [39 / 512, 5 / 64], x3 ∈ [255 / 256, 511 / 512], x4 ∈ [0, 1 / 256]
                          have d1lo : (0:ℝ) ≤ x1 - 39 / 512 := sub_nonneg.mpr hs11
                          have d1hi : (0:ℝ) ≤ 5 / 64 - x1 := sub_nonneg.mpr hs2
                          have d3lo : (0:ℝ) ≤ x3 - 255 / 256 := sub_nonneg.mpr hs9
                          have d3hi : (0:ℝ) ≤ 511 / 512 - x3 := sub_nonneg.mpr hs12
                          have d4lo : (0:ℝ) ≤ x4 - 0 := sub_nonneg.mpr hlo4
                          have d4hi : (0:ℝ) ≤ 1 / 256 - x4 := sub_nonneg.mpr hs10
                          linarith only [c1, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
                        · rcases le_total x4 (1 / 512 : ℝ) with hs13 | hs13
                          · rcases le_total x1 (79 / 1024 : ℝ) with hs14 | hs14
                            · -- `quit_at_most_L` ≥ 1427549 / 776994816 > 0 on x1 ∈ [39 / 512, 79 / 1024], x3 ∈ [511 / 512, 1], x4 ∈ [0, 1 / 512]
                              have d1lo : (0:ℝ) ≤ x1 - 39 / 512 := sub_nonneg.mpr hs11
                              have d1hi : (0:ℝ) ≤ 79 / 1024 - x1 := sub_nonneg.mpr hs14
                              have d3lo : (0:ℝ) ≤ x3 - 511 / 512 := sub_nonneg.mpr hs12
                              have d3hi : (0:ℝ) ≤ 1 - x3 := sub_nonneg.mpr hhi3
                              have d4lo : (0:ℝ) ≤ x4 - 0 := sub_nonneg.mpr hlo4
                              have d4hi : (0:ℝ) ≤ 1 / 512 - x4 := sub_nonneg.mpr hs13
                              linarith only [c1, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
                            · rcases le_total x3 (1023 / 1024 : ℝ) with hs15 | hs15
                              · -- `quit_at_most_L` ≥ 5814751 / 8546942976 > 0 on x1 ∈ [79 / 1024, 5 / 64], x3 ∈ [511 / 512, 1023 / 1024], x4 ∈ [0, 1 / 512]
                                have d1lo : (0:ℝ) ≤ x1 - 79 / 1024 := sub_nonneg.mpr hs14
                                have d1hi : (0:ℝ) ≤ 5 / 64 - x1 := sub_nonneg.mpr hs2
                                have d3lo : (0:ℝ) ≤ x3 - 511 / 512 := sub_nonneg.mpr hs12
                                have d3hi : (0:ℝ) ≤ 1023 / 1024 - x3 := sub_nonneg.mpr hs15
                                have d4lo : (0:ℝ) ≤ x4 - 0 := sub_nonneg.mpr hlo4
                                have d4hi : (0:ℝ) ≤ 1 / 512 - x4 := sub_nonneg.mpr hs13
                                linarith only [c1, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
                              · rcases le_total x4 (1 / 1024 : ℝ) with hs16 | hs16
                                · rcases le_total x1 (159 / 2048 : ℝ) with hs17 | hs17
                                  · -- `quit_at_most_L` ≥ 651101 / 776994816 > 0 on x1 ∈ [79 / 1024, 159 / 2048], x3 ∈ [1023 / 1024, 1], x4 ∈ [0, 1 / 1024]
                                    have d1lo : (0:ℝ) ≤ x1 - 79 / 1024 := sub_nonneg.mpr hs14
                                    have d1hi : (0:ℝ) ≤ 159 / 2048 - x1 := sub_nonneg.mpr hs17
                                    have d3lo : (0:ℝ) ≤ x3 - 1023 / 1024 := sub_nonneg.mpr hs15
                                    have d3hi : (0:ℝ) ≤ 1 - x3 := sub_nonneg.mpr hhi3
                                    have d4lo : (0:ℝ) ≤ x4 - 0 := sub_nonneg.mpr hlo4
                                    have d4hi : (0:ℝ) ≤ 1 / 1024 - x4 := sub_nonneg.mpr hs16
                                    linarith only [c1, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
                                  · rcases le_total x3 (2047 / 2048 : ℝ) with hs18 | hs18
                                    · -- `quit_at_most_L` ≥ 2217967 / 8546942976 > 0 on x1 ∈ [159 / 2048, 5 / 64], x3 ∈ [1023 / 1024, 2047 / 2048], x4 ∈ [0, 1 / 1024]
                                      have d1lo : (0:ℝ) ≤ x1 - 159 / 2048 := sub_nonneg.mpr hs17
                                      have d1hi : (0:ℝ) ≤ 5 / 64 - x1 := sub_nonneg.mpr hs2
                                      have d3lo : (0:ℝ) ≤ x3 - 1023 / 1024 := sub_nonneg.mpr hs15
                                      have d3hi : (0:ℝ) ≤ 2047 / 2048 - x3 := sub_nonneg.mpr hs18
                                      have d4lo : (0:ℝ) ≤ x4 - 0 := sub_nonneg.mpr hlo4
                                      have d4hi : (0:ℝ) ≤ 1 / 1024 - x4 := sub_nonneg.mpr hs16
                                      linarith only [c1, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
                                    · rcases le_total x4 (1 / 2048 : ℝ) with hs19 | hs19
                                      · rcases le_total x1 (319 / 4096 : ℝ) with hs20 | hs20
                                        · -- `quit_at_most_L` ≥ 262877 / 776994816 > 0 on x1 ∈ [159 / 2048, 319 / 4096], x3 ∈ [2047 / 2048, 1], x4 ∈ [0, 1 / 2048]
                                          have d1lo : (0:ℝ) ≤ x1 - 159 / 2048 := sub_nonneg.mpr hs17
                                          have d1hi : (0:ℝ) ≤ 319 / 4096 - x1 := sub_nonneg.mpr hs20
                                          have d3lo : (0:ℝ) ≤ x3 - 2047 / 2048 := sub_nonneg.mpr hs18
                                          have d3hi : (0:ℝ) ≤ 1 - x3 := sub_nonneg.mpr hhi3
                                          have d4lo : (0:ℝ) ≤ x4 - 0 := sub_nonneg.mpr hlo4
                                          have d4hi : (0:ℝ) ≤ 1 / 2048 - x4 := sub_nonneg.mpr hs19
                                          linarith only [c1, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
                                        · rcases le_total x3 (4095 / 4096 : ℝ) with hs21 | hs21
                                          · -- `quit_at_most_L` ≥ 32275 / 657457152 > 0 on x1 ∈ [319 / 4096, 5 / 64], x3 ∈ [2047 / 2048, 4095 / 4096], x4 ∈ [0, 1 / 2048]
                                            have d1lo : (0:ℝ) ≤ x1 - 319 / 4096 := sub_nonneg.mpr hs20
                                            have d1hi : (0:ℝ) ≤ 5 / 64 - x1 := sub_nonneg.mpr hs2
                                            have d3lo : (0:ℝ) ≤ x3 - 2047 / 2048 := sub_nonneg.mpr hs18
                                            have d3hi : (0:ℝ) ≤ 4095 / 4096 - x3 := sub_nonneg.mpr hs21
                                            have d4lo : (0:ℝ) ≤ x4 - 0 := sub_nonneg.mpr hlo4
                                            have d4hi : (0:ℝ) ≤ 1 / 2048 - x4 := sub_nonneg.mpr hs19
                                            linarith only [c1, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
                                          · rcases le_total x4 (1 / 4096 : ℝ) with hs22 | hs22
                                            · rcases le_total x1 (639 / 8192 : ℝ) with hs23 | hs23
                                              · -- `quit_at_most_L` ≥ 68765 / 776994816 > 0 on x1 ∈ [319 / 4096, 639 / 8192], x3 ∈ [4095 / 4096, 1], x4 ∈ [0, 1 / 4096]
                                                have d1lo : (0:ℝ) ≤ x1 - 319 / 4096 := sub_nonneg.mpr hs20
                                                have d1hi : (0:ℝ) ≤ 639 / 8192 - x1 := sub_nonneg.mpr hs23
                                                have d3lo : (0:ℝ) ≤ x3 - 4095 / 4096 := sub_nonneg.mpr hs21
                                                have d3hi : (0:ℝ) ≤ 1 - x3 := sub_nonneg.mpr hhi3
                                                have d4lo : (0:ℝ) ≤ x4 - 0 := sub_nonneg.mpr hlo4
                                                have d4hi : (0:ℝ) ≤ 1 / 4096 - x4 := sub_nonneg.mpr hs22
                                                linarith only [c1, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
                                              · rcases le_total x3 (8191 / 8192 : ℝ) with hs24 | hs24
                                                · rcases le_total x4 (1 / 8192 : ℝ) with hs25 | hs25
                                                  · rcases le_total x1 (1279 / 16384 : ℝ) with hs26 | hs26
                                                    · -- `quit_at_most_L` ≥ 1980127 / 28789702656 > 0 on x1 ∈ [639 / 8192, 1279 / 16384], x3 ∈ [4095 / 4096, 8191 / 8192], x4 ∈ [0, 1 / 8192]
                                                      have d1lo : (0:ℝ) ≤ x1 - 639 / 8192 := sub_nonneg.mpr hs23
                                                      have d1hi : (0:ℝ) ≤ 1279 / 16384 - x1 := sub_nonneg.mpr hs26
                                                      have d3lo : (0:ℝ) ≤ x3 - 4095 / 4096 := sub_nonneg.mpr hs21
                                                      have d3hi : (0:ℝ) ≤ 8191 / 8192 - x3 := sub_nonneg.mpr hs24
                                                      have d4lo : (0:ℝ) ≤ x4 - 0 := sub_nonneg.mpr hlo4
                                                      have d4hi : (0:ℝ) ≤ 1 / 8192 - x4 := sub_nonneg.mpr hs25
                                                      linarith only [c1, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
                                                    · -- `wait_at_most_L` ≥ 12991870133 / 211106232532992 > 0 on x1 ∈ [1279 / 16384, 5 / 64], x3 ∈ [4095 / 4096, 8191 / 8192], x4 ∈ [0, 1 / 8192]
                                                      have d1lo : (0:ℝ) ≤ x1 - 1279 / 16384 := sub_nonneg.mpr hs26
                                                      have d1hi : (0:ℝ) ≤ 5 / 64 - x1 := sub_nonneg.mpr hs2
                                                      have d3lo : (0:ℝ) ≤ x3 - 4095 / 4096 := sub_nonneg.mpr hs21
                                                      have d3hi : (0:ℝ) ≤ 8191 / 8192 - x3 := sub_nonneg.mpr hs24
                                                      have d4lo : (0:ℝ) ≤ x4 - 0 := sub_nonneg.mpr hlo4
                                                      have d4hi : (0:ℝ) ≤ 1 / 8192 - x4 := sub_nonneg.mpr hs25
                                                      linarith only [c2, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
                                                  · -- `wait_at_most_L` ≥ 1493596648671929 / 9511602413006487552 > 0 on x1 ∈ [639 / 8192, 5 / 64], x3 ∈ [4095 / 4096, 8191 / 8192], x4 ∈ [1 / 8192, 1 / 4096]
                                                    have d1lo : (0:ℝ) ≤ x1 - 639 / 8192 := sub_nonneg.mpr hs23
                                                    have d1hi : (0:ℝ) ≤ 5 / 64 - x1 := sub_nonneg.mpr hs2
                                                    have d3lo : (0:ℝ) ≤ x3 - 4095 / 4096 := sub_nonneg.mpr hs21
                                                    have d3hi : (0:ℝ) ≤ 8191 / 8192 - x3 := sub_nonneg.mpr hs24
                                                    have d4lo : (0:ℝ) ≤ x4 - 1 / 8192 := sub_nonneg.mpr hs25
                                                    have d4hi : (0:ℝ) ≤ 1 / 4096 - x4 := sub_nonneg.mpr hs22
                                                    linarith only [c2, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
                                                · rcases le_total x4 (1 / 8192 : ℝ) with hs25 | hs25
                                                  · rcases le_total x1 (1279 / 16384 : ℝ) with hs26 | hs26
                                                    · rcases le_total x3 (16383 / 16384 : ℝ) with hs27 | hs27
                                                      · -- `quit_at_most_L` ≥ 931871 / 57579405312 > 0 on x1 ∈ [639 / 8192, 1279 / 16384], x3 ∈ [8191 / 8192, 16383 / 16384], x4 ∈ [0, 1 / 8192]
                                                        have d1lo : (0:ℝ) ≤ x1 - 639 / 8192 := sub_nonneg.mpr hs23
                                                        have d1hi : (0:ℝ) ≤ 1279 / 16384 - x1 := sub_nonneg.mpr hs26
                                                        have d3lo : (0:ℝ) ≤ x3 - 8191 / 8192 := sub_nonneg.mpr hs24
                                                        have d3hi : (0:ℝ) ≤ 16383 / 16384 - x3 := sub_nonneg.mpr hs27
                                                        have d4lo : (0:ℝ) ≤ x4 - 0 := sub_nonneg.mpr hlo4
                                                        have d4hi : (0:ℝ) ≤ 1 / 8192 - x4 := sub_nonneg.mpr hs25
                                                        linarith only [c1, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
                                                      · rcases le_total x4 (1 / 16384 : ℝ) with hs28 | hs28
                                                        · rcases le_total x1 (2557 / 32768 : ℝ) with hs29 | hs29
                                                          · -- `quit_at_most_L` ≥ 20237 / 776994816 > 0 on x1 ∈ [639 / 8192, 2557 / 32768], x3 ∈ [16383 / 16384, 1], x4 ∈ [0, 1 / 16384]
                                                            have d1lo : (0:ℝ) ≤ x1 - 639 / 8192 := sub_nonneg.mpr hs23
                                                            have d1hi : (0:ℝ) ≤ 2557 / 32768 - x1 := sub_nonneg.mpr hs29
                                                            have d3lo : (0:ℝ) ≤ x3 - 16383 / 16384 := sub_nonneg.mpr hs27
                                                            have d3hi : (0:ℝ) ≤ 1 - x3 := sub_nonneg.mpr hhi3
                                                            have d4lo : (0:ℝ) ≤ x4 - 0 := sub_nonneg.mpr hlo4
                                                            have d4hi : (0:ℝ) ≤ 1 / 16384 - x4 := sub_nonneg.mpr hs28
                                                            linarith only [c1, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
                                                          · -- `wait_at_most_L` ≥ 4649903903 / 1688849860263936 > 0 on x1 ∈ [2557 / 32768, 1279 / 16384], x3 ∈ [16383 / 16384, 1], x4 ∈ [0, 1 / 16384]
                                                            have d1lo : (0:ℝ) ≤ x1 - 2557 / 32768 := sub_nonneg.mpr hs29
                                                            have d1hi : (0:ℝ) ≤ 1279 / 16384 - x1 := sub_nonneg.mpr hs26
                                                            have d3lo : (0:ℝ) ≤ x3 - 16383 / 16384 := sub_nonneg.mpr hs27
                                                            have d3hi : (0:ℝ) ≤ 1 - x3 := sub_nonneg.mpr hhi3
                                                            have d4lo : (0:ℝ) ≤ x4 - 0 := sub_nonneg.mpr hlo4
                                                            have d4hi : (0:ℝ) ≤ 1 / 16384 - x4 := sub_nonneg.mpr hs28
                                                            linarith only [c2, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
                                                        · -- `wait_at_most_L` ≥ 26863446438177551 / 532649735128363302912 > 0 on x1 ∈ [639 / 8192, 1279 / 16384], x3 ∈ [16383 / 16384, 1], x4 ∈ [1 / 16384, 1 / 8192]
                                                          have d1lo : (0:ℝ) ≤ x1 - 639 / 8192 := sub_nonneg.mpr hs23
                                                          have d1hi : (0:ℝ) ≤ 1279 / 16384 - x1 := sub_nonneg.mpr hs26
                                                          have d3lo : (0:ℝ) ≤ x3 - 16383 / 16384 := sub_nonneg.mpr hs27
                                                          have d3hi : (0:ℝ) ≤ 1 - x3 := sub_nonneg.mpr hhi3
                                                          have d4lo : (0:ℝ) ≤ x4 - 1 / 16384 := sub_nonneg.mpr hs28
                                                          have d4hi : (0:ℝ) ≤ 1 / 8192 - x4 := sub_nonneg.mpr hs25
                                                          linarith only [c2, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
                                                    · -- `wait_at_most_L` ≥ 26614969525 / 422212465065984 > 0 on x1 ∈ [1279 / 16384, 5 / 64], x3 ∈ [8191 / 8192, 1], x4 ∈ [0, 1 / 8192]
                                                      have d1lo : (0:ℝ) ≤ x1 - 1279 / 16384 := sub_nonneg.mpr hs26
                                                      have d1hi : (0:ℝ) ≤ 5 / 64 - x1 := sub_nonneg.mpr hs2
                                                      have d3lo : (0:ℝ) ≤ x3 - 8191 / 8192 := sub_nonneg.mpr hs24
                                                      have d3hi : (0:ℝ) ≤ 1 - x3 := sub_nonneg.mpr hhi3
                                                      have d4lo : (0:ℝ) ≤ x4 - 0 := sub_nonneg.mpr hlo4
                                                      have d4hi : (0:ℝ) ≤ 1 / 8192 - x4 := sub_nonneg.mpr hs25
                                                      linarith only [c2, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
                                                  · -- `wait_at_most_L` ≥ 7032737624791301 / 44387477927363608576 > 0 on x1 ∈ [639 / 8192, 5 / 64], x3 ∈ [8191 / 8192, 1], x4 ∈ [1 / 8192, 1 / 4096]
                                                    have d1lo : (0:ℝ) ≤ x1 - 639 / 8192 := sub_nonneg.mpr hs23
                                                    have d1hi : (0:ℝ) ≤ 5 / 64 - x1 := sub_nonneg.mpr hs2
                                                    have d3lo : (0:ℝ) ≤ x3 - 8191 / 8192 := sub_nonneg.mpr hs24
                                                    have d3hi : (0:ℝ) ≤ 1 - x3 := sub_nonneg.mpr hhi3
                                                    have d4lo : (0:ℝ) ≤ x4 - 1 / 8192 := sub_nonneg.mpr hs25
                                                    have d4hi : (0:ℝ) ≤ 1 / 4096 - x4 := sub_nonneg.mpr hs22
                                                    linarith only [c2, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
                                            · -- `wait_at_most_L` ≥ 28223853405323 / 216172782113783808 > 0 on x1 ∈ [319 / 4096, 5 / 64], x3 ∈ [4095 / 4096, 1], x4 ∈ [1 / 4096, 1 / 2048]
                                              have d1lo : (0:ℝ) ≤ x1 - 319 / 4096 := sub_nonneg.mpr hs20
                                              have d1hi : (0:ℝ) ≤ 5 / 64 - x1 := sub_nonneg.mpr hs2
                                              have d3lo : (0:ℝ) ≤ x3 - 4095 / 4096 := sub_nonneg.mpr hs21
                                              have d3hi : (0:ℝ) ≤ 1 - x3 := sub_nonneg.mpr hhi3
                                              have d4lo : (0:ℝ) ≤ x4 - 1 / 4096 := sub_nonneg.mpr hs22
                                              have d4hi : (0:ℝ) ≤ 1 / 2048 - x4 := sub_nonneg.mpr hs19
                                              linarith only [c2, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
                                      · -- `quit_at_most_L` ≥ 92173 / 2330984448 > 0 on x1 ∈ [159 / 2048, 5 / 64], x3 ∈ [2047 / 2048, 1], x4 ∈ [1 / 2048, 1 / 1024]
                                        have d1lo : (0:ℝ) ≤ x1 - 159 / 2048 := sub_nonneg.mpr hs17
                                        have d1hi : (0:ℝ) ≤ 5 / 64 - x1 := sub_nonneg.mpr hs2
                                        have d3lo : (0:ℝ) ≤ x3 - 2047 / 2048 := sub_nonneg.mpr hs18
                                        have d3hi : (0:ℝ) ≤ 1 - x3 := sub_nonneg.mpr hhi3
                                        have d4lo : (0:ℝ) ≤ x4 - 1 / 2048 := sub_nonneg.mpr hs19
                                        have d4hi : (0:ℝ) ≤ 1 / 1024 - x4 := sub_nonneg.mpr hs16
                                        linarith only [c1, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
                                · -- `quit_at_most_L` ≥ 560387 / 2330984448 > 0 on x1 ∈ [79 / 1024, 5 / 64], x3 ∈ [1023 / 1024, 1], x4 ∈ [1 / 1024, 1 / 512]
                                  have d1lo : (0:ℝ) ≤ x1 - 79 / 1024 := sub_nonneg.mpr hs14
                                  have d1hi : (0:ℝ) ≤ 5 / 64 - x1 := sub_nonneg.mpr hs2
                                  have d3lo : (0:ℝ) ≤ x3 - 1023 / 1024 := sub_nonneg.mpr hs15
                                  have d3hi : (0:ℝ) ≤ 1 - x3 := sub_nonneg.mpr hhi3
                                  have d4lo : (0:ℝ) ≤ x4 - 1 / 1024 := sub_nonneg.mpr hs16
                                  have d4hi : (0:ℝ) ≤ 1 / 512 - x4 := sub_nonneg.mpr hs13
                                  linarith only [c1, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
                          · -- `quit_at_most_L` ≥ 1496815 / 2330984448 > 0 on x1 ∈ [39 / 512, 5 / 64], x3 ∈ [511 / 512, 1], x4 ∈ [1 / 512, 1 / 256]
                            have d1lo : (0:ℝ) ≤ x1 - 39 / 512 := sub_nonneg.mpr hs11
                            have d1hi : (0:ℝ) ≤ 5 / 64 - x1 := sub_nonneg.mpr hs2
                            have d3lo : (0:ℝ) ≤ x3 - 511 / 512 := sub_nonneg.mpr hs12
                            have d3hi : (0:ℝ) ≤ 1 - x3 := sub_nonneg.mpr hhi3
                            have d4lo : (0:ℝ) ≤ x4 - 1 / 512 := sub_nonneg.mpr hs13
                            have d4hi : (0:ℝ) ≤ 1 / 256 - x4 := sub_nonneg.mpr hs10
                            linarith only [c1, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
                    · -- `quit_at_most_L` ≥ 3369671 / 2330984448 > 0 on x1 ∈ [19 / 256, 5 / 64], x3 ∈ [255 / 256, 1], x4 ∈ [1 / 256, 1 / 128]
                      have d1lo : (0:ℝ) ≤ x1 - 19 / 256 := sub_nonneg.mpr hs8
                      have d1hi : (0:ℝ) ≤ 5 / 64 - x1 := sub_nonneg.mpr hs2
                      have d3lo : (0:ℝ) ≤ x3 - 255 / 256 := sub_nonneg.mpr hs9
                      have d3hi : (0:ℝ) ≤ 1 - x3 := sub_nonneg.mpr hhi3
                      have d4lo : (0:ℝ) ≤ x4 - 1 / 256 := sub_nonneg.mpr hs10
                      have d4hi : (0:ℝ) ≤ 1 / 128 - x4 := sub_nonneg.mpr hs7
                      linarith only [c1, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
              · -- `quit_at_most_L` ≥ 7115383 / 2330984448 > 0 on x1 ∈ [9 / 128, 5 / 64], x3 ∈ [127 / 128, 1], x4 ∈ [1 / 128, 1 / 64]
                have d1lo : (0:ℝ) ≤ x1 - 9 / 128 := sub_nonneg.mpr hs5
                have d1hi : (0:ℝ) ≤ 5 / 64 - x1 := sub_nonneg.mpr hs2
                have d3lo : (0:ℝ) ≤ x3 - 127 / 128 := sub_nonneg.mpr hs6
                have d3hi : (0:ℝ) ≤ 1 - x3 := sub_nonneg.mpr hhi3
                have d4lo : (0:ℝ) ≤ x4 - 1 / 128 := sub_nonneg.mpr hs7
                have d4hi : (0:ℝ) ≤ 1 / 64 - x4 := sub_nonneg.mpr hs4
                linarith only [c1, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
        · -- `quit_at_most_L` ≥ 14606807 / 2330984448 > 0 on x1 ∈ [1 / 16, 5 / 64], x3 ∈ [63 / 64, 1], x4 ∈ [1 / 64, 1 / 32]
          have d1lo : (0:ℝ) ≤ x1 - 1 / 16 := sub_nonneg.mpr hlo1
          have d1hi : (0:ℝ) ≤ 5 / 64 - x1 := sub_nonneg.mpr hs2
          have d3lo : (0:ℝ) ≤ x3 - 63 / 64 := sub_nonneg.mpr hs3
          have d3hi : (0:ℝ) ≤ 1 - x3 := sub_nonneg.mpr hhi3
          have d4lo : (0:ℝ) ≤ x4 - 1 / 64 := sub_nonneg.mpr hs4
          have d4hi : (0:ℝ) ≤ 1 / 32 - x4 := sub_nonneg.mpr hs1
          linarith only [c1, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
    · rcases le_total x3 (63 / 64 : ℝ) with hs3 | hs3
      · rcases le_total x4 (1 / 64 : ℝ) with hs4 | hs4
        · rcases le_total x1 (11 / 128 : ℝ) with hs5 | hs5
          · rcases le_total x3 (125 / 128 : ℝ) with hs6 | hs6
            · -- `quit_at_most_L` ≥ 3470045 / 776994816 > 0 on x1 ∈ [5 / 64, 11 / 128], x3 ∈ [31 / 32, 125 / 128], x4 ∈ [0, 1 / 64]
              have d1lo : (0:ℝ) ≤ x1 - 5 / 64 := sub_nonneg.mpr hs2
              have d1hi : (0:ℝ) ≤ 11 / 128 - x1 := sub_nonneg.mpr hs5
              have d3lo : (0:ℝ) ≤ x3 - 31 / 32 := sub_nonneg.mpr hlo3
              have d3hi : (0:ℝ) ≤ 125 / 128 - x3 := sub_nonneg.mpr hs6
              have d4lo : (0:ℝ) ≤ x4 - 0 := sub_nonneg.mpr hlo4
              have d4hi : (0:ℝ) ≤ 1 / 64 - x4 := sub_nonneg.mpr hs4
              linarith only [c1, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
            · rcases le_total x4 (1 / 128 : ℝ) with hs7 | hs7
              · rcases le_total x1 (21 / 256 : ℝ) with hs8 | hs8
                · -- `quit_at_most_L` ≥ 46577023 / 8546942976 > 0 on x1 ∈ [5 / 64, 21 / 256], x3 ∈ [125 / 128, 63 / 64], x4 ∈ [0, 1 / 128]
                  have d1lo : (0:ℝ) ≤ x1 - 5 / 64 := sub_nonneg.mpr hs2
                  have d1hi : (0:ℝ) ≤ 21 / 256 - x1 := sub_nonneg.mpr hs8
                  have d3lo : (0:ℝ) ≤ x3 - 125 / 128 := sub_nonneg.mpr hs6
                  have d3hi : (0:ℝ) ≤ 63 / 64 - x3 := sub_nonneg.mpr hs3
                  have d4lo : (0:ℝ) ≤ x4 - 0 := sub_nonneg.mpr hlo4
                  have d4hi : (0:ℝ) ≤ 1 / 128 - x4 := sub_nonneg.mpr hs7
                  linarith only [c1, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
                · -- `wait_at_most_L` ≥ 774287221 / 103079215104 > 0 on x1 ∈ [21 / 256, 11 / 128], x3 ∈ [125 / 128, 63 / 64], x4 ∈ [0, 1 / 128]
                  have d1lo : (0:ℝ) ≤ x1 - 21 / 256 := sub_nonneg.mpr hs8
                  have d1hi : (0:ℝ) ≤ 11 / 128 - x1 := sub_nonneg.mpr hs5
                  have d3lo : (0:ℝ) ≤ x3 - 125 / 128 := sub_nonneg.mpr hs6
                  have d3hi : (0:ℝ) ≤ 63 / 64 - x3 := sub_nonneg.mpr hs3
                  have d4lo : (0:ℝ) ≤ x4 - 0 := sub_nonneg.mpr hlo4
                  have d4hi : (0:ℝ) ≤ 1 / 128 - x4 := sub_nonneg.mpr hs7
                  linarith only [c2, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
              · -- `quit_at_most_L` ≥ 59355445 / 90131398656 > 0 on x1 ∈ [5 / 64, 11 / 128], x3 ∈ [125 / 128, 63 / 64], x4 ∈ [1 / 128, 1 / 64]
                have d1lo : (0:ℝ) ≤ x1 - 5 / 64 := sub_nonneg.mpr hs2
                have d1hi : (0:ℝ) ≤ 11 / 128 - x1 := sub_nonneg.mpr hs5
                have d3lo : (0:ℝ) ≤ x3 - 125 / 128 := sub_nonneg.mpr hs6
                have d3hi : (0:ℝ) ≤ 63 / 64 - x3 := sub_nonneg.mpr hs3
                have d4lo : (0:ℝ) ≤ x4 - 1 / 128 := sub_nonneg.mpr hs7
                have d4hi : (0:ℝ) ≤ 1 / 64 - x4 := sub_nonneg.mpr hs4
                linarith only [c1, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
          · -- `wait_at_most_L` ≥ 191964089 / 12884901888 > 0 on x1 ∈ [11 / 128, 3 / 32], x3 ∈ [31 / 32, 63 / 64], x4 ∈ [0, 1 / 64]
            have d1lo : (0:ℝ) ≤ x1 - 11 / 128 := sub_nonneg.mpr hs5
            have d1hi : (0:ℝ) ≤ 3 / 32 - x1 := sub_nonneg.mpr hhi1
            have d3lo : (0:ℝ) ≤ x3 - 31 / 32 := sub_nonneg.mpr hlo3
            have d3hi : (0:ℝ) ≤ 63 / 64 - x3 := sub_nonneg.mpr hs3
            have d4lo : (0:ℝ) ≤ x4 - 0 := sub_nonneg.mpr hlo4
            have d4hi : (0:ℝ) ≤ 1 / 64 - x4 := sub_nonneg.mpr hs4
            linarith only [c2, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
        · -- `wait_at_most_L` ≥ 262435653475 / 9070970929152 > 0 on x1 ∈ [5 / 64, 3 / 32], x3 ∈ [31 / 32, 63 / 64], x4 ∈ [1 / 64, 1 / 32]
          have d1lo : (0:ℝ) ≤ x1 - 5 / 64 := sub_nonneg.mpr hs2
          have d1hi : (0:ℝ) ≤ 3 / 32 - x1 := sub_nonneg.mpr hhi1
          have d3lo : (0:ℝ) ≤ x3 - 31 / 32 := sub_nonneg.mpr hlo3
          have d3hi : (0:ℝ) ≤ 63 / 64 - x3 := sub_nonneg.mpr hs3
          have d4lo : (0:ℝ) ≤ x4 - 1 / 64 := sub_nonneg.mpr hs4
          have d4hi : (0:ℝ) ≤ 1 / 32 - x4 := sub_nonneg.mpr hs1
          linarith only [c2, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
      · rcases le_total x4 (1 / 64 : ℝ) with hs4 | hs4
        · rcases le_total x1 (11 / 128 : ℝ) with hs5 | hs5
          · rcases le_total x3 (127 / 128 : ℝ) with hs6 | hs6
            · rcases le_total x4 (1 / 128 : ℝ) with hs7 | hs7
              · rcases le_total x1 (21 / 256 : ℝ) with hs8 | hs8
                · rcases le_total x3 (253 / 256 : ℝ) with hs9 | hs9
                  · -- `quit_at_most_L` ≥ 17506207 / 8546942976 > 0 on x1 ∈ [5 / 64, 21 / 256], x3 ∈ [63 / 64, 253 / 256], x4 ∈ [0, 1 / 128]
                    have d1lo : (0:ℝ) ≤ x1 - 5 / 64 := sub_nonneg.mpr hs2
                    have d1hi : (0:ℝ) ≤ 21 / 256 - x1 := sub_nonneg.mpr hs8
                    have d3lo : (0:ℝ) ≤ x3 - 63 / 64 := sub_nonneg.mpr hs3
                    have d3hi : (0:ℝ) ≤ 253 / 256 - x3 := sub_nonneg.mpr hs9
                    have d4lo : (0:ℝ) ≤ x4 - 0 := sub_nonneg.mpr hlo4
                    have d4hi : (0:ℝ) ≤ 1 / 128 - x4 := sub_nonneg.mpr hs7
                    linarith only [c1, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
                  · -- `wait_at_most_L` ≥ 2140709 / 51539607552 > 0 on x1 ∈ [5 / 64, 21 / 256], x3 ∈ [253 / 256, 127 / 128], x4 ∈ [0, 1 / 128]
                    have d1lo : (0:ℝ) ≤ x1 - 5 / 64 := sub_nonneg.mpr hs2
                    have d1hi : (0:ℝ) ≤ 21 / 256 - x1 := sub_nonneg.mpr hs8
                    have d3lo : (0:ℝ) ≤ x3 - 253 / 256 := sub_nonneg.mpr hs9
                    have d3hi : (0:ℝ) ≤ 127 / 128 - x3 := sub_nonneg.mpr hs6
                    have d4lo : (0:ℝ) ≤ x4 - 0 := sub_nonneg.mpr hlo4
                    have d4hi : (0:ℝ) ≤ 1 / 128 - x4 := sub_nonneg.mpr hs7
                    linarith only [c2, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
                · -- `wait_at_most_L` ≥ 131839757 / 17179869184 > 0 on x1 ∈ [21 / 256, 11 / 128], x3 ∈ [63 / 64, 127 / 128], x4 ∈ [0, 1 / 128]
                  have d1lo : (0:ℝ) ≤ x1 - 21 / 256 := sub_nonneg.mpr hs8
                  have d1hi : (0:ℝ) ≤ 11 / 128 - x1 := sub_nonneg.mpr hs5
                  have d3lo : (0:ℝ) ≤ x3 - 63 / 64 := sub_nonneg.mpr hs3
                  have d3hi : (0:ℝ) ≤ 127 / 128 - x3 := sub_nonneg.mpr hs6
                  have d4lo : (0:ℝ) ≤ x4 - 0 := sub_nonneg.mpr hlo4
                  have d4hi : (0:ℝ) ≤ 1 / 128 - x4 := sub_nonneg.mpr hs7
                  linarith only [c2, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
              · -- `wait_at_most_L` ≥ 1208940139047 / 84662395338752 > 0 on x1 ∈ [5 / 64, 11 / 128], x3 ∈ [63 / 64, 127 / 128], x4 ∈ [1 / 128, 1 / 64]
                have d1lo : (0:ℝ) ≤ x1 - 5 / 64 := sub_nonneg.mpr hs2
                have d1hi : (0:ℝ) ≤ 11 / 128 - x1 := sub_nonneg.mpr hs5
                have d3lo : (0:ℝ) ≤ x3 - 63 / 64 := sub_nonneg.mpr hs3
                have d3hi : (0:ℝ) ≤ 127 / 128 - x3 := sub_nonneg.mpr hs6
                have d4lo : (0:ℝ) ≤ x4 - 1 / 128 := sub_nonneg.mpr hs7
                have d4hi : (0:ℝ) ≤ 1 / 64 - x4 := sub_nonneg.mpr hs4
                linarith only [c2, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
            · -- `wait_at_most_L` ≥ 772157 / 8589934592 > 0 on x1 ∈ [5 / 64, 11 / 128], x3 ∈ [127 / 128, 1], x4 ∈ [0, 1 / 64]
              have d1lo : (0:ℝ) ≤ x1 - 5 / 64 := sub_nonneg.mpr hs2
              have d1hi : (0:ℝ) ≤ 11 / 128 - x1 := sub_nonneg.mpr hs5
              have d3lo : (0:ℝ) ≤ x3 - 127 / 128 := sub_nonneg.mpr hs6
              have d3hi : (0:ℝ) ≤ 1 - x3 := sub_nonneg.mpr hhi3
              have d4lo : (0:ℝ) ≤ x4 - 0 := sub_nonneg.mpr hlo4
              have d4hi : (0:ℝ) ≤ 1 / 64 - x4 := sub_nonneg.mpr hs4
              linarith only [c2, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
          · -- `wait_at_most_L` ≥ 395695033 / 25769803776 > 0 on x1 ∈ [11 / 128, 3 / 32], x3 ∈ [63 / 64, 1], x4 ∈ [0, 1 / 64]
            have d1lo : (0:ℝ) ≤ x1 - 11 / 128 := sub_nonneg.mpr hs5
            have d1hi : (0:ℝ) ≤ 3 / 32 - x1 := sub_nonneg.mpr hhi1
            have d3lo : (0:ℝ) ≤ x3 - 63 / 64 := sub_nonneg.mpr hs3
            have d3hi : (0:ℝ) ≤ 1 - x3 := sub_nonneg.mpr hhi3
            have d4lo : (0:ℝ) ≤ x4 - 0 := sub_nonneg.mpr hlo4
            have d4hi : (0:ℝ) ≤ 1 / 64 - x4 := sub_nonneg.mpr hs4
            linarith only [c2, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
        · -- `wait_at_most_L` ≥ 616717 / 22020096 > 0 on x1 ∈ [5 / 64, 3 / 32], x3 ∈ [63 / 64, 1], x4 ∈ [1 / 64, 1 / 32]
          have d1lo : (0:ℝ) ≤ x1 - 5 / 64 := sub_nonneg.mpr hs2
          have d1hi : (0:ℝ) ≤ 3 / 32 - x1 := sub_nonneg.mpr hhi1
          have d3lo : (0:ℝ) ≤ x3 - 63 / 64 := sub_nonneg.mpr hs3
          have d3hi : (0:ℝ) ≤ 1 - x3 := sub_nonneg.mpr hhi3
          have d4lo : (0:ℝ) ≤ x4 - 1 / 64 := sub_nonneg.mpr hs4
          have d4hi : (0:ℝ) ≤ 1 / 32 - x4 := sub_nonneg.mpr hs1
          linarith only [c2, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
  · -- `wait_at_most_L` ≥ 571405 / 22020096 > 0 on x1 ∈ [1 / 16, 3 / 32], x3 ∈ [31 / 32, 1], x4 ∈ [1 / 32, 1 / 16]
    have d1lo : (0:ℝ) ≤ x1 - 1 / 16 := sub_nonneg.mpr hlo1
    have d1hi : (0:ℝ) ≤ 3 / 32 - x1 := sub_nonneg.mpr hhi1
    have d3lo : (0:ℝ) ≤ x3 - 31 / 32 := sub_nonneg.mpr hlo3
    have d3hi : (0:ℝ) ≤ 1 - x3 := sub_nonneg.mpr hhi3
    have d4lo : (0:ℝ) ≤ x4 - 1 / 32 := sub_nonneg.mpr hs1
    have d4hi : (0:ℝ) ≤ 1 / 16 - x4 := sub_nonneg.mpr hhi4
    linarith only [c2, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]

theorem seed202_r78_gen011_minmax_lower_2_sub008
    (x1 x3 x4 : ℝ)
    (hlo1 : (3 / 32 : ℝ) ≤ x1)
    (hhi1 : x1 ≤ (1 / 8 : ℝ))
    (hlo3 : (15 / 16 : ℝ) ≤ x3)
    (hhi3 : x3 ≤ (1 : ℝ))
    (hlo4 : (0 : ℝ) ≤ x4)
    (hhi4 : x4 ≤ (1 / 16 : ℝ))
    (c2 : seed202_r78_gen011_minmax_lower_2_f02 x1 (0 : ℝ) x3 x4)
    : False := by
  simp only [seed202_r78_gen011_minmax_lower_2_f02] at c2
  -- `wait_at_most_L` ≥ 15331627 / 536870912 > 0 on x1 ∈ [3 / 32, 1 / 8], x3 ∈ [15 / 16, 1], x4 ∈ [0, 1 / 16]
  have d1lo : (0:ℝ) ≤ x1 - 3 / 32 := sub_nonneg.mpr hlo1
  have d1hi : (0:ℝ) ≤ 1 / 8 - x1 := sub_nonneg.mpr hhi1
  have d3lo : (0:ℝ) ≤ x3 - 15 / 16 := sub_nonneg.mpr hlo3
  have d3hi : (0:ℝ) ≤ 1 - x3 := sub_nonneg.mpr hhi3
  have d4lo : (0:ℝ) ≤ x4 - 0 := sub_nonneg.mpr hlo4
  have d4hi : (0:ℝ) ≤ 1 / 16 - x4 := sub_nonneg.mpr hhi4
  linarith only [c2, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]

theorem seed202_r78_gen011_minmax_lower_2_sub009
    (x1 x3 x4 : ℝ)
    (hlo1 : (1 / 16 : ℝ) ≤ x1)
    (hhi1 : x1 ≤ (1 / 8 : ℝ))
    (hlo3 : (15 / 16 : ℝ) ≤ x3)
    (hhi3 : x3 ≤ (1 : ℝ))
    (hlo4 : (1 / 16 : ℝ) ≤ x4)
    (hhi4 : x4 ≤ (1 / 8 : ℝ))
    (c2 : seed202_r78_gen011_minmax_lower_2_f02 x1 (0 : ℝ) x3 x4)
    : False := by
  simp only [seed202_r78_gen011_minmax_lower_2_f02] at c2
  -- `wait_at_most_L` ≥ 608943 / 7340032 > 0 on x1 ∈ [1 / 16, 1 / 8], x3 ∈ [15 / 16, 1], x4 ∈ [1 / 16, 1 / 8]
  have d1lo : (0:ℝ) ≤ x1 - 1 / 16 := sub_nonneg.mpr hlo1
  have d1hi : (0:ℝ) ≤ 1 / 8 - x1 := sub_nonneg.mpr hhi1
  have d3lo : (0:ℝ) ≤ x3 - 15 / 16 := sub_nonneg.mpr hlo3
  have d3hi : (0:ℝ) ≤ 1 - x3 := sub_nonneg.mpr hhi3
  have d4lo : (0:ℝ) ≤ x4 - 1 / 16 := sub_nonneg.mpr hlo4
  have d4hi : (0:ℝ) ≤ 1 / 8 - x4 := sub_nonneg.mpr hhi4
  linarith only [c2, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]

theorem seed202_r78_gen011_minmax_lower_2_sub010
    (x1 x3 x4 : ℝ)
    (hlo1 : (0 : ℝ) ≤ x1)
    (hhi1 : x1 ≤ (1 / 8 : ℝ))
    (hlo3 : (7 / 8 : ℝ) ≤ x3)
    (hhi3 : x3 ≤ (1 : ℝ))
    (hlo4 : (1 / 8 : ℝ) ≤ x4)
    (hhi4 : x4 ≤ (1 / 4 : ℝ))
    (c2 : seed202_r78_gen011_minmax_lower_2_f02 x1 (0 : ℝ) x3 x4)
    : False := by
  simp only [seed202_r78_gen011_minmax_lower_2_f02] at c2
  -- `wait_at_most_L` ≥ 295499 / 3145728 > 0 on x1 ∈ [0, 1 / 8], x3 ∈ [7 / 8, 1], x4 ∈ [1 / 8, 1 / 4]
  have d1lo : (0:ℝ) ≤ x1 - 0 := sub_nonneg.mpr hlo1
  have d1hi : (0:ℝ) ≤ 1 / 8 - x1 := sub_nonneg.mpr hhi1
  have d3lo : (0:ℝ) ≤ x3 - 7 / 8 := sub_nonneg.mpr hlo3
  have d3hi : (0:ℝ) ≤ 1 - x3 := sub_nonneg.mpr hhi3
  have d4lo : (0:ℝ) ≤ x4 - 1 / 8 := sub_nonneg.mpr hlo4
  have d4hi : (0:ℝ) ≤ 1 / 4 - x4 := sub_nonneg.mpr hhi4
  linarith only [c2, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]

theorem seed202_r78_gen011_minmax_lower_2_sub011
    (x1 x3 x4 : ℝ)
    (hlo1 : (1 / 8 : ℝ) ≤ x1)
    (hhi1 : x1 ≤ (1 / 4 : ℝ))
    (hlo3 : (3 / 4 : ℝ) ≤ x3)
    (hhi3 : x3 ≤ (1 : ℝ))
    (hlo4 : (0 : ℝ) ≤ x4)
    (hhi4 : x4 ≤ (1 / 4 : ℝ))
    (c2 : seed202_r78_gen011_minmax_lower_2_f02 x1 (0 : ℝ) x3 x4)
    : False := by
  simp only [seed202_r78_gen011_minmax_lower_2_f02] at c2
  -- `wait_at_most_L` ≥ 6601043 / 100663296 > 0 on x1 ∈ [1 / 8, 1 / 4], x3 ∈ [3 / 4, 1], x4 ∈ [0, 1 / 4]
  have d1lo : (0:ℝ) ≤ x1 - 1 / 8 := sub_nonneg.mpr hlo1
  have d1hi : (0:ℝ) ≤ 1 / 4 - x1 := sub_nonneg.mpr hhi1
  have d3lo : (0:ℝ) ≤ x3 - 3 / 4 := sub_nonneg.mpr hlo3
  have d3hi : (0:ℝ) ≤ 1 - x3 := sub_nonneg.mpr hhi3
  have d4lo : (0:ℝ) ≤ x4 - 0 := sub_nonneg.mpr hlo4
  have d4hi : (0:ℝ) ≤ 1 / 4 - x4 := sub_nonneg.mpr hhi4
  linarith only [c2, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]

theorem seed202_r78_gen011_minmax_lower_2_sub012
    (x1 x3 x4 : ℝ)
    (hlo1 : (0 : ℝ) ≤ x1)
    (hhi1 : x1 ≤ (1 / 4 : ℝ))
    (hlo3 : (3 / 4 : ℝ) ≤ x3)
    (hhi3 : x3 ≤ (1 : ℝ))
    (hlo4 : (1 / 4 : ℝ) ≤ x4)
    (hhi4 : x4 ≤ (1 / 2 : ℝ))
    (c2 : seed202_r78_gen011_minmax_lower_2_f02 x1 (0 : ℝ) x3 x4)
    : False := by
  simp only [seed202_r78_gen011_minmax_lower_2_f02] at c2
  -- `wait_at_most_L` ≥ 1081931 / 3145728 > 0 on x1 ∈ [0, 1 / 4], x3 ∈ [3 / 4, 1], x4 ∈ [1 / 4, 1 / 2]
  have d1lo : (0:ℝ) ≤ x1 - 0 := sub_nonneg.mpr hlo1
  have d1hi : (0:ℝ) ≤ 1 / 4 - x1 := sub_nonneg.mpr hhi1
  have d3lo : (0:ℝ) ≤ x3 - 3 / 4 := sub_nonneg.mpr hlo3
  have d3hi : (0:ℝ) ≤ 1 - x3 := sub_nonneg.mpr hhi3
  have d4lo : (0:ℝ) ≤ x4 - 1 / 4 := sub_nonneg.mpr hlo4
  have d4hi : (0:ℝ) ≤ 1 / 2 - x4 := sub_nonneg.mpr hhi4
  linarith only [c2, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]

theorem seed202_r78_gen011_minmax_lower_2_sub013
    (x1 x3 x4 : ℝ)
    (hlo1 : (1 / 4 : ℝ) ≤ x1)
    (hhi1 : x1 ≤ (1 / 2 : ℝ))
    (hlo3 : (1 / 2 : ℝ) ≤ x3)
    (hhi3 : x3 ≤ (1 : ℝ))
    (hlo4 : (0 : ℝ) ≤ x4)
    (hhi4 : x4 ≤ (1 / 2 : ℝ))
    (c2 : seed202_r78_gen011_minmax_lower_2_f02 x1 (0 : ℝ) x3 x4)
    : False := by
  simp only [seed202_r78_gen011_minmax_lower_2_f02] at c2
  -- `wait_at_most_L` ≥ 3836791 / 25165824 > 0 on x1 ∈ [1 / 4, 1 / 2], x3 ∈ [1 / 2, 1], x4 ∈ [0, 1 / 2]
  have d1lo : (0:ℝ) ≤ x1 - 1 / 4 := sub_nonneg.mpr hlo1
  have d1hi : (0:ℝ) ≤ 1 / 2 - x1 := sub_nonneg.mpr hhi1
  have d3lo : (0:ℝ) ≤ x3 - 1 / 2 := sub_nonneg.mpr hlo3
  have d3hi : (0:ℝ) ≤ 1 - x3 := sub_nonneg.mpr hhi3
  have d4lo : (0:ℝ) ≤ x4 - 0 := sub_nonneg.mpr hlo4
  have d4hi : (0:ℝ) ≤ 1 / 2 - x4 := sub_nonneg.mpr hhi4
  linarith only [c2, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]

theorem seed202_r78_gen011_minmax_lower_2_sub014
    (x1 x3 x4 : ℝ)
    (hlo1 : (0 : ℝ) ≤ x1)
    (hhi1 : x1 ≤ (1 / 2 : ℝ))
    (hlo3 : (1 / 2 : ℝ) ≤ x3)
    (hhi3 : x3 ≤ (1 : ℝ))
    (hlo4 : (1 / 2 : ℝ) ≤ x4)
    (hhi4 : x4 ≤ (1 : ℝ))
    (c2 : seed202_r78_gen011_minmax_lower_2_f02 x1 (0 : ℝ) x3 x4)
    : False := by
  simp only [seed202_r78_gen011_minmax_lower_2_f02] at c2
  -- `wait_at_most_L` ≥ 2654795 / 3145728 > 0 on x1 ∈ [0, 1 / 2], x3 ∈ [1 / 2, 1], x4 ∈ [1 / 2, 1]
  have d1lo : (0:ℝ) ≤ x1 - 0 := sub_nonneg.mpr hlo1
  have d1hi : (0:ℝ) ≤ 1 / 2 - x1 := sub_nonneg.mpr hhi1
  have d3lo : (0:ℝ) ≤ x3 - 1 / 2 := sub_nonneg.mpr hlo3
  have d3hi : (0:ℝ) ≤ 1 - x3 := sub_nonneg.mpr hhi3
  have d4lo : (0:ℝ) ≤ x4 - 1 / 2 := sub_nonneg.mpr hlo4
  have d4hi : (0:ℝ) ≤ 1 - x4 := sub_nonneg.mpr hhi4
  linarith only [c2, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]

theorem seed202_r78_gen011_minmax_lower_2_sub015
    (x1 x3 x4 : ℝ)
    (hlo1 : (1 / 2 : ℝ) ≤ x1)
    (hhi1 : x1 ≤ (1 : ℝ))
    (hlo3 : (0 : ℝ) ≤ x3)
    (hhi3 : x3 ≤ (1 : ℝ))
    (hlo4 : (0 : ℝ) ≤ x4)
    (hhi4 : x4 ≤ (1 : ℝ))
    (c1 : seed202_r78_gen011_minmax_lower_2_f01 x1 (0 : ℝ) x3 x4)
    (c2 : seed202_r78_gen011_minmax_lower_2_f02 x1 (0 : ℝ) x3 x4)
    : False := by
  simp only [seed202_r78_gen011_minmax_lower_2_f01, seed202_r78_gen011_minmax_lower_2_f02] at c1 c2
  rcases le_total x3 (1 / 2 : ℝ) with hs1 | hs1
  · rcases le_total x4 (1 / 2 : ℝ) with hs2 | hs2
    · rcases le_total x1 (3 / 4 : ℝ) with hs3 | hs3
      · rcases le_total x3 (1 / 4 : ℝ) with hs4 | hs4
        · -- `quit_at_most_L` ≥ 3564033535 / 8546942976 > 0 on x1 ∈ [1 / 2, 3 / 4], x3 ∈ [0, 1 / 4], x4 ∈ [0, 1 / 2]
          have d1lo : (0:ℝ) ≤ x1 - 1 / 2 := sub_nonneg.mpr hlo1
          have d1hi : (0:ℝ) ≤ 3 / 4 - x1 := sub_nonneg.mpr hs3
          have d3lo : (0:ℝ) ≤ x3 - 0 := sub_nonneg.mpr hlo3
          have d3hi : (0:ℝ) ≤ 1 / 4 - x3 := sub_nonneg.mpr hs4
          have d4lo : (0:ℝ) ≤ x4 - 0 := sub_nonneg.mpr hlo4
          have d4hi : (0:ℝ) ≤ 1 / 2 - x4 := sub_nonneg.mpr hs2
          linarith only [c1, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
        · -- `wait_at_most_L` ≥ 3836791 / 25165824 > 0 on x1 ∈ [1 / 2, 3 / 4], x3 ∈ [1 / 4, 1 / 2], x4 ∈ [0, 1 / 2]
          have d1lo : (0:ℝ) ≤ x1 - 1 / 2 := sub_nonneg.mpr hlo1
          have d1hi : (0:ℝ) ≤ 3 / 4 - x1 := sub_nonneg.mpr hs3
          have d3lo : (0:ℝ) ≤ x3 - 1 / 4 := sub_nonneg.mpr hs4
          have d3hi : (0:ℝ) ≤ 1 / 2 - x3 := sub_nonneg.mpr hs1
          have d4lo : (0:ℝ) ≤ x4 - 0 := sub_nonneg.mpr hlo4
          have d4hi : (0:ℝ) ≤ 1 / 2 - x4 := sub_nonneg.mpr hs2
          linarith only [c2, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
      · rcases le_total x3 (1 / 4 : ℝ) with hs4 | hs4
        · -- `quit_at_most_L` ≥ 149211109 / 449839104 > 0 on x1 ∈ [3 / 4, 1], x3 ∈ [0, 1 / 4], x4 ∈ [0, 1 / 2]
          have d1lo : (0:ℝ) ≤ x1 - 3 / 4 := sub_nonneg.mpr hs3
          have d1hi : (0:ℝ) ≤ 1 - x1 := sub_nonneg.mpr hhi1
          have d3lo : (0:ℝ) ≤ x3 - 0 := sub_nonneg.mpr hlo3
          have d3hi : (0:ℝ) ≤ 1 / 4 - x3 := sub_nonneg.mpr hs4
          have d4lo : (0:ℝ) ≤ x4 - 0 := sub_nonneg.mpr hlo4
          have d4hi : (0:ℝ) ≤ 1 / 2 - x4 := sub_nonneg.mpr hs2
          linarith only [c1, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
        · -- `wait_at_most_L` ≥ 12492239 / 50331648 > 0 on x1 ∈ [3 / 4, 1], x3 ∈ [1 / 4, 1 / 2], x4 ∈ [0, 1 / 2]
          have d1lo : (0:ℝ) ≤ x1 - 3 / 4 := sub_nonneg.mpr hs3
          have d1hi : (0:ℝ) ≤ 1 - x1 := sub_nonneg.mpr hhi1
          have d3lo : (0:ℝ) ≤ x3 - 1 / 4 := sub_nonneg.mpr hs4
          have d3hi : (0:ℝ) ≤ 1 / 2 - x3 := sub_nonneg.mpr hs1
          have d4lo : (0:ℝ) ≤ x4 - 0 := sub_nonneg.mpr hlo4
          have d4hi : (0:ℝ) ≤ 1 / 2 - x4 := sub_nonneg.mpr hs2
          linarith only [c2, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
    · -- `wait_at_most_L` ≥ 5609785 / 34603008 > 0 on x1 ∈ [1 / 2, 1], x3 ∈ [0, 1 / 2], x4 ∈ [1 / 2, 1]
      have d1lo : (0:ℝ) ≤ x1 - 1 / 2 := sub_nonneg.mpr hlo1
      have d1hi : (0:ℝ) ≤ 1 - x1 := sub_nonneg.mpr hhi1
      have d3lo : (0:ℝ) ≤ x3 - 0 := sub_nonneg.mpr hlo3
      have d3hi : (0:ℝ) ≤ 1 / 2 - x3 := sub_nonneg.mpr hs1
      have d4lo : (0:ℝ) ≤ x4 - 1 / 2 := sub_nonneg.mpr hs2
      have d4hi : (0:ℝ) ≤ 1 - x4 := sub_nonneg.mpr hhi4
      linarith only [c2, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]
  · -- `wait_at_most_L` ≥ 1606219 / 4194304 > 0 on x1 ∈ [1 / 2, 1], x3 ∈ [1 / 2, 1], x4 ∈ [0, 1]
    have d1lo : (0:ℝ) ≤ x1 - 1 / 2 := sub_nonneg.mpr hlo1
    have d1hi : (0:ℝ) ≤ 1 - x1 := sub_nonneg.mpr hhi1
    have d3lo : (0:ℝ) ≤ x3 - 1 / 2 := sub_nonneg.mpr hs1
    have d3hi : (0:ℝ) ≤ 1 - x3 := sub_nonneg.mpr hhi3
    have d4lo : (0:ℝ) ≤ x4 - 0 := sub_nonneg.mpr hlo4
    have d4hi : (0:ℝ) ≤ 1 - x4 := sub_nonneg.mpr hhi4
    linarith only [c2, mul_nonneg (mul_nonneg (d1hi) d3hi) d4hi, mul_nonneg (mul_nonneg (d1lo) d3hi) d4hi, mul_nonneg (mul_nonneg (d1hi) d3lo) d4hi, mul_nonneg (mul_nonneg (d1lo) d3lo) d4hi, mul_nonneg (mul_nonneg (d1hi) d3hi) d4lo, mul_nonneg (mul_nonneg (d1lo) d3hi) d4lo, mul_nonneg (mul_nonneg (d1hi) d3lo) d4lo, mul_nonneg (mul_nonneg (d1lo) d3lo) d4lo]

end Quitting.V0
